### ISSUE TITLE
Add Airsonic to a translation service

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#100]
<a href="https://github.com/jooola"><img src="https://avatars2.githubusercontent.com/u/19195485?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jooola](https://github.com/jooola)**
_Sunday Jun 05, 2016 at 17:39 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/100_

----

After reading some comments and tried to translate some of the language files, i suggest that we add libresonic to a translations service !

Maybe Transifex  or so  ?

**Comment by jooola** [comment]
cc @muff1nman @biconou 
I reask my question now that we forked : 
Do we still have an interest in a translations service ?

I asked Weblate to move there libresonic translations to our repo ( airsonic translations ).
And now we only need to set it up !
I already linked the how we can do this above !

New weblate repo is now : https://hosted.weblate.org/projects/airsonic/develop/

**Comment by muff1nman** [comment]
I think this should be fine to do and will help getting it setup after we get 6.3 out the door

**Comment by jooola** [comment]
Sorry if I solved this so fast (before 10.0.0 is released ) but I don't want to work on this anymore !

So everything is set up !

It is pretty simple : 
Weblate repo (Using Weblate service attached to our github repo ( see services on the github settings )) read every push we make on the github repo and sync all new translations to Weblate's repo.

If some translations are made on Weblate repo the Weblate user ( attached to our repo with Write access ) push the new translations on the github repo ( I'm not sure but push can be manual or automatic ).

For any more informations please contact me on our communication channels
