### ISSUE TITLE
Replace wz_tooltip.js with jquery-ui

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1018]
Since we're already using jquery-ui.js for stuff™, it might make sense to replace the 1300-lines-long-old-school-steaming-pile-of-javascript-wz_tooltip.js with it.

**Comment by jvoisin** [comment]
Done in 195a0879

**Comment by muff1nman** [comment]
Reverted #1019 due to #1112

**Comment by eharris** [comment]
The current incarnation of this is in PR #1154.

**Comment by jvoisin** [comment]
Done in 584ee96f
