### ISSUE TITLE
Airsonic becomes unresponsive within 24-48 hours after DLNA enabled

### ISSUE THREAD

**Issue by timbuktumor** [airsonic/airsonic#1043]
## Problem description

*Airsonic becomes unresponsive within 24-48 hours after enabling the DLNA server in **Settings**-->**DLNA/UPnP**.  The server is unable to be contacted using DLNA, Airsonic web console, or mobile apps.*

*I am running Airsonic in a Docker container on unRAID server.  I do not know if the root of this issue is caused by unRAID, Docker, or Airsonic, but I do know enabling the DLNA setting within Airsonic's web console causes the Airsonic server to crash.  It appears Airsonic is consuming all the docker's allocated memory. Increasing the memory will buy a couple more days, but it will eventually crash.*  

The server runs **flawless** with the DLNA setting **disabled**.

### Steps to reproduce

Steps 1-5 may not be necessary, but I have not tried Airsonic outside of unRAID.

1. *Install unRAID server*
2. *Enable Docker from unRAID Settings-->Docker*
3. *From unRAID Docker menu, load template repository: https://github.com/linuxserver/docker-templates*
4. *Add Container.  Select Airsonic template.  Complete data paths as required,  Verify JAVA_OPTS is set to -Xms256m -Xmx512m*
5. *Edit Airsonic Docker container configuration by changing Network type to Custom: br:0, then assign an ip address for Airsonic to use.*
6. *Login to airsonic using http://ipaddress:4040/airsonic/*
7. *Click Settings-->DLNA/UPnP*
8. *Check box "Enable DLNA Server," set media server name, set LAN server address to http://ipaddress:4040/airsonic/*
9. *Verify DLNA is working.*
10. *Wait 24-48 hours*

## System information

 * **Airsonic version**: *10.2.1-RELEASE – February 18, 2019*
 * **Operating system**: *Docker on unRAID v6.6.6*
 * **Docker version**: *18.06.1-ce*

## Additional notes

*Attached are some screen snips showing memory consumption and up-time along with the respective logs.  It looks like a lot of podcast activity until finally crashing.
[airsonic_logs.zip](https://github.com/airsonic/airsonic/files/3144152/airsonic_logs.zip)

**Comment by jvoisin** [comment]
Looks like a memory leak somewhere :/
