### ISSUE TITLE
Airsonic not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by mainulainen** [airsonic/airsonic#1044]
## Problem description

I installed Airsonic using these instructions: 
https://airsonic.github.io/docs/install/war-standalone/

When I attempt to run Airsonic using Ubuntu it starts but fails somehow. I know this because when I try to connect to localhost:8080, there is nothing there. 

Here is a pastebin link of the log I get when I try to run Airsonic. https://pastebin.com/BrAmvTt2

### Steps to reproduce

1. Install Airsonic using these instructions:
https://airsonic.github.io/docs/install/war-standalone/
2. Run the command java -jar airsonic.war

## System information

 * **Airsonic version**: *v10.2.1*
 * **Operating system**: *Ubuntu 18.04.*
 * **Proxy server**: *None*
 * **Client**: *Mozilla Firefox 66.0.3*

**Comment by jooola** [comment]
You need to install Java 8 to get airsonic working properly. Java > 9 will be supported in next release.

**Comment by mainulainen** [comment]
Yeah, that did the trick. I can't believe I missed something that simple! Thanks!
