### ISSUE TITLE
Constant errors: "Could not verify the provided CSRF token because your session was not found"

### ISSUE THREAD

**Issue by tliron** [airsonic/airsonic#1047]
## Problem description

This happens a lot. I could be using Airsonic just fine, and then I click on some page, like "Settings" or "About" it either shows me this message or sends me back to the login screen. I do not see anything in the log. Deleting cookies, restarting Airsonic (systemd), and starting over does not make it go away.

### Steps to reproduce

I have no idea -- it doesn't seem to happen to other people and it seems entirely random to me.

## System information

 * **Airsonic version**: 10.2.1
 * **Operating system**: Fedora 30
 * **Java version**: 1.8.0_212
 * **Proxy server**: None
 * **Client**: Firefox 66.0.4

**Comment by fxthomas** [comment]
Did you by any chance submit a form (any form) or restart Airsonic before the error happened?

**Comment by tliron** [comment]
I apologize, but I don't understand the question. What do you mean by "form"?

**Comment by fxthomas** [comment]
Ah, sorry. I meant, any part of a page that has a "Save" or "Submit" button or lets you change something in Airsonic. The reason I asked is that, usually, CSRF issues happen there.

**Comment by tliron** [comment]
No, I am just doing things like pressing "Settings" or "About", so this is just an HTTP GET.

However, I looked with a debugger and I see there are POSTs being done on a timer to the nowPlayingService. An example URL:
```
dwr/call/plaincall/nowPlayingService.getScanningStatus.dwr
```
Could it be that one of these is causing the CSRF issue?

**Comment by fxthomas** [comment]
Hum, that's strange then. Is there a stack trace in the logs?

**Comment by tliron** [comment]
Nope.

**Comment by tliron** [comment]
Weird discovery: If I access Airsonic using the hostname, e.g. `http://server:8080`, then everything is fine. The bug only occurs if I use the IP address directly, e.g. `http://192.168.0.2`.
