### ISSUE TITLE
Can't list or play music even though music was found

### ISSUE THREAD

**Issue by Marenz** [airsonic/airsonic#1052]
## Problem description

I added two folders to the database, one for music, one for movies. Both contain files.
After scanning, the left side bar showed 

```
1 artists
3 albums
40 songs
974.6 MB
2 hours
```

So it clearly found my music. However, when I click on `Home` or use the search button, no music is to be found. Only my movies are visible (and can be played).
I then disabled my movie folder to see if it makes the music files work, but no such luck.
I checked the permissions of both and they all seem to be in order. (they were the same, +rx for world)

### Steps to reproduce

1. Add music & movie folders to the database
2. Try to find music, fail.

## System information

 * **Airsonic version**: 10.2.1-RELEASE – February 18, 2019
 * **Operating system**: FreeNAS-11.2-U4 (Build Date: May 7, 2019 0:46)
 * **Java version**: Apache Tomcat/8.0.50, java 1.8.0_202, FreeBSD (820.2 MB / 1.40 GB)
 * **Client**: Chromium Version 74.0.3729.131 (Offizieller Build) Arch Linux (64-Bit)

**Comment by muff1nman** [comment]
Check the permissions on the user page to make sure access didnt get turned off.

**Comment by eharris** [comment]
Closing this due to no followup.
