### ISSUE TITLE
Javascript /script/utils.js could not be loaded

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#1065]
## Problem description
The newly created and refactor utils.js script could not be loaded in airsonic. The content gets blocked by `The resource from “https://domain.tld/script/utils.js” was blocked due to MIME type (“application/json”) mismatch (X-Content-Type-Options: nosniff)`

This file is supposed to be loaded in the playqueue frame and could not.

I think the scheme handling is bugged and need to be fixed asap.

### Steps to reproduce

1. *Open airsonic 10.3 in browser*

## System information

 * **Airsonic version**: 10.3
 * **Operating system**: Debian 9 amd64
 * **Java version**: OpenJDK8
 * **Proxy server**: HAproxy 1.9 (no changes made after upgrading to 10.3)
 * **Client**: Firefox 66.0.4

**Comment by jooola** [comment]
I suspect this issue to be the source of some other problems, like many `Blocked loading mixed active content “http://domain.tld/main.view?id=79076”` when trying to open a album from the playqueue.

**Comment by Smarre** [comment]
Happens here also after upgrade.

OpenSUSE 15
proxy nginx
Java 10
Firefox 60.6.3

**Comment by jooola** [comment]
https://blog.mozilla.org/security/2016/08/26/mitigating-mime-confusion-attacks-in-firefox/

**Comment by jvoisin** [comment]
Thanks for fixing it ♥
