### ISSUE TITLE
Playqueue album link broken: Blocked loading mixed active content

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#1071]
## Problem description

I thought the album links in the play queue where broken because of #1065 but it seems they have there own bug.

Clicking on the album links in the play queue triggers a  `Blocked loading mixed active content “http://domain.tld/main.view?id=96281”` in the browser console.
Display content is displayed, by just printing a warning in the console, but this is active content and gets blocked.

### Steps to reproduce

1. Open airsonic in your browser (over HTTPS)
2. Fill your play queue and click on an album name in the play queue

## System information

 * **Airsonic version**: 10.3
 * **Operating system**: Debian 9 amd64
 * **Java version**: OpenJDK8
 * **Proxy server**: HAproxy 1.9 (no changes made after upgrading to 10.3)
 * **Client**: Firefox 66.0.4

HAproxy configuration:
```
# Omitted global section

defaults
  log  global
  mode  http
  option  httplog
  option  dontlognull
  timeout connect 5000
  timeout client  50000
  timeout server  50000
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

  option forwardfor
  option http-server-close
  option http-use-htx

frontend main
  bind :80
  bind :443 ssl crt /etc/haproxy/certs/XXXXXX.pem alpn h2,http/1.1
  
  # Force HTTPS
  redirect scheme https code 301 if !{ ssl_fc }
  reqadd X-Forwarded-Proto:\ https
  
  # HSTS (63072000 seconds = 1 year)
  http-response set-header Strict-Transport-Security max-age=63072000;\ includeSubDomains;\ preload

  use_backend audio-auk-airsonic_backend if { hdr(host) -i audio.XXXXXX }

backend audio-auk-airsonic_backend
  server audio-auk-airsonic 127.0.0.1:6081 check
  http-response replace-value Location ^http://(.*)$ https://\1
```

**Comment by jooola** [comment]
I posted the reverse proxy conf, but I think this has something to do with the webapp JavaScript.

**Comment by jvoisin** [comment]
Can you find where the loaded http resource is coming from? Is this some javascript-powered-loading, a java-generated-link, … ?

**Comment by fxthomas** [comment]
No issues for me with Nginx as a reverse proxy, by the way, the link is a proper https URL.

**Comment by jooola** [comment]
Ok, if X-Forwarded-For and X-Forwarded-Proto are set but not X-Forwarded-Host, the base url won't be properly decoded on the airsonic side. I guess I'll have to read a bit more the docs (I'll update the haproxy docs)
