### ISSUE TITLE
"Folder not found" error when adding external media path

### ISSUE THREAD

**Issue by alexi10** [airsonic/airsonic#1081]
## Problem description

I'm not able to add my external hardrive as a media source as I am getting a "folder not found", tried giving the whole drive 777 permission and still no luck. Any help is appreciated.

### Steps to reproduce

1. Fresh Install
2. Add external media folder
3. "Folder not found" error

## System information

 * **Airsonic version**: 10.3.1
 * **Operating system**: Raspbian kernel v4.4
 * **Java version**: 1.8.0.65
 * **Proxy server**: None
 * **Client**: Chrome Version 74.0.3729.157 (Official Build) (64-bit)

## Additional Information
[airsonic.log](https://github.com/airsonic/airsonic/files/3219790/airsonic.log)

Drive is formatted in ntfs

**Comment by fxthomas** [comment]
What user are you using to run Tomcat? Does it have the permission to list/read the contents of `/media/pi` (I assume that's the folder you want to add)?

**Comment by saintfrater** [comment]
Hello,

I've quiet the same problem on a fresh debian 9 setup... 
When I try to specify "/home/music" (where all my MP3 are stored) as music folder, AirSonic tell me that the folder doesn't exist.

I've tryed couple of thing (chown to airsonic user or chmod 0777 without success...
I've been able to add the "/home" folder, but scanning failed later on...

I've moved the "/home/music" folder to "/var/arisonic/music" and change the music folder to "/var/airsonic/music" to access music...

I'll suspect that something with the securtiy and/or exclusive directory access is involved into this trouble...

**Comment by fxthomas** [comment]
Can you guys post the user / systemd units you use to run the Airsonic/Tomcat services? The default service provided by https://github.com/airsonic/airsonic/blob/master/contrib/airsonic.service has a bunch of `ProtectXXXX` directives that may be the cause of this.

**Comment by saintfrater** [comment]
Sure,

airsonic.service : 
```
[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/var/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx700m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=4040"
Environment="CONTEXT_PATH=/"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/default/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.context-path=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=airsonic
Group=airsonic

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
# for details
DevicePolicy=closed
NoNewPrivileges=yes
PrivateDevices=yes
PrivateTmp=yes
PrivateUsers=yes
ProtectControlGroups=yes
ProtectHome=true
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=~@clock,@debug,@module,@mount,@obsolete,@privileged,@reboot,@setuid,@swap
ProtectSystem=full

# You can uncomment the following line if you don't want airsonic to be able to
# write anything on your filesystem outside of AIRSONIC_HOME.
# Don't forget to remove the other `ProtectSystem` line above.
#ProtectSystem=strict
#ReadWritePaths=/var/airsonic

# You can uncomment the following line if you're not using the OpenJDK.
# This will prevent processes from having a memory zone that is both writeable
# and executeable, making hacker's lifes a bit harder.
#MemoryDenyWriteExecute=yes

[Install]
WantedBy=multi-user.target
```
pretty straight forward from the github...

**Comment by fxthomas** [comment]
Yup, that's what I thought as well ;)

I feel that we should make that optional in the default service : commented by default, but still there to indicate that it could be a good idea to hide home directories.

**Comment by jvoisin** [comment]
Meh, this is annoying :/

But I guess that you're right, people might put their music into a `/home/`. I'll send a PR to comment the line and add some doc on top of it.

**Comment by jvoisin** [comment]
Done in 40a5150b6e62a113f2de6f28ca189ea376e3e778

**Comment by MightyPork** [comment]
I'm currently trying to debug an issue with the same symptoms, my music is located in `/home/data/music`. `/home/data` is a mount point for an encrypted data disk, mounted in fstab:

```
UUID=xxx  /home/data  ext4  rw,nofail,noatime,user  0 2
```
```
drwxr--r-- 22 ondra users 4.0K 21. Feb 11.27 data
drwxr-xr-x 7 ondra users 4.0K  5. Aug  2019 data/music
```

The service file is unchanged from the release archive, `ProtectHome` is commented out. I set the `airsonic` user's shell to bash to try it manually, and it can't access the folder either - ruling out the service file, imo.

```
[airsonic@N202 /]$ ls home
data ...
[airsonic@N202 /]$ ls home/data
lost+found  photo  video  music
[airsonic@N202 /]$ ls home/data/music
ls: cannot access 'home/data/music': Permission denied
[airsonic@N202 /]$ 
```
The user is created by sysusers `u airsonic - "Airsonic user" /var/lib/airsonic` - nothing unusual

I'm honestly out of ideas. Do you have any guess what could be causing this?
I tried fiddling with the mount flags to no avail, chmodding the folder, nothing helps

**Comment by fxthomas** [comment]
If you're getting the issue even with a shell it sounds like it is a system configuration issue... I don't know what could be causing this on your particular setup unfortunately.

I assume you checked that folders are at least r-x and files are at least r-- from the root to your music directory for the `airsonic` user?

**Comment by MightyPork** [comment]
@fxthomas thanks for the super quick response! It pointed me in the right direction:

Tried `ls -la`, since `ls` worked fine:

```
[airsonic@N202 /]$ ls -la home
drwxr--r-- 22 ondra users 4096 21. Feb 11.27 data
...

[airsonic@N202 home]$ cd data
bash: cd: data: Permission denied

[airsonic@N202 home]$ ls data
music ...

[airsonic@N202 home]$ ls -la data
ls: cannot access 'data/data': Permission denied
d????????? ? ? ? ?             ? music
...
```

I searched "question marks in ls" and the solution was .... missing executable flag on the `data` directory :roll_eyes: 

That was such a stupid issue. Run `chmod a+x data` and all working fine now!
