### ISSUE TITLE
Add a "Check that everything is fine" page

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1082]
Most of the bugs we're getting are permissions-related, or reposts of already-opened issues.

We should have a "check" page, to check for common configuration issues:

- Permissions in airsonic's home
- Permissions in podcasts storage folder
- Disk space
- Version not up to date
- Old browser
- …

**Comment by fxthomas** [comment]
Also, current locale, database size (if using embedded).

**Comment by jooola** [comment]
SMTP settings test

**Comment by tesshucom** [comment]
Checking for ffmpeg may be a good place to go here...
(There is no problem at present, but there is no check of ffprobe)
I was surprised that the details were made more than expected.

**Comment by fxthomas** [comment]
Good idea, I added ffmpeg/ffprobe checks to the PR. Thanks!

**Comment by jvoisin** [comment]
Done in 7a27e081
