### ISSUE TITLE
turn db logging off

### ISSUE THREAD

**Issue by nopoz** [airsonic/airsonic#1085]
Lots of data being written to /airsonic/data/db/airsonic.log
Looks like debug level logging? See log snippet below. The longer Airsonic stays up, the bigger this file gets. I have seen it grow over 80MB in size. 
Is there anyway to disable writing to this file? 

Using the latest version of airsonic docker image (10.3.1) from https://hub.docker.com/r/airsonic/airsonic/

example from log:
```
/*C37*/SET SCHEMA PUBLIC                    
CONNECT USER SA                                            
SET AUTOCOMMIT FALSE
SET AUTOCOMMIT TRUE
DISCONNECT
/*C38*/SET SCHEMA PUBLIC
CONNECT USER SA
SET AUTOCOMMIT FALSE
SET AUTOCOMMIT TRUE    
DISCONNECT     
/*C39*/SET SCHEMA PUBLIC
CONNECT USER SA        
SET AUTOCOMMIT FALSE
SET AUTOCOMMIT TRUE 
DISCONNECT    
```

**Comment by jooola** [comment]
Agreed, also the migration logs from liquidbase where pretty verbose between 10.2 => 10.3

**Comment by fxthomas** [comment]
It's actually not debug logs at all, this file contains the actual database logs (added/removed rows before they are written to persistent storage, equivalent to the WAL in Postgres). It is necessary if you want to keep your data, which I assume you do :)

10.3 should reduce the size of this file a lot (10.2 did not clean it well), and I'm expecting migrating to HSQLDB 2+ should help a lot with the connect/disconnect spam you see.
