### ISSUE TITLE
admin password cannot be changed from "admin"

### ISSUE THREAD

**Issue by thearthur** [airsonic/airsonic#1088]
## Problem description

I changed the admin password when first setting ip airsonic. later I went to the login page and got a message saying 
```
Airsonic is not secured. Please log in with username and
password "admin". Then change the password immediately.
```

I tried logging in with the password i had set for admin, and it didn't work. 
then i tried with the password "admin" and it worked. 

then on the getting started page presented i clicked "Change administrator password."
then checked the "change password" box. the number of *'s in the box is correct for the
password i tried to change it to (not sure if that's a coincidence).

Then i tried to change the password again. I get a green messaage saying settings saved.

I log out and still see the message "Airsonic is not secured. Please log in with username and
password "admin". Then change the password immediately" and "admin" is still the only password that works
### Steps to reproduce

* change the admin password away from "admin"
* login with the password admin.

## System information

 * **Airsonic version**: v10.3.1-RELEASE
 * **Operating system**: Linux 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
   Linux, what distribution; debian
 * **Java version**: OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
 * **Proxy server**: None
 * **Client**: Firefox

**Comment by jvoisin** [comment]
Did you check that everything was working fine in the logs?
