### ISSUE TITLE
The videoplayer is broken

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1093]
cf1f86f2 broke the video player, by moving the javascript code to an external file, where patterns like `${…}` aren't replaced.

We can either:

1. Revert the commit
2. Declare that since nobody noticed in 7 weeks that it was broken that we can get rid of it
3. Refactor the javascript/jsp so that we can have a working separate javascript file without trivial xss in it, eg by assigning the `model.…` variable to javascript variables, and sanitizing them.

**Comment by jvoisin** [comment]
I'll try to do 3. tonight.

**Comment by muff1nman** [comment]
Either 1 or 3 are fine with me.

**Comment by jvoisin** [comment]
Fixed in  #1097
