### ISSUE TITLE
Wtf is /rest/videoPlayer.view

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1098]
1. Why do we have a video player in the rest API?
2. Why is it using Flash (and some old-school javascript libraries along with it)?
3. Can we get rid of it?

To play videos, there is already the decently-working `/videoPlayer.view` page.

**Comment by jooola** [comment]
I'm more a make a one thing and make it right kind of guy. So I would even totally get rid of the video player. Other tools are doing video streaming way better than *sonic.

We already made chat api endpoint 'Gone', and some new video endpoint 'Not implemented'. Same could be applied here.

https://airsonic.github.io/docs/api/

**Comment by heyarne** [comment]
I'd support that as well: https://github.com/airsonic/airsonic/issues/921#issuecomment-480834513

**Comment by jvoisin** [comment]
`/rest/videoPlayer` isn't a subsonic API endpoint.

**Comment by jvoisin** [comment]
@muff1nman I would like to have your opinion on this one :)

**Comment by heyarne** [comment]
So if I understand this correctly it iseems to be used by DSub, see [here](https://github.com/daneren2005/Subsonic/search?q=getVideoUrl&unscoped_q=getVideoUrl). The actual implementation is in [RESTMusicService.java](https://github.com/daneren2005/Subsonic/blob/166d395e3e5de223527fec96d8b17dd42ed9a991/app/src/main/java/github/daneren2005/dsub/service/RESTMusicService.java#L892), even though there are also methods to defer to `stream` and `hls`.

I can't test this right now, but my guess would be that it might

a. not be used directly
b. broken if it's used to embed a fragment of HTML that uses `swf` to play videos.

**Comment by muff1nman** [comment]
It looks like this method wasn't migrated correctly when the REST api got migrated. See 5b2297af968dfe903b45170e8204d81116f1de80 for an example of how the other methods were migrated. Its also interesting that this method isn't documented in the subsonic api.

**Comment by jvoisin** [comment]
Can we delete it?

**Comment by muff1nman** [comment]
It still might be useful for apps like dsut, whats broken about it other than it not being annotated correctly?

**Comment by jvoisin** [comment]
It's using flash, so I don't think that it's working on DSub :D

**Comment by muff1nman** [comment]
> **muff1nman**
jvoisin: where do you see flash in the videoPlayer method in SubsonicRESTController?
**jvoisin (@freenode_jvoisin:matrix.org)**
in ./airsonic-main/src/main/webapp/WEB-INF/jsp/rest/videoPlayer.jsp
**muff1nman**
ah interesting
i didnt catch that the method was returning html from a rest endoint
thats quite silly
okay im down to axe that jsp and the related method

**Comment by jvoisin** [comment]
Done in #1118
