### ISSUE TITLE
label element have a fixed width

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#1105]
In the webapp, the `label` element have a fixed with of 5 em.

This make many things really ugly.

![image](https://user-images.githubusercontent.com/19195485/59149601-80206b80-8a17-11e9-93a1-c089e5db5ec3.png)
![image](https://user-images.githubusercontent.com/19195485/59149608-9fb79400-8a17-11e9-8436-6871f92930d1.png)

**Comment by jooola** [comment]
@jvoisin By curiosity why did you removed the issue label ?

**Comment by jvoisin** [comment]
Because most of the issues are, well, … issues. I think that it makes more sense to consider that issues are issues by default, and t add labels to indicate otherwise.
