### ISSUE TITLE
Layout and alignment issues in current master branch

### ISSUE THREAD

**Issue by eharris** [airsonic/airsonic#1112]
## Problem description

I was just trying out the current HEAD of master rather than the current release v10.3.1 branch, and it looks like there are several layout and formatting issues in the settings pages.

### Steps to reproduce

Build and install current master HEAD.
Login as admin and look at the rendering of the settings pages.

In the `Media folders` page, the checkboxes are word-wrapped unnecessarily.
In the `General` page, the Index text is not wrapped but should be.
In the `Personal` page, the first table of checkboxes is ok, but the later checkboxes are messed up.
There are several others too.

<img width="637" alt="Screen Shot 2019-06-09 at 15 06 27" src="https://user-images.githubusercontent.com/19860244/59163750-b539c600-8aca-11e9-91ab-5205580cc35d.png">
<img width="753" alt="Screen Shot 2019-06-09 at 15 05 19" src="https://user-images.githubusercontent.com/19860244/59163753-b834b680-8aca-11e9-9c92-0ac74670df1e.png">

## System information

 * **Airsonic version**: 10.4.0-SNAPSHOT – June 9, 2019
 * **Operating system**: Debian 9 stretch
 * **Java version**: java-8-openjdk
 * **Proxy server**: Apache proxy
 * **Client**: Chrome for OSX, Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by jooola** [comment]
I reported the same issue in #1105  but this issue has more details. Closing mine in favor of this one.

**Comment by eharris** [comment]
I think this is also resulting in broken error/validation pages.  For instance, trying to do invalid-y things in the Users page kicks you back to the form, but doesn't show the error message of what's wrong.

**Comment by eharris** [comment]
Looks like these problems were introduced with 195a0879c3e86e7e10adcfcb35b57a5a7070ba96. @jvoisin that was yours, can we revert or get a fix for that please?

**Comment by eharris** [comment]
That only fixed some of the problems.  There are still problems in the `General` and `Advanced` pages, possibly elsewhere.
