### ISSUE TITLE
Reverting patch broke ability for web player to seek within transcoded streams

### ISSUE THREAD

**Issue by eharris** [airsonic/airsonic#1117]
## Problem description

Commit 3efa2d3 (reverting an earlier feature commit) broke the ability for the web player to seek within a transcoded stream.

### Steps to reproduce

1. Install v10.3.1, and enable `Enable seeking on transcodes` in the Transcoding settings page.
2. Play a file that gets transcoded or downsampled using the web player.
3. Observe that the seek bar works, and can seek within the content that has already been received.
4. Build and install the current master branch which contains the above commit and do the same.
5. Note that the seek bar in the web player doesn't work anymore, just shows `Live Broadcast` where the seek bar should be.

## System information

 * **Airsonic version**: 10.4.0-SNAPSHOT
 * **Operating system**: Debian 9 stretch
 * **Java version**: java-8-openjdk
 * **Proxy server**: Apache builtin
 * **Client**: Chrome for OSX Version 74.0.3729.131 (Official Build) (64-bit)

## Additional info

The original patch was #798.  The predecessor was #759.

**Comment by tari** [comment]
This is an unfortunate side effect of how we need to handle transcoding- not using chunked encoding triggers #685, while the HTML player decides chunked encoding means a live stream.

Ideally the player should be fixed to allow seeking inside the buffered parts of the track; in my experiments on #685 the native <audio> element in at least some browsers already has that behavior.

**Comment by eharris** [comment]
That kind of seems like why this workaround was made, to provide the end user with the choice of which behavior (and risks) they preferred, having seeking work with transcoding or risking the chance being afflicted by the content-mismatch problem.

I have no idea when someone might have time to work on fixing the media player, but in the meantime it seems to me that providing the option to allow seeking to work when transcoding is worth the other side effects.  We could probably mitigate or even eliminate the early termination problem when this option is enabled by "lying" to the web player (by padding the calculated/expected length by some small percentage) to make sure that we over-estimate rather than under-estimate the content length, and then padding the transfer with silence (would zeros work?) to match the length we originally predicted.

**Comment by muff1nman** [comment]
We probably need to move to dash (https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) so that we're no longer dealing with bytes but rather with time intervals. This would allow seeking without having to prematurely guess what the content length should be. 

However in the meantime we need to squash #685 one way or another. @eharris if you want to draft an alternate PR for consideration that'd be great. It also might be the case that #1080 solves #685 on its own, but I havent' personally tested that yet.

**Comment by eharris** [comment]
@tari, @muff1nman please check out https://github.com/eharris/airsonic/commit/02de6d9a775dd116d3f5054d94e72bdc16a39e41 which I think is a reasonable workaround solution to the content length problem for transcodes that still allows seeking in the web player (until the web player gets fixed to support seeking on chunked transfers).

This patch does not re-apply the parts of #798 that added a user-configurable option, but if this looks like an acceptable method and still needs to be opt-in, that can of course be added.

In my testing of this patch, I have not been able to make the web player hang at the end of tracks as long as you don't seek past the portion of the stream that has already been buffered, although I was occasionally seeing those kinds of hangs with `v10.3.1` which had the earlier workaround.

I did notice while I was testing this is that if you try to seek ahead into an area that hasn't been buffered yet, the client drops the current stream and connects again which restarts the transcode (which is expected).  If you then wait for the new transcode to catch up and the file is played all the way to the end, then the web player still seems to hang.

Because the hang never happens when you don't seek past the buffered area, I'm thinking that is probably evidence that the hang no longer has anything to do with transcoding, but instead is some other bug either in in Airsonic or the web player itself, and probably with range handling.  So maybe that's a bit of additional data for #1080?

**Comment by tari** [comment]
I don't like unconditionally doing this, because the estimate could always be much further off than anticipated here- especially with VBR codecs (I've been using opus transcoding on my server to great effect after #1035.

I think a user option is the right approach to this given the tension between "works correctly in all cases" and "wonky UI"- the simplest case would be to re-introduce the option that I removed, and slightly more complex but maybe a bit more reliable is what you've got now. There's also the possibility of spooling transcoded media and delaying responses, which might be fine for fast machines but probably not very good in general.

**Comment by eharris** [comment]
I discovered another very bad side effect of the change disallowing range requests for transcoded media.

I listen to music a LOT on my phone, but because of data plan limits I have my listening restricted to 128kbps when on cellular data (often I'm in my car so with the road noise I don't need the best quality anyway).  I also happen to be in areas with less reliable cell service a lot, so I often get connection resets.  With the no-ranges-for-transcodes change, if my mobile client gets a connection reset during the download of a song (which it often does), it either has to re-download ALL of the song rather than just the portion it didn't get, or skip unceremoniously to the next song in the middle of that track.

If the client attempts a re-fetch of the song (which might happen several times for the same track, especially for longer tracks), it's wasting a lot more of my data plan uselessly re-downloading data it already has and doesn't need.  This is a complete killer for me for this use-case, which is exactly the one that downsampling was intended for, to reduce data use.  This change has significantly increased data use for me.

**Comment by eharris** [comment]
I think #1123 is ready to be merged.  I've added a few more checks to make it as "safe" as reasonably possible.  However, I will need assistance fixing the `travis-ci` tests since I don't have access to that platform to test them beforehand.

**Comment by jvoisin** [comment]
We can try to figure this out together next week :)
