### ISSUE TITLE
Please add Step-by-step for QNAP Users

### ISSUE THREAD

**Issue by PStrat** [airsonic/airsonic#1128]
## Problem description

Please add/include a step-by-step guide from the point of a QNAP user Please!!!! I tried following https://airsonic.github.io/docs/ but it is not clear or illustrated enough to understand. 
I installed it using QNAPCLUB but it only sends you to the above link for instructions...again not clear enough.

### Steps to reproduce

I installed via QNAPCLUB and it requires you to install "Container Station 2.0.117, JRE 8.151.2, ffmpeg and Qapache". It appears to have installed properly...I can log into Airsonic from launching link from QNap App center. 
* I assume Container Station is like "Docker Container" and Qapache is like "TomCat" where you install or set up WAR package TomCat but the instructions are not clear enough on how to do it with QNAP exactly. (I'm more of visual learner). Do I need to set up a container? How? 
* Also QNAPCLUB does not come with a demonstration of installation/setup on QNAP only that is it compatible. 
*Again, I am able to login and open AirSonic so I assume QNAP installed Airsonic properly but I can not see or find the file system. Therefore, I am guessing more needs to be done?  

## System information

 QTS version 4.3.6.0959 (05-31-2019) Storage-DataVol1
Airsonic Version | 10.3.1-RELEASE – May 21, 2019
Server | Apache Tomcat/8.5.40
java 1.8.0_201
Linux (107.1 MB / 481.5 MB)
Proxy server**:  None at the moment but considering it
Client**: *Chrome Version 75.0.3770.90 (Official Build) (64-bit)

 ## Additional notes
- Before installing Airsonic, you will have to install a working JDK. Follow this guide to install it.
-- QNAP makes you install does that count as in your guide?

- Here you can pick your installation docs for:
-- DO I pick War package TOMCAT because QNAP makes me install Qapache? Not clear and does not say what to do if using QNAP.

Could use a helpful Step-by-step guide that walks you though the set up (not install since it seems it stalled through Qnap). Including location of file system. Here's my existing file structure. (I do not see AirSonic anywhere). Would greatly appreciate a guide from the point of a QNAP user please! 

DataVol1
AllShare
Container
Documents
Multimedia
Public
Recordings
TMBackup
Web
home
homes
htdocs
  ->Apache
  ->cgi-bin
1TBUSB (ext storage)

**Comment by jvoisin** [comment]
Unfortunately, most of us don't have a QNAP device. If you ever manage to make airsonic work on yours, please do tell us how, so we can edit the documentation. Or, you can even [edit it yourself]( https://github.com/airsonic/documentation/tree/master/install ) if you can :)

**Comment by rafisagatm** [comment]
In qnap 
1 go to app center 
2 add custom repo : https://qnapclub.eu/pl/repo.xml
3 install from new app center qnapcloud : JDK8
4 install from new app center airsonic
5 goto settings in qnap 
6 download from https://winscp.net Winscp application
7 enable ssh , sftp
8 run Winscp and connect using qnap ip adress and admin user and pass
9 in winscp go to /share/
10 find u share with music
11 copy that adress to settings in airsonic
12 close winscp
13 disable ssh and sftp
in any question  ask me :https://www.facebook.com/RLenarczyk
If u like this make a tip here : https://pomagam.pl/rlenarczyk

**Comment by kashuuu** [comment]
>     5. Configure airsonic to point it to your music.

Hi rafisagatm,
Could you please explain this step more in detail? I have multiple volumes, and cannot browse from the web UI of Airsonic. I tried multiple possible paths, but none worked except /share, though this is not a folder I can use to store my media files.
Thanks.

**Comment by rafisagatm** [comment]
yep but jvoisin edit my post give me email i sent instruction

**Comment by jvoisin** [comment]
Or sent a [pull-request]( https://github.com/airsonic/documentation ) to improve the documentation :)
