### ISSUE TITLE
Last song in playlist repeating.

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#1160]
On current master branch, the last song in the playlist seems to repeat without end.

**Comment by fxthomas** [comment]
Caused by the workaround in #1080, will be fixed once https://github.com/mediaelement/mediaelement/issues/2650 is taken care of (unless we find a better workaround).

**Comment by Kieltux** [comment]
Just for the history (and maybe for other people): airsonic release 10.4.0 does still have the problem with repeating the last song from a playlist.

**Comment by eharris** [comment]
@fxthomas Do you have any ideas on how to fix this?  I'm not really a JS guy but would it be possible to add a check if it tries to play the same streamUrl again without having had user intervention, and if so stop?

**Comment by fxthomas** [comment]
@eharris Feel free to work on this if you have time, I'm going on holidays until mid-September so I definitely won't work on this until then... I think it is possible to do it as you propose, provided we make really sure that we don't accidentally trigger the race conditions in MEJS.

**Comment by Mycah** [comment]
It seems to repeat the entire playlist for me, no matter what I have the repeat setting at.

**Comment by nanawel** [comment]
Only repeating the last track in my case, but yes, on `10.4.0-RELEASE` this bug's still here.
