### ISSUE TITLE
Add title attribute to player icons

### ISSUE THREAD

**Issue by SenorSmartyPants** [airsonic/airsonic#1168]
## Problem description

Add title attribute to player icons. Use same text as the alt attribute. This will display the text when hovering over the icons.

### Steps to reproduce

place mouse over icons in the player at the bottom of the UI. No text is displayed.

## System information

 * **Airsonic version**: 10.4.0
 * **Operating system**: LSIO Docker
 * **Proxy server**: None
 * **Client**: Chrome

**Comment by jvoisin** [comment]
Done in d256386cbb01897a062f5d9ad5b3e27552e589e3
