### ISSUE TITLE
Integration tests do not clean up docker instances

### ISSUE THREAD

**Issue by eharris** [airsonic/airsonic#1181]
## Problem description

When the integration tests that use docker images fail, they don't seem to clean up after themselves.

### Steps to reproduce

1. Run integration tests including creation of docker containers.
2. Cause the integration tests to fail.
3. Observe that the docker containers still exist and are running using `docker ps`

## System information

 * **Airsonic version**: Current master
 * **Operating system**: Debian stretch amd64
 * **Java version**: java-8-openjdk-amd64

**Comment by shyamindra** [comment]
Hi @jvoisin , can I please work on this?

**Comment by jvoisin** [comment]
Be my guest

**Comment by shyamindra** [comment]
Hi @jvoisin, I've been trying to setup the project and run the integration tests and I keep getting a Non parseable pom error 

`The project org.airsonic.player:airsonic-integration-test:10.5.0-SNAPSHOT (/home/sid/IdeaProjects/airsonic/integration-test/pom.xml) has 9 errors
    Non-parseable POM /home/sid/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.5.21.RELEASE/spring-boot-dependencies-1.5.21.RELEASE.pom: end tag name </head> must be the same as start tag <meta> from line 25 (position: TEXT seen ... maximum-scale=1.0; user-scalable=0;" name="viewport">\n    </head>... @26:12)  @ /home/sid/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.5.21.RELEASE/spring-boot-dependencies-1.5.21.RELEASE.pom, line 26, column 12 -> [Help 2]
    'dependencies.dependency.version' for org.springframework:spring-context:jar is missing. @ line 50, column 21
    'dependencies.dependency.version' for org.springframework:spring-test:jar is missing. @ line 55, column 21
    'dependencies.dependency.version' for junit:junit:jar is missing. @ line 59, column 21
    'dependencies.dependency.version' for commons-codec:commons-codec:jar is missing. @ line 69, column 21
    'dependencies.dependency.version' for org.apache.httpcomponents:httpcore:jar is missing. @ line 79, column 21
    'dependencies.dependency.version' for org.apache.httpcomponents:httpclient:jar is missing. @ line 84, column 21
    'dependencies.dependency.version' for org.slf4j:slf4j-api:jar is missing. @ line 95, column 21
    'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 100, column 21`

Any idea how I could resolve this?
I have tried multiple things like removing .m2/repo and re-importing dependencies and updating to the latest spring dependencies version etc. to no avail. Any help is appreciated. 
Thanks

**Comment by jvoisin** [comment]
Can you try to remove the whole `~/.m2` folder?

**Comment by shyamindra** [comment]
#1220

**Comment by eharris** [comment]
I believe this was fixed when #1220 was merged.
