### ISSUE TITLE
Replacing Tomcat with Nginx

### ISSUE THREAD

**Issue by ice954pw** [airsonic/airsonic#1202]
Is there any practical reason we are running tomcat vs nginx, in just about every respect Nginx is a superior platform for speed and size. I'd be willing to port a war with nginx if that's something that's interesting people, Apache is great but for small installs and for the sake of high performance wouldn't nginx be a better candidate. Just my .02c

**Comment by TheFlatworm** [comment]
I would love this for ARM installs which require: Oracle Java, an arm compiled FFMPEG, and something other than Tomcat - I like Jetty and have never tried Nginx but if it works, yay!

**Comment by ice954pw** [comment]
I can probably throw something together for a test Flat

**Comment by TheFlatworm** [comment]
That would be great!

**Comment by ice954pw** [comment]
Let me see what I can put together. Branding of this thing would be nice so all default pages dont have to hack up the system. Give me a week or two i'll be travling.

**Comment by jvoisin** [comment]
[Tomcat]( https://en.wikipedia.org/wiki/Apache_Tomcat ) is a servlet container, while nginx is a reverse proxy/http server. Airsonic being usually compiled to a [.war file]( https://en.wikipedia.org/wiki/WAR_(file_format) ), it can't be run outside of tomcat.

Airsonic supports running in Jetty, as an experiment for developers, but it's not production-ready yet, and I don't think that anyone is working on this.
