### ISSUE TITLE
Debian 10 (Buster) - Transcoding Video

### ISSUE THREAD

**Issue by JugglerMaster** [airsonic/airsonic#1210]
## Problem description

I am trying to get transcoding working on my RPI running buster, Debian 10. The client I am connecting with is Soundwaves on ios. This client shows a slash through the play symbol and says it's buffering. While everything works fine on my debian 9 server, I do understand that this is likely not fully supported yet on debian 10. MP3 audio plays just fine on my Soundwaves ios client on both servers.

### Steps to reproduce

I followed the instruction guide to set this server up on a fresh install. I logged into the web interface and setup my media library and configured transcoding

```
/var/arisonic/
***-rw-r----- 1 tomcat8 tomcat8 1164095 Aug 15 07:15 airsonic.log***
***-rw-r----- 1 tomcat8 tomcat8     645 Aug 15 03:00 airsonic.properties***
***drwxr-x--- 2 tomcat8 tomcat8    4096 Aug 15 03:00 db***
***drwxr-x--- 7 tomcat8 tomcat8    4096 Aug 14 21:13 lucene2***
***-rw-r----- 1 tomcat8 tomcat8     741 Aug 15 00:13 rollback.sql***
***drwxr-x--- 5 tomcat8 tomcat8    4096 Aug 14 22:44 thumbs***
***drwxr-x--- 2 tomcat8 tomcat8    4096 Aug 14 23:58 transcode***

/var/airsonic/transcode/
***lrwxrwxrwx 1 tomcat8 tomcat8   15 Aug 14 22:18 ffmpeg -> /usr/bin/ffmpeg***
```

installed ffmpeg using `apt install ffmpeg`

```
***ffmpeg version 4.1.3-1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers***
 ***built with gcc 8 (Raspbian 8.3.0-6+rpi1)***
 ***configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --arch=armhf --enable-shared***
 ***libavutil      56. 22.100 / 56. 22.100***
  ***libavcodec     58. 35.100 / 58. 35.100***
  ***libavformat    58. 20.100 / 58. 20.100***
  ***libavdevice    58.  5.100 / 58.  5.100***
  ***libavfilter     7. 40.101 /  7. 40.101***
 ***libavresample   4.  0.  0 /  4.  0.  0***
  ***libswscale      5.  3.100 /  5.  3.100***
  ***libswresample   3.  3.100 /  3.  3.100***
  ***libpostproc    55.  3.100 / 55.  3.100***
***Hyper fast Audio and Video encoder***
```

I downloaded a static ffmpeg version and linked that to see if that would help but it didn't change. If there is something missing I will compile it so I can get this working on Debian 10.

```
***ffmpeg version N-49554-g52939a2c57-static https://johnvansickle.com/ffmpeg/  Cop***                ***copyright (c) 2000-2019 the FFmpeg developers***
  ***built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516***
  ***configuration: --enable-gpl --enable-version3 --enable-static --disable-debug                  --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enabl                 e-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enab                 le-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3                 lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberban                 d --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable                 -libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable                 -libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid --en                 able-libzimg***
  ***libavutil      56. 33.100 / 56. 33.100***
  ***libavcodec     58. 55.100 / 58. 55.100***
  ***libavformat    58. 30.100 / 58. 30.100***
  ***libavdevice    58.  9.100 / 58.  9.100***
  ***libavfilter     7. 58.100 /  7. 58.100***
  ***libswscale      5.  6.100 /  5.  6.100***
  ***libswresample   3.  6.100 /  3.  6.100***
  ***libpostproc    55.  6.100 / 55.  6.100***
***Hyper fast Audio and Video encoder***
```

## System information

Airsonic: 
***Version | 10.4.0-RELEASE – July 13, 2019***

Hardware:
***Raspberry pi 3b+ Buster***
***PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"***
***NAME="Raspbian GNU/Linux"***

Java:
***java -version***
***openjdk version "1.8.0_212"***

Proxy?
I'm running airsonic in tomcat8

I tested video within firefox and it does play

**Comment by eharris** [comment]
I would not be surprised at all if a RPi doesn't have enough cpu power to do live transcoding of video.  Perhaps the client you are using realizes this and never allows it to play rather than "stuttering"?

Have you tried running an identical `ffmpeg` transcoding command manually on that hardware and verifying that the transcode completes in significantly less time than the video length?

**Comment by JugglerMaster** [comment]
Yeah, I can do some tests. The working version on Debian 9 shows the first frame on the client before buffering a long time on x265 encoded video. This video I am referring to is the same one that doesn’t work now. This is why I had assumed it was ffmpeg I could be wrong because it did play native x264 videos without the transcoding folder setup on Debian 9. No videos play on my Soundwaves client on Debian 10

Christopher Dadisman

On Aug 15, 2019, at 7:26 PM, Evan Harris <notifications@github.com<mailto:notifications@github.com>> wrote:


I would not be surprised at all if a RPi doesn't have enough cpu power to do live transcoding of video. Perhaps the client you are using realizes this and never allows it to play rather than "stuttering"?

Have you tried running an identical ffmpeg transcoding command manually on that hardware and verifying that the transcode completes in significantly less time than the video length?

**Comment by JugglerMaster** [comment]
I just tried running this on another raspberry pi but a 3B model. This time I installed the full raspbian desktop vs. lite and it worked. I ran a ffmpeg conversion test and it said it ran at 0.6 speed so not sure why it works fine on my ios client in real time. So this probably means I just need to either activate something graphics display related or run the full debian 10 image. Any ideas?

**Comment by JugglerMaster** [comment]
I found the issue, I followed the guide to install the Openjdk-8-jre but you have to do the jdk for video to work. 100% fixed now!

Christopher Dadisman

On Aug 15, 2019, at 7:26 PM, Evan Harris <notifications@github.com<mailto:notifications@github.com>> wrote:


I would not be surprised at all if a RPi doesn't have enough cpu power to do live transcoding of video. Perhaps the client you are using realizes this and never allows it to play rather than "stuttering"?

Have you tried running an identical ffmpeg transcoding command manually on that hardware and verifying that the transcode completes in significantly less time than the video length?
