### ISSUE TITLE
Airsonic to reciever?

### ISSUE THREAD

**Issue by tctfox** [airsonic/airsonic#1225]
Not really an issue, rather a question. Is it possible to stream music to a reciever that has airplay etc via airsonic?

**Comment by jvoisin** [comment]
I don't think that we support Airplay, but we do support Google's cast™ protocol.

**Comment by tctfox** [comment]
Thanks for the quick reply

**Comment by eharris** [comment]
I'm sure a pull request to add Airplay support would be welcome.
