### ISSUE TITLE
Index not scanned automatically after update to lucene 8.2.0.

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#1234]
According to the intent, the index should be scanned automatically:

```java
    @PostConstruct
    public void init() {
        indexManager.initializeIndexDirectory();
        statistics = settingsService.getMediaLibraryStatistics();
        schedule();
    }
```

```java
    public synchronized void schedule() {
        if (timer != null) {
            timer.cancel();
        }
        timer = new Timer(true);

        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                scanLibrary();
            }
        };

        long daysBetween = settingsService.getIndexCreationInterval();
        int hour = settingsService.getIndexCreationHour();

        if (daysBetween == -1) {
            LOG.info("Automatic media scanning disabled.");
            return;
        }

        Date now = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(now);
        cal.set(Calendar.HOUR_OF_DAY, hour);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);

        if (cal.getTime().before(now)) {
            cal.add(Calendar.DATE, 1);
        }

        Date firstTime = cal.getTime();
        long period = daysBetween * 24L * 3600L * 1000L;
        timer.schedule(task, firstTime, period);

        LOG.info("Automatic media library scanning scheduled to run every " + daysBetween + " day(s), starting at " + firstTime);

        // In addition, create index immediately if it doesn't exist on disk.
        if (settingsService.getLastScanned() == null) {
            LOG.info("Media library never scanned. Doing it now.");
            scanLibrary();
        }
    }
```

So it looks like we need to tweak the `if it doesn't exist on disk` logic.

**Comment by tesshucom** [comment]
I get the point. 
Let's fix it.

**Comment by muff1nman** [comment]
I'm wondering if it makes sense to store the index metadata like scan date inside the index itself. I don't like the idea of storing it in the property file.

**Comment by tesshucom** [comment]
I checked a little, but it is difficult to reproduce.
If we start Airsonic with empty data, an empty scan will be performed.
If the schedule is validated from the fsat start, the date should be shifted by approximately 2 days.
Because there is a determination of lastscan.

If shift it for two days, this will appear to work.
There seems to be no problem when switching from an existing data environment.
(There may be an opinion that it is unnatural whether to count the first-time empty scan.)

As for the save destination, there may be a idea to save it in DB or eject it to yaml cron file with SpringTask.
Of course, there is a idea to add to the index.
Cool in terms of modernization.

I think that the original code is written in this way may have the intention of not depending on a specific product.
We don't know what happens if we can't read it.

Considering the certainty of whether or not the task has been executed, It must be quite close to the current implementation.
(Status at the time of implementation)

**Comment by tesshucom** [comment]
wmm ..

I compared 8e279a2 (before) and 5c3c558 (after) but It worked the same way.
it doesn't seem to be reproduced.

 - Perform the first startup (At this time, the first scan is automatically performed.)
 - Set the desired scan time on the settings screen.
 - Stop Server (JVM)
 - Stagger the system time. At this time, set 24 hours or more after the first scan and immediately before the set scan time.
 - Start the server and wait for scan execution. Make sure it works.
 - Stop Server (JVM)
 - Shift the system time. Set immediately before the scan time set for the next day
 - Start the server and wait for scan execution. Make sure it works.
 - Stop Server (JVM)....repetition

The schedule setting is set to be shifted by one day in consideration of the first activation at MediaScannerService#schedule(). 
```
        if (cal.getTime().before(now)) {
            cal.add(Calendar.DATE, 1);
        }
```
I think the operation is consistent (It's complicated but ...).
5c3c558 does not contain a fix that seems to be relevant.

**Comment by tesshucom** [comment]
wmm ..

I compared 8e279a2 (before) and 5c3c558 (after) but It worked the same way.
it doesn't seem to be reproduced.

 - Perform the first startup (At this time, the first scan is automatically performed.)
 - Set the desired scan time on the settings screen.
 - Stop Server (JVM)
 - Stagger the system time. At this time, set 24 hours or more after the time setting  scan time, and immediately before the set scan time.
 - Start the server and wait for scan execution. Make sure it works.
 - Stop Server (JVM)
 - Shift the system time. Set immediately before the scan time set for the next day
 - Start the server and wait for scan execution. Make sure it works.
 - Stop Server (JVM)....repetition

The schedule setting is set to be shifted by one day in consideration of the first activation at MediaScannerService#schedule(). 
```
        if (cal.getTime().before(now)) {
            cal.add(Calendar.DATE, 1);
        }
```
I think the operation is consistent (It's complicated but ...).
5c3c558 does not contain a fix that seems to be relevant.

**Comment by muff1nman** [comment]
I don't think that test case will trigger the issue. I ran into issues with the following:

1. Delete index.
2. Start up airsonic 10.4.0
3. Ensure index is created and function
4. Shutdown and startup airsonic on master
5. See if index is scanned automatically.
