### ISSUE TITLE
CSS file causes fetch for nonexistent spin.png

### ISSUE THREAD

**Issue by eharris** [airsonic/airsonic#1256]
## Problem description

I noticed in the web console that browsing pages using the webapp causes a failed fetch for `/script/spin.png` on just about every page load.

`jquery-3.4.0.min.js:2 GET https://someserver.name/script/spin.png 404 (Not Found)`

After further investigation, it looks like this was caused by change 15a1e5e7d63083f7b11a041d9ce877dc3b5a696f where `#` was used on some added lines.  Perhaps that was meant to be a comment, and just used the wrong comment style?

**Comment by jvoisin** [comment]
```
$ git grep spin.png
airsonic-main/src/main/webapp/style/default-without-mediaelement.css:461:#zoom_spin { position: absolute; display: none; z-index: 525; width: 50px; height: 50px; background: url(/script/spin.png) no-repeat; }
$
```

I think that it can safely be removed.

**Comment by Row** [comment]
This is not reproducible, there is no error, and the spin.png is in use. `#zoom_spin` in CSS refers id selector with the id zoom_spin, and the jQuery script `airsonic/airsonic-main/src/main/webapp/script/jquery.fancyzoom.js` applies the id `zoom_spin` to a dynamically created element. This functionality is used when clicking album covers.

**Comment by eharris** [comment]
The problem is that Airsonic is installed under `/airsonic/`, so the `/script/` path (note these are absolute, not relative) is outside of Airsonic's install, which makes fetching `spin.png` from that path incorrect.

**Comment by Row** [comment]
While you're at it, perhaps you should format the long CSS lines.
