### ISSUE TITLE
Signing key is expired

### ISSUE THREAD

**Issue by Amgine0** [airsonic/airsonic#1257]
## Problem description
Signing key for Andrew DeMaria is expired.

### Steps to reproduce

1. Follow steps at [Tomcat WAR Installation](https://airsonic.github.io/docs/install/war-tomcat/) to import Andrew DeMaria public key.
2. Download signed checksum
2. Verify
```bash
$ gpg --verify artifacts-checksums.sha.asc
gpg: Signature made Sat 13 Jul 2019 05:04:09 PM PDT
gpg:                using RSA key F7E5D48CF5F4061684A626200A3F5E91F8364EDF
gpg: Good signature from "Andrew DeMaria (Colorado Hacker) <lostonamountain@gmail.com>" [expired]
gpg:                 aka "Andrew DeMaria (Work) <ademaria@redhat.com>" [expired]
gpg:                 aka "Andrew DeMaria (Work) <ademaria@credera.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: F7E5 D48C F5F4 0616 84A6  2620 0A3F 5E91 F836 4EDF
```

## System information

 * **Airsonic version**: *the version listed on the About page*
    * n/a
 * **Operating system**: *the operating system you're running Airsonic on.
   Linux, what distribution; Windows or Mac, what version?*
    * Raspbian GNU/Linux 10 (buster)
 * **Java version**: *the Java version your using to run Airsonic.*
    * OpenJDK 11
 * **Proxy server**: *if running Airsonic behind a proxy, what server and
   version? Otherwise,* None
    * eventually nginx
 * **Client**: *what browser and version you use to access the Airsonic web
   interface, or the name and version of another app you're using.*
    * n/a

**Comment by muff1nman** [comment]
Should be fixed now: http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0x0A3F5E91F8364EDF.
