### ISSUE TITLE
Subsonic api doesn't provide ArtistId for some songs

### ISSUE THREAD

**Issue by Superpiffer** [airsonic/airsonic#1260]
For some of my songs, expecially "non album tracks", Subsonic API doesn't provide ArtistId in json or xml response, because I think that Airsonic doesn't assign one to this tracks in the first place. 
One example:
```
{
	"album": "[non-album tracks]",
	"albumId": "79",
	"artist": "Blues Brothers",
	"bitRate": 128,
	"contentType": "audio/mpeg",
	"created": "2019-05-29T14:05:00.000Z",
	"duration": 472,
	"id": "1342",
	"isDir": false,
	"isVideo": false,
	"parent": "32",
	"path": "Single/Blues Brothers - Sweet Home Chicago.mp3",
	"playCount": 0,
	"size": 7561361,
	"suffix": "mp3",
	"title": "Sweet Home Chicago",
	"type": "music"
}
```

In this condition, Strawberry player cannot add this songs (https://github.com/jonaski/strawberry/issues/266#issuecomment-533978641).
I don't know if this is an expected behaviour or not.

**Comment by eharris** [comment]
Based on my reading of the API specs, `artistId` seems to only be used when navigating files by tag info, and so the presence/absence of an `artistId` is probably very much dependent on the files containing good tag info.  Make sure that your files are well-tagged (MusicBrainz Picard is a good option for this) and that will probably resolve this issue.

**Comment by Superpiffer** [comment]
The developer of the player solved the problem for me, avoiding the need of the ArtistId tag during the import. Anyway I use beets for tagging but some of my tracks are unknown albums or random single songs that I want to keep in one folder.
Also I wanted to report that the artists of the songs with this issue doesn't show up in the list  on the left bar in Airsonic, youncan only found it by searching, so maybe can be an minor issue.
Thanks.

**Comment by tesshucom** [comment]
It looks like it's resolved, so I'll close it.
If you have any problems, please report again.

**Comment by tesshucom** [comment]
It looks like it's resolved, so I'll close it.
If you have any problems, please report again.
