### ISSUE TITLE
Compile instructions for latest release 10.4.0 no longer work

### ISSUE THREAD

**Issue by yohan-b** [airsonic/airsonic#1277]
It is no longer possible to compile the latest release as written in the documentation (https://airsonic.github.io/docs/install/source/) :
```
git checkout v10.4.0
mvn clean package
```
This is because teleal.org is dead.
pom.xml must be edited that way:

```diff
diff --git a/pom.xml b/pom.xml
index 9b1bedb4..73a5c2fa 100644
--- a/pom.xml
+++ b/pom.xml
@@ -33,9 +33,11 @@
             <url>https://download.java.net/maven/2/</url>
         </repository>
         <repository>
-            <id>teleal</id>
-            <name>teleal</name>
-            <url>http://teleal.org/m2</url>
+          <id>4thline-repo</id>
+          <url>http://4thline.org/m2</url>
+          <snapshots>
+              <enabled>false</enabled>
+          </snapshots>
         </repository>
         <repository>
             <id>jaudiotagger-repository</id>
```

Not sure if it is worth updating the documentation, but at least there should be a note about it somewhere. So this is it.

**Comment by yohan-b** [comment]
I forgot that you also need to skip tests as mentioned here: https://github.com/airsonic/airsonic/issues/1163
`mvn clean package -DskipTests`

**Comment by jvoisin** [comment]
I guess that this will be automatically fixed by the next release?

**Comment by yohan-b** [comment]
Yes. :-)

**Comment by fxthomas** [comment]
Might as well close it, 10.4.1 has been out for a while!
