### ISSUE TITLE
Get rid of airsonic's custom Pair implementation

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1283]
Airsonic has its [own implementation]( https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/util/Pair.java ) of `Pair`.
It also has a second one, named []( https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/command/EnumHolder.java )

It would be nice to replace them all with the one from [apache commons]( https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/tuple/Pair.html ).

**Comment by h93xV2** [comment]
I will do this. Can you assign this issue to me?

**Comment by jvoisin** [comment]
Done in 78480ab7
