### ISSUE TITLE
Get rid of airsonic's custom circular buffer implementation 

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1284]
Airsonic has its [own implementation]( https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/util/BoundedList.java ) of a circular buffer.

It would be nice to replace it with [either]( https://stackoverflow.com/questions/5498865/size-limited-queue-that-holds-last-n-elements-in-java ) the one from Apache Commons or Guava.

**Comment by kessiler** [comment]
Hi @jvoisin, I can take this.

**Comment by jvoisin** [comment]
Thanks!
