### ISSUE TITLE
Illegal reflective access operation: Java 11 warning on airsonic start 

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#1297]
## Problem description

Java is raising a warning on airsonic start. 

### Steps to reproduce

1. Install airsonic as standalone package
2. Start airsonic

## System information

 * **Airsonic version**: 10.4.0
 * **Operating system**: Debian Buster 10
 * **Java version**: OpenJDK 11 JRE

## Additional notes

Here is what Java says:

```
Oct 09 16:06:39 audio-auk java[26817]: WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/opt/airsonic/airsonic.war!/WEB-INF/
Oct 09 16:06:39 audio-auk java[26817]: WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
Oct 09 16:06:39 audio-auk java[26817]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Oct 09 16:06:39 audio-auk java[26817]: WARNING: All illegal access operations will be denied in a future release
```

**Comment by jooola** [comment]
https://github.com/spring-projects/spring-framework/issues/22674
This is what I found, seems spring needs to be upgraded.

**Comment by muff1nman** [comment]
Will be remedied when we upgrade to spring 2.x which is in progress.

**Comment by eharris** [comment]
I believe this has been fixed, as I recently upgraded to Java 11 and do not get this error from that component with current master.
