### ISSUE TITLE
Logout link not clickable (10.5.0-SNAPSHOT – 9th of oct)

### ISSUE THREAD

**Issue by masterblaster79** [airsonic/airsonic#1305]
## Problem description

The logout link on the right side of the top.view is not clickable anymore (Verified with Firefox and Edge browsers).

### Steps to reproduce

1. Deploy latest snapshot
2. Login
3. Try to logout

## System information

 * **Airsonic version**: *10.5.0-SNAPSHOT – 9. Oktober 2019*
 * **Operating system**: *Apache Tomcat/9.0.16 (Debian), java 11.0.4, Linux a20 5.2.0-0.bpo.3-armmp-lpae #1 SMP Debian 5.2.17-1~bpo10+1 (2019-09-30) armv7l GNU/Linux*
 * **Java version**: *11.0.4*
 * **Proxy server**: *Nginx*
 * **Client**: *Firefox*
 * **Language**: *DE*

## Additional notes
Maybe related to this:
https://github.com/airsonic/airsonic/commit/53d835e6ede69ffc9d7adfb0098f63002cae49c9
https://github.com/airsonic/airsonic/issues/1178

**Comment by fxthomas** [comment]
Can confirm!

**Comment by eharris** [comment]
That's strange.  It works fine here.

**Comment by eharris** [comment]
Tested fine here with both Firefox and Chrome.  I'm on a different java version tho.  Perhaps this is a Java 11 issue?  Anything useful in developer console in the browser?

**Comment by fxthomas** [comment]
Apparently Firefox is picky with having one `<a>` tag inside another?

![Screenshot from 2019-10-11 22-50-36](https://user-images.githubusercontent.com/613594/66684132-9e260300-ec79-11e9-8b7b-f8f73ea32c62.png)

**Comment by eharris** [comment]
Ah, that's only a problem if you have an avatar configured (there's a conditional in the template).  That's why it didn't show up here.

**Comment by eharris** [comment]
Confirmed here, just configured an avatar and now the logout link is broken.

**Comment by eharris** [comment]
So the question now is how do we want to fix it?  Personally I don't like the action for a top level icon changing based on whether an avatar image is configured or not, so I'd just remove the link to the personal settings page.

**Comment by fxthomas** [comment]
Can we add a generic icon?

**Comment by eharris** [comment]
There is a generic icon, but it is currently replaced with the avatar icon if one is configured.

**Comment by fxthomas** [comment]
Personally, I would think that "click on profile icon to get user profile settings" is a widely-spread pattern. So, it's not so bad? But ideally we should link to the user profile even if no avatar is configured.

**Comment by eharris** [comment]
Except that when it's not an avatar it's a logout icon, and going to the user settings page doesn't make sense there.

**Comment by fxthomas** [comment]
Ah... duh. Can we replace it with a "unknown avatar" icon? This would make more sense, and still keep the user profile somewhat accessible.

**Comment by eharris** [comment]
I'm playing with just keeping the logout icon there always, and making the user avatar be next to it.
