### ISSUE TITLE
Multiple JSON parsers

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1311]
Currently, in airsonic, to parse json, we have:

- com.jayway.jsonpath
- com.fasterxml.jackson.databind.JsonNode
- com.fasterxml.jackson.core.JsonProcessingException

and I started to work on #1282 and #1247 to replace jackson2 by javax.json, because jackson2's jackson-databind is [terrible security-wise]( https://www.cvedetails.com/product/42991/Fasterxml-Jackson-databind.html?vendor_id=15866 ), but @muff1nman (rightfully) disagreed, and suggested that, since Spring is depending on jackson2, we should use it everywhere.

I'm entirely fine with this, and do volunteer to nuke all the other json things that we have lying around, as long as I can kick jackson-databind out to.

Thoughts?

**Comment by eharris** [comment]
I think it's a good idea to consolidate down to one instead of 3 or 4.  If we are already forced to use jackson2 because of spring, might as well just use it.

**Comment by fxthomas** [comment]
Agreed. The less dependencies the better!

**Comment by randomnicode** [comment]
Sorry for arriving late to the party, but a minor (and perhaps moot) point: JsonPath and Jackson are not equivalent.

- Jackson is a _databinding library_. You serialize and deserialize data with it. Usually string, either json or xml, to a POJO (a java object) and vice versa. You need a databinding library every time a request comes into application to deserialize it into an object, and every time you return an object that goes out (from say a Controller).
- JsonPath is the json equivalent of XPath (which is for XML). It is a _query language_ for json. You can use it to query for objects in a json document (like you use SQL to query in relational dbs).

They're orthogonal libraries with different concerns.

I mostly just looked cursorily through the aforementioned PRs, but it seems we are only tangentially using JsonPath (to parse the version from github), and we can maybe do without it. I'll leave some comments on the PR.

In terms of a databinding library, we cannot do without one. My vote is to use Jackson, similar to @muff1nman .

While JSR 367 provides the JSON binding api (Yasson is the reference implementation), we're (a) free to not use it, and (b) we still need an implementation (which I assume will be Yasson if we choose to go down that route)

**Comment by fxthomas** [comment]
Thank you, that's actually informative, I only had a cursory look at both libraries and was not aware of the differences between them.

**Comment by jvoisin** [comment]
Done in faa49737
