### ISSUE TITLE
10.4.0 -> 10.4.1: 404 Not found after Update

### ISSUE THREAD

**Issue by phrapow0rl** [airsonic/airsonic#1333]
## Problem description

Hi there,

i just replaced my airsonic.war with the newest 10.4.1 release from this github repos releases. After restarting the tomcat service and browsing to my airsonic installation with chrome, i had to notice a generic tomcat generated 404 error. the airsonic.log-File on my C:-Drive spits lots of liquibase checksum errors

### Steps to reproduce

1. Stop running Apache tomcat service
2. replace airsonic.war in webapps folter of apache
3. Start Apache tomcat service
4. Browse to airsonic with webbrwoser, wait for 404

## System information

 * **Airsonic version**: before: 10.4.0, after: 10.4.1
 * **Operating system**: Windows Server 2016
 * **Java version**: 1.8.0_211
 * **Proxy server**: nginx reverse proxy
 * **Client**: Chrome - current version
 * **Language**: german browser and OS

## Additional notes

Do I need to do anything else than replacing the war-file to update to the current release?  
[airsonic.log](https://github.com/airsonic/airsonic/files/3731325/airsonic.log)

**Comment by fxthomas** [comment]
Do you use MariaDB/MySQL? Which version?

**Comment by phrapow0rl** [comment]
Hi @fxthomas,
yes, I do use MariaDB - for quiet a long time now. 

```
SELECT
	VERSION();
```
says: 10.3.8-MariaDB

**Comment by fxthomas** [comment]
Summoning known MariaDB residents then (@jooola, @Celedhrim ).

I can mark previous migrations as valid, but do you know if we should consider the result of a successful migration done before #1188 as correct, or could it cause issues down the line for some queries in some MariaDB versions? Which versions couldn't use Airsonic at all before #1188?

**Comment by muff1nman** [comment]
@phrapow0rl did you run a modified version of airsonic prior to #1188 in order to get maria db working?

**Comment by Celedhrim** [comment]
Hi !

I have never use airsonic , I'm on subsonic.

Before summer , when I try to migrate from subsonic to airsonic , I faced mariadb issue.

Now that mariadb is supported with 10.4.1 , I tried to test another time , but I have 404 , even without mysql backend

**Comment by phrapow0rl** [comment]
@muff1nman no, I cant remember any modification I did to the mysql/mariadb/hsql part of airsonic. I sadly cant give you a straight answer to that question, because i did some modifications on another airsonic instance running with the same mariadb backend. I did some minor modifications to the sql schema itself, mostly added some indices, to speed up querys, but as far as I remember, I never touched the mysql/db handling insinde airsonic. But while modifying a seperated airsonic instance, a "proper" release has always been running too (without any problems).

Does this answers your question apropriate?

**Comment by fxthomas** [comment]
@phrapow0rl Can you share your database configuration settings in `airsonic.properties`?

For reference @Neogrey had this in #1347:

```
DatabaseConfigType=embed
DatabaseConfigEmbedDriver=com.mysql.jdbc.Driver
DatabaseConfigEmbedUrl=jdbc:mysql://192.168.1.22:3306/airsonic
DatabaseConfigEmbedUsername=airsonic
DatabaseConfigEmbedPassword=xxxxx-pw-xxxxxx
```

**Comment by fxthomas** [comment]
Can any of you test https://github.com/fxthomas/airsonic/releases/tag/10.4.1-fix-1333 ? I'd like to know if it works on your end.

**Comment by Neogrey** [comment]
@fxthomas about your question. My only modification was convert the database entries to utf8 (character) and utf8_general_ci (collate) because with the default character/collate there was some issue. 

If I remember correctly, my first installation was 10.2.1 and my next update was then 10.4.0. I was using until yesterday the following airsonic.properties:
```
DatabaseMysqlMaxlength=512
DatabaseConfigType=embed
DatabaseConfigEmbedDriver=org.mariadb.jdbc.Driver
DatabaseConfigEmbedUrl=jdbc:mysql://192.168.1.22:3306/airsonic?sessionVariables=sql_mode=ANSI_QUOTES&useSSL=false
DatabaseConfigEmbedUsername=airsonic
DatabaseConfigEmbedPassword=---------pw------------
```

But with following airsonic.properties and 10.4.0, as well works fine for me.  
```
DatabaseConfigType=embed
DatabaseConfigEmbedDriver=com.mysql.jdbc.Driver
DatabaseConfigEmbedUrl=jdbc:mysql://192.168.1.22:3306/airsonic
DatabaseConfigEmbedUsername=airsonic
DatabaseConfigEmbedPassword=xxxxx-pw-xxxxxx
```

**Comment by fxthomas** [comment]
@phrapow0rl Can you also test this and tell us if everything works for you on the new build over at #1352?
