### ISSUE TITLE
Clients get empty albums

### ISSUE THREAD

**Issue by mase76** [airsonic/airsonic#1341]
## Problem description

When I open an album in a client like Clementine on Linux, or UltraSonic on Android, the album is empty (no media), until I opened the album once in the webif. After that I can open the album as expected. As database I use Mariadb.

 * **Airsonic version**:  10.4.1
 * **Operating system**: Debian Gnu / Linux 10
 * **Java version**: OpenJDK 11
 * **Proxy server**: Nginx, but also tried direct access
 * **Client**: Every client using the api. Tested with clementine (Linux), UltraSonic and Audinaut (Android)

**Comment by eharris** [comment]
Are you sure that you've scanned your media library?  This seems like it might be an issue where you haven't done a library scan on those directories yet.

**Comment by mase76** [comment]
Yes, I scanned the library. It works as it should in the Webif. There are only problems with clients.

**Comment by mase76** [comment]
I deleted my database tables and started from scratch. Still the same issue.

**Comment by mase76** [comment]
I dropped my whole config and the database. Built from scratch and now it seems to work.
