### ISSUE TITLE
Database (MariaDB) issue with 10.4.1

### ISSUE THREAD

**Issue by Neogrey** [airsonic/airsonic#1347]
## Problem description

After updating to 10.4.1 some errors/issue appears with the external database, rollback to 10.4.0 and there is no issue.

I saw that there some mariadb changes with airsonic 10.4.1, would suspect it's related with that?. 

### Steps to reproduce

1. docker rm airsonic
2. docker pull linuxserver/airsonic
3. docker create [...] linuxserver/airsonic
4. docker start airsonic

## System information

 * **Airsonic version**: 10.4.1
 * **Operating system**: Debian 10.1
 * **Java version**: 1.8.0_222
 * **Proxy server**: None
 * **Client**: Firefox ESR 68.1
 * **Language**: German
 * **MariaDB version**: 10.3.18 (linuxserver/mariadb)

## Additional notes
airsonic.properties
```
DatabaseConfigType=embed
DatabaseConfigEmbedDriver=com.mysql.jdbc.Driver
DatabaseConfigEmbedUrl=jdbc:mysql://192.168.1.22:3306/airsonic
DatabaseConfigEmbedUsername=airsonic
DatabaseConfigEmbedPassword=xxxxx-pw-xxxxxx
```
Log after updating to 10.4.1 [airsonic_10_4_1.log](https://github.com/airsonic/airsonic/files/3747166/airsonic_10_4_1.log)
Log after rollback to 10.4.0 [airsonic_10_4_0.log](https://github.com/airsonic/airsonic/files/3747167/airsonic_10_4_0.log)

**Comment by Neogrey** [comment]
Hmmm could be the same issue #1333 ?

**Comment by fxthomas** [comment]
Yes, it looks like it's the same issue. I'll go ahead and close this one if that's okay with you?

Can you comment on the other one on whether you did some manual actions to have MariaDB support on previous releases?
