### ISSUE TITLE
Upgrade Lucene to improve Unicode handling

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#135]
<a href="https://github.com/fxthomas"><img src="https://avatars0.githubusercontent.com/u/613594?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fxthomas](https://github.com/fxthomas)**
_Wednesday Nov 02, 2016 at 21:48 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/135_

----

According to the [docs](https://lucene.apache.org/core/4_2_0/analyzers-common/org/apache/lucene/analysis/standard/StandardAnalyzer.html), more recent Lucene versions handle Unicode character segmentation much better than the current (3.0.3), which could come in handy for collections that have a lot of such characters, including mine.

The latest version is 6.0, but maybe that's a bit much. Can we upgrade at least to 3.6?

**Comment by fxthomas** [comment]
Doing some cleanups, I think I'll close that one given we already upgraded Lucene! Thank you @tesshucom for the work :wink:
