### ISSUE TITLE
No testing of MariaDB/PostgreSQL support

### ISSUE THREAD

**Issue by fxthomas** [airsonic/airsonic#1351]
We don't currently test external databases. Since we use Docker, it could be a good idea to add integration tests for them in our test suite?

See https://github.com/airsonic/airsonic/issues/1333 for an example of an issue caused by not testing this.

**Comment by tesshucom** [comment]
If adding to the integration test is a small burden, that's fine.
If you are concerned about the increase in build time, you may be able to deal with parallel processing, such as creating a single task using travis and running it in LTS Java11 only.

I think the test itself is absolutely necessary.
There is no immediate need for an exhaustive one, but there should be a place to add a corresponding test when an issue is raised.

We should not overtrust reviews.
Only testing can ultimately guarantee stability.

**Comment by tesshucom** [comment]
Close this issue because #1351 is open.
The current testing method is different than when this issue was opened.

**Comment by tesshucom** [comment]
Close this issue because #1363 is open.
The current testing method is different than when this issue was opened.
