### ISSUE TITLE
How to set a new language translation

### ISSUE THREAD

**Issue by prschopf** [airsonic/airsonic#1395]
## Problem description

Airsonic is completely translated to Portuguese-Brazil (pt_BR) but it doesnt show up in Airsonic Server as an option in Settings->General->Default language. Translation is here: https://hosted.weblate.org/translate/airsonic/airsonic/pt_BR/?type=all

### Steps to reproduce

Go to https://hosted.weblate.org/translate/airsonic/airsonic/pt_BR/?type=all

## System information

 * **Airsonic version**: 10.4.2-RELEASE – October 23, 2019
 * **Operating system**: Centos 6.10
 * **Java version**: OpenJDK Runtime Environment (build 1.8.0_232-b09)
 * **Proxy server**: None
 * **Client**: Chrome 78.0.3904.87 in Windows 7 32 bits.
 * **Language**: Portuguese-Brazil in Chrome and English in Airsonic

## Additional notes

If weblate is not used anymore for translations, where translations are being done?

**Comment by fxthomas** [comment]
Mostly Weblate needs to be merged into the development branch. I believe https://github.com/airsonic/airsonic/pull/1263 is doing this?

**Comment by fxthomas** [comment]
Closing since #1397 has been merged, congrats on your first PR :wink:
