### ISSUE TITLE
Download page is no longer working

### ISSUE THREAD

**Issue by fxthomas** [airsonic/airsonic#1399]
The download page at https://airsonic.github.io/download/ (used in the "new version available" link in the main UI) is no longer working.

**Comment by jooola** [comment]
Gonna add a redirection. Still this needs to be changed in the translation files

**Comment by jooola** [comment]
Fixed in https://github.com/airsonic/airsonic.github.io/commit/f7ba82093f1d7681cfb7db4092d3828717a8f577
