### ISSUE TITLE
Airsonic uses 100% of a core on JDK 13

### ISSUE THREAD

**Issue by protist** [airsonic/airsonic#1401]
## Problem description

I just updated Airsonic from 10.4.2 to 10.5.0. It's now uses 100% of one core. There is nothing in the logs. This occurs even without the web GUI being accessed. I let it run overnight, but it was still 100% in the morning. I've also tried restarting the server, but there was no change.

### Steps to reproduce

1. Update Airsonic to 10.5.0
2. Inspect the CPU usage

## System information

 * **Airsonic version**: 10.5.0-RELEASE – November 7, 2019
 * **Operating system**: Arch Linux ARM, on a Raspberry Pi
 * **Java version**: jre-openjdk-headless 13.0.1.u9-1
 * **Proxy server**: None
 * **Client**: N/A (but Firefox)
 * **Language**: English

## Additional notes

Happy to troubleshoot more of course, but not sure what to do.

**Comment by muff1nman** [comment]
First thoughts:

1. Have you tried an older jdk?
2. Can you take a thread dump and share the results (I usually use `kill -3` but here's a whole article https://access.redhat.com/solutions/18178)

**Comment by protist** [comment]
I downgraded from `jre-openjdk-headless 13.0.1.u9-1` -> `jre11-openjdk-headless 11.0.5.u10-1`, and it's fine now. I'm happy to troubleshoot more if you'd like. Personally, I'm happy using whichever version works best for airsonic (it's the only package requiring java on my server).

**Comment by fxthomas** [comment]
I've been running `jre-openjdk-headless 13.0.1.u9-1` for about as long as it's been made available on the repositories, without experiencing any issues.

It could be related to the db driver though, what database are you using?

**Comment by protist** [comment]
> It could be related to the db driver though, what database are you using?

I'm just using the default HSQLDB database.

**Comment by fxthomas** [comment]
Hmm, then I have no idea ; the thread dump might get us some more information as to what exactly Airsonic is doing.

**Comment by ice954pw** [comment]
Been running JVM13 haven't experienced this, 10tb library.

**Comment by Whisprin** [comment]
I'm encountering the same problem here on Arch Linux x86 (Intel): High CPU on all 4 cores

After downgrading Java to 11 everything is fine

**Comment by protist** [comment]
@Whisprin I'm not using the Jukebox.

P.S. if you edit to tag me, then I don't get notified.

**Comment by protist** [comment]
I'm now using Airsonic with the latest Java 14, which works fine. Arch doesn't have the Java 13 package any more, so I guess I'll just close this issue.
