### ISSUE TITLE
Ubuntu 16.04/Tomcat 8.0.32 - HTTP 500 at login screen >= v10.4.2

### ISSUE THREAD

**Issue by 4oo4** [airsonic/airsonic#1403]
## Problem description

I have had issues with running Airsonic 10.4.2 and 10.5.0, where the builds appear to succeed but when I reload tomcat it gives me an HTTP 500 error on the login screen (see gist). As soon as I downgrade back to 10.4.1 I don't encounter the issue anymore. Both of the two newest versions throw up the same error. The only thing I can potentially think of is that my maven and/or tomcat are super out of date?

### Steps to reproduce
1. Clone airsonic repo
2. Run `mvn clean package`
3. Reload tomcat8 with new .war file

## System information

 * **Airsonic version**: 10.4.2, 10.5.0
 * **Operating system**: Ubuntu 16.04
 * **Java version**: openjdk-8 uu222b10 / tomcat 8.0.32 / maven 3.3.9
 * **Proxy server**: nginx 1.17.4
 * **Client**: Airsonic web, Firefox 70.0.0.1
 * **Language**: en_US

## Additional notes
`catalina.out`: https://gist.github.com/4oo4/c34d7294d0ea453f57036268ef0bf20a

**Comment by 4oo4** [comment]
Just tested the pre-build .war for 10.5.0 and get the exact same result, so doesn't appear to be an issue with the build itself.

**Comment by randomnicode** [comment]
Not an issue with maven, I think maybe it's an issue with your tomcat? I believe we are compiling with 8.5.x, whereas you seem to be using 8.0.x. Maybe worth upgrading tomcat and seeing if that fixes the issue?

**Comment by 4oo4** [comment]
Thanks, I'll give that a try and let you know. It might also be helpful to add a minimum tomcat version in the docs somewhere, I don't think I saw anything like that when researching.

**Comment by 4oo4** [comment]
@randomnicode Yep that was definitely it, I made a PR to add the minimum tomcat version.

https://github.com/airsonic/airsonic-docs/pull/81

Cheers
