### ISSUE TITLE
systemd example doesn't work

### ISSUE THREAD

**Issue by dorel14** [airsonic/airsonic#1417]
## Problem description

I've installed airsonic with help of the docs
Download systemd file from doc link , when i try to run it as service , systemd crashes with this error

 airsonic.service: Failed at step USER spawning /usr/bin/java: Invalid argument

### Steps to reproduce

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

1. Intall in standalone mode ike described in doc
2. *Enable the service
3. *run service airsonic start
4; Look at service airsonic status

## System information

 * **Airsonic version**: *10.5*
 * **Operating system**: *Debian 9.
   
 * **Java version**: *OpenJDK 1.8.*
 * **Proxy server**: *None

**Comment by fxthomas** [comment]
Is this maybe https://superuser.com/questions/1156676/what-causes-systemd-failed-at-step-user-spawning-usr-sbin-opendkim-no-such-p ?

**Comment by dorel14** [comment]
I don't know , finally i installa airsonic with tomcat and it's working .

**Comment by fxthomas** [comment]
Ah, glad to know you managed to make it work!
