### ISSUE TITLE
Toggle play queue by clicking on a link/button

### ISSUE THREAD

**Issue by fxthomas** [airsonic/airsonic#1421]
What do y'all think of adding something like ▼ (Hide) on the right next to the song count/duration label, and make this clickable so that the user can manually hide/close the play queue?

Play queue shown:

![Screenshot from 2019-11-28 22-34-54](https://user-images.githubusercontent.com/613594/69832591-8279ba80-122f-11ea-8375-77adfa8f559a.png)

Play queue hidden:

![Screenshot from 2019-11-28 22-33-52](https://user-images.githubusercontent.com/613594/69832599-932a3080-122f-11ea-830b-6a076c80f352.png)

**Comment by eharris** [comment]
I like it.  My only (minor) concern is for the impact when users have a narrower window.

**Comment by fxthomas** [comment]
Yup, it's a bit unfortunate... In any case Airsonic is not very usable anyway if your width is less than, say, 800-900 px.

**Comment by jvoisin** [comment]
Other players (soundcloud, …) are doing this, and I like it.
But I think that it should be a bit more visible.

**Comment by fxthomas** [comment]
Thanks bot, I think we can close it :wink:
