### ISSUE TITLE
New Transcode playback failing.

### ISSUE THREAD

**Issue by nx6** [airsonic/airsonic#1423]
## Problem description

I'm having trouble with playback on the web player when the song needs to be transcoded. Only a portion of the track plays and then things just kinda drop.

### Steps to reproduce

1. *Start playing a longer (5+ minute) song*
2. *Do nothing*
3. *Wait between 2 and 4 minutes for the playback to stop*

Note: These are not FLAC files like those other Issues seem to be about.

## System information

 * **Airsonic version**: 10.5.0-RELEASE
 * **Operating system**: FreeBSD 11.2-RELEASE-p9
 * **Java version**: Apache Tomcat/8.5.43, java 1.8.0_192,
 * **Proxy server**: nginx 1.16.1 -- but it happens when I play direct by LAN IP, too.
 * **Client**: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3

 * **Language**: en-US

## Additional notes

Logs:

2019-12-02 20:23:53.057  INFO ---  o.a.p.io.PlayQueueInputStream            : 192.168.9.254: admin  listening to October Rust/08 Die With Me.m4a
2019-12-02 20:23:53.063  INFO ---  o.a.p.io.TranscodeInputStream            : Starting transcoder:  [/var/airsonic/transcode/ffmpeg] [-i] [/MUSIC/Type O Negative/October  Rust/08 Die With Me.m4a] [-map] [0:0] [-b:a] [192k] [-v] [0] [-f] [mp3]  [-]
2019-12-02 20:25:58.101  INFO ---  o.a.p.c.StreamController                 : 192.168.9.254: Client  unexpectedly closed connection while loading  http://192.168.9.226:4040/airsonic/stream?player=2&id=19557  (java.net.SocketTimeoutException)
2019-12-02 20:29:23.613  INFO ---  o.a.p.io.PlayQueueInputStream            : 192.168.9.254: admin  listening to Pop/01 Discotheque.m4a
2019-12-02 20:29:23.617  INFO ---  o.a.p.io.TranscodeInputStream            : Starting transcoder:  [/var/airsonic/transcode/ffmpeg] [-i] [/MUSIC/U2/Pop/01 Discotheque.m4a]  [-map] [0:0] [-b:a] [192k] [-v] [0] [-f] [mp3] [-]
2019-12-02 20:31:19.232  INFO ---  o.a.p.c.StreamController                 : 192.168.9.254: Client  unexpectedly closed connection while loading  http://192.168.9.226:4040/airsonic/stream?player=2&id=18603  (java.net.SocketTimeoutException)

## Comments

Wasn't there some talk about having a setting so the user can continue to use the old transcoding method (the one that lets you seek in tracks) if they want? I don't have any problems with Airsonic 10.2.1.

**Comment by fxthomas** [comment]
Let me try to figure out what happens.

* Can you open the Network panel on your browser (right click then "Inspect", then "Network" tab), try to stream something and see if it matches what you are listening to (especially the status and size of the stream request)?
* Can you copy that stream request as a cURL command (right click on the request in the Network tab, then "Copy as cURL" ; this includes your login cookie so don't copy that off on the internet) and download the streamed file directly to a console?
* Other than this, could Nginx be dropping the connection? What if you bypass Nginx and connect to Airsonic directly?

About your comment, I believe that https://github.com/airsonic/airsonic/pull/1123 would handle going back to working seeks now that the HTML5 player is working correctly?

**Comment by nx6** [comment]
>     * Can you open the Network panel on your browser (right click then "Inspect", then "Network" tab), try to stream something and see if it matches what you are listening to (especially the status and size of the stream request)?

Wouldn't the size _not_ match the what I am listening to, since it's being transcoded into another format? O.o
 
>     * Can you copy that stream request as a cURL command (right click on the request in the Network tab, then "Copy as cURL" ; this includes your login cookie so don't copy that off on the internet) and download the streamed file directly to a console?

I can follow this until we get to "download in a console". I should probably clarify this a bit. I don't use FreeBSD as a desktop OS. This is actually running in a jail on FreeNAS 11.2U7. My normal desktop OS is Windows 8.1. But I think I know what you are trying to figure out. How about this:

- Logged on to the web player via local LAN IP, not through the reverse proxy.
- Started playing an Apple Lossless file (9m52s, 68.3 MB) in the web player, where it gets transcoded.
- Started _ripping_ the playing stream with a browser downloading extension.
- The stream rip finished at 2:26 into playback.
- Actual playback failed at 2:46 in the web player.
- The saved MPEG stream is 13.5 MB
- Opened stream file in VLC.
- The entire song is there -- so it appears Airsonic did finish the transcoding job. It just failed to play it back in its entirety.

Was there something else you were wanting?

**Comment by fxthomas** [comment]
Ah, yes, that's exactly what I wanted to check, thank you! This narrows down the issue as a front-end issue since you were able to download a fully-transcoded file.

Is the size reported by the `stream` request in the "Network" panel the same as your downloaded MPEG file? This would narrow this down further as either "borked while playing" or "borked while downloading".

![image](https://user-images.githubusercontent.com/613594/70185247-ae8eb300-16e9-11ea-982c-13be26fc2fa6.png)

**Comment by nx6** [comment]
> Is the size reported by the `stream` request in the "Network" panel the same as your downloaded MPEG file? This would narrow this down further as either "borked while playing" or "borked while downloading".

- Logged on via local IP again.
- Started playing an AAC file (7m09s, 9.9 MB).
- Started ripping stream.
- Stream rip finished at 1:58.
- Playback ended at 2:18.
- The transcode is about the same size (9.83 MB) as the original, but that's because the original AAC file was 192 kbps VBR by coincidence.
- The stream download on the browser inspector does not match this:
![screenshot](https://i.imgur.com/eTzU5yF.png)
...
- Went back to transcode settings and removed m4a from transcoding types (this was originally set to make sure Apple Lossless plays, since they have the same file extension in iTunes as AAC files).
- Played another track from the same album (6m17s, 8.7 MB)...
- The song played directly without issue through the whole track.

**Comment by nx6** [comment]
Is there a normal limit to the size of these stream requests? I just tried (direct) playing the longest track on the album, and it was broken up into two requests. It played back fine, I just wondered if this might be related.

! [edited screenshot](https://i.imgur.com/m2Fj8iM.png)

**Comment by fxthomas** [comment]
There isn't really a normal size per se, but normally the browser should download the entire stream, not part of it (until we reintroduce range requests properly in #1123).

Is that an MP4 video though? Asking because the transcoding might be a bit different for videos.

**Comment by nx6** [comment]
> Is that an MP4 video though? Asking because the transcoding might be a bit different for videos.

No, it's just a normal red book CD from my collection I ripped with iTunes to AAC format years ago. There may be some similarities between the .m4a files iTunes makes and mp4's though. I once acquired an album of AAC files and found them to me mp4 extension. They played fine but iTunes listed them as video files. I tried just changing the file extensions to .m4a and re-imported the album and they listed as audio files and worked the same.

**Comment by fxthomas** [comment]
Can you try to do the same (using .m4a instead of .mp4) with Airsonic? Does something change?

Also, could you investigate why there is a warning about a connection timing out in the console in one of your earlier screenshots? Maybe start by disabling Nginx and connecting to Airsonic directly?

**Comment by nx6** [comment]
The answer to both your questions was reflected in my last screen shot I believe.

![screenshot markup](https://i.imgur.com/vP6AB1o.png)

I'm not using mp4's with Airsonic. All AAC and ALAC audio files are all .m4a extension, because otherwise iTunes would treat them as video files instead of audio. The stream coming through as MP4 on the Inspector is Airsonic repackaging it that way.

I'm not using the reverse proxy in any of this testing with you, as it would add an unknown element to the troubleshooting. I _do_ have a couple issues with Airsonic and my reverse proxy, but those are things I'll bring up another time.

**Comment by fxthomas** [comment]
Ah, my bad, did not notice the extension and the port. Thanks! :wink: 

I first want to check if it isn't by any chance resolved after the changes made by #1123. Can you test the build at https://github.com/fxthomas/airsonic/releases/tag/10.5.0-test-seeks-1423 and let me know if it is better?

If it isn't, we have more investigating to do.

**Comment by nx6** [comment]
I'll do some more testing on this in the coming days, but my initial playback of a few tracks here seems to show that new build works. Both (unnecessarily transcoded) AAC and Apple Lossless files are playing back in their entirety.

**Comment by fxthomas** [comment]
Nice, glad to know that! I definitely want to get #1123 in for 10.6 then.

As for the reason, in some cases we don't fully control what the HTML5 player does. My hypothesis is that in your case, restoring the ability to request part of a stream made it take a different code path.

**Comment by fxthomas** [comment]
Forgot about this, since #1123 has been merged let's close this!
