### ISSUE TITLE
Use original release date when appropriate

### ISSUE THREAD

**Issue by heyarne** [airsonic/airsonic#1445]
## Problem description

It is common for recordings to be released several times, sometimes identically and sometimes in different versions. Usually the original release date (tagged as `TORY` or `TDOR`) is the one you'd be interested in (when asking for example for "70ies music"), but currently "date" ist taken by Airsonic. There are however times when "date" is what you want (for covers and remixes for example).

### Steps to reproduce

1. Get an album which has been re-mastered
2. Tag it via Musicbrainz Picard
3. Import it into Airsonic

## Proposed solution

There are different tags that can be used quite well to differentiate between different cases. An overview is given [in the hydrogenaudio wiki](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:ID3_Tag_Mapping).

My proposal would be this:

* When scanning a new song, check if it the `TPE4` field is empty
  * … if yes: try `TDOR`, then `TYOR`, then (if unsuccesful) use the same as now 
  * … ff no, assume it's a cover and use the date just like you would now

Eventually maybe we could just expose more meta data and let a client decide this. This might or might not break existing clients.

**Comment by heyarne** [comment]
@eharris [provided some additional useful information](https://matrix.to/#/!JoBghRcWpkhFlnsvoq:matrix.org/$1577120684634483nFqti:matrix.org?via=matrix.org&via=popcornrules.com&via=chat.138.io) in the Matrix channel:

> IIRC, the "date" is usually meant to indicate when the particular medium used was produced, not when recorded or anything else. So for re-releases or remasters or remixes, it's going to be later than you expect.
They (Muzicbrainz and other projects) has worked to try to provide more info in other tags, but they may or may not be complete or correct.
https://community.metabrainz.org/t/date-vs-original-release-date/168992
https://github.com/beetbox/beets/issues/1498

Especially the second link is quite useful to figure this out I think. To be clear, this is how I get back the tags for a 1980 ablum re-released in 2000 (which serves as my main example):

![2019-12-24-150909_424x547_scrot](https://user-images.githubusercontent.com/525780/71416108-623af100-265f-11ea-914d-201e12aa44cd.png)

**Comment by jvoisin** [comment]
I'm not sure I understand your suggestion, so I'll try to rephrase it:
You would like airsonic to use the *original release date* when available, and to fallback to the *date* when it isn't?

**Comment by heyarne** [comment]
@jvoisin Basically yes. It's not that clear however and I'm unsure how to best solve it. Let's say you have a song that is released in 1980, and you have two versions of it: One is one a release from 2000 an it's remastered, one is a cover version from 2010. On Musicbrainz (which I'll just treast as _the_ authority on tagging in this case) they'd be tagged like this:

- *Remaster:* Original Release Date 1980, Date: 1990
- *Cover:* Original Release Date 1980, Date: 2000 (same for Remixes etc., if they're tagged as per the guidelines)

In the second case the date is more interesting than the first one because the work stands on its own. This is rarely the case for remasters / re-releases. I was suggesting to use the

The more I think about it, the messier it gets. I suggested to use the `TPE4` tag to find out whether we're dealing with a cover as described in the hydrogenaudio wiki above. But what about live albums? That tag would be empty but the live version would fall into the same category as a cover as a specific version of a track / recording providing additional value. Some people might also have preferences for one re-release over another of course.

I honestly don't think airsonic can solve this because it is just very messy, so treat this as me just thinking aloud. Maybe, once a new rest api is in reach, we can just query both. :)
