### ISSUE TITLE
Continue random play queues after last song

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#145]
<a href="https://github.com/fxthomas"><img src="https://avatars0.githubusercontent.com/u/613594?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fxthomas](https://github.com/fxthomas)**
_Sunday Nov 20, 2016 at 14:23 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/145_

----

When using the "Shuffle" feature in the "More" section, the play queue stops at the last song. It should instead automatically add more random songs and start playing them.

While the whole playlist could be replaced with new songs, it would be nice if we kept one or two songs that were played before, so that the user can go back to them. For reference, this is what the [DSub](https://github.com/daneren2005/Subsonic/) app already does when shuffling songs.

The feature has already been [requested](http://forum.subsonic.org/forum/viewtopic.php?f=3&t=16373) on the main Subsonic forums. I have a very crude working version on [my local branch](https://github.com/fxthomas/libresonic/tree/local), so if there is interest in bringing it to Libresonic I can clean it up and make a PR.

**Comment by etyrnal** [comment]
" I would welcome a Pull Request that replace it with a button to "Shuffle Library" and "Shuffle Starred". "

Would also be cool to be able to "Shuffle unu-Starred".

Some days it's nice to set a playlist in motion that plays your tried and true tracks, but on other days, it's nice to be able to discover hidden gems you may not have heard in a long time, or at all.

It would also be great to be able to generate a playlist that just starts playing SONGS (not Artists or Albums), starting from the most recent song you added to your library, and playing each song you added backwards in time, or to set a range.  Like Shuffle all songs (starred, unstarred, or combined) added in the Last week, month, year, date~range.
