### ISSUE TITLE
Archlinux integration

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#146]
<a href="https://github.com/Superpiffer"><img src="https://avatars0.githubusercontent.com/u/1334453?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Superpiffer](https://github.com/Superpiffer)**
_Tuesday Nov 22, 2016 at 10:23 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/146_

----

I'm trying to create an AUR package of libresonic on Archlinux for beta versions. I've created [this](https://aur.archlinux.org/packages/libresonic/) package for the stable version and it works. 
The problem is that right now I use the booter from the original subsonic package, with the new beta it's not working anymore because of the different working paths. 
Is it possible to have the file libresonic-booter-jar-with-dependencies.jar builded with the .war file in the next releases? Of course I can build myself but may be a problem with the PKGBUILD.

**Comment by Superpiffer** [comment]
I've created an AUR package for [airsonic](https://aur.archlinux.org/packages/airsonic/), maybe can be useful to someone.
