### ISSUE TITLE
Direct download of Podcast Episode not working

### ISSUE THREAD

**Issue by Faeb35** [airsonic/airsonic#1479]
## Problem description

Direct download of a Podcast episode is not starting to download in Airsonic 10.5.
There are no errors shown neighter in the browser console nor in the Airsonic logs.

### Steps to reproduce

When I go to the Podcasts section, open a Podcast channel, select the checkbox on an (or multiple) episode(s) and click on "Download selected" the page refreshes, but no download is starting. Tested this with Firefox and Chrome. 

Workaround: Play the episode and download it through the web player, this works like a charm.

## System information

 * **Airsonic version**: 10.5
 * **Operating system**: Windows Server 2012
 * **Java version**: Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
 * **Proxy server**: Nope
 * **Client**: Tested in Firefox and Chrome
 * **Language**: English

**Comment by Faeb35** [comment]
Just wanted to ask if anyone could quickly double check if he has the same issue? Is it a general bug or just related to my environment...?

**Comment by seitzbg** [comment]
Podcasts never worked for me either.

**Comment by Faeb35** [comment]
I'd like to link this issue with a reddit thread I opened:
https://www.reddit.com/r/airsonic/comments/f8r30d/direct_download_of_podcast_episode_not_working/

Here also a screenshot:
![grafik](https://user-images.githubusercontent.com/9485516/75443983-7e2f7b80-599d-11ea-8288-5a8d664de9ad.png)

**Comment by SyntrophicConsortium** [comment]
I can confirm this is an issue. On a related note, I really wish there was a select all option. I wanted to download 50+ episodes of a podcast, and I had to click each box. Then I found that download selected didn't work!

**Comment by Faeb35** [comment]
I just started to debug this issue. As I figured out from the code there isn't really an issue. There is just a missunderstanding of what the "Download selected" link does from my side.

What I was thinking: "Download selected" would start download the selected Episode from Airsonic to my Client by using the browser download (like when I click "Download" in the player).

What this it really does: "Download selected" forces the download of an episode from the Podcast source to the Airsonic Server. This is e.g. usefull if an episode has the status skipped.

**Comment by SyntrophicConsortium** [comment]
> What this it really does: "Download selected" forces the download of an episode from the Podcast source to the Airsonic Server. This is e.g. usefull if an episode has the status skipped.

It doesn't do that for me. I assume the status should update from skipped to downloaded, but that doesn't happen. I will open another issue for that specifically. Thanks for looking into it.
