### ISSUE TITLE
SQL query when there is no more db.view?

### ISSUE THREAD

**Issue by xanthos84** [airsonic/airsonic#1547]
Hi,

after you decided to remove db.view - what is your replacement to query airsonic?
I used this to autogenerate unheard songs playlists.
Now I cant do this anymore as I have no more db.view interface.
I use the embeded default airsonic db and I dont want to switch to anything other.
Thanks

**Comment by jvoisin** [comment]
Can't you just directly query the database?

**Comment by xanthos84** [comment]
i would love to, but how?

**Comment by randomnicode** [comment]
sorry no one's responded yet.

The embedded airsonic db is HSQLDB 1.8 and is stored at your airsonic home/db/airsonic

- You may use the HSQLDB jar (download at their website) to connect to it and run queries.
- You may also use an external db viewer like dbeaver or a myriad of other db viewers to connect to it and visualize and query it.

In both cases, the jar you use to connect to the DB is extremely important. The latest for HSQLDB is 2.5, and if you use that jar to connect, it will upgrade your db and render it unconnectable by airsonic itself (which is using the older 1.8). So in both cases make sure you use the 1.8 jar to connect to the DB.

**Comment by xanthos84** [comment]
thanks for trying to help.
but the work amount to get this now running is huge instead of the simple web api.
i am so sad that this decision was made, now it seems to be impossible to make sql queries on the airsonic database when it runs inside a docker container.

i would need to research days for how to connect now... as I dont have any clue about hsqldb - and some kind of dbviewer does not help here as I run automated cronjobs to refresh the playlists via sql statements.

**Comment by randomnicode** [comment]
sorry buddy. i'm not sure the reasons that went into eliminating the web dbview, but I'm sure security was a part of it. you might be able to find the pr that did it along with explanations of the motives.

hsqldb is just like any other db. you just need a jdbc driver to connect. i don't know the old api, but how were you running cron jobs against results presented in a UI? were you scraping or using a web driver?

just trying to understand the usecase

**Comment by di-dc** [comment]
Here's the commit: https://github.com/airsonic/airsonic/commit/348c698e35453db00742b768fd2a4a3796375c1c

"This page wasn't linked anywhere, and was allowing an administrator to issue arbitrary sql comments, and was vulnerable to reflected XSS."

**Comment by di-dc** [comment]
The docs mention a command line tool that can be used to run queries against the db:
https://airsonic.github.io/docs/database/#hsqldb

Download that tool (either in the container itself, or locally + attach that folder as a volume when starting the container), and you should be able to run queries against the database.

**Comment by xanthos84** [comment]
thanks for adding the information to the docs - this helps me through the wild ride!
I can now hopefully get back writing a script which makes some random playlists for me again.

**Comment by fxthomas** [comment]
Are you guys okay with closing it since https://airsonic.github.io/docs/database/#hsqldb provides a good help for running commands on the embedded db?

**Comment by xanthos84** [comment]
yes seems fine so far, even though its not so easy as before.
