### ISSUE TITLE
Use of obsolete HTML5 tags: frames and framesets

### ISSUE THREAD

**Issue by randomnicode** [airsonic/airsonic#1552]
This is a reopening of https://github.com/airsonic/airsonic/issues/1140 it seems and should not be closed as it hasn't been fixed nor addressed.

HTML5 not just deprecates `frames` and `framesets` but actually _obsoletes_ them. They have been _removed_ from HTML5 spec.

We use them extensively in our layout. We should replace it with a proper HTML5 compatible layout.

If our HTML document is labeled and rendered as an HTML5 doc, all we should see is a blank page.

**Comment by fxthomas** [comment]
Please comment/reopen on the the old issue instead of creating a new one?
