### ISSUE TITLE
Remove GStatic (What is it being used for?)

### ISSUE THREAD

**Issue by grravity** [airsonic/airsonic#1576]
GStatic is showing as a third party script through uMatrix, I have it blocked but I fail to see anything broken. What is this being used for? I figured maybe it might be one of the themes, but It seems to persist if I change themes. 
I am encouraging either replacing (with a privacy friendly alternative, if it's something that is truly needed) or just removing GStatic though.

## System information

 * **Airsonic version**: *the version listed on the About page*
 * **Operating system**: *Win 10*
 * **Java version**: *OpenJDK - 11.0.6*
 * **Proxy server**: *Caddy (not sure version)*
 * **Client**: *Firefox ESR*
 * **Language**: *English*

**Comment by jvoisin** [comment]
It's used to provide the Chromecast feature. There are some work in progress pull-requests to make its loading optional.

**Comment by eharris** [comment]
FYI, the issues you probably want to follow for this are #712 and #993
