### ISSUE TITLE
when I click play, airsonic sends an m3u file

### ISSUE THREAD

**Issue by redlegoman** [airsonic/airsonic#1580]
I am running 10.5.0 (I tried 10.6.0 from source too). When I click the play button on an album cover, or the play/pause button in the player at the bottom of the window, my browser (I have tried Chrome, Firefox and Edge) downloads a "play.m3u" file instead of playing audio. This used to work, so I'm not sure what's going on. Any pointers for troubleshooting?
I'm using the war file in tomcat8 on Ubuntu 18.04 with open jdk 8.
![image](https://user-images.githubusercontent.com/1895294/76238253-7ab2b480-6227-11ea-9552-717369f4a390.png)

**Comment by eharris** [comment]
This should be controlled by the player type settings in `Settings` -> `Player`.  You have likely selected `External player with playlist` rather than the internal `Web` player.
