### ISSUE TITLE
Crashes: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by TheFrenchGhosty** [airsonic/airsonic#1582]
## Problem description

```
[TIME] [HOSTNAME] java[5810]:         at org.airsonic.player.service.PodcastService.lambda$schedule$1(PodcastService.java:129) [classes!/:10.5.0-RELEAS>
[TIME] [HOSTNAME] java[5810]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_242]
[TIME] [HOSTNAME] java[5810]:         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_242]
[TIME] [HOSTNAME] java[5810]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.ja>
[TIME] [HOSTNAME] java[5810]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)>
[TIME] [HOSTNAME] java[5810]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
[TIME] [HOSTNAME] java[5810]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
[TIME] [HOSTNAME] java[5810]:         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
[TIME] [HOSTNAME] java[5810]: [TIME]  INFO --- o.a.p.service.PodcastService             : Completed scheduled Podcast refresh.
[TIME] [HOSTNAME] java[5810]: Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-8080-AsyncTimeout"
```

## System information

 * **Airsonic version**: 10.5.0-RELEASE
 * **Operating system**: Arch
 * **Java version**: Java 1.8.0_242
 * **Proxy server**: Nginx

## Additional notes

Using the AUR package: https://aur.archlinux.org/packages/airsonic/

**Comment by fxthomas** [comment]
You might want to increase the `-Xmx` setting in the service file, although the default is in fact fairly large. How big is your library?

**Comment by TheFrenchGhosty** [comment]
My library is: 46,846 songs / 1.34 TB

I will try to increase the memory it uses, but it weird because the crash happens (already happened 2 times) when no one is using it.

**Comment by TheFrenchGhosty** [comment]
I just checked the memory usage, it's now using 961.1 MB (according to the About tab), again no one is using it.

**Comment by TheFrenchGhosty** [comment]
@fxthomas It's now using 1.34 GB of 1.36 GB (according to the About page), it's been running for 10 days, no one is using it right now.

It looks like there is an issue.

**Comment by TheFrenchGhosty** [comment]
Airsonic just "soft-crashed" (504 timeout was returned).

I tried restarting it, it crashed:

```
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_242]
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_242]
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDat>
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource>
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBas>
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSour>
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:302) ~[liquibase-core->
Mar 28 [TIMECODE] [HOSTNAME] java[3780503]:         ... 41 common frames omitted
Mar 28 [TIMECODE] [HOSTNAME] systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Mar 28 [TIMECODE] [HOSTNAME] systemd[1]: airsonic.service: Failed with result 'exit-code'.
```


I changed its maximum memory to 2G, restarted checked the about tab, it's using 1.42 GB.

**Comment by fxthomas** [comment]
That's definitely a lot of memory. I have two ideas:

* Given that this is a large amount of memory, can you try doing a heap dump using something like VIsualVM, then sort by package and share a screenshot of the dump?

    ![VisualVM main interface](https://user-images.githubusercontent.com/613594/77820492-f98e6500-70e2-11ea-9d84-040d56867b73.png)

    ![Example heap dump](https://user-images.githubusercontent.com/613594/77820518-34909880-70e3-11ea-8933-906a12185e0c.png)

* Can you try https://github.com/fxthomas/airsonic/releases/tag/10.6-snapshot-hsqldb-2.5 out on a copy of your database? How is the memory usage?

**Comment by TheFrenchGhosty** [comment]
I think I found the issue.

I have one podcast feed added... and I noticed that Airsonic downloaded the same episodes multiple times... for a total of 4.2TB, yesterday I removed some stuff and freed around 100GB, and today it's filled, so I'm guessing that's part of the problem.

I will remove the podcast feed, and check if it fixes the ram issue.

**Comment by fxthomas** [comment]
Haha, of course that would not have helped :wink: 

I'm still curious if you could spare some time to test the snapshot I mentioned in https://github.com/airsonic/airsonic/issues/1582#issuecomment-605422220 (but read the notes before trying it out!), as your library seems like a nice test case.

**Comment by TheFrenchGhosty** [comment]
After removing the 4.2TB (and spending lots of time trying to get to the page of the podcast feed without crashing the browser to delete it).

The problem is solved.

For your information, it was using 4.2TB of hard disk (consisting of more than 180 000 files), the podcast feed contained "309.120 episodes".

After removing the files, deleting the podcast feed, restarting, scanning the media folders, cleaning up the db, and restarting again. Airsonic is back to using around 800MB (for a 1.5TB/50 000+ files collection).

The issue was that the podcast feed was serving every episode named "media.mp3" and for whatever reason Airsonic didn't get that it was right and kept downloading the same episode (over 300 000 times it seems).

**Comment by fxthomas** [comment]
Oh wow, okay, that's a lot of copies :sweat_smile: 

This still sounds like a bug, Airsonic should definitely not be doing this. I'll close this one (since the out of memory is solved) and open a new one about the issue with podcasts.
