### ISSUE TITLE
Questions and doubts before installing ...

### ISSUE THREAD

**Issue by luisbalboa** [airsonic/airsonic#1596]
Hello I have some questions before installing:
1 - What is the recommended Operating System to use ARSONIC, is Debian 9?
2 - Can I install AIRSONIC on a virtual server using CPanel or Plesk? If so, which is the most recommended?
3 - Do I need a VPS server with dedicated IP only for AIRSONIC?
4 - Can I have several users with independent access to the content: music, path folders, albums, artists, Streaming Channels?
5 - Can I have several ARSONIC installed in several server subfolders in the same domain? Example:
/ html / arsonic1
/ html / arsonic2
/ html / arsonic3

Thank you for help

**Comment by obbardc** [comment]
using docker would make this all a lot easier

**Comment by nx6** [comment]
> Do I need a VPS server with dedicated IP only for AIRSONIC?
No.

> Can I have several users with independent access to the content: music, path folders, albums, artists, Streaming Channels?
You can create multiple user accounts and give each user access to only specific folders. You can't limit this by artist unless you segregate the files in different directories.

> Can I have several AIRSONIC installed in several server subfolders in the same domain?
If multiple instances of Airsonic are running on virtualized/compartmentalized machines, you can have a single domain for them and just use a reverse proxy to set the specific instance you route to.

**Comment by fxthomas** [comment]
Thanks everyone for answering! Let us know when you think we can close this.

**Comment by tesshucom** [comment]
I will close it.
If you have any questions, please report again.
