### ISSUE TITLE
HTTP Status 500 - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by vestingz** [airsonic/airsonic#1612]
## Problem description

I have just update from 10.4.2 to 10.5.0 on a Tomcat 8 deployment, following this method: https://airsonic.github.io/docs/update/

Now it is throwing following error: `HTTP Status 500 - java.lang.NoSuchMethodError: org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(Ljavax/servlet/jsp/tagext/Tag;Lorg/apache/tomcat/InstanceManager;Z)V`

I'll attach the full error report here: 
[tomcat-error.txt](https://github.com/airsonic/airsonic/files/4470084/tomcat-error.txt)

## System information

 * **Airsonic version**: v10.5.0
 * **Operating system**: Ubuntu 16.04 LTS, Linux ubuntu 4.4.0-177-generic
 * **Java version**: java-8-openjdk-amd64
 * **Client**: Chromium 84.0.4105.0
 * **Language**: en

**Comment by tesshucom** [comment]
I feel like I saw somewhere that a version error occurred if I created a draft release before...
The timing seems to match.

**Comment by tesshucom** [comment]
I feel like I saw somewhere that a version error occurred if I created a draft release before...
The timing seems to match.

@fxthomas
I think there is a similar report somewhere in the old issues. . . 
Cannot be found immediately:weary:

**Comment by tesshucom** [comment]
I feel like I saw somewhere that a version error occurred if I created a draft release before...
The timing seems to match.

I think there is a similar report somewhere in the old issues. . . 
Cannot be found immediately:weary:

**Comment by fxthomas** [comment]
@tesshucom Hmm, I'm not convinced it is because of the draft release (it's not public yet, if you are not logged in a a member of the org you should not see it). If you can find other error reports that'd be great!

@vestingz Other than that, I unfortunately don't deploy Airsonic on Tomcat, so no idea what's wrong here. Have you tried running a completely clean install (backup/clean the old Tomcat/Airsonic directories and configuration then reinstall everything)? Does the error persist?

**Comment by vestingz** [comment]
@vestingz Yeah, I actually did a `apt-get purge openjdk-8-jre` and then a reinstall, no difference. Maybe I should finally hop onto the docker image..

**Comment by fxthomas** [comment]
Can you also purge `tomcat8`?

**Comment by vestingz** [comment]
That actually worked, at least the standalone is running now :) Now I just have to figure out what is wrong with my reverse proxy :D 
And I thought I would just quickly update..

**Comment by fxthomas** [comment]
After a quick search for your issue a lot of people seemed to have issues with Tomcat keeping some old classes cached on upgrades, so I figured it was worth a shot to clear everything. Glad you got it working!

**Comment by vestingz** [comment]
Thank you very much for your help :) Weirdly enough, I am running in another problem, apparently with my Apache reverse proxy. Airsonic is running on a subdomain: `sub.domain.xyz`
I've been using the following in my directive since the last years: `ProxyPass /airsonic http://127.0.0.1:8080` and `ProxyPassReverse /airsonic http://127.0.0.1:8080`. Now, while Airsonic successfully is running in standalone mode, sending a simple `HTTP GET` to `http://localhost:8080` returns a 302 and accessing it through the reverse proxy via `https://sub.domain.xyz/airsonic` only forwards me to `https://sub.domain.xyz/login`, where I get a 404 obviously. I am starting to feel stupid. Am I not seeing the obvious?

**Comment by fxthomas** [comment]
For basic proxy configuration look at https://airsonic.github.io/docs/proxy/prerequisites/ (especially the bit about the context path, which seems to be what's missing for you).

**Comment by vestingz** [comment]
That indeed did the trick! So I actually did not see the obvious - thank you very much for pointing that out :)
