### ISSUE TITLE
migrate to mysql/postgresql

### ISSUE THREAD

**Issue by anarcat** [airsonic/airsonic#1639]
Hi!

I believe I am using the builtin database in JDBC. I'm not sure *what* it is or how it works, all I know is that it doesn't look like a MySQL or PostgreSQL database that I can grok. I understand there might be some downsides to host other database systems (namely performance, according to #1340) but I'm considering migrating away to another server than Airsonic so I'm wondering if there's a way to at least *dump* the database in some "standard" (say ANSI SQL) format so that I could try converting it or at least extracting the good stuff (like ratings and play times).

Is *there* a way to dump the HSQL database easily? How about converting it to MySQL or PostgreSQL?

I understand this is a pretty "generic Java" question that might sound trivial for Java developers, but I'm not familiar with that database system at all so any help would be tremendously useful.

Thanks!

**Comment by tesshucom** [comment]
See around here?

https://github.com/airsonic/airsonic/issues/1547
https://airsonic.github.io/docs/database/#hsqldb

We might use an external tool like the one above, and most IDEs have a simple DB resource accessor built in.
Therefore, it may not be talked about very much ...

It seems to be familiar with DBs like MySQL or PostgreSQL, so it's also a good idea to look directly at ``airsonic/db/ airsonic.script``.
(Server should be stopped)

____

Another approach is to stop managing your favorites locally.
You can consider the scrobble.
(It depends on your taste)

Users who use various products seem to like this method.
This is to avoid making similar transitions over and over.

**Comment by anarcat** [comment]
thanks, that's pretty much what i was looking for. also, it seems that what I actually mostly care about is the playlists, and there's a neat export button for that... 

(... now obviously the alternatives i'm considering don't support *importing* playlists, but that's not your fault)

**Comment by tesshucom** [comment]
I will close it.
If you have any questions, please report again.
