### ISSUE TITLE
Last.fm scrobbling no longer working on 10.6.1-RELEASE

### ISSUE THREAD

**Issue by sardaukar** [airsonic/airsonic#1655]
## Problem description

Scrobbling no longer works on the latest release. I see

```
2020-04-23 15:02:09.888 WARN --- o.a.p.s.s.LastFMScrobbler : Failed to scrobble song '02 Chemical Reaction [Snyderman]' at Last.fm. Unknown response: <html><head>
```
### Steps to reproduce

1. Play a song
2. Wait for the scrobble to show up on Last.fm
3. Weep as you read the log message on Airsonic

## System information

 * **Airsonic version**: 10.6.1-RELEASE
 * **Operating system**: Linux, Debian 10, kernel  5.4.19-1~bpo10+1 (2020-03-09) x86_64
 * **Java version**: Apache Tomcat/8.5.51, java 1.8.0_242, Linux (353.6 MB / 475.0 MB)
 * **Proxy server**: nginx
 * **Client**: Firefox latest version
 * **Language**: en-GB

**Comment by sardaukar** [comment]
I re-entered the correct username and pasword in settings, no go.

**Comment by randomnicode** [comment]
There's a reddit topic regarding this: https://www.reddit.com/r/airsonic/comments/g48dzg/does_lastfm_scrobbling_work_for_you/

And a Github issue: #785 with an operative comment https://github.com/airsonic/airsonic/issues/785#issuecomment-616228733

I guess eventually Airsonic devs will get around to it. [Airsonic-Advanced](https://github.com/airsonic-advanced/airsonic-advanced) does not have the issue (fixed in https://github.com/airsonic-advanced/airsonic-advanced/pull/112 in early March, and alerted here)

**Comment by fxthomas** [comment]
Can you test #1660 (particularly the build at https://github.com/fxthomas/airsonic/releases/tag/fix-lastfm-10.6) and let me know if it works?

**Comment by sardaukar** [comment]
@fxthomas I use a Docker container - how can I test this with my setup?

**Comment by sardaukar** [comment]
OK, so I entered the container, replaced the file and killed the process, so the supervisor would bring it back up and it works fine! Thanks

**Comment by sardaukar** [comment]
@randomnicode I tried using the Airsonic Advanced Docker container, but first it kept running out of memory even with 16GB available. Then I added `-Xmx2g` or something to the `JAVA_OPTS` env var in the container and it didn't run out of memory anymore but after finishing the media folder scan it just froze taking up 100% of the CPU. After 15 minutes of waiting, I killed it. I think "vanilla" Airsonic is more my speed. But it was cool to see the paginated play queue and credentials management being better!

**Comment by fxthomas** [comment]
Thanks for the testing, I'll get that running on a 10.6.2 release!

**Comment by SyntrophicConsortium** [comment]
Works for me as well!

**Comment by randomnicode** [comment]
> @randomnicode I tried using the Airsonic Advanced Docker container, but first it kept running out of memory even with 16GB available. Then I added -Xmx2g or something to the JAVA_OPTS env var in the container and it didn't run out of memory anymore but after finishing the media folder scan it just froze taking up 100% of the CPU. After 15 minutes of waiting, I killed it. I think "vanilla" Airsonic is more my speed. But it was cool to see the paginated play queue and credentials management being better!

File bugsss. Specify version, etc etc etc... You know the works...

**Comment by sardaukar** [comment]
@randomnicode I could but Airsonic works for me now.
