### ISSUE TITLE
Set Correct Mimetypes

### ISSUE THREAD

**Issue by Neurrone** [airsonic/airsonic#1657]
## Problem description

The `audio/mpeg` mimetype is being unconditionally returned regardless of what the actual file being played is. This causes problems such as Firefox treating it as a video file. 

Possibly related: #528. I suspect this is why playlists played in Foobar2000 aren't able to show the right track titles, since Foobar2000 doesn't attempt to conpensate for incorrect mimetypes.

### Steps to reproduce

1. Login and create a playlist.
2. Download the playlist and open it to see the url for each track.
3. Use `curl --head <url>` to see what headers are being returned. 

## System information

 * **Airsonic version**: 10.6.1
 * **Operating system**: Synology DS918+ on Docker
 * **Java version**: official Docker image
 * **Proxy server**: Traefik 2.20
 * **Client**: curl

**Comment by randomnicode** [comment]
The actual media type is set here: https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/controller/StreamController.java#L199

It depends on (a) what the transcoded output format is expected to be and (b) what the original file extension is (for scenarios where there is no transcode)

The RFC media type for mp3 _is_ `audio/mpeg`.

Have you tried playing a flac _without_ transcode? Do you still get `audio/mpeg`?

Here is the mapping for media types to the extensions: https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/util/StringUtil.java#L49-L85

**Comment by Neurrone** [comment]
Oh sorry, I didn't realize that Firefox was automatically requesting mp3 encoded files, my source was flac which is why I thought it wasn't working correctly, and I thought Firefox supported flac.

How do I turn it off?
