### ISSUE TITLE
Settings problems after update to 10.6.1

### ISSUE THREAD

**Issue by The-Exterminator** [airsonic/airsonic#1666]
Hello.
I get this problem
[https://www.reddit.com/r/airsonic/comments/g76ndv/where_are_the_rest_af_the_settings_after_update/](url)
after i update to 10.6.1, i drive the tomcat8 skabelon with airsonic.war on raspberry pi3
when i rollback to 10.6.0 the menu is fine. so how can i get the settings menu back. ???
Sorry my bad english

**Comment by The-Exterminator** [comment]
I have found out, when i make a total clean a 10.6.1 the settings menu is okay, but when i taek my old airsonic.script the settings menu not okay more.
How can i fix that. ???

**Comment by jzinkweg** [comment]
Spring Boot was updated to version 2.2.
Looks like some startup parameters were changed:
* server.address -> server.host
* server.context-path -> server.servlet.context-path

For server.use-forward-headers, see:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#deprecations-in-spring-boot-22
The "native" setting did not work for me (apache reverse proxy), "framework" did.

**Comment by The-Exterminator** [comment]
I have fixed it now.
I miss the admin 1 ,2 and 3 in the airsonic.script.
INSERT INTO USER_ROLE VALUES('admin',1)
INSERT INTO USER_ROLE VALUES('admin',2)
INSERT INTO USER_ROLE VALUES('admin',3)
INSERT INTO USER_ROLE VALUES('admin',4)
INSERT INTO USER_ROLE VALUES('admin',5)
INSERT INTO USER_ROLE VALUES('admin',6)
INSERT INTO USER_ROLE VALUES('admin',7)
INSERT INTO USER_ROLE VALUES('admin',8)
INSERT INTO USER_ROLE VALUES('admin',9)
INSERT INTO USER_ROLE VALUES('admin',10)
INSERT INTO USER_ROLE VALUES('admin',11)
