### ISSUE TITLE
"Starred" songs link (lower one) does not work.

### ISSUE THREAD

**Issue by nx6** [airsonic/airsonic#1670]
## Problem description

*The lower "Starred" songs link does not seem to work. The top (toolbar) one does, though.*

### Steps to reproduce

1. Bring up home page.
2. Click the "Starred" link with the icon in the toolbar (between "Playing" and "Playlists").
3. All your Starred tracks are there.
4. Go back to the home page again.
5. Click the "Starred" that shows up in the view bar (Random  |  Recently added  |  Starred  |  Top rated...)
6. There's nothing here.

## System information

 * **Airsonic version**: 10.6.1-RELEASE – April 25, 2020 -- Note: this is actually that test build that fixes the Last.fm scrobbling.
 * **Operating system**: FreeBSD 11.3
 * **Java version**: 1.8.0_242
 * **Proxy server**: nginx, but it's the same without it.
 * **Client**: Waterfox 2020.04, and I also tried Chrome v. 81.0.4044.122
 * **Language**: en-US

**Comment by fxthomas** [comment]
I think this one is for starred albums, not songs (but you're right, the UI is completely confusing) :wink:

**Comment by nx6** [comment]
Okay, so I've been playing around with this. I never starred an album itself before so that might be why I was confused on this. At the very least there is an issue with DSub syncing this back, though. 

When I saw you reply earlier today on my email on my phone I jumped over to DSub and starred two albums, then I went to work. Now that I'm home I'm checking the web player and the albums are not appearing under that lower "Starred" category after all this time. So I just now picked my phone back up and starred a single track. Then checked the (top) Starred on the web player. It's there now. Synced immediately to the server. But the albums aren't.

Then I starred an album from the web player. That works. The album appears in the "album view" starred section, and above the track list in the other (toolbar) view as well. But again it's not syncing with DSub. But if I star a single track from the web player, a manual refresh of the list on the phone adds it.

**Comment by fxthomas** [comment]
There are actually two kinds of stars for album, i.e. "starring" (on/off) and "rating" (1-5 scale). Did DSub maybe use the other one?

As far as I can tell the lower "Starred" section only shows "starred" albums (not "rated", these are shown in "Top rated").

**Comment by nx6** [comment]
DSub has both. The star ratings are set on a dialog that comes up when to click the rating display (for more finger-friendly use). The Star album is a separate toggle. That's what I'm using.

**Comment by nx6** [comment]
It looks like the starred-album syncing issue is on DSub's side. I just checked the official Subsonic app and the album I starred from Airsonic's web interface is marked there, and starring an album from the Subsonic app does sync it back to Airsonic's web UI.

**Comment by nx6** [comment]
Now that I understand the lower "Starred" option is specifically for albums only, and the syncing works correct with the Subsonic Android app, I guess there is no issue here really. Closing.
