### ISSUE TITLE
Apache2 Reverse Proxy is now redirecting but not proxying on Ubuntu Server?

### ISSUE THREAD

**Issue by surfrock66** [airsonic/airsonic#1672]
I am using these instructions exactly for my reverse proxy; I do not believe it is necessarily an airsonic issue but a sudden apache one, I am not sure where else to ask: https://airsonic.github.io/docs/proxy/apache/

I am running Apache2 on Ubuntu Server 19.10.  I have a couple of sites that are reverse proxied and have been working forever, but suddenly my reverse proxy for my airsonic server stopped working.  

Here is the content of my /etc/apache2/sites-available/airsonic.conf:

    <VirtualHost *:4040>
        SSLEngine On
        SSLCertificateFile /etc/apache2/ssl/domaincert.crt
        SSLCertificateKeyFile /etc/apache2/ssl/domaincert.key
        SSLCACertificateFile /etc/apache2/ssl/intermediate.crt
        SSLProxyEngine on
        ServerName ##OBFUSCATED FQDN##
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/airsonic-access.log combined
        ErrorLog ${APACHE_LOG_DIR}/airsonic-error.log
        ProxyPass /airsonic http://127.0.0.1:8080/airsonic
        ProxyPassReverse /airsonic http://127.0.0.1:8080/airsonic
        RequestHeader set X-Forwarded-Proto "https"
    </VirtualHost>

This had been working, but suddenly stopped.  When I go to "https://FQDN:4040/airsonic" I am redirected to "http://127.0.0.1:8080/login" instead of maintaining the correct URL.  If I navigate to "http://fqdn:8080/login" I can access the airsonic server.

I do have a rewrite rule to redirect traffic on 80 to 443, but that shouldn't come into play here.  I have a site configured for an install of "pydio" which is basically just an alias, I have a 000-default site which is just an https redirect listening on port 80, and a default-ssl which only defines a 443 virtualhost if it detects mod_ssl.  Below is the list of enabled mods:

    root:mods-enabled# ls -1
    access_compat.load
    actions.load
    alias.conf
    alias.load
    auth_basic.load
    authn_core.load
    authn_file.load
    authz_core.load
    authz_groupfile.load
    authz_host.load
    authz_user.load
    autoindex.conf
    autoindex.load
    cgi.load
    deflate.conf
    deflate.load
    dir.conf
    dir.load
    dnssd.conf
    dnssd.load
    env.load
    filter.load
    headers.load
    mime.conf
    mime.load
    mpm_prefork.conf
    mpm_prefork.load
    negotiation.conf
    negotiation.load
    php7.2.conf
    php7.2.load
    proxy_ajp.load
    proxy_balancer.conf
    proxy_balancer.load
    proxy.conf
    proxy_connect.load
    proxy_html.conf
    proxy_html.load
    proxy_http.load
    proxy.load
    reqtimeout.conf
    reqtimeout.load
    rewrite.load
    setenvif.conf
    setenvif.load
    slotmem_shm.load
    socache_shmcb.load
    ssl.conf
    ssl.load
    status.conf
    status.load
    xml2enc.load

Nothing shows up in the logs out of place, I'm not sure what changed or what I'm doing wrong, did a module break or something?  I updated all packages and rebooted to no improvement.  Any diagnostic advice is appreciated.

**Comment by nx6** [comment]
Wouldn't you just be browsing to FQDN/airsonic? Why the 4040?

**Comment by surfrock66** [comment]
That was the default for subsonic I think so I wanted to preserve it for legacy; I also have something on 8080.  the primary worry here though was SSL; even if I moved it to 8080 permanently the redirect wouldn't be working.

**Comment by nx6** [comment]
No, not that. You said you were going to "https://FQDN:4040/airsonic". Yeah, the server itself is on 4040, but you wouldn't browse to 4040 on your domain, that's done as part of the redirect. Your reverse proxy is only listening on port 80 and 443, the former just being a redirect to the latter. The reverse proxy should be rerouting the browser to the SSL port if needed, and reroute the page requests to port 4040 on the correct local IP for you on the backend. You don't call the non-standard port on your end, because you're not entering that way from outside.

**Comment by surfrock66** [comment]
That makes a ton of sense; how do I define that then?  Would the configuration go under default-ssl.conf, or do I keep a separate airsonic.conf site with a virtualhost on 443?  My goal then would be to have "https://fqdn/airsonic" proxy to "http://127.0.0.1:8080/airsonic", right?

I can't get over the fact that it was working and now it isn't; I suspect some module broke in apache but can't find any error or anything, I did do an apt upgrade a bit ago and probably didn't notice if this broke then, so I can't figure out what changed.  My worry is, if I do that, I'll just get sent to literally "http://127.0.0.1:8080/airsonic" which won't load.

**Comment by nx6** [comment]
Rereading your original post, you need to **close** port 8080 on your router (at least once you get this working). Your goal should be to have all communication with your servers over SSL with the remote proxy when possible. If you can still access the server over http://FQDN:8080 then you have an opening in your firewall you don't want.

Your reverse proxy needs to be sending the traffic for /airsonic to port 8080 on the local IP of the machine that is hosting Airsonic. I'm not sure if this is the same server that is hosting the reverse proxy or not, though. If they are both on the same machine I would assume a redirect to 127.0.0.1:8080 would work. But if they are on different machines (or different containerized systems on the same machine), then they would have unique local IPs and that's what you need instead. Those local IPs should be statically assigned, too.

I should mention I'm using nginx, so my assistance will be limited here.

**Comment by surfrock66** [comment]
They are the same server and 8080 is closed to the WAN (4040 is not, but we can ignore that).  If I am on a client and go to "https://fqdn/airsonic" (or, formerly, https://fqdn:4040/airsonic) I am redirected to "http://127.0.0.1:8080/airsonic" making me think the proxy part is broken and the only thing working is a redirect, which I don't understand.

**Comment by surfrock66** [comment]
I had been on the airsonic v11 snapshot and I believe there is a regression where the context path is not being respected in the standalone war when invoked from the systemd unit file.  I have submitted a more direct bug for this: https://github.com/airsonic/airsonic/issues/1734
