### ISSUE TITLE
Crash at settings -> players

### ISSUE THREAD

**Issue by hboetes** [airsonic/airsonic#1679]
Version	10.6.1-RELEASE – April 19, 2020
Server	Apache Tomcat/8.5.51, java 11.0.5, OpenBSD (132.8 MB / 218.0 MB)

Upon clicking settings -> players I get an immediate crash. I tailed the log for something useful but it remained empty.

What can I do to fix/debug this problem?

**Comment by fxthomas** [comment]
How are you running Airsonic? Via a service file? Deployed as a WAR on an external Tomcat installation? Do you have system/service logs that could help?

**Comment by hboetes** [comment]
Hello François-Xavier,

I _was_ running the .war standalone. I didn't find anything in any log file so that's why I asked.

To fix a problem with UTF-8 filenames I just switched over to tomcat and java-8 and lo and behold, the players item works all of a sudden. :-)

**Comment by fxthomas** [comment]
Uh, glad to know you fixed it then! Maybe the Java VM segfaulted if you don't have any log?

**Comment by hboetes** [comment]
I guess so. I really should run the process in the foreground and see what happens.

**Comment by hboetes** [comment]
Alright I just tested with java11 and tomcat and it also crashes on players. So... not a good combination. Let's see if I can run this in the foreground.

**Comment by hboetes** [comment]
```
java:/usr/local/jdk-11/lib/libjsound.so: undefined symbol 'DAUDIO_GetDirectAudioDeviceCount'
ld.so: java: lazy binding failed!
```
I guess that's a problem with the java11 package for openbsd. But you are the expert @fxthomas what do you think?

**Comment by fxthomas** [comment]
Sounds like you're using a JDK release that's incompatible with the libraries on your system?

Totally unfamiliar with the BSDs, but on Linux this would be triggered by using either an incompatible version of one of the dependant libraries of `/usr/local/jdk-11/lib/libjsound.so`, or potentially a non-Glibc runtime (such as Musl). Maybe that's the case for you?

**Comment by hboetes** [comment]
This got solved with this release: https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/devel/jdk/11/Makefile?sortby=date
After I reported the problem. It was a packaging problem on the OpenBSD side. Thanks!
