### ISSUE TITLE
A small question about liquibase

### ISSUE THREAD

**Issue by tesshucom** [airsonic/airsonic#1700]
@fxthomas @eharris 

With the following commit, a new log has been added.

https://github.com/airsonic/airsonic/commit/994c1d61ed8389cd9aed7a00d35135fce2e88c98

``<include file="10.3/changelog.xml" relativeToChangelogFile="true"/>``

 - Is it a general practice to add a record in the middle of the liquibase log?
 - Is there a strong reason you didn't choose 10.6?

**Comment by fxthomas** [comment]
I don't think there's any consensus on this, so @eharris probably just picked a directory?

I'm actually confused by the current structure a bit : storing migrations in directories is good for legacy (they were originally migrated from non-Liquibase Java code running SQL by hand, in different packages, so it's nice to be able to figure out where they came from), but I doubt they're useful for new migrations starting from 10.x.

I would prefer a single directory with e.g. a simple naming scheme like `<id>-<short description>.xml`, for example like:

```
subsonic/5.1/*.xml
subsonic/5.2/*.xml
...
123-description-of-changes-1.xml
124-description-of-changes-2.xml
...
```

That's definitely open to discussion though :wink:

**Comment by tesshucom** [comment]
Is this #1428?
I agree with you. It does not make sense to create a directory because it can be managed with git's history.
On the contrary, there is a risk that questions like this issues.

We should fix it rather:tada:

**Comment by tesshucom** [comment]
Is this #1428?
I agree with you. It does not make sense to create a directory because it can be managed with git's history.
On the contrary, there is a risk that questions like this issues.

We should fix it rather:tada:


Speaking of a little, I think that the words "external" and "embedded" do not have a lexicographical meaning, but rather indicate the start mode of HSQLDB. standalone etc. There should be about 4 startup modes. (It's hard to understand, but early designers may think so...)

**Comment by fxthomas** [comment]
I think #1428 is a slightly different issue (that of being, maybe, able to simplify how database configuration is done for the user)?
