### ISSUE TITLE
Airsonic on Ubuntu 20.04, Standalone WAR, where do settings go?

### ISSUE THREAD

**Issue by surfrock66** [airsonic/airsonic#1734]
I am setting up a fresh airsonic install on a brand new server.  I'm using the standalone WAR on Ubuntu 20.04.  I have some questions about the configuration, specifically how things deviate from the docs using this configuration.  I have an old install using the standalone WAR on Ubuntu 18.04, but I wanted to start fresh.

I am following the directions here, using the exact systemd unit file indicated: https://airsonic.github.io/docs/install/war-standalone/

First, the systemd unit file points to an environmentfile at /etc/sysconfig/airsonic.  /etc/sysconfig doesn't exist on this server and doesn't exist on the old one either...seems like it was never a problem, but should I be concerned about that?

I am not sure the context path is being respected.  When I navigate to http://IP:8080/airsonic OR http://IP:8080/ I get redirected to http://10.1.2.10:8080/login.  My expectation was that i would be bound to the subdirectory /airsonic, is that not the case?

I will be putting this behind an apache2 reverse proxy.  I am following this guide here: https://airsonic.github.io/docs/proxy/apache/  If I navigate to "https://IP/airsonic" I get redirected to "https://IP/login" and an error saying the requested URL was not found on this server.  I believe this is because I have not completed one of the prerequisites listed here: https://airsonic.github.io/docs/proxy/prerequisites/ specifically placing this in the application.properties file: server.use-forward-headers=true As it turns out, when I search my system, I don't have that file; is that a tomcat thing?  I do have the autoconfigured airsonic.properties file in /var/airsonic, and when I add it there nothing changes.  How do I set that configuration on the standalone WAR?

## System information

Airsonic Version: 11.0.0-SNAPSHOT – May 1, 2020
OS: Ubuntu Server 20.04
 Java: OpenJDK 8
Apache2
Accessed through Chrome and DSub
Language: English

**Comment by surfrock66** [comment]
If I back up the configuration and use the 10.6.2 war this issue goes away; this appears to be a regression in the 11 code.

**Comment by randomnicode** [comment]
https://github.com/airsonic-advanced/airsonic-advanced/blob/master/contrib/airsonic.service#L18

the 11.0 is a major revision change. the envvar name is actually different for the snapshot (to apply the correct context path). change your service file accordingly. Since 11.0 hasn't been released, the instructions still talk about the 10.6.2 release.

**Comment by surfrock66** [comment]
I have to admit I didn't notice the change in that line of the service file.  The other thing...I have no idea why I'm doing this, I fully update my server automatically every 3 days (I have good backups and this thing is meant to be bleeding edge) but I apparently run the following code every 3 days:

```
printf "\nUpdating Airsonic\n"
cd /home/surfrock66/.sources/airsonic
rm -Rf ./*
git clone https://github.com/airsonic/airsonic.git
cd airsonic
git checkout master
mvn clean package
if [ -f airsonic-main/target/airsonic.war ]
then
        systemctl stop airsonic.service
        mv /var/airsonic/airsonic.war /var/airsonic/airsonic.war.old
        mv airsonic-main/target/airsonic.war /var/airsonic/airsonic.war
        chown airsonic:airsonic /var/airsonic/airsonic.war
        systemctl start airsonic.service
        printf "\nDone"
else
        printf "\nSomething went wrong, the Airsonic war did not get created!"
fi
```
The output of that script is mailed to me every 3 days so I see when something is broken..  I'm stuck since I'm on 11 now and have been since...I have no idea.  I must have wanted to test a feature some time ago.  When 11 comes out, I'll stop that.  I don't even remember setting that up, but I'll be more mindful that I've been running absolutely bleeding edge for a long time.

When I moved to my new hardware, I copied my unit file, bringing the legacy cruft over and making this issue persist across the 2 pieces of hardware.  Thanks for helping me troubleshoot.

**Comment by randomnicode** [comment]
> I have to admit I didn't notice the change in that line of the service file. 

It is not in the service file for _this_ repo on master even though the rest of master is clearly using Spring Boot 2.x with the new env names, and thus this _is_ a bug (the changes should have been copied over from my original PR but weren't).

The instructions should be pointing to a tag or branch for 10.6.2 instead of master which has already merged the changes for Boot 2.x.

I think you should consider reopening this bug.

The file I pointed out to you is on the [`airsonic-advanced`](https://github.com/airsonic-advanced/airsonic-advanced) repo which is more bleeding edge.
