### ISSUE TITLE
Airsonic doesn't play transcoded files on Windows

### ISSUE THREAD

**Issue by SonnyGillissen** [airsonic/airsonic#1749]
**## Problem description**

I've installed a clean version on Windows of Airsonic using the standalone version (10.6.2) and added the ffmpeg transcoding libraries. I don't see any errors due to missing transcoding libraries but still I'm unable to play transcoded files. I'm using an IIS reverse proxy, but it doesn't work locally either. I boot up my Airsonic instance through the command below:

_java.exe -Dairsonic.home="D:\\Airsonic" -Dserver.port=4040 -Dserver.address=127.0.0.1 -Dserver.use-forward-headers=true -jar airsonic.war_

IIS is set-up using every aspect and prerequisite noted in the official documentation, but still no luck. I get the following error when playing through the proxy:

_Client unexpectedly closed connection while loading https://localhost/stream?player=1&id=39588 (java.io.IOException: Connection reset by peer)_

And this error when I try to do it locally:

_Client unexpectedly closed connection while loading http://localhost:4040/stream?player=4&id=39783 (java.io.IOException: An established connection was aborted by the software in your host machine)_

Strange thing I noticed though is that it is telling me that it tries to load https://localhost when going through the proxy, but that proto/port doesn't exist on the server. The message I get from the local call is the right one locally, which I would also expect when transcoding through the proxy as the proxy should handle that.

**### Steps to reproduce**

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

1. Install Airsonic
2. Add the ffmpeg library
3. Configure the IIS reverse proxy
3. Load (for example) a WMA file in the library
4. Try to play it locally
5. Try to play it through the reverse proxy

**## System information**

 * **Airsonic version**: *10.6.2-RELEASE – May 3, 2020*
 * **Operating system**: *Windows Server 2019*
 * **Java version**: *JDK 14.0.1*
 * **Proxy server**: *IIS 10*
**Client**: *Edge (Chromium), Chrome, Internet Explorer, play:Sub. All the same issue.*
 * **Language**: *NL*

**Comment by The-Exterminator** [comment]
Work fine on raspberry with debrian 10

**Comment by SonnyGillissen** [comment]
But not on my Windows installation with IIS. Haven’t tested RPi.

**Comment by SonnyGillissen** [comment]
Managed to fix it! The -map 0:0 parameter in the ffmpeg command was bugging me. It seems that some WMA files have a blank video on stream 0, and others only have audio. I removed the -map parameter entirely so it auto-selects the correct stream which did the trick!
