### ISSUE TITLE
Firefox 78 on openSUSE/Linux + airsonic 10.6.2 on CentOS 7 cannot play anything

### ISSUE THREAD

**Issue by mcepl** [airsonic/airsonic#1777]
## Problem description

It used to work previously with older versions of Firefox, but with this update (and unchanged transform profile), I somehow got corrupted my main profile, and airsonic cannot play anything ... it just pushes this message (backtranslated from Czech) to the console:

"Video on this page cannot be played. Your system may not have required video codecs for: video/mp4" playQueue.view

which doesn't make any sense, because it is just MP3 file, and Firefox can play MP3 files natively.

### Steps to reproduce

1. Start with new Firefox profile
2. Select track to play
3. Nothing happens

## System information

 * **Airsonic version**: 10.6.2-RELEASE – 3. května 2020 (that’s May 3, 2020 in Czech)
 * **Operating system**: CentOS 7
 * **Java version**: OpenJDK Runtime Environment (build 1.8.0_252-b09), OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
 * **Proxy server**: None
 * **Client**: web client with Firefox 78 on openSUSE/Tumbleweed
 * **Language**: cs_CZ.UTF-8

**Comment by jolny** [comment]
Sounds like maybe the wrong Content-Type header is sent by the server.
Can you press Ctrl+Shift+I and go to the network tab, then click the play button for a song.
You should get a lot of new entries in the list, look for something like "stream?player=XXX&id=XXX". Click it and you'll see the response headers on the right. Check if "Content-Type" is "video/mp4" for that particular song.

**Comment by mcepl** [comment]
Damn, and now it works! OK, I cannot reproduce anymore, dang. Just let the server couple of days and it fixes somehow? Not good solution, I know, but I cannot offer anything better.

**Comment by mcepl** [comment]
![Snímek z 2020-08-14 09-44-46](https://user-images.githubusercontent.com/198999/90226373-313c4600-de13-11ea-92a8-572c85ae83c6.png)

I guess this is not right? These three XHRs are going again and again. And this is Firefox 81.0/Nightly (and YouTube plays just fine, so it is not general problem with playing the music, also locally stored MP3s play just fine).

**Comment by jolny** [comment]
Mine does that too, and I have an older version. I assume this is how the frontend is updated, by calling the methods to find out what's playing, scanning status etc. Not sure why they're POST methods, though, but maybe a HTTP body is sent with the request.
Do you also have playback problems? I'm using Firefox 78, and I'm having no issues.

**Comment by mcepl** [comment]
The system 79.0 works just fine, this is just with the Nightly.

**Comment by mcepl** [comment]
Works again.
