### ISSUE TITLE
How do I play songs?

### ISSUE THREAD

**Issue by diabl0w** [airsonic/airsonic#1786]
How do I play songs? The homepage shows all the artists properly, If I click on one it just gives me an artist biography next to a picture of a gray star. 
I feel like I am missing something really obvious, since this was a highly recommended music server.

EDIT: oh and there is also a Play Radio button but that doesnt do anything

**Comment by nx6** [comment]
Are you not seeing the songs you have in your library for the artist below the bio? Can we get a screenshot?

**Comment by diabl0w** [comment]
> Are you not seeing the songs you have in your library for the artist below the bio? Can we get a screenshot?

Hello, thanks for the reply. It seems that maybe it takes a few hours after first importing songs? I only have about 30 songs in my library... in the megabyte range. It took at least an hour for the songs to actually be available to play after scanning. I had a lot of problems with even getting to the point to log in and get to settings to configure players. It takes about 5 minutes per screen. I think I saw some other issues pointing to the same thing, I am guessing it is all related. Unfortunately this is just too slow for me, but thank you anyway.
