### ISSUE TITLE
Expected Behavior of the /Playlists Folder

### ISSUE THREAD

**Issue by TheFlatworm** [airsonic/airsonic#1788]
I am switching over to Airsonif from Subsonic using the linuxserver/airsonic Docker image.  There is a volume created for /playlists which is mapped to a host path.  When a playlist is created, the playlist does not appear in the host folder.

Is this expected or should Airsonic be automatically storing playlists here?

linuxserver/airsonic
Odroid c4 Debian Buster 64bit
Airsonic 10.6.1

**Comment by randomnicode** [comment]
Airsonic stores playlists in its database. It will look at /playlists to auto-import playlists there into its db (during media scans), but otherwise uses the db. What this means is that when you create a new playlist in Airsonic, it just creates it in its db (thus /playlist remains empty)

**Comment by TheFlatworm** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Ok. Thank you!                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: notifications@github.comSent: August 19, 2020 10:40 PMTo: airsonic@noreply.github.comReply-to: reply@reply.github.comCc: ebasta@ca.rr.com; author@noreply.github.comSubject: Re: [airsonic/airsonic] Expected Behavior of the /Playlists Folder (#1788)  
Airsonic stores playlists in its database. It will look at /playlists to auto-import playlists there into its db (during media scans), but otherwise uses the db. What this means is that when you create a new playlist in Airsonic, it just creates it in its db (thus /playlist remains empty)

**Comment by TheFlatworm** [comment]
OK. Thank you!
