### ISSUE TITLE
nssm/windows instructions: service doesn't run, is paused

### ISSUE THREAD

**Issue by jenny787** [airsonic/airsonic#1792]
## Problem description

Created the service using the airsonic instructions for windows and nssm.  The service never starts and is always in the paused state.  Tried with nssm x86 and x64, same result for both.  The airsonic.cmd runs fine when run manually.  If you try to start or stop the service in the services manager, you can't, it says it is already running or other errors.

### Steps to reproduce

install airsonic service in nssm just like the windows instructions.

## System information

 * **Airsonic version**: latest
 * **Operating system**:windows server 2019
   Linux, what distribution; Windows or Mac, what version?*
 * **Java version**: latest java
 * **Proxy server**: None
 * **Client**: firefox
 * **Language**: english

**Comment by Faeb35** [comment]
Hi @jenny787 
When you start the service. Do you see any java.exe in the Taskmanager (under Details tab)? Probably you may need to show the "Command Line" column in the Taskmanager to verify if all the parameters are set right.

**Comment by jenny787** [comment]
> 
> 
> Hi @jenny787
> When you start the service. Do you see any java.exe in the Taskmanager (under Details tab)? Probably you may need to show the "Command Line" column in the Taskmanager to verify if all the parameters are set right.

No I don't see anything with java in there.  Not listed as an exe on the left column, or in the command line column.

**Comment by jenny787** [comment]
quick update...I tried some other software...there's one called AlwaysOn, and it can setup this service pretty easily and it works.  I could not get nssm to work I tried so many things.

**Comment by Faeb35** [comment]
Glad you got it to work!
I would have guessed, that there could be an permission issue with nssm, that the account under which the service is running, doesn't have (write) access to the eighter airsonic or nssm executables.
