### ISSUE TITLE
library scan does not work after changing user permission

### ISSUE THREAD

**Issue by zolstarym** [airsonic/airsonic#1807]
On a new install, I change the media folder to one that tomcat does not have access to then hit scan folders now. The logs say it finds one entry but nothing shows, as expected. I then give add tomcat to the group that the folders and music files belongs to, restart tomcat and hit scan folders now button again, but nothing is added. It seems bugged because it first got scanned without having access, and then any subsequent scans just fail silently.
Once tomcat has access, airsonic should be able to add the media files despite any previous scans.

Ubuntu 20.04. Tomcat9. Latest airsonc version.

## Problem description

*Describe your problem here. Describe what you want to happen, and what happens
if you try to do it. If you have a stack trace or any logs, please format them using
github's triple-backquote notation, or if they are large you may also consider
attaching them as a file or gist.*

**Comment by eharris** [comment]
Try touching (changing the modification date) of the top level folder before rescanning.  Airsonic tries to "optimize" the scan by skipping directories and files that do not appear to have been updated.

**Comment by zolstarym** [comment]
It was a new install, so I just wiped the db folder and trying again worked, but at the least I think the logs should mention something about any skipping going on, or maybe a UI option to for a thorough/complete rescan. The latter would also be useful for corrupt DBs.

**Comment by eharris** [comment]
Logging when files or directories are skipped would be incredibly verbose, so undesirable.  There is an option to force a rescan without looking at the timestamps, but it isn't exposed in the UI yet, see #607 and https://github.com/airsonic/airsonic/issues/732#issuecomment-625782137
