### ISSUE TITLE
Context path and params when using standalone integrated in Systemd

### ISSUE THREAD

**Issue by bolinocroustibat** [airsonic/airsonic#1815]
Thanks for the great work.

In case of an installation as a standalone integrated with Systemd, I cannot find where to change context-path.
Is it in `/etc/sysconfig/airsonic` / `/etc/default/airsonic`? I uncommented `CONTEXT_PATH=/airsonic` in there, but after restarting the service I still can access Airsonic on `xxxx:8080/ ` and not on `xxxx:8080/airsonic `, so I assume it's not the right config file.

**Comment by cascooscuro** [comment]
The config goes in your systemd unit config file, located in your /etc/systemd/system/ folder. For example:

```
[Unit]
Description=Airsonic Media Server
After=remote-fs.target network-online.target
AssertPathExists=/var/airsonic
Wants=network-online.target

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx1900m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=8080"
Environment="CONTEXT_PATH=/airsonic"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/default/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.context-path=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=airsonic
Group=airsonic
```

**Comment by bolinocroustibat** [comment]
@cascooscuro perfect, thanks!
