### ISSUE TITLE
Airsonic use same upnp port booksonic-air

### ISSUE THREAD

**Issue by Animatrix1986** [airsonic/airsonic#1835]
## Problem description

On my Docker runs Airsonic in portainer. Very smoth and good. I used network mode "host" that i can use Upnp/DLNA Server. This works fine for me. But several days later i tried Booksonic-air and here is the problem. It uses the same port 4041 to enable the upnp server. The result is, my devices see airsonic or booksonic-air, but not both. Is it possible to change the upnp port 4041 to an another port? So that airsonic enable the upnp server on an other port? 

## System information

 * **Airsonic version 
 * the newest from.hub.docker.
 
 * **Operating system**:  
 * Debian 10.7, OMV 5, Docker, Portainer.
  

## Additional notes

I spend 3 days of testing, searching for this problem. But i think no one use Airsonic and Booksonic-air at the same time, both with an DLNA/Upnp server.

**Comment by nx6** [comment]
Airsonic uses port 4040 or 8080 depending on your setup method, so you could just set the port forward you need manually and not worry about uPnP. But if you're accessing Airsonic externally you really should be using a reverse proxy so you can have a secure  connection. In that case you don't need to worry about the port either way.

**Comment by Animatrix1986** [comment]
Airsonic uses port 4040 i know. Booksonic the same bute i chabged the port here. But upnp hostet the upnp server on port 4041. When airsonic runs first all my clients see airsonic via dlna. But nut booksonic. When i first run booksonic the devices see booksonic via dlna but not airsonic.

**Comment by Animatrix1986** [comment]
I have a solution that function for me very well. I set in portainer under Environment "JAVA_OPTS" "-DUPNP_PORT=5051" and "-Dserver.port=5050" and now the server runs on port 5050 and it hosts the UPNP Server on port 5051 , parallel to Booksonic-air which runs on standart port 4040 with upnp server on port 4041. Great
