### ISSUE TITLE
Starred field missing from getArtist (api) responses for starred artists.

### ISSUE THREAD

**Issue by ctedgar** [airsonic/airsonic#1840]
## Problem description

Hello, i am able to star an artist using the [star](http://www.subsonic.org/pages/api.jsp#star) endpoint. However, when using the [getArtist](http://www.subsonic.org/pages/api.jsp#getArtist) endpoint to obtain the details of the starred artist i am unable to tell that the artist is starred as the getArtist response does not contain the starred field. Songs and Albums work as expected when using star/getAlbum and star/getSong endpoints, but not Artists.

### Steps to reproduce (using postman.... you can use any other tool to hit the endpoints)

1. use star endpoint to star an artist (in screen capture it's artist with id 256
![image](https://user-images.githubusercontent.com/23557307/103277446-e76a8b80-49c0-11eb-8163-9721c959d0b4.png)

2. use getArtist endpoint to obtain artist info **(the missing starred field is the issue)**
![image](https://user-images.githubusercontent.com/23557307/103277554-3d3f3380-49c1-11eb-8464-c9e0205f95ae.png)

3. use getStarred2 endpoint to see all starred items (this step is just to show that the artists is indeed starred as it's in the getStarred2 response)
![image](https://user-images.githubusercontent.com/23557307/103277718-91e2ae80-49c1-11eb-949e-3b139ace7d83.png)

## System information

 * **Airsonic version**: *10.6.2-RELEASE*
 * **Operating system**: *Linux (Raspbian)*
 * **Java version**: *1.8.0_65*
 * **Server**: *Apache Tomcat/9.0.31*
 * **Client**: *Postman*
 * **Language**: *English*

**Comment by randomnicode** [comment]
Airsonic adheres to the Subsonic API contract for REST, which does not show starring as part of that API response. Adding it would effectively be an airsonic-specific add-on with no guarantees about whether the rest of the ecosystem uses it.

Here is the Subsonic API doc: http://www.subsonic.org/pages/api.jsp

Also, understand how Subsonic/Airsonic treats and distinguishes between album and artists (at the end of the day, they're all just folders; it's not done on basis of ID3 tags). It is delineated here:
https://github.com/airsonic-advanced/airsonic-advanced/issues/450

**Comment by ctedgar** [comment]
Hi @randomnicode,
Thanks for getting back to me!  The same could be said about Songs and Albums... Yet they contain the starred field (where applicable) in their responses. If you are able to star artists I don't see why their respective objects don't contain the starred field as the Album/Song objects do.
Looking at http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.15.0.xsd 
I can see that starred is indeed an attribute of Artist objects.
![image](https://user-images.githubusercontent.com/23557307/106288308-c60af280-623f-11eb-9436-566f7bb07be0.png)

Also looking at the airsonic datastore, I can see starred tables for albums. songs and artists. In fact you can see the starred artist i used in my issue description
![image](https://user-images.githubusercontent.com/23557307/106289497-41b96f00-6241-11eb-8fc2-c65b7eb05af6.png)


Thanks,
Cris

**Comment by randomnicode** [comment]
See the issue, airsonic-advanced should have the fix

**Comment by ctedgar** [comment]
Hi @randomnicode, 
I guess it's time to head to airsonic-advanced! Your PR looks to be spot on!

Thanks again for the quick turn around,
Cris

**Comment by ctedgar** [comment]
Hi @randomnicode,

Switched to the latest airsonic-advanced snapshot... Your fix worked as expected. 
Just fetched the same artist is used in my issue description.
![image](https://user-images.githubusercontent.com/23557307/106374038-281a4380-6377-11eb-93b0-46de6ef6b5df.png)
The starred field is there :) 

Thanks again,
Cris
