### ISSUE TITLE
Standalone install seems to ignore -Dserver.port

### ISSUE THREAD

**Issue by TedTed** [airsonic/airsonic#1856]
## Problem description

I'm running the latest standalone Airsonic .war as described in [this page](https://airsonic.github.io/docs/install/war-standalone/), launching it with `java -jar airsonic.war -Dserver.port=4040`. Despite the command-line argument, the program seems to listen to port 8080.

### Steps to reproduce

1. Run `netstat -nlp`, paste the output somewhere.
2. Follow [standalone instructions](https://airsonic.github.io/docs/install/war-standalone/) to install & run Airsonic.
3. Launch `java -jar airsonic.war -Dserver.port=4040`.
4. Run `netstat -nlp` again, compare the output to the one before.

Nothing is listening on port 4040, but a new line has appeared, which looks like this on my machine:

`tcp6       0      0 :::8080                 :::*                    LISTEN      17742/java          `

Airsonic is now (successfully) running and listening on port 8080, but not on port 4040.
## System information

 * **Airsonic version**: v10.6.2-RELEASE
 * **Operating system**: up-to-date Debian stretch, kernel 4.9.0-14-amd64
 * **Java version**: ```openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)```
 * **Proxy server**: I normally use nginx, but here the problem appears even if I try to `curl` the web UI from localhost:4040.
 * **Client**: same as above
 * **Language**: English

**Comment by jobenvil** [comment]
@TedTed I would suggest to check the airsonic logfile (`airsonic.log`) to see what's happening. I think `4040` is/was used by the DLNA service or If remember well, something was running exactly under this port. I'm using [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced) (latest snapshot) not with the standard port. Here is my command line: `/usr/bin/java -Xmx2000m -Dairsonic.home=/usr/local/etc/airsonic/config -Dserver.servlet.contextPath= -Dserver.host=0.0.0.0 -Dserver.port=8090 -Djava.awt.headless=true -Dserver.forward-headers-strategy=native -jar /usr/local/etc/airsonic/airsonic.war --illegal-access=warn`

**Comment by randomnicode** [comment]
> java -jar airsonic.war -Dserver.port=4040

the command order is your issue. The jvm arguments need to be before the application arguments. Anything after the app name serves as application arguments.

Try
`java -Dserver.port=4040 -jar airsonic.war`

**Comment by TedTed** [comment]
Ah indeed, this fixes it. Thanks a lot & sorry for the noise! And thanks a bunch for the work you're doing on Airsonic =)
