### ISSUE TITLE
Discussion : do we need a windows installer ?

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#205]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Wednesday Jan 04, 2017 at 13:18 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/204_

----

**Comment by Gallardo26** [comment]
I've been running Libresonic in Windows 10 no issue. Installing Apache Tomcat with it.
Took me a while to figure out as it's not very well documented.

Of course an installer would lower the barrier for entry, but I think for now, a well documented installation guide for tomcat and loading .war package would be good enough until Airsonic is much more recognized and there's more demand for windows installer.

There's an issue I face with it though, running Tomcat and another web server (wamp) requires me to do reverse proxy for easy access, but there's complications to it. If it (Airsonic/Libresonic) could run under a server like Madsonic, that could be more beneficial than running under a webserver.

**Comment by muff1nman** [comment]
We can add one when there is more demand and someone steps up to maintain a windows installer.

**Comment by smaragdus** [comment]
Without installer [Airsonic](https://airsonic.github.io/) will never get traction on Windows and will never become a real alternative to [Subsonic](http://www.subsonic.org/pages/index.jsp).

**Comment by jvoisin** [comment]
Feel free to contribute.

**Comment by smaragdus** [comment]
@jvoisin 

> Feel free to contribute.

I cannot contribute because I am not a developer, just a user.

Currently I use [AudioStreamer](https://audiostreamer.org/) which is cross platform (Windows and Linux) and open source (I could not find the source code though). It works fine and supports not only MP3 but also other lossy and lossless formats via ffmpeg. However it is always better to have alternatives.
