### ISSUE TITLE
Last Fm informations

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#226]
<a href="https://github.com/dorel14"><img src="https://avatars3.githubusercontent.com/u/10910133?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dorel14](https://github.com/dorel14)**
_Monday Jan 16, 2017 at 21:00 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/225_

----

Hello 
Is it possible to have  Last Fm artist informations in french  or another language.

I think it would be great to have these informations in the same language as the user's one .

**Comment by tesshucom** [comment]
This is a fairly old issue and appears to have been resolved.
Is it okay to close it?
