### ISSUE TITLE
New JukeBox

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#257]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Tuesday May 30, 2017 at 19:40 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/pull/446_

----

This PR is for the new JukeBox (and replaces #277).
The new JukeBox works both from Android app or web UI.
This PR can be reviewed, tested and merged.

We could also wait for improvements I'd like to do. I'd like to use the Rest API to control the JukeBox from the web UI but it needs some work on Rest authentication before.

**Mini documentation**

To create a new JukeBox player choose the _Java Jukebox_ technology in the player settings page and select an available audio device (sound card) in the _Audio device_ combo.

![sc1](https://cloud.githubusercontent.com/assets/5565107/26601366/ea22219c-457f-11e7-9720-f6b85ecef283.png)

The Java Jukebox UI player controller now has a slider to scroll while playing.

![sc2](https://cloud.githubusercontent.com/assets/5565107/26601440/1c454b18-4580-11e7-8e80-3fe7982046ca.png)

This control bar could be improved but I think it's worth change things in the playqueue UI before.

Enjoy.

----

_**[biconou](https://github.com/biconou)** included the following code: https://github.com/Libresonic/libresonic/pull/446/commits_

**Comment by andresmoschini** [comment]
There were a confusion here? Am I missing something?

> muff1nman closed this issue in 502b5fb
8 months ago

> Fix #257 Playlist download dups

**Comment by jooola** [comment]
@andresmoschini Yes it happened when we imported issues and PR's from libresonic and mixing PR/Issues numbers broke some issue links in the old posts.

But this ticket can be closed anyway (Also really old 4 Jul 2017).
