### ISSUE TITLE
FLAC playback

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#258]
<a href="https://github.com/aairey"><img src="https://avatars2.githubusercontent.com/u/7644094?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aairey](https://github.com/aairey)**
_Wednesday Feb 22, 2017 at 09:00 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/256_

----

Hello,

I have been using this workaround successfully with Madsonic and Subsonic in the past.

https://wiki.archlinux.org/index.php/Subsonic#FLAC_playback

However, it does not seem to work on Libresonic.
I am running it as a deployed war inside a jail on FreeNAS (FreeBSD 10), inside a jail that was formerly used by madsonic.

The flac and lame binaries are available and symlinked from the /var/lib/libresonic/transcoders dir ...

**Comment by pozgo** [comment]
For all of those like me who love Hi-Res audio, I have settings like below working perfectly

Name|Convert From|Convert to| Step 1|Step2
-- | -- | -- | -- | --
|flac|... any...|flac|`ffmpeg -i %s -af aformat=s32:176000 -f flac -`|| 

The above encodes to a 176 kHz 24-bit sample, stored as 32-bits 

In my case, most of my files are already Hi-Res so not losing any quality.
