### ISSUE TITLE
Possible bug and information

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#268]
<a href="https://github.com/dubima"><img src="https://avatars0.githubusercontent.com/u/26127860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dubima](https://github.com/dubima)**
_Friday Mar 03, 2017 at 20:17 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/266_

----

version 6.1
Firstly, i have to get ffmpeg in order to be able to transcode, is this intended?

Playing videos with the web player doesn't allow me to use the time tracker, every video is always 0.00:0.00. Clicking anywhere on the time track restarts the video. Music plays fine and is tracked.

Another thing, subsonic used to open various ports, one i recall is 9412, which looking at the code it is for DeployerService. Now if i bound subsonic to local only that port and the others would ignore and still be accessible via the internet. Libresonic on the other hand, as it's behind tomcat doesn't apart from one port, I can't find it in the code as I'm guessing it's a random port every start, right now it's port 35141, before it was 45676, I'm guessing if restarted then it would be a different port too.

My question to that one is, what's it used for, is it the callback service for url.libresonic.org or for DLNA/UPnP or Sonos or lastfm or ...?

**Comment by pwepwe973** [comment]
Je sais pas si c'est ici qu'on fait les rapports de bug.
mais j'ai constaté que les boutons "flèche suivant ou précèdent" pour lancer la lecture de la piste suivant ou précèdent fonctionne pas correctement  ni sur les application comme dsub, ni sur l'interface web de airsonic.

Cordialement SYLVAIN

**Comment by pwepwe973** [comment]
Je sais pas si c'est ici qu'on fait les rapports de bug.
mais j'ai constaté que les boutons "flèche suivant ou précèdent" pour lancer la lecture de la piste suivant ou précèdent fonctionne pas correctement  ni sur les application comme dsub, ni sur l'interface web de airsonic.

Cordialement SYLVAIN
