### ISSUE TITLE
Web player stops advancing

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#269]
<a href="https://github.com/n8wood"><img src="https://avatars3.githubusercontent.com/u/23563716?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [n8wood](https://github.com/n8wood)**
_Friday Mar 03, 2017 at 21:42 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/267_

----

After a few songs in the web player, it stops advancing and effectively pauses. This only seems to occur in Chrome, Firefox works normally. Is this an HTML vs Flash issue?

Libresonic 6.1, Chrome (56.0.2924.87) on Linux.

**Comment by jooola** [comment]
Closing this since JWplayer has been replaced by and HTML5 player !

**Comment by jooola** [comment]
@gryphonmyers Please feel free to open a new issue, and give us all the details of your problem !
