### ISSUE TITLE
Jukebox improvement

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#278]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Monday Mar 06, 2017 at 21:29 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/276_

----

I use Subsonic for streaming music on my Android phone but also to listen to music on my Hi-Fi stereo system. 
That's why I am very fond of the Jukebox player. 
Unfortunately, the legacy jukebox player is (IMOO) poorly developed. 
In past years, I developed for myself a better jukebox technology based on the [cmus](https://cmus.github.io/) audio player;  it works perfectly but has also downsides :

- cmus is only available on linux
- it requires a cmus process to be running
- it brings some hairy synchronization problems between Subsonic play queue

At the moment, I am working on a new improved jukebox player that aims to solve some of the legacy jukebox weaknesses. 
My new jukebox seems to work properly and I am on the way to submit a pull request for experimental purpose.
The new jukebox is based on the Java Sound API thus there is no dependencies on ffmpeg. It should work on both linux and windows and take every advantage of audio devices. 

For discussion, I propose the following list of all the legacy jukebox downsides that could be considered as a first attempt to build a roadmap around this development.

- no gapless play
- systematically resamples (through ffmpeg command line) thus it can not take advantage of Hi-Res medias
- depends on ffmpeg
- not able to scroll to a desired position
- can not deal with several audio devices (in case you have multiple audio cards plugged)
- difficult to drive from android devices

**Comment by jooola** [comment]
@biconou Any news on this issue ? I know you have been working on it since then.

I guess as a road map this issue can now be closed since we have more recent issue on this ?
