### ISSUE TITLE
version.txt

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#297]
<a href="https://github.com/jooola"><img src="https://avatars2.githubusercontent.com/u/19195485?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jooola](https://github.com/jooola)**
_Wednesday Mar 15, 2017 at 13:58 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/295_

----

I see that the [https://libresonic.org/release/version.txt](https://libresonic.org/release/version.txt) still is named SUBSONIC, should we move it to LIBRESONIC ?

**Comment by jooola** [comment]
Closing this since after we rebrande to Airsonic, we use github as version checker !

See #493
