### ISSUE TITLE
cue sheet support for one flac per disc files

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#303]
<a href="https://github.com/svolki"><img src="https://avatars2.githubusercontent.com/u/26509675?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [svolki](https://github.com/svolki)**
_Saturday Mar 18, 2017 at 18:56 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/301_

----

It would be great, if libresonic could handle cue sheets embedded into flac files, see https://en.wikipedia.org/wiki/Cue_sheet_(computing).

Using this a whole CD image can be stored in one flac file and be used as playback source as well as backup of the original disc.

**Comment by jooola** [comment]
A PR is present on the libresonic repo, #495 is following this PR.

Closing this ! ( can be reopened if the PR isn't merged in Airsonic )

**Comment by muff1nman** [comment]
Let's not get too hasty closing issues. The policy should be the issue gets closed after the PR is merged.

**Comment by tesshucom** [comment]
At Airsonic, #856 looks like successor work. Too many multiple posts. I'll close it. If there is a problem, please reopen it.
