### ISSUE TITLE
Tomcat not Shutting down correctly

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#313]
<a href="https://github.com/muff1nman"><img src="https://avatars2.githubusercontent.com/u/1531528?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [muff1nman](https://github.com/muff1nman)**
_Thursday Mar 23, 2017 at 03:55 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/311_

----

`./catalina.sh stop` doesn't stop tomcat with libresonic running. I have a feeling it might be something we are leaving open.

**Comment by jooola** [comment]
@muff1nman Any news on this issue ?

**Comment by muff1nman** [comment]
Lets close this as I don't think its a problem any more.
