### ISSUE TITLE
Domain included twice when using X-Forwarded-Host

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#315]
<a href="https://github.com/EugeneKay"><img src="https://avatars0.githubusercontent.com/u/528798?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EugeneKay](https://github.com/EugeneKay)**
_Friday Mar 24, 2017 at 05:30 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/313_

----

Nginx config:

```
server {
    listen [::]:443 ssl;
    server_name libresonic.org;
    rewrite ^/$ https://github.com/Libresonic/libresonic;
    location /libresonic {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Forwarded-Host "libresonic.org";
        proxy_set_header X-Forwared-Proto "https";
    }
}
```

Playing a video yields the error message: `The video could not be loaded, either because the server or network failed or because the format is not supported: https://libresonic.org/libresonic.org/libresonic/stream?id=7&player=2&maxBitRate=2000&timeOffset=0`

**Comment by jooola** [comment]
cc @airsonic/maintainers I guess if this is only a Typo issue we can close it ?
