### ISSUE TITLE
6.2B2 "confused" music playback

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#323]
<a href="https://github.com/texneus"><img src="https://avatars2.githubusercontent.com/u/23441049?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [texneus](https://github.com/texneus)**
_Tuesday Mar 28, 2017 at 15:33 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/321_

----

I had a very strange thing happen to me this morning.  This may have been a complete fluke (still researching) but this seemed significant enough to at warrant a heads up.

Basically what happened is, when using random play on Dsub, only the first track played correctly.  From memory (so the details may not be exact),  the second track played the indicated song, but displayed cover art from a different artist.  The third song was the right cover art, but was playing a track from a different artist.  The fourth track was the right cover art (I think) and artist, but not the indicated song.   On and on where nothing matched up 100%.  I eventually stopped playback, deleted my cache, and upon restart it seemed to be OK.

Install details:
- Installed 6.2 beta 2 last night
- Clean install of Beta 2 into a new, clean jail
- Used Springboot feature (no Tomcat)
- 6.2 beta 1 was working correctly under Tomcat8 previously
- Proxied via Nginx over HTTPS
- NAS4Free 11.0.0.4 (FreeBSD 11.0-P7) OS

Other potential factors:
- Even though flushing cache seemed to resolve it, none of the songs affected were already cached.
- DSUB client on mobile network
- DSUB set to random play
- Large music library (~20,000 titles).
- Streaming is set to convert all audio to .ogg w/ffmpeg
- Testing at home (on local and mobile network) immediately after install did not show any problem
- The fifth or so track wouldn't download at all but skipping past it was no problem (need to follow-up and see if there is a corrupt file).  However tracks both before and after we're impacted.
- Verified my wife was not playing audio at the same time...so no chance of "crossed streams".

I owe:
Longer playtime...is this repeatable?
~~Log files from this morning~~ See below
~~Troubleshoot non-playing track~~ All tracks on album are fine

**Comment by jooola** [comment]
@texneus any news on this issue ? Any changes after upgrading to v10.1.1 ?
