### ISSUE TITLE
DISCUSSION: JavaScript code is messy in Subsonic

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#334]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Monday Apr 03, 2017 at 20:24 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/332_

----

I am working on some piece of javascript code (in playQueue.jsp) and I think it is very messy.
I think that we should discuss of some guidelines to write a better javascript code in our Libresonic evolutions.

- javascript is mixed with jsp tags.
example in playQueue.jsp
```
    function onSkip(index) {
    <c:choose>
    <c:when test="${model.player.web}">
        skip(index);
    </c:when>
    <c:otherwise>
        currentStreamUrl = songs[index].streamUrl;
        playQueueService.skip(index, playQueueCallback);
    </c:otherwise>
    </c:choose>
    }
```
 
- javascript should be stored in separate .js files and shrinked
- jQuery core is misused
Example 
```
        if ($("#start")) {
            $("#start").toggle(!playQueue.stopEnabled);
            $("#stop").toggle(playQueue.stopEnabled);
        }
```
This will not test if an element whose id is "start" exists. One should write $("#start").length > 0
see https://learn.jquery.com/using-jquery-core/faq/how-do-i-test-whether-an-element-exists/

**Comment by jooola** [comment]
See #473
