### ISSUE TITLE
DISCUSSION : JavaScript dependency management

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#361]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Saturday Apr 22, 2017 at 20:02 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/360_

----

I'd  like to introduce a solution for JavaScript lib dependency management. 
I think a choice should be made between 

- NPM
- bower

Any suggestion ?

**Comment by muff1nman** [comment]
@bfkelsey I imagine you've already solved this problem in your current work?

**Comment by bfkelsey** [comment]
Yeah, it is all handled by npm.

**Comment by muff1nman** [comment]
Cool, closing this then
