### ISSUE TITLE
DISCUSSION : JavaScript model/view binding

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#362]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Saturday Apr 22, 2017 at 20:07 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/361_

----

I'd like to introduce a JavaScript model/view binding and templating tool. 
I think **Knockout** (http://knockoutjs.com/index.html) is a very smart solution. 

What to you think ?

**Comment by gryphonmyers** [comment]
I think using a modern web framework sans dated practices like jQuery-reliant DOM manipulation would be nice, but I think the more important / bigger goal should be adapting Airsonic to a more modern server / client architecture where the Java code functions primarily as a REST API and the frontend is all AJAX queries to the API. Obviously there's already the Subsonic API in place, but there's certainly Airsonic-specific functionality that would need to be refactored into an API as well.

Which front end framework gets used is more or less arbitrary, but if I had to cast a vote I'd probably go with Vue over Knockout, React, Angular, Riot... etc.

**Comment by jooola** [comment]
@gryphonmyers This is actually happening ! We are trying to make airsonic a RESTful API based webapp. The airsonic API pr is mostly for this and the airsonic-ui is also taking this way.

Backend based using spring and frontend using Angular.

See airsonic/airsonic-ui also #533 #522 #479

**Comment by gryphonmyers** [comment]
Oh very cool! Thanks for that history. I'm glad to hear that it's in progress. I'd say this issue can be closed then! I am very busy but will see if I can find time to contribute in the future. I am primarily front end.
