### ISSUE TITLE
DISCUSSION : very interesting audio player components

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#363]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Monday Apr 24, 2017 at 19:49 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/362_

----

SoundManager 2 seems to be worth studying to improve audio player UI.
http://www.schillmania.com/projects/soundmanager2/

**Comment by jooola** [comment]
Obsolete issue since we moved to html5 player using meadielement.js
