### ISSUE TITLE
Libresonic v6.3 Planning

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#374]
<a href="https://github.com/EugeneKay"><img src="https://avatars0.githubusercontent.com/u/528798?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EugeneKay](https://github.com/EugeneKay)**
_Tuesday May 02, 2017 at 16:28 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/373_

----

This will be the Omnibus Release Planning thread for Libresonic 6.3. This is a developer discussion; please limit user discussions/problems to IRC or other Issues. This will be a development release, meaning that there will be a lot of breakage in the develop branch before it is stable. Questions to be answered:

- What is the release date: Planned for July 4th, 2017(approximately two months from 6.2)
- What features are targeted for this release? Suggestions: removal/replacement of JWPlayer, Windows/Linux packaging
- Are there any outstanding issues from 6.2 that should go into develop instead of stable(to become 6.2.1)?
- [Do you want a :taco:?](https://youtu.be/k3tcQI5EEiA)

Please indicate what you would like to work on for this release, so that we can get an estimate of what will actually happen(in the form of a checklist).

**Comment by jooola** [comment]
cc @airsonic/maintainers I'm going to close this and reopen a new issue for the 6.3 release !
The enhancement mentioned above will need to move to the 6.4 release !
