### ISSUE TITLE
Show all albums missing in List View

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#381]
<a href="https://github.com/fozzedout"><img src="https://avatars1.githubusercontent.com/u/6894919?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fozzedout](https://github.com/fozzedout)**
_Thursday May 04, 2017 at 10:52 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/380_

----

I've noticed that when you have many albums, the "Show All Albums" button is missing when I'm in a list view, but it does show when it's in the tile/grid view.
In mine, I have 120 albums under one artist, but only 40 show.

**Comment by jooola** [comment]
@fozzedout I think this hs been fixed since then, could your tell us ? With airsonic 10.1.1 ?
