### ISSUE TITLE
Chromecast is not working

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#391]
<a href="https://github.com/Tapchicoma"><img src="https://avatars3.githubusercontent.com/u/1595262?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tapchicoma](https://github.com/Tapchicoma)**
_Monday May 08, 2017 at 17:26 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/390_

----

After updating to 6.2 I've checked if chromecast now working, but it is not.

I can start casting session, but streaming itself fails.

From chrome dev tools I see that chrome session is successfully started, but failed to load stream url:
`code: "session_error", description: "LOAD_FAILED"`

I've checked stream url and it is valid (at least browser opens it and plays song).

My suspicion is that this stream url doesn't allow other then current browser to access it and casting device so can't open it.

**Comment by siyb** [comment]
Using airsonic "10.1.1-RELEASE – December 16, 2017" I am still encountering this issue when attempting to cast to a Chromecast audio. Should I open up a new ticket or did this fix not make it into the release?

**Comment by bonswouar** [comment]
Another issue that might be related (except if I'm the only one having this problem ?), the jwt token sent to Chromecast with in cover image url (in the metadatas) is apparently not valid anymore. Is it revoked after being consumed or there is another explanation ?
