### ISSUE TITLE
Large playlists import

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#396]
<a href="https://github.com/jooola"><img src="https://avatars2.githubusercontent.com/u/19195485?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jooola](https://github.com/jooola)**
_Thursday May 11, 2017 at 12:06 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/395_

----

I tried to upload a .xspf playlist to libresonic, and I the playlists duplicates itself at the end of the "importing process" ( which takes TIME )

![capture d ecran de 2017-05-11 00-12-43](https://cloud.githubusercontent.com/assets/19195485/25948173/ac6d6ea6-3652-11e7-8682-b7b8273710b4.png)

I guess this is due to a huge amount of entries in this playlist, Or maybe juste simply the .xspf import is buggy.

And some improvement really needs to be done when trying to play large playlists

**Comment by muff1nman** [comment]
@jooola have you tried this recently? Is this still a problem?

**Comment by jooola** [comment]
Nope, let me try this again in the next days

**Comment by jooola** [comment]
This seems to be fixed ! nice ! Imported a 2870 track play list with no problems and much faster than last time !
