### ISSUE TITLE
Find new fonts and provide them locally

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#399]
<a href="https://github.com/jooola"><img src="https://avatars2.githubusercontent.com/u/19195485?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jooola](https://github.com/jooola)**
_Friday May 12, 2017 at 01:58 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/398_

----

I think we should provide fonts locally instead of loading them from the google api

**Comment by jooola** [comment]
Moved to #853
