### ISSUE TITLE
Sound control issue with internet radios

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#408]
<a href="https://github.com/dvoijen"><img src="https://avatars2.githubusercontent.com/u/28559228?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dvoijen](https://github.com/dvoijen)**
_Tuesday May 16, 2017 at 14:36 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/407_

----

When listening to a created internet Radio, you cannot stop it from playing.
When playing a new song it will play bothe the same time...

**Comment by sprnza** [comment]
Hi gents! The issue is still there.
Version: 10.1.0-SNAPSHOT – October 26, 2017

**Comment by antipiot** [comment]
I came here to report this aswell :-)

**Comment by KingDuckZ** [comment]
Good for you, I can't play any radio at all! (through nginx/https)

**Comment by sprnza** [comment]
It starts playing for me only if I click on the triangle play button in front of a station name if I recall correctly.

**Comment by VinArt** [comment]
I can confirm this with airsonic running from docker container:
10.1.0-RELEASE – November 4, 2017
jetty/9.4.7.v20170914, java 1.8.0_131, Linux
Nginx 1.12.1-1.fc26
Chrome 62

I can add a TV/Radio station and start playing with clicking play button next to station name, but I cannot stop it and it plays together with anything else if started.

**Comment by incyclum** [comment]
I also have the same issue. I need to refresh the page (F5) to circumvent it.

**Comment by jriker1** [comment]
Same here, just installed WAR file into Tomcat8.

**Comment by Sp33dFr34k** [comment]
Still seems to be an issue almost 2 years later, any hope for a fix?

**Comment by skyzem** [comment]
Same here.

**Comment by fxthomas** [comment]
I had a quick look at this ; now that we have an HTML5 player, I think this could be solved by adding some logic to parse external .pls/.m3u files and load their items into the `mediaelement.js` player (right now webradios don't use the player at all, which is why they cannot be stopped).

I ran a test with some webradios I have, and it works well if you select the source manually ; but because of CORS I wasn't able to load .pls/.m3u files directly in JS, so we might need to implement it server-side.

**Comment by pwepwe973** [comment]
i have a same problem.
when I click on the triangular button in front 
of the name of the radio it is impossible to listen to the radio

**Comment by fxthomas** [comment]
@pwepwe973 If you're feeling adventurous you can try testing my work-in-progress branch in the PR linked above ; it still has a few UI issues but should otherwise be usable.

**Comment by pwepwe973** [comment]
@fxthomas I will wait for an update :) for the moment not too much time to embark on the adventure.
