### ISSUE TITLE
Homebrew formula - help requested

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#431]
<a href="https://github.com/mshick"><img src="https://avatars2.githubusercontent.com/u/277401?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mshick](https://github.com/mshick)**
_Sunday May 21, 2017 at 20:13 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/430_

----

I recently migrated from Subsonic to libresonic on my Mac mini music server. 

I found getting started a bit overwhelming as a non-Java dev (it's easy in the end, to the credit of the project, just made me feel dumb). I've been working on a Homebrew script to make getting started with sane defaults easier, and for the excellent plist / service support in Homebrew. 

I've set about creating a Homebrew formula with sane defaults, so that somebody in a similar situation could get going quickly. I've had some good luck here: https://github.com/mshick/homebrew-personal/blob/master/Formula/libresonic.rb

Next, I'm looking to have this formula use PostgreSQL as the database — my library is 50k and the embedded db really struggles with it.

Can anyone offer tips? Is this something I can reasonably accomplish with just java runtime flags, as I've been doing, or will I need to work out writing config files as well?

I've been through all the docs, and links, but am still a bit stumped on things like the `classpath` and where / how I might acquire the postgres DB driver and where I should place it, given my direct invocation / Spring Boot approach.

**Comment by jooola** [comment]
Any news here ?

**Comment by muff1nman** [comment]
Perhaps we should consider doing this for the next 10.0.0 release -- provide versions of the war with supported db drivers.

**Comment by muff1nman** [comment]
This has been resolved with #508

**Comment by muff1nman** [comment]
cc @mshick
