### ISSUE TITLE
Jukebox doesn't close files properly

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#433]
<a href="https://github.com/Whisprin"><img src="https://avatars1.githubusercontent.com/u/3153136?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Whisprin](https://github.com/Whisprin)**
_Monday May 22, 2017 at 17:26 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/432_

----

I am using the Android App Dsub to connect to my Libresonic instance. After using the jukebox Libresonic doesn't release the last played file.

Steps to reproduce:
- Mount a drive `/mt/drive` and add it as a media folder in Libresonic
- Connect to Libresonic jukebox
- Play a song
- Disconnect from the jukebox
- Try to unmount the drive
- Check with lsof `/mnt/drive` who's blocking the file:
```
COMMAND   PID    USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
ffmpeg  29061 tomcat8    3r   REG   0,40 26939742 117812 /mnt/drive/path/to/last/played/file.flac
```

As you can see the actual command is ffmpeg, which was invoked by Libresonic. It looks like this:
`Starting transcoder: [/var/libresonic/transcode/ffmpeg] [-ss] [10] [-i] [/mnt/drive/path/to/last/played/file.flac] [-map] [0:0] [-v] [0] [-ar] [44100] [-ac] [2] [-f] [s16be] [-]`

My proposal: Since ffmpeg is writing to a pipe and Libresonic stops reading the ffmpeg process is never terminated.

I read #373 and especially #277. Maybe it can be tackled during one of the bigger changes? Since, as per my understanding, the new jukebox won't replace the old one I think this is still a valid bug.

Versions:
- Libresonic v4.2 stable (EDIT jooola : v6.2 i think ! )
- tomcat 8.0.42
- Apache 2.4.25

**Comment by jooola** [comment]
@Whisprin Any news on this ? With airsonic 10.1.1 ?
