### ISSUE TITLE
curl-based cookie auth (for automated library scans)

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#440]
<a href="https://github.com/mshick"><img src="https://avatars2.githubusercontent.com/u/277401?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mshick](https://github.com/mshick)**
_Saturday May 27, 2017 at 03:27 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/439_

----

I've long used a hack that would curl into my subsonic instance and trigger the scan endpoint. This is to update my library when I add music.

The script looks like this (using `watchman`)

```
if [[ $json == *"\"files\":"* ]] && [[ $json != *"\"files\": []"* ]]
then
	echo "[$(date)] Found changed files. Refreshing Subsonic database.";
	/usr/bin/curl -d "j_username=admin&j_password=admin&submit=Log in" -c /tmp/subsonic-cookie.txt -s http://localhost:4040/j_acegi_security_check > /dev/null
	/usr/bin/curl -b /tmp/subsonic-cookie.txt -s http://localhost:4040/musicFolderSettings.view?scanNow > /dev/null
fi
```

Unfortunately this isn't working with libresonic. Can anybody suggest what might need to change to make this work?

Also, it doesn't appear that libresonic yet has the [startScan](http://www.subsonic.org/pages/inc/api/examples/scanStatus_example_1.xml) endpoint — which I only realized was recently introduced in 6.1 / API v1.15.0. Are there plans to support it? That would make this whole scenario much simpler.

**Comment by jooola** [comment]
Closing this since we update API to Subsonic API 1.15 ! See #461
