### ISSUE TITLE
FR: Add button that appends album to the current playlist

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#442]
<a href="https://github.com/Tapchicoma"><img src="https://avatars3.githubusercontent.com/u/1595262?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tapchicoma](https://github.com/Tapchicoma)**
_Sunday May 28, 2017 at 09:19 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/441_

----

When I am on albums overview screen and point mouse over album image - play button appears, but it would be nice also to have button that on click appends selected album to the current playlist. Currently I need to click on album to open it and there click on "Add all".

![librefr](https://cloud.githubusercontent.com/assets/1595262/26527592/44c3ab56-4397-11e7-9c7f-641e990f4055.jpg)

**Comment by jvoisin** [comment]
This is implemented :)
