### ISSUE TITLE
Support the new startScan endpoint

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#443]
<a href="https://github.com/mshick"><img src="https://avatars2.githubusercontent.com/u/277401?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mshick](https://github.com/mshick)**
_Monday May 29, 2017 at 04:21 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/442_

----

In version 6.1 / API version 1.15 Subsonic added the `startScan` endpoint: http://www.subsonic.org/pages/inc/api/examples/scanStatus_example_1.xml

It would be great to see this supported, perhaps along with the `getScanStatus` endpoint for feature parity.

I added an issue #439 discussing a use-case I have for this — triggering scans on library updates determined via external routines.

**Comment by mshick** [comment]
@muff1nman Thanks! I was able to adapt my script using the new endpoint.

For anybody interested, here's a gist with my service plist and the shell script I run to perform updates whenever files in my Airsonic library change. 

https://gist.github.com/mshick/abf4664c85cd511f86b9f91ee813ecb3

It uses Facebook's watchman tool.

@muff1nman I can submit a docs PR if you think this might be valuable for others in a Tips & Tricks section.

**Comment by muff1nman** [comment]
@mshick that looks like something folks might find useful. Hopefully in the future we could build something like this directly into airsonic.
