### ISSUE TITLE
Prevent Play Queue automatically popping up

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#445]
<a href="https://github.com/SuperNerd-James"><img src="https://avatars1.githubusercontent.com/u/2358163?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SuperNerd-James](https://github.com/SuperNerd-James)**
_Tuesday May 30, 2017 at 13:41 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/444_

----

On SubSonic and LibreSonic, the play queue constantly pops up whenever you go anywhere near the bottom of the screen with the mouse, and I find it *really* annoying, it's obtrusive.

Would it be viable to add a button around where the queue pops up from, so it only pops up when we want it to by clicking it. Would this be viable? There could be an option in the settings to keep the original behaviour for other people that like it the way it is by default.

**Comment by rfporter** [comment]
I also agree that a button for show/hide play queue would be much more comfortable than auto-hide.

On V10.1.2 you can disable auto-hide. That makes the play queue always shown but it is only 3 tracks high and can't be resized.
