### ISSUE TITLE
Mediaelement.js Placeholder issue

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#448]
<a href="https://github.com/muff1nman"><img src="https://avatars2.githubusercontent.com/u/1531528?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [muff1nman](https://github.com/muff1nman)**
_Wednesday May 31, 2017 at 02:50 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/448_

----

This issue is to track the larger progress on mediaelment.js migration effort. So far we have the basics in place from #425. The updated checklist of remaining items is as follows:

#### PR Merged
- [x] Liquibase changes reverted
- [x] New Liquibase migration for any new transcodings we want/need to use with mediaelement to at least get it working OR see if `video/flv` works
- [X] steps for reproducing the mediaelement sources (i.e. in case of upgrade)

#### Develop Merged to Stable
- [ ] ~Remove duplicate code between audio and video `CastPlayer`s~ EDIT: descoped
- [ ] ~Move `CastPlayer` javascript embedded in videoPlayer/playQueue.jsp to standalone js~ EDIT: descoped
- [ ] ~Chrome cast support (use mediaelement plugin)~ EDIT: descoped
- [X] Stylizing of ME to match themes (#457)

#### Future work
- [ ] Support no transcode in the case none is needed.
- [ ] Change format type to use accept header (allows proper negotiation with server without a statically set format)
- [ ] Research into the most optimal video formats to use and prioritize them.
- [ ] Full screen control OR use ME controls for video (although I'd like to see this one done as part of the PR, it might be dependent on some of these other tasks)
- [ ] Update external player to use ME
- [x] Remove jwplayer sources

**Comment by muff1nman** [comment]
Couple changes here:
- I've moved this to milestone v10.0. Specifically I would like to have everything in the "Develop Merged to Stable" section completed
- I've deprioritized changes to the video controls for now as that is probably out of scope of v10.0.

**Comment by muff1nman** [comment]
Moved external player and cleanup task out of the tasks to be completed for 10.0.
