### ISSUE TITLE
Move to HTML5 Player

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#45]
<a href="https://github.com/EugeneKay"><img src="https://avatars0.githubusercontent.com/u/528798?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EugeneKay](https://github.com/EugeneKay)**
_Thursday May 05, 2016 at 01:24 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/45_

----

Moving to a HTML5 player is desired. Patches welcome.

**Comment by jooola** [comment]
Closing this since we have a HTML5 player in da house ! #426 

See #448 for future discuss
