### ISSUE TITLE
451 dlna browse

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#452]
<a href="https://github.com/akpdw"><img src="https://avatars3.githubusercontent.com/u/1761239?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [akpdw](https://github.com/akpdw)**
_Saturday Jun 03, 2017 at 14:49 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/pull/452_

----

Fixes Libresonic/libresonic#451

This replaces the existing FolderBasedContentDirectory with a new DispatchingContentDirectory.  The new system then dispatches requests to subclasses of UpnpContentProcessor, which then handle the requests as appropriate.

This also adds a new searchSongsByName method to MediaFileDao, which is used for the search by song functionality.

----

_**[akpdw](https://github.com/akpdw)** included the following code: https://github.com/Libresonic/libresonic/pull/452/commits_

**Comment by gerroon** [comment]
I think this broke content listing for most dlna players on android. Request by the dlna apps returns all empty

  INFO --- o.a.p.s.u.DispatchingContentDirectory    : UPnP request - objectId: recent, browseFlag: BrowseDirectChildren, filter: *, firstResult: 0, maxResults: 512
  INFO --- o.a.p.s.u.DispatchingContentDirectory    : UPnP request - objectId: recent, browseFlag: BrowseDirectChildren, filter: *, firstResult: 512, maxResults: 512
  INFO --- o.a.p.s.u.DispatchingContentDirectory    : UPnP request - objectId: recent, browseFlag: BrowseDirectChildren, filter: *, firstResult: 1024, maxResults: 512
  INFO --- o.a.p.s.u.DispatchingContentDirectory    : UPnP request - objectId: recent, browseFlag: BrowseDirectChildren, filter: *, firstResult: 1536, maxResults: 512
