### ISSUE TITLE
Ability to ignore album subfolders such as "scans"

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#455]
<a href="https://github.com/codicusmaximus"><img src="https://avatars1.githubusercontent.com/u/11328458?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [codicusmaximus](https://github.com/codicusmaximus)**
_Wednesday Jun 07, 2017 at 02:34 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/455_

----

Feature request - add the ability in the settings to define a list of folder names / wildcards that should be ignored.  The issue is that when an Album folder contains a folder named "scans" or "extras" it shows up as a clickable item in both the Web UI and most phone clients yet when you click them they contain no music.  It might also be a good idea to simply not show folders if they contain no music.

**Comment by jooola** [comment]
This can now be accomplish using the exclude pattern tool
