### ISSUE TITLE
MediaElement ui for default theme

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#457]
<a href="https://github.com/muff1nman"><img src="https://avatars2.githubusercontent.com/u/1531528?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [muff1nman](https://github.com/muff1nman)**
_Thursday Jun 08, 2017 at 00:55 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/pull/457_

----

First crack at stylizing mediaelement. #448 

----

_**[muff1nman](https://github.com/muff1nman)** included the following code: https://github.com/Libresonic/libresonic/pull/457/commits_

**Comment by muff1nman** [comment]
6.4? It seems silly to delay this till then. We could merge this as is and if someone wants to come through and change it to a better transparent css method, it should be easy to swap out.

**Comment by jooola** [comment]
I though 6.3 will be for the rebranding and any further enhancement will be merged for 6.4 ?

We should write some planning on the 2 next releases that we all agree !

**Comment by muff1nman** [comment]
Should we schedule an irc planning meeting for this?

**Comment by jooola** [comment]
Yeah why not !?

Can't in the next days but this week end maybe ?

**Comment by muff1nman** [comment]
How about Saturday 22, at 15:00 UTC?

**Comment by jooola** [comment]
Fine for me !

@biconou what de you think ?

**Comment by biconou** [comment]
Sorry i am away for 3 weeks for summer hollydays

**Comment by muff1nman** [comment]
Although there are rumors of larger changes that we can do for the play queue, #496 has been merged which is the minimum of what needed to be done here. We can address further improvements in other issues.
