### ISSUE TITLE
Subsonic api 1.15.0

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#461]
<a href="https://github.com/muff1nman"><img src="https://avatars2.githubusercontent.com/u/1531528?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [muff1nman](https://github.com/muff1nman)**
_Friday Jun 09, 2017 at 01:59 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/pull/461_

----

Reverts #329 as I think it was causing issues. Updates libresonic to implement subsonic api 1.15.0 with the following exceptions:

getChatMessages returns 410 Gone
addChatMessage returns 410 Gone
getVideoInfo returns 501 Not implemented
getCaptions returns 501 Not implemented

`converted` parameter is not yet supported for /rest/stream
playlist is not returned on playlist creation

----

_**[muff1nman](https://github.com/muff1nman)** included the following code: https://github.com/Libresonic/libresonic/pull/461/commits_

**Comment by xsteadfastx** [comment]
`/getVideoInfo` still gets a 501. im writing a python async wrapper for the api and discovered that,
