### ISSUE TITLE
Moderate CPU usage even when idle

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#465]
<a href="https://github.com/protist"><img src="https://avatars2.githubusercontent.com/u/646668?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [protist](https://github.com/protist)**
_Thursday Jun 15, 2017 at 12:01 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/465_

----

I followed (all of) the [instructions](https://libresonic.github.io/docs/install/example/raspberrypi/) for installation of Libresonic 6.2 in Raspbian, on a Raspberry Pi 3.

(FWIW I had to make a few changes. I don't have systemd, so instead of `sudo systemctl stop tomcat8.service` I ran `sudo /etc/init.d/tomcat8 stop`. Tomcat didn't install to `/var/tomcat8`, but `/var/lib/tomcat8` instead, so I had to change those commands. And since I had multiple javas installed, and Tomcat didn't respond to `sudo update-alternatives --config java`, I had to hardcode the java version at `/etc/default/tomcat8`.)

In any case, I got Libresonic working, then [migrated](https://libresonic.github.io/docs/migrate/) from Subsonic. However, I'm finding that CPU usage is always moderate, even when nothing is happening. Tomcat seems to vacillate from ~40% to ~150% of a core.

In comparison, I'm concurrently running subsonic 6.0, and this uses essentially 0% CPU. I also tried removing `/var/lib/tomcat8/webapps/libresonic.war` and `/var/lib/tomcat8/webapps/libresonic` and restarting tomcat, and CPU usage went down to <1%.

During this moderate CPU usage, there is nothing at all happening in `/var/libresonic/libresonic.log`. I'm not sure what else to check, but I'm happy to troubleshoot more. Unlike issue #281, I'm using the recommended `/usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt`.

**Comment by protist** [comment]
Hello, and nice fork. 😁 I'm happy to provide more information if helpful, although I imagine you have a few other things to do. This discussion stalled a bit in the Libresonic issue tracker, but I'm still keen to get this resolved.

**Comment by muff1nman** [comment]
Thanks for the reminder on this one. I'm not seeing anything jump out at me from the thread dump, I might have to pull out one of my RPis and give it a go (though I think mine is V2)

**Comment by protist** [comment]
Thank you for the response. I've actually just upgraded from Raspbian (Debian) Wheezy to Stretch, and it seems to be fine now! I guess it was some bug in tomcat or similar that was exposed by libresonic/airsonic. Please feel free to close this issue. Cheers.
