### ISSUE TITLE
Player stops working after hibernate, even after logout and login again

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#466]
<a href="https://github.com/SuperNerd-James"><img src="https://avatars1.githubusercontent.com/u/2358163?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SuperNerd-James](https://github.com/SuperNerd-James)**
_Thursday Jun 15, 2017 at 22:20 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/466_

----

This is using the development version with new player. The server runs fine, 24/7. Hoever in a browser, if I have Libresonic running, pause or stop the music, and then hibernate the client computer (not the server, obviously as that needs to run 24/7, it powers my enterprise), when I come back to it it acts weird. It does these things:

1. It acts as if it's playing, even showing the browser notifications on track change.

however:

2. It plays no sound.

3. The player bar (both current time and total time sections) is stuck at 0.00, and the volume bar drops to 0, even if I put it back to 100%, select another track, it drops back to 0.

![libresonic weird player bug](https://user-images.githubusercontent.com/2358163/27204010-8c103de8-5220-11e7-947d-85e767ff0e20.jpg)

Logging out, then back in doesn't help, nor does hitting refresh or opening in another tab in the same browser. Opening another browser (Chrome) works though. Surely the cookie should expire and boot back to login screen? I shouldn't have to close the entire browser (and all my tabs) to fix it. There's nothing in the logs, only the last library refresh.

I suspect the new player has issues, because my SubSonic server running alongside the Libresonic one on the same server doesn't have the issue and hibernates fine on a client browser.

**Comment by jooola** [comment]
@SuperNerd-James Any news on this issue ? did you tried airsonic 10.1.1 ?

**Comment by SuperNerd-James** [comment]
I haven't tried it yet. LibreSonic went quiet for ages so I assumed it had died, I just noticed the new fork as AirSonic today, phew, glad it isn't dead!

I'll download the latest, and retest this evening :)

**Comment by jooola** [comment]
@SuperNerd-James So ?
