### ISSUE TITLE
AIrsonic Specific API

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#467]
<a href="https://github.com/muff1nman"><img src="https://avatars2.githubusercontent.com/u/1531528?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [muff1nman](https://github.com/muff1nman)**
_Friday Jun 16, 2017 at 14:22 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/467_

----

I think this is a good topic for IRC, but would like to get some extra visibility and @biconou s opinion
```
08:12:27 muff1nman Anyone have any opinions on how the libresonic-specific rest api should be implemented? I'm curious to hear anyones thoughts
08:14:33 muff1nman Currently I'm thinking we improve the authentication and dont use the same auth as the old api
08:15:14 muff1nman Also we should use the built-in serialization capabilities of spring rather than handrolling it like is done in the subsonic rest endpoint
08:15:39 muff1nman Also I'm thinking we make it so that it can be used by itself
08:15:59 muff1nman To avoid folks from having to talk with both the subsonic rest api and the libresonic rest api
08:16:17 muff1nman so we would copy over all of the existing methods with some cleanups
08:18:36 muff1nman Im thinking we put it at a different endpoint than /rest
08:18:38 muff1nman perhaps /api
08:18:53 muff1nman wheres biconou?
```

**Comment by jooola** [comment]
@muff1nman I agree on all the points you mentioned in quotes.

(cc @airsonic/maintainers Trying to dig out old topics and maybe close them if we already have more recent issue duplicates as this one.))

**Comment by jooola** [comment]
Related to #474 Almost duplicate. Closing this.
