### ISSUE TITLE
What is the use of jetty in pom.xml ?

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#469]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Saturday Jun 17, 2017 at 17:24 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/469_

----

In libresonic-main/pom.xml 

```
        <!-- Embedded Jetty -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>apache-jsp</artifactId>
            <scope>provided</scope>
        </dependency>
```

I can't catch what is the use of this because the prefered embedded container is Tomcat. 

The following doc,explains how to use jetty but our configuration seems odd. 
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-use-jetty-instead-of-tomcat

**Comment by muff1nman** [comment]
@biconou Closing this but feel free to reopen if you want to discuss more.
