### ISSUE TITLE
DISCUSSION: First step in javascript code refactoring.

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#473]
<a href="https://github.com/biconou"><img src="https://avatars0.githubusercontent.com/u/5565107?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [biconou](https://github.com/biconou)**
_Saturday Jun 24, 2017 at 13:55 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/pull/473_

----

This PR is for review and discussion. 
It brings nothing new but it is a first step of a way to write a better js code. This is important to be able to turn progressively to a modern UI technology. 

This first step concentrates on the playQueue view that has a lot of js logic. 
I have extracted all js code in a separate playQueue.js file. 
I have created a javascript namespace called libresonic.playQueue with both private and plublic members. 

I use two transport objects to transfer datas from the jsp to javascript : 

- model : a javascript transposition of the Spring MVC model. 
- resources : a javascript object containing the needed i18n resources keeping the namespacing logic.

Review is required especially from @muff1nman.
Contributions from @fxthomas and @Eusmilis would be appreciated.

----

_**[biconou](https://github.com/biconou)** included the following code: https://github.com/Libresonic/libresonic/pull/473/commits_

**Comment by jooola** [comment]
@biconou Since we started a new UI with angular this is kinda obsolete no ?

Closing, reopen if needed !
