### ISSUE TITLE
Complete Rebranding

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#476]
Some items to finish the rebrand:
- [x] Rename all the things
- [x] Update history section
- [X] Choose and change out logo
- [x] Setup reddit/slack/etc
- [x] Finish setting up admin/teams
- [x] Announce to external channels

**Comment by muff1nman** [comment]
I think before we do a rebrand, it might make sense to try to get any large PR's we have merged in so that we can reduce the amount of duplicated effort. @biconou perhaps your jukebox PR should go in? I would also like to get in the REST api changes as well.

**Comment by biconou** [comment]
Agree.

I'll re-create the jukebox PR last week as I'll be in vacation next days.

**Comment by Tapchicoma** [comment]
Is there any link to discussion why another fork was created?

**Comment by muff1nman** [comment]
@Tapchicoma The original discussion was on IRC:

```
13:30:58 muff1nman hey Eugene, can i help with releases?
13:31:42 muff1nman if you dont mind id like to push out a new stable release
13:32:16 Eugene muff1nman - no PMs; every release question is an extended deadline; and my fileserver is still offline ;-)
13:32:48 muff1nman fine can you add me to admins so i can do it?
13:33:06 Eugene Nope. My project, my tags.
13:33:23 muff1nman that isnt sustainable
13:33:32 muff1nman and going to be a problem with a community project
13:33:46 muff1nman i joined this project under the impression it was a community effort
13:33:49 muff1nman not your project
13:34:16 Eugene Well then your impressions are bad. This has always been for my personal efforts. Anything more is welcome, but guarantees are exactly zero
13:35:24 muff1nman k well should be easy enough to leave you and your personal project in the dust
13:35:28 muff1nman time to fork off i guess
13:35:30 Eugene Bye!
13:35:33 muff1nman see ya
```

There was a reddit discussion about the IRC converstation, but it has since been [deleted](https://www.reddit.com/r/libresonic/comments/6jngiz/time_for_a_new_fork/). Due to all our communication channels being under control by Eugene, a couple of us discussed things out-of-band which aren't really linkable to.

The plan is to create a document with the above IRC snippet and why a fork was necessary under the history section of the main Readme.

**Comment by biconou** [comment]
I create a PR for the new jukebox #477 and tested it.

**Comment by muff1nman** [comment]
Cool, I'll try and pull it in asap. Also looks like we need to resetup the build checker.

**Comment by biconou** [comment]
Do you mean Travis ?

**Comment by muff1nman** [comment]
right

**Comment by codicusmaximus** [comment]
Ah, I see.  I don't know why the open source community is absolutely LITTERED with people like that.  A while back I tried to contribute to mplayer and mplayer2 and made a bugfix that fixed a broken VFW codec in them that previously crashed the player but those people were absolute nightmares to work with and so my fix is still not there to this day lol.

**Comment by plastikman** [comment]
I created https://github.com/airsonic/airsonic/pull/483 for the rebrand.

**Comment by csobsidian** [comment]
100% on board. Eugene is the reason I stopped contributing to Libresonic.

**Comment by gerroon** [comment]
Right on guys!

**Comment by jooola** [comment]
We made a pretty good start ! Let's close this !
