### ISSUE TITLE
Project Ownership

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#478]
Since it has happened twice to the *sonic community where a main project owner has decided to take the project in a strange direction, I propose we setup at least 3 project owners such that it is agreed that they are equal in ownership and any two of them can override the third.  The role of a project owner is not necessarily admin related, rather I view it as more of a group of folks who have final say in any potential disagreements. 

Please nominate anyone you would like to see in this role in the comments.

**Comment by muff1nman** [comment]
I would like to nominate @biconou, @joola and @fxthomas.

**Comment by biconou** [comment]
ok for me.

**Comment by jooola** [comment]
I would like to see @muff1nman as admin ?
Or are you admin anyway since you created the repo ?

**Comment by jooola** [comment]
OK for me btw

**Comment by jooola** [comment]
May I get the collaborator ( not admin ) rights on the main repo ? airsonic/airsonic ?

**Comment by jooola** [comment]
I guess this is good for now !

**Comment by Lightsockie** [comment]
Huh, weird.

As a nobody who lurks the repos and occasionally the irc, I'd cast a vote for @muff1nman and @biconou

**Comment by muff1nman** [comment]
Just to update anyone whos looking at this issue, @biconou and myself are currently owners and @joola currently has admin rights to help with issue management.  This issue being closed means to me that this is good enough for the near term, but doesn't mean this is set in stone. We can always make changes as people come and go.
