### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#481]
As part of the rebranding process #476  i would like to propose some new logo's and icon's.

===========================
#### Dark
![airsonic_blue_dark_1400x512](https://user-images.githubusercontent.com/19195485/27872857-79d77044-61aa-11e7-992f-9e73f94475e0.png)
![airsonic_dark_1400x512](https://user-images.githubusercontent.com/19195485/27872858-79d91638-61aa-11e7-8f66-930c4069b3be.png)

===========================
#### Light
![airsonic_blue_light_1400x512](https://user-images.githubusercontent.com/19195485/27872868-8220bbde-61aa-11e7-90f3-d178a50fbdd7.png)
![airsonic_light_1400x512](https://user-images.githubusercontent.com/19195485/27872869-822758ea-61aa-11e7-8e8a-894495aafcdd.png)

===========================
#### Icons
![airsonic_blue_512x512](https://user-images.githubusercontent.com/19195485/27872874-8d0a8098-61aa-11e7-8256-a98dbf546c08.png)
![airsonic_dark_512x512](https://user-images.githubusercontent.com/19195485/27872875-8d2904be-61aa-11e7-83a9-2297b9d33a86.png)
![airsonic_red_512x512](https://user-images.githubusercontent.com/19195485/27872876-8d29dd08-61aa-11e7-83eb-87a9433fa79e.png)

===========================
#### Buttons
![airsonic_blue_512x512](https://user-images.githubusercontent.com/19195485/27872946-ca25aaac-61aa-11e7-9364-73ca3439f5f5.png)
![airsonic_dark_512x512](https://user-images.githubusercontent.com/19195485/27872948-ca3f1f00-61aa-11e7-8357-c579defab52e.png)
![airsonic_red_512x512](https://user-images.githubusercontent.com/19195485/27872949-ca45bb3a-61aa-11e7-984b-afb9ba13d1a9.png)

**Comment by jooola** [comment]
Some variant:

![airsonic_blue_dark_1400x512](https://user-images.githubusercontent.com/19195485/27994244-0e1aae4e-64ba-11e7-85f0-5a7193fc3985.png)
![airsonic_blue_light_1400x512](https://user-images.githubusercontent.com/19195485/27994246-0e223010-64ba-11e7-9759-c9adfe322c97.png)
![airsonic_dark_1400x512](https://user-images.githubusercontent.com/19195485/27994245-0e20f70e-64ba-11e7-9a82-0049702d0db8.png)
![airsonic_light_1400x512](https://user-images.githubusercontent.com/19195485/27994247-0e2711fc-64ba-11e7-94c9-d888fdd8cf04.png)

**Comment by jooola** [comment]
And another ones : 

![airsonic_blue_dark_1400x512](https://user-images.githubusercontent.com/19195485/27994280-c18b5b68-64ba-11e7-9ed3-0b49d01643a8.png)
![airsonic_blue_light_1400x512](https://user-images.githubusercontent.com/19195485/27994277-c1156282-64ba-11e7-8a77-bed7bb48ee10.png)
![airsonic_dark_1400x512](https://user-images.githubusercontent.com/19195485/27994279-c145f4e2-64ba-11e7-8e8e-9ab3568cfee7.png)
![airsonic_light_1400x512](https://user-images.githubusercontent.com/19195485/27994278-c11d3ee4-64ba-11e7-81af-191a8640c2d5.png)

**Comment by jooola** [comment]
![icon_cloud](https://user-images.githubusercontent.com/19195485/27994370-c2686236-64bc-11e7-9b96-0504b2dcd96a.png)

An icon idea

**Comment by biconou** [comment]
We should not use a blue "air" as blue was chosen by libresonic. But the idea to have a logo looking like the libresonic one sounds good since airsonic is very close to libresonic.

**Comment by jooola** [comment]
@biconou To be honest with you, I think libresonic will be dead in few weeks. With no maintainers the repo won't get the html5 player done.

That sayd I don't think we need to take libresonic in count since we are trying to remplace it.
We sould use the logo we want and simple use it.

Blue makes me think at "air". The red comes from the website I builded.

@airsonic/maintainers What do you think about the logo I made ?

**Comment by Tapchicoma** [comment]
My variation of @jooola logo:

![airsonic-new](https://user-images.githubusercontent.com/1595262/28152419-abe1aa68-67a0-11e7-8ba7-f80a9dae56ed.png)

**Comment by jooola** [comment]
I propose we start a vote So that we can close this and finish the rebranding !

cc @airsonic/maintainers

**Comment by jooola** [comment]
Another variation : ( Again colors can, be changed this is just about the shapes !)
![airsonic_dark_1400x512](https://user-images.githubusercontent.com/19195485/28268307-0cfef70a-6afe-11e7-85cf-e516d9db7830.png)

**Comment by jooola** [comment]
And again some more variations : (Nextcloud style)
![airsonic_3](https://user-images.githubusercontent.com/19195485/28268778-d655cb82-6aff-11e7-874d-0e96395a7383.png)

**Comment by jooola** [comment]
![airsonic_2](https://user-images.githubusercontent.com/19195485/28268810-f2f4a178-6aff-11e7-9fb7-ee9e236227c0.png)

**Comment by jooola** [comment]
![airsonic_4](https://user-images.githubusercontent.com/19195485/28268815-fc125f48-6aff-11e7-9228-0b98746a6934.png)

**Comment by jooola** [comment]
![airsonic_5](https://user-images.githubusercontent.com/19195485/28268821-05adbbce-6b00-11e7-8d89-2f00e6f8e2a0.png)

**Comment by muff1nman** [comment]
What if you took the one in  https://github.com/airsonic/airsonic/issues/481#issuecomment-313920488, but instead of having the "sound waves" from the corner, put one or two waves on either side of the cloud, almost like its vibrating.

**Comment by jooola** [comment]
yeah is see what you're talking about I'll try this later tonight but i think i like you're idea !

**Comment by jooola** [comment]
![icon_red_cloud](https://user-images.githubusercontent.com/19195485/28327197-07d300ec-6be3-11e7-80d3-fda4ef1e3768.png)
![icon_red_cloud_2](https://user-images.githubusercontent.com/19195485/28327198-07e1df5e-6be3-11e7-8010-7e2e1e3b9fa8.png)

**Comment by jooola** [comment]
![airsonic_7](https://user-images.githubusercontent.com/19195485/28327248-23a5642c-6be3-11e7-88b4-8227f13c4206.png)


I'm out of inspiration ... Making crappy icons ... Does some one else have some ideas or what i build is good enough ?

**Comment by hschroedl** [comment]
My favourites so far: 

[Clouds](https://github.com/airsonic/airsonic/issues/481#issuecomment-316111696)
[Variation](https://github.com/airsonic/airsonic/issues/481#issuecomment-315744432)

But its not like I know anything about design so... :man_shrugging:

**Comment by joshuaboniface** [comment]
I'll second @hschroedl in my favourites, though I'm a big fan of the blue instead of red (Libresonic be damned).

**Comment by CharlesSchaack** [comment]
I also have come to the same conclusion as @hschroedl and @joshuaboniface  although I prefer the red! (just to be difficult)

**Comment by jooola** [comment]
If you add the red icons to the current default light theme of airsonic something with the colors is wrong...
Will get some screenshots later tonight !

**Comment by jooola** [comment]
After creating a new PR with the logo we decided, The took some screen shots and it was ugly i simply really didn't like my own PR ... see #498 
So 'im foing to post some more ideas : 

![dessin](https://user-images.githubusercontent.com/19195485/28500042-6f6908f4-6fc2-11e7-8472-9eac3ead4887.png)

**Comment by jooola** [comment]
Basically we are going to keep the text ( airsonic in blue and dark/grey/white ) the only thing missing is the icon/logo.

**Comment by jooola** [comment]
Another logo/icon : ( I like this one ! )
![cloudsound](https://user-images.githubusercontent.com/19195485/28501059-fa726cae-6fd3-11e7-9c3f-8ad79136e69e.png)

**Comment by jooola** [comment]
Another one

**Comment by jooola** [comment]
![cloudsound_3 svg](https://user-images.githubusercontent.com/19195485/28501107-40573988-6fd5-11e7-82e2-4639daef5e5b.png)

**Comment by jooola** [comment]
![airsonic_dark_1000x400 svg](https://user-images.githubusercontent.com/19195485/28501157-61e20e74-6fd6-11e7-9ab8-cdefd29a2d1a.png)

**Comment by jooola** [comment]
![airsonic_dark_1000x400_2 svg](https://user-images.githubusercontent.com/19195485/28501201-377e7996-6fd7-11e7-8a82-959987049951.png)
![airsonic_light_1000x400_2 svg](https://user-images.githubusercontent.com/19195485/28501205-5b15712a-6fd7-11e7-9747-290010caf00c.png)

**Comment by Tapchicoma** [comment]
My opinion that any proposed icon are good enough. For now better to select one and use it, as releasing first rebranded version is pretty important.

After we can open a new ticket and post new icon ideas there.

**Comment by jooola** [comment]
Actually we are releasing next release only next week or so !
See [here](https://gist.github.com/muff1nman/570a3021f5d98453333090bb933a3865)
So not to work twice on same thing I would like to do this only one time !

( All services attached to airsonic will have this icon too )

**Comment by muff1nman** [comment]
![airsonic_blackback](https://user-images.githubusercontent.com/1531528/28505241-2863046a-6fdf-11e7-9e0b-7de935b1a08f.png)
![airsonic_whiteback](https://user-images.githubusercontent.com/1531528/28505242-28631ef0-6fdf-11e7-85e2-4da0f9025f31.png)

**Comment by jooola** [comment]
![cloudsound_5 svg](https://user-images.githubusercontent.com/19195485/28518744-489a48da-7069-11e7-9288-5a677cfd3e15.png)

**Comment by jooola** [comment]
![cloudsound_7 svg](https://user-images.githubusercontent.com/19195485/28577236-898448f8-7156-11e7-817b-fe131eb9395b.png)

**Comment by jooola** [comment]
What if i make a set of text/icon with : 
[this text](https://github.com/airsonic/airsonic/issues/481#issuecomment-317265970)
[this icon](https://github.com/airsonic/airsonic/issues/481#issuecomment-317756023)

Which mixed together gives a nice logo

**Comment by jooola** [comment]
#### Introduction

First of all sorry for pinging you all on this thread but some help was needed here and the idea to pick the logo contributors from libresonic wasn't that bad !

cc @williamkray @jolny @csobsidian @tiagoad @muff1nman @biconou @hschroedl @joshuaboniface @fxthomas

If some of you didn't get why libresonic has been forked to airsonic please see the following : 
[Rebrand ticket](https://github.com/airsonic/airsonic/issues/476)
[Airsonic README (history section)](https://github.com/airsonic/airsonic#history)

#### Vote

I would like to create a vote to decide which logo (text/icon) will be used for airsonic.
( The picture with the most thumbs up will be chosen )
So the idea is to get a vote done by Thursday/Friday since we are releasing the first airsonic this weekend !
Thanks for participating !

Obviously any participation is welcomed !

**Comment by biconou** [comment]
I'd like tout vote but dis not succeded tout thumb antivirus comment fromage my Android phone. My favourite logo is the word airsonic with waves bars inside.

**Comment by biconou** [comment]
Argh fuck Android that corrects from in fromage !!!

**Comment by jooola** [comment]
@biconou What about the icon ? Same style icon ? Or something else ? ( the vote here is mainly about the icon/logo not really the text )

**Comment by DArtagan** [comment]
jooola, those last five are outstanding.  I love how the style has developed.

**Comment by jolny** [comment]
While most of these logos look fine, I wouldn't go for one with small bars inside as it might look a bit cluttered when used as smaller image sizes. I vote for something with cloud/s and/or waves.

**Comment by jooola** [comment]
Actually I think that this [one](https://github.com/airsonic/airsonic/issues/481#issuecomment-317756023) is better than  this [one](https://github.com/airsonic/airsonic/issues/481#issuecomment-317378825) for the scaling problem ! We can make the same but with bigger bars for small icons (and keep  ( if we really don't recognize the original ! ).

About the old [cloud/waves](https://github.com/airsonic/airsonic/issues/481#issuecomment-316111696) I made, really hate it right now ! See the PR #498 with the screenshots I made. ( I may have been to fast when building those but it is really ugly ... (imo))

If some icons can't be recognize at small size we can use then in monochrome (B&W)

**Comment by jolny** [comment]
Possibly. Test it out, but for the second one I would increase the spacing
between bars so it's closer to 50/50. Maybe 75/25.

How about a cloud with a sinus wave running through it?
Den 26 jul 2017 1:33 em skrev "Jonas L." <notifications@github.com>:

**Comment by muff1nman** [comment]
@jolny, the sine wave idea would be neat to see

**Comment by jolny** [comment]
Heh, if someone doesn't beat me to it, I'll throw my paint skills at it
later :-)
Den 26 jul 2017 3:27 em skrev "Andrew DeMaria" <notifications@github.com>:

**Comment by jooola** [comment]
![cloudsound_8 svg](https://user-images.githubusercontent.com/19195485/28625795-9b74013a-721d-11e7-9db6-89ce09dabad2.png)

**Comment by jooola** [comment]
cc @bonome you're pleased to vote too !

**Comment by CharlesSchaack** [comment]
@jooola if you have time at some point would you mind miniturizing https://github.com/airsonic/airsonic/issues/481#issuecomment-317378825 so we can see how it looks as a small icon?

**Comment by jooola** [comment]
@CharlesSchaack Done ( Maybe we could use the community channels for such request ? )

**Comment by biconou** [comment]
Ok I finally voted with the thumb for the logo very close to Soundcloud's.

**Comment by jooola** [comment]
So vote is now over, I'll create a PR with the following set of pictures : 
![cloud](https://user-images.githubusercontent.com/19195485/28518744-489a48da-7069-11e7-9288-5a677cfd3e15.png)
and
![text](https://user-images.githubusercontent.com/19195485/28501201-377e7996-6fd7-11e7-8a82-959987049951.png)

**Comment by muff1nman** [comment]
Seems a bit busy to mix those two together. Might be best to just have some simple black text underneath the cloud.

**Comment by tiagoad** [comment]
Agreed, the bottom one doesn't fit with the first one at all.
Both also have way too much detail for a logo, especially the second, the bars will look like blue and black blobs.

**Comment by jolny** [comment]
Here are some quick wave/cloud mockups I did in Illustrator. Note I suck at Illustrator :smiley: 
![clouds](https://user-images.githubusercontent.com/5852901/28749122-c967f81a-74bd-11e7-99f5-616890c0ddb3.png)

Maybe it inspires someone.

**Comment by jooola** [comment]
Fine i'll use the softer ones !
Didn't had time to create the PR yet ! 
Maybe later tonight or tomorrow !
