### ISSUE TITLE
First release of Airsonic

### ISSUE THREAD

**Issue by Tapchicoma** [airsonic/airsonic#488]
Hi, is there any release of Airsonic available already?

If not, can you make 6.2.1 release? 

I think it is better to also make a bugfix releases adding bugfix version in the end.

**Comment by muff1nman** [comment]
Good question. So far we haven't released one yet. I think we could do a 6.2.1 release and then rebranding effort can go into 6.3 along with the other large changes. Is https://github.com/airsonic/airsonic/commit/56f5625e79ef876905f9ff1850d19fd287f2b367 tested by anyone?

Can you expand on what you mean by adding a bugfix version? Or do you just mean we should follow semver with a patch number as should be acomplished with 6.2.1. Then 6.3 should be 6.3.0.

**Comment by Tapchicoma** [comment]
Yes, Libresonic master branch has several bugfixes that doesn't add any new functionality, but fixes existing one. I was expected that version 6.2.1 will be released, but it never happened.

My opinion is that users doesn't test beta releases, but usually wait for common one to update their installations. And it is a good practice to release bugfixes version for current releases, while still changing/adding new functionality in upcoming release branch.

**Comment by jooola** [comment]
Agree with @Tapchicoma ! ( We should set the stable /develop branch asap )
On Libresonic the stable branch had some commits since the latest release and those commits should be released as bugfix as 6.2.1.

**Comment by muff1nman** [comment]
6.2.1 was created. Its not exactly the first airsonic release as the rebrand efforts will be done with 6.3.
