### ISSUE TITLE
History Section of Readme

### ISSUE THREAD

**Issue by hschroedl** [airsonic/airsonic#492]
The history section of the Readme is inaccurate. It currently reads:

> Airsonic is maintained by Eugene E. Kashpureff Jr. It originated as an unofficial("Kang") of Subsonic which did not contain the Licensing code checks present in the official builds. With the announcement of Subsonic's closed-source future, a decision was made to make a full fork and rebrand to Airsonic.

Unless I misunderstood something this fork is not maintained by Eugene. My guess is this section was overlooked during the rebrand.

**Comment by jooola** [comment]
#491 Was simply missing !
I just merged it and everything should be fine now !

**Comment by hschroedl** [comment]
Yeah, didn't see that pull request. Sorry for that.
