### ISSUE TITLE
Lastfm scrobbling twice.

### ISSUE THREAD

**Issue by CharlesSchaack** [airsonic/airsonic#500]
I have last.fm scrobbling setup in airsonic and it seems to be scrobbling my songs twice, ie:

https://pastebin.com/raw/kP8j4izc

I'm running the latest version of libresonic before the airsonic fork. I can update to the release of airsonic if that makes a difference. I'm running standalone. I have my last.fm information filled in under 'Personal' and also have the checkbox 'Register what I'm playing at last.fm' checked.

**Edit:** This might belong as separate issue, but I'm also curious if there would be a way to implement a threshold of % song duration before scrobbling to lastfm. As in I would like to wait until I've listened to 20% of a song before scrobbling to last.fm. This would allow the user to skip over songs without scrobbling them, because in reality they didn't really 'listen' to the song.

**Comment by muff1nman** [comment]
The threshold before scrobbling sounds like a good addition, I would make that a separate issue to give it visibility.

**Comment by CharlesSchaack** [comment]
Seems like my issue might somewhat be related to https://github.com/Libresonic/libresonic/issues/256 all the files I am playing are flac and I'm using the web player.

I will go ahead and make a separate issue for the last.fm threshold.

**Comment by CharlesSchaack** [comment]
I am closing this. This issue seems to have been fixed by the new html5 player. I still receive broken pipe errors but the scrobble information is only relayed to last.fm once like intended. If it comes up again I might reopen this issue but for now everything seems good. Really enjoying the new player.
