### ISSUE TITLE
Add Smtp configuration testing button

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#509]
To test the configuration of the smtp server we could add a send mail button to test the configuration ( send to the admin mail (if set))

**Comment by hyptechdev2015** [comment]
@jooola  this is a good idea.
Also I love open community project; Airsonic for air is free!!! 👍 

> Airsonic's goal is to provide a full-featured, stable, self-hosted media server based on the Subsonic codebase that is free, open source, and community driven.

**Comment by jvoisin** [comment]
This is superseded by #1082
