### ISSUE TITLE
Running the docker image with external database. 

### ISSUE THREAD

**Issue by barrygwn** [airsonic/airsonic#510]
I have tried today to make the docker image work with an external mysql database connection, but I didn't exactly made it work. Building with the 10.0 release airsonic-jdbc-extra.war works fine, however following the docs I didn't find out where to put the mysql connector, what the should be, and basically what to put in the airsonic.properties file. With these settings added:

```
DatabaseMysqlMaxlength=512
DatabaseConfigType=EMBED
DatabaseConfigEmbedDriver=com.mysql.jdbc.Driver
DatabaseConfigEmbedPassword=****
DatabaseConfigEmbedUrl=jdbc:mysql://address:db/table
DatabaseConfigEmbedUsername=username
DatabaseUsertableQuote=
```

The docker image fails to start and complains the jbdc connector can't be found. Since Java is not my cup of tea and adding a classpath envar to the connector didn't resolve my issue I'm kind of lost. I think updating the docs with documention on the docker image would really make a difference. Someone point me in the right direction? If I get it to work I'm willing to improve the docs. Anyway, the rebranding looks slick guys! Keep up the good work..

**Comment by jooola** [comment]
I can't answer you really but a ticket is already open in the documentation repo for the docker set up !

See airsonic/documentation#19

**Comment by barrygwn** [comment]
Sure thing, I'm not in a hurry. I'll wait for the doc update on docker.

**Comment by hschroedl** [comment]
I've been playing around quite a bit with Docker lately, i'll give this a try over the weekend. Will probably do [#19](https://github.com/airsonic/documentation/issues/19) too while I'm at it.

**Comment by hschroedl** [comment]
@barrygwn There's good news and weird news. The weird news is that I could initially reproduce your problem (that is, the missing drivers) but for some reason when I tried again this morning the problem no longer persisted. I have no clue why :confused:

The good news is that I managed to make the Airsonic docker container work with the [MySQL docker image](https://hub.docker.com/_/mysql/). I think that this qualifies as "external database"? 

Here's what I did. First of all, run the MySQL container like so

    docker run --name mysql -e MYSQL_ROOT_PASSWORD=mypassword -p 3307:3306 -e MYSQL_DATABASE=db -d mysql

Change ports and stuff to your liking. Next, to run the Airsonic container, first create a hosted volume for easy access to the config file and such.
 
    mkdir /home/user/data
    docker volume create --name data -o type=none -o device=/home/user/data -o o=bind

In there, add your `airsonic.properties` file. I pretty much copied your input and adjusted for the MySQL container. 

    DatabaseMysqlMaxlength=512
    DatabaseConfigType=EMBED
    DatabaseConfigEmbedDriver=com.mysql.jdbc.Driver
    DatabaseConfigEmbedPassword=mypassword
    DatabaseConfigEmbedUrl=jdbc:mysql://172.17.0.1:3307/db 
    DatabaseConfigEmbedUsername=root
    DatabaseUsertableQuote=

Running Airsonic with the following command then yields the expected result. The container runs and accesses the MySQL-DB.

    docker run -v data:/airsonic/data/ -p 4040:4040 airsonic/airsonic:10.0.0-RELEASE

Please confirm that this procedure works. I have now tried it on two different machines, and not running into the driver problem confuses me a ton. 

Btw, you may be able to skip the volume stuff by passing the properties directly using `JAVA_OPTS` like so: 

    docker run -p 4040:4040 -e JAVA_OPTS="-DDatabaseMysqlMaxlength=512 -DDatabaseConfigType=embed ..." airsonic/airsonic:10.0.0-RELEASE

**Comment by muff1nman** [comment]
Interesting, not sure if it helps, but the one thing im not sure was a good idea was including both the mariadb and MySQL jdbc drivers on the class path. From my testing, it didn't seem to cause issues, but that's the first thing that comes to mind that might cause issues

**Comment by hschroedl** [comment]
I wasn't even sure which drivers were on the classpath. Maybe an update to the [Database config documentation](https://airsonic.github.io/docs/database/) is also in order?
 
Btw, I also tested with PostgreSQL, and that worked without a hitch too. So, good work I guess? :smile:

**Comment by muff1nman** [comment]
Good to hear about postgres working. Yeah, we could update the docs. Although I was hoping we could let it fly under the radar for a bit. If the airsonic-jdbc-extra.war works well, we should just make it the default for the next release, so that the docs don't have to worry about which war people are using.

**Comment by barrygwn** [comment]
Nice work, I'll give it a try this evening or tomorrow. Let's see if the problem is also vanished on my setup :)

**Comment by muff1nman** [comment]
Any update here? This would be a good candidate to get resolved in a 10.0.1 release if needed.

**Comment by barrygwn** [comment]
I'm sorry about the late update, but I can confirm the method described by @hschroedl works. The database has to created in advance with passing MYSQL_DATABASE=db parameter to your mysql docker image (if that is your method of running mysql anyway), Airsonic does not try to create it if it doesn't exist, even when having sufficient rights. I also checked running with a MariaDB db and can confirm this as working as well.

**Comment by patsaindon** [comment]
Is there a way to pass airsonic.properties in the docker-compose config?

**Comment by hschroedl** [comment]
@patsaindon Airsonic does not offer a docker-compose file, so not sure what you mean with docker-compose config.

Anyways. Please see the official documentation right at the bottom [here](https://airsonic.github.io/docs/install/docker/) on how to add the properties file to a docker container. 

If you use docker compose this basically amounts to specifying a directory containing your airsonic.properties in the volumes section of your docker-compose.yaml. Found a [example online](https://codegists.com/code/docker-self-hosted/) (again, right at the bottom).

**Comment by patsaindon** [comment]
I'm using a mariadb container. Is this what I should add to my
airsonic.properties file?

DatabaseMysqlMaxlength=512
DatabaseConfigType=EMBED
DatabaseConfigEmbedDriver=com.mysql.jdbc.Driver
DatabaseConfigEmbedPassword=airsonic
DatabaseConfigEmbedUrl=jdbc:mysql://192.168.0.10:3306/db
DatabaseConfigEmbedUsername=airsonic
DatabaseUsertableQuote=

2017-09-20 10:40 GMT-04:00 Hans-Jörg Schrödl <notifications@github.com>:

**Comment by hschroedl** [comment]
An issue is not really the place for personal support matters. 

Please do use the official communication channels, such as Reddit or IRC for help. See the readme on where the find help.
