### ISSUE TITLE
Missing latest docker tag

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#513]

**Comment by hschroedl** [comment]
If you want I can take care of this. If not (not sure about permissions regarding the docker repo) you can ping me to update the docs, as they still use the 10.0.0-LATEST tag.

**Comment by muff1nman** [comment]
@hschroedl, Okay this should be fixed now. For the future, we'll need to come up with a good way to share the docker credentials. Perhaps something like a [password-store](https://www.passwordstore.org/) repo.
