### ISSUE TITLE
Discussion: What do you think of using Kotlin on new backend code?

### ISSUE THREAD

**Issue by bfkelsey** [airsonic/airsonic#519]
For those that don't know Kotlin is a newer JVM language originally developed by Jetbrains. It has excellent interop with current java code and provides many features to develop cleaner code. Recently it has also become an officially supported language on Android.

Here are some pages to read about it: 
https://kotlinlang.org/docs/reference/server-overview.html
https://www.wired.com/story/kotlin-the-upstart-coding-language-conquering-silicon-valley
http://us12.campaign-archive1.com/home/?u=f39692e245b94f7fb693b6d82&id=93b2272cb6
http://talkingkotlin.com/

**Comment by biconou** [comment]
I am interested in Kotlin but still did not find any spare time to try it. 
Kotlin is also known as beeing able to produce front end applications. Right ? 
At the moment, we are looking for some solution for a new UI.

**Comment by bfkelsey** [comment]
@biconou I don't think Kotlin would be the best tool for a javascript app right now. For that I think typescript would be a better choice. Which after talking to @muff1nman I have started on but waiting on a JSON api to really wire it up. 

Anyways you should try Kotlin, it is pretty easy to learn after using java and has excellent support in intellij.

**Comment by biconou** [comment]
@bfkelsey  Well I'm both interested in TypeScript for frontend and a bit of Kotlin for backend.
As you mentionned, java/kotlin integration is fluent so, I think that, using Kotlin progressively could be possible. 
I am testing a bit of webpack at the moment. Did ya consider using it to package typescript compiled code ?

**Comment by biconou** [comment]
@bfkelsey  What do you exactly mean by 
`waiting on a JSON api to really wire it up`

**Comment by bfkelsey** [comment]
It is using angular cli so it provides a webpack build. While I could use xml in angular it is kind of a pain to set up and since @muff1nman is working on adding a json airsonic api I could wait for that. So currently I have a basic layout and I am just using sample data.

**Comment by bfkelsey** [comment]
I would like to add a few more features to what I have, then I can make the code available somewhere.
