### ISSUE TITLE
Files and Folders with non-latin characters not detected on scan

### ISSUE THREAD

**Issue by veyen** [airsonic/airsonic#520]
Hello,
I am experiencing an issue very similar to #171 . 

Installed according to stand-alone instructions, running the .war
Airsonic 10.0.0-Release, java 1.8.0_141, on Ubuntu 14.04

- Paths with non-latin characters are ignored during scanning. No files in these paths are detected.
- Non-latin characters are not displayed.
- Files with non-latin characters appear to be detected but treated like folders (?). I can click to an empty subpage. Buttons next to the links do nothing. Shown in screenshot below.

Screenshot:
![airs1](https://user-images.githubusercontent.com/22732638/29288892-dd9575c2-813a-11e7-9c53-c790c75070be.PNG)

Any workaround suggestions are welcome. Thanks.

Edit: Same thing happens for accented characters, such as 'é' and 'ê', each character is replaced by two '�'s

**Comment by muff1nman** [comment]
Can you read through this issue here: https://github.com/airsonic/airsonic/issues/287 and see if any suggestions there help?

**Comment by veyen** [comment]
Thank you! That did the trick

I just had to add to the upstart script: env LC_ALL="en_US.UTF-8"

**Comment by seed1234** [comment]
hey @veyen Could you show me which file you edited in the airsonic Jail of the FreeNas. is it in apache-tomcat-8.0/bin/startup.sh?

or was it in another file cause i did that file and no changes happened i am still getting those triangles

**Comment by veyen** [comment]
I'm not familiar with FreeNas, sorry. What I did was exactly as stated previously. I'm on Ubuntu, where init scripts are located in /etc/init.

Perhaps someone else can help or you can ask on FreeNAS forums.

**Comment by anarcat** [comment]
i'm having the same issue here - and adding `LC_ALL=en_US.UTF-8` to the envrionment fixes the problem *but only if I completely reset the database*. This is, presumably, because airsonic doesn't rescan files it already knows about...

is there a way to force-rescan those corrupted file entries?
