### ISSUE TITLE
Homebrew formula for possible tap / project inclusion

### ISSUE THREAD

**Issue by mshick** [airsonic/airsonic#523]
I put together a simple Homebrew formula, which I use to run Airsonic as a service on my Mac mini media server. Here it is: https://github.com/mshick/homebrew-personal/blob/master/Formula/airsonic.rb

I wonder if this project would be interested in creating a brew tap repository for this? I think it could be useful for anybody looking to get up and running with Airsonic on a Mac. 

I'd be happy to maintain it, and perhaps in the future we could try to get it included in the mainline Homebrew repo.

**Comment by mshick** [comment]
Bump on this — I think this could really help adoption for users on Mac platforms. Happy to maintain the repo, add some docs, and so forth. 

Would also like to collaborate on the formula, in case others have ideas for how to improve it, perhaps with a PG dependency.

**Comment by muff1nman** [comment]
Is there anything specific you need to move forward on it? I'm not a Mac user so can't help with it

**Comment by muff1nman** [comment]
Also I think you might want to change the line `logging.level.*` to `logging.level.root`. see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html

**Comment by mshick** [comment]
That's smart, I'll make the logging update.

The only thing to move forward would be an airsonic org repo and access to it. To work with Homebrew taps it would need to be named, e.g., `homebrew-airsonic`. 

I would put together docs there (which you could include in the website if you want) that have the simple `brew tap airsonic/airsonic` command and any other info useful for this installation method.

**Comment by muff1nman** [comment]
Repo created. Although can we keep the documentation in the documentation repo? You can submodule it in if necessary.

**Comment by bfkelsey** [comment]
@mshick Is there any reason it couldn't just be pr'd back to homebrew?

**Comment by jooola** [comment]
I'd prefer not to split the documentation in submodules !

Or we grant you permissions to write in the docs repo, or you simply create pr's and I'll try to be reactive !

**Comment by muff1nman** [comment]
@jooola I did not mean to split the documentation repo. I meant to pull in the documentation repo as a submodule into the homebrew-airsonic repo.

**Comment by jooola** [comment]
Ah alright !
Still if this can be avoid !?

**Comment by mshick** [comment]
@bfkelsey Can definitely PR against Homebrew directly, but I think the process is a bit political. Was thinking this would be a good intermediary step to vet and improve the formula before taking it to Homebrew. 

@muff1nman @jooola Happy to just submit PRs against the main docs. Whatever is easiest.

**Comment by muff1nman** [comment]
The advantage of putting the homebrew docs in the documentation repo is that it can easily be pulled into the website. With that said, I would say focus on getting the formula to a good state first then we can figure out docs at that point.
