### ISSUE TITLE
Settings, player selector disappear

### ISSUE THREAD

**Issue by Aanok** [airsonic/airsonic#531]
Overnight, I've had the dropdown player selection menu and the Settings tab disappear from the web interface. If I manually (re)set ``GettingStartedEnabled=true`` in airsonic.properties and reach Settings from the welcome page it works, but I get a 403 on the Personal, Players, and Shared media pages.

Airsonic is running on Tomcat on a Debian 9 system. The issue pops up on Chromium, Firefox and Qutebrowser, so it's likely browser-agnostic. It happens when accessing the applet directly (:8080/airsonic) and behind an HTTPS Nginx reverse proxy, both locally and remotely.

The browser console reports an error from vapi-client.js. Logs attached from a Chromium session.
Catalina.out and airsonic.log also attached, pruned up to a Tomcat reboot.

I've already had this problem with Libresonic in the past, still seemingly at random, and I could only solve by wiping the applet and reinstalling from scratch.

![navigation](https://user-images.githubusercontent.com/18417628/29240574-6443cc4c-7f68-11e7-82cd-5a7db3d3ef3b.png)
^ missing Settings tab

[airsonic.log.txt](https://github.com/airsonic/airsonic/files/1244608/airsonic.log.txt)
[catalina.out.txt](https://github.com/airsonic/airsonic/files/1244607/catalina.out.txt)
[console on 403.log.txt](https://github.com/airsonic/airsonic/files/1244602/console.on.403.log.txt)
[console on boot.log.txt](https://github.com/airsonic/airsonic/files/1244601/console.on.boot.log.txt)

**Comment by llucps** [comment]
Yes, It just happened to me this morning, suddenly the Settings panel is gone. I can access to Settings panel through Podcast -> Podcast Settings but I also get an 403 error on the Personal. Players and Shared media pages..

My system is Debian 9 with Tomcat and openjdk-8-jre-headless:amd64 installed.

Is it bug? Is there something we can do?

Thanks

**Comment by jeroenmarinus** [comment]
Also happening here.

10.1.1-RELEASE
jetty/9.3.14.v20161028, java 1.8.0_151, Linux (330.9 MB / 747.5 MB)
Running in a docker, on unRAID.

**Comment by jooola** [comment]
Did you tested with a fresh DB ?

**Comment by ondresel** [comment]
Happened here aswell a week ago, no exception in the logs.
10.5.0-RELEASE
Docker Image airsonic/airsonic

When trying to visit /advancedSettings.view:

Status | 403
-- | --
Error | Forbidden
Message | Access is denied
Path | /advancedSettings.view
Time | Wed Feb 12 07:52:11 CET 2020
Exception |  
Java version | IcedTea 1.8.0_212
Operating system | Linux 4.4.0-148-generic
Server | Apache Tomcat/8.5.43
Memory | Used 709 of 840 MB

The same happens when visiting /personalSettings.view

**Comment by vestingz** [comment]
I am experiencing the exact same issue (403 - Forbidden) with following paths:
```
/airsonic/personalSettings.view?
/airsonic/playerSettings.view?
/airsonic/shareSettings.view?
```
Also, the Settings tab disappeared from the menu and I can access the settings page only through manually requesting `https://domain.abc/airsonic/musicFolderSettings`. Interestingly enough, the Settings tab still exists on other user accounts than mine (admin).

I am running airsonic behind an Apache reverse proxy with following settings:
```
<VirtualHost *:443>
    ProxyPreserveHost On
    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/domain.abc/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/domain.abc/privkey.pem
    SSLProxyEngine on
    ServerName domain.abc
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/airsonic-access.log combined
    ErrorLog ${APACHE_LOG_DIR}/airsonic-error.log
    ProxyPass /airsonic/ http://127.0.0.1:8080/airsonic/
    ProxyPassReverse /airsonic/ http://127.0.0.1:8080/airsonic/
    RequestHeader set X-Forwarded-Proto "https"
</VirtualHost>
```

My airsonic command is as follows: `java -Dairsonic.home=/var/airsonic -Dserver.context-path=/airsonic -Xmx512m -Dserver.use-forward-headers=true -jar airsonic.war`.

Any ideas?

**Comment by awsms** [comment]
> I am experiencing the exact same issue (403 - Forbidden) with following paths:
> 
> ```
> /airsonic/personalSettings.view?
> /airsonic/playerSettings.view?
> /airsonic/shareSettings.view?
> ```

Funny, that's exactly the three ones I can access. Can't access the others anymore, having a 403 error.

**Comment by vestingz** [comment]
> edit: for anynone else having the same issue, check if your /airsonic/db/airsonic.script file contains the following lines:
> 
> ```
> INSERT INTO USER_ROLE VALUES('admin',1)
> INSERT INTO USER_ROLE VALUES('admin',2)
> INSERT INTO USER_ROLE VALUES('admin',3)
> INSERT INTO USER_ROLE VALUES('admin',4)
> INSERT INTO USER_ROLE VALUES('admin',5)
> INSERT INTO USER_ROLE VALUES('admin',6)
> INSERT INTO USER_ROLE VALUES('admin',7)
> INSERT INTO USER_ROLE VALUES('admin',8)
> INSERT INTO USER_ROLE VALUES('admin',9)
> INSERT INTO USER_ROLE VALUES('admin',10)
> INSERT INTO USER_ROLE VALUES('admin',11)
> ```

Thanks for the hint. I do have this entries in that file, with the exception of values 9 and 10. What does this mean?
