### ISSUE TITLE
search breaks when the session times out

### ISSUE THREAD

**Issue by postags** [airsonic/airsonic#536]
![2017-08-25 21_26_54-chillin - x i b sweizy gang ent - airsonic - waterfox](https://user-images.githubusercontent.com/22846348/29745492-79c190be-8a70-11e7-8dfb-137f9f63ef62.png)

Airsonic encountered an internal error. You can report this error in the Airsonic Forum. Please include the information below. 

```
Status     403 
Error     Forbidden Message Invalid CSRF Token '5c0b766f-42b3-4a58-b08d-2d8a389c706a' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'. 
Path     /airsonic/search.view 
Time     Sat Aug 26 04:23:56 PDT 2017 
Exception
Java version Oracle Corporation 1.8.0_131 
Operating system Linux 4.10.0-32-generic Server Apache Tomcat/8.0.38 (Ubuntu) 
Memory Used 371 of 601 MB
```

Any search query started throwing this error, although everything else was working fine. The session time-out assessment is per plastikman187 on Reddit.

**Comment by muff1nman** [comment]
I think this is related to #517

**Comment by evertvp** [comment]
This is indeed the same bug as #517 as far as I can tell, but I don't think the behaviour should be to log out. The only problem is that the csrf token has expired, not the user session.

A refresh of the top frame fixes this.

**Comment by muff1nman** [comment]
Okay, so while a refresh of the top frame would indeed get around this, perhaps the best thing to do here is to change /search from a GET to a POST. It doesn't change any state anyways so shouldn't require CSRF protection.

**Comment by jooola** [comment]
This looks like
