### ISSUE TITLE
Pausing playback in Jukebox mode not working

### ISSUE THREAD

**Issue by hschroedl** [airsonic/airsonic#541]
Pausing playback when in Jukebox mode is not possible in v. 10.0.1 (and 10.0.0 for that matter). When clicking the pause button nothing happens. The airsonic log does not contain any errors, but viewing the web console reveals this: 

    Uncaught` TypeError: Cannot read property 'pause' of undefined
    at onStop (playQueue.view:534)
    at HTMLImageElement.onclick (playQueue.view:1017)

The error is thrown in this line: 

     $('#audioPlayer').get(0).pause();

This was tested on my Rasberry PI [Debian 9] (where I noticed the error first) and reproduced using the standalone installation on another machine [Ubuntu 16.04] using [this tutorial](https://airsonic.github.io/docs/install/war-standalone/). Here is my player configuration: 

![image](https://user-images.githubusercontent.com/5294464/29768547-f10227c0-8be6-11e7-8962-fa36a97d727f.png)

Changing the configuration did not have any effect for me in regards to this issue. So, I guess this is just some weird front-end issue?

**Comment by hschroedl** [comment]
I forgot to mentions: When using web playback all works fine :)

**Comment by biconou** [comment]
@hschroedl I noticed this but a couple of days and I'll fix it.

**Comment by biconou** [comment]
Fixed by #544

**Comment by hschroedl** [comment]
Good thing this is already closed. Just tested this and it works. Thanks for the quick fix!
