### ISSUE TITLE
[10.0.1] Adding Music Files Type 'ac3' won't work

### ISSUE THREAD

**Issue by nRaecheR** [airsonic/airsonic#542]
I'm running AS 10.0.1 as Docker container.
In my music library there are some AC3-coded files with .ac3 file suffix ripped from a DVD. Here the output of 'file':

```
<filename>.ac3: ATSC A/52 aka AC-3 aka Dolby Digital stream, 48 kHz,, complete main (CM) 2 front/0 rear, Dolby Surround not indicated, 192 kbit/s
```

I've added 'ac3' to 'Music files' in 'General' tab and to 'Transcoding' "mp3 audio". ffmpeg is able transcode the files without problems.
When I rescan my library the files won't be recognized and the folders are listed as empty.

**Comment by jooola** [comment]
You need to add the format is the scanned types in the media folders settings tab.
Tell me if this fixes your problem !

**Comment by nRaecheR** [comment]
As stated in the first post I've added ac3 to 'Music files' in General Tab and to 'Transcoding' "mp3 audio", the AC3 files won't be recognized.

**Comment by jooola** [comment]
Could I have a ac3 sample file ?

**Comment by jooola** [comment]
Duplicate of #603 
Please try to workaround from there.
Closing this since its a duplicate
