### ISSUE TITLE
[10.0.1] Webinterface is using local IP on public server

### ISSUE THREAD

**Issue by nRaecheR** [airsonic/airsonic#546]
I'm running AS 10.0.1 in a Docker container, I've slightly modified the Dockerfile from the Git repo. The server is accessible behind an Apache2 server as public server from the Internet. SSL encryption is done by the Apache2 server too. Apache is configured to use 'proxypass' to pass requests to the local server in the Docker container. 
This works very good for any app like DSub etc. on devices using the REST API. The Webinterface is working too but the included Web Player isn't. It tries to access the server by the local IP address of the Docker server instance. The same goes for the Lyrics window and the 'Now Playing" panel.

```
Internet -> (Public-IP:8181) Firewall (NAT) ----> Apache2 (ProxyPass,192.168.1.20:8181) ---> Airsonic(Docker, 192.168.1.10:4040)
```
Example: The URL for the lyrics of one song is 

```
http://192.168.1.10:4040//lyrics.view?artistUtf8Hex=4f6e65&songUtf8Hex=49276c6c2057616974
```

but it should be
 
```
https://<Public-IP>:8181//lyrics.view?artistUtf8Hex=4f6e65&songUtf8Hex=49276c6c2057616974
```

As one can see the port is the local port and protocol too.

Airsonic needs to rewrite the IP address to the public IP address, normally there is a setting for this to let the server know the public address of the server (e.g. https://Public-IP:8181/)

AFAIR my old Madsonic installation has done this rewriting right.

**Comment by jooola** [comment]
I think something is wrong with your apache configuration could you past it here ?

**Comment by jooola** [comment]
https://airsonic.github.io/docs/proxy/apache/

**Comment by nRaecheR** [comment]
I don't think so, it works well with the REST API and any other servers I've running on the same site. Even most of the Airsonic web-if works as expected, only the Web player, Lyrics and Now Playing panel (misses the thumbs of user and song) are using the local IP. 

The Apache2  configuration looks exactly like on the link you've mentioned. This will work with any connection initiated by the browser directly. I think the Web Player starts an extra connection with a new URL that has been generated by Airsonic with the local IP address.

**Comment by nRaecheR** [comment]
Okay, I solved it, it was a problem with the Apache config. The following line must be modified:

```
 RequestHeader set X-Forwarded-Proto "https"
```
https instead of http and now it works. Thank you for the head up, Jonas!
