### ISSUE TITLE
[Documentation] Add step to installation instructions

### ISSUE THREAD

**Issue by eykamp** [airsonic/airsonic#566]
When installing airsonic on a new Raspberry Pi server, I needed to do this to get it to work:

    sudo apt-get install libservlet3.1-java

This should be added to the installation guide, and probably applies to other platforms as well.

**Comment by jooola** [comment]
Coule you specify your setup and on what system you needed to install this and why you needed his extra package ?

**Comment by jooola** [comment]
This also goes in our documentation repo so please reopen a new issue there airsonic/documentation
