### ISSUE TITLE
Rewrite Issue and Pull Request templates

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#57]
<a href="https://github.com/EugeneKay"><img src="https://avatars0.githubusercontent.com/u/528798?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EugeneKay](https://github.com/EugeneKay)**
_Sunday May 08, 2016 at 18:59 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/57_

----

The Issue and Pull Request templates are currently symlinked to CONTRIBUTING.md. While useful, these should be actual templates.

**Comment by jooola** [comment]
I'm happy with the current contributing template, Issue template was the main part to change here ! 
Closing this.
