### ISSUE TITLE
Add the ability to ignore symlinks in media scan

### ISSUE THREAD

**Issue by akpdw** [airsonic/airsonic#570]
Some of us have symlinks in place in our media folders so that old playlists, etc. will still work. But that means that when airsonic scans our folders it finds duplicates of those files. So there should be a way to ignore symlinks so that we only get one copy of each music file.

This can be set as a SettingsService option, since obviously not everyone would want this functionality.

**Comment by jooola** [comment]
Fixed by https://github.com/airsonic/airsonic/pull/571
