### ISSUE TITLE
new jukebox: audio drop-outs

### ISSUE THREAD

**Issue by adamdmoss** [airsonic/airsonic#573]
If I start playing a song with the new jukebox, and then interact with the airsonic web interface (or let the home screen automatically refresh a random album list), then audio will drop out for a fraction of a second (sometimes more).

The previous jukebox didn't have this issue on this system.

Hardware is raspberry pi 3 and a USB amp-DAC.  2 of the 4 CPU cores are idle.

**Comment by adamdmoss** [comment]
I'm at f5454bb0fd9a288774220b3d16b38075730cf5e8

**Comment by muff1nman** [comment]
Assigned @biconou
