### ISSUE TITLE
new jukebox: m4a files don't play

### ISSUE THREAD

**Issue by adamdmoss** [airsonic/airsonic#575]
The new jukebox will happily play mp3 and flac music, but I get silence when I try to play m4a audio.

**Comment by adamdmoss** [comment]
I'm at f5454bb0fd9a288774220b3d16b38075730cf5e8

**Comment by jooola** [comment]
About m4a files I think we already had some trouble with it : 
#345 #472

**Comment by biconou** [comment]
@adamdmoss I'll work on your issues soon.

**Comment by adamdmoss** [comment]
No rush @biconou, thanks for looking :)

**Comment by biconou** [comment]
Supporting m4a format is not easy. My first attempt using jaad fails. 
If necessary, it will be supported via ffmpeg.

**Comment by muff1nman** [comment]
@biconou I would definitely use the transcoder for this.

**Comment by biconou** [comment]
I'm preparing for that.
