### ISSUE TITLE
Cannot cast to Chomecast when using FQDNs for the airsonic server

### ISSUE THREAD

**Issue by vajonam** [airsonic/airsonic#576]
Assuming you have URL like.

http://hal.fqdn.com:4040/ss/ext/stream?player=5&id=4525&jwt=eyJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL3NzL2V4dC9zdHJlYW0_cGxheWVyPTUmaWQ9NDUyNSIsImV4cCI6MTUwNjEzMjIzMH0.6vyzq3nyqte2mEo9700154HoLT9Awo1W1JxUvklIuUU

This won't resolve on the Chromecast beauce the chromecast is set to use google's DNS server not the DNS servers provided by the DHCP service.

So the work around is either to doing Static Route to a local DNS server (network wide), while this might be out of the capabilities of some users, an alternative is fix the mediaURL when sending the cast command and replace with the bound interface of when creating the mediainfo object. 

 var mediaInfo = new chrome.cast.media.MediaInfo(song.remoteStreamUrl);

I am not very familiar with the code, else would have provided a PR. But think should be quite easily solvable! Nice work on the fork BTW! Awesome!

**Comment by muff1nman** [comment]
That is quite unfortunate behavior with the chromecast, but the workaround as you suggested is pretty much guaranteed to fail in the case of a reverse proxy. Some other work arounds are:

1. Use an ip address to access airsonic, which will be used when casting.
2. (Not verified) Block google's dns servers which will make the chromecast use the DHCP provided DNS servers.

**Comment by vajonam** [comment]
I am using a reverse proxy, so the one option that works for is redirect all network requests at my router to local DNS and then have the DNS resolver resolve upto google etc.

**Comment by muff1nman** [comment]
It shouldn't matter whether you use an IP or a server name in the proxy configuration as Airsonic essentially uses the hostname you typed into the browser. That same hostname is used for casting as it is assumed that same hostname is valid from the Chromecasts perspective. 

The solution to redirect/block all dns requests is good but unfortunately going to be difficult for some users. 

Perhaps we could add an option to pre resolve the server name before sending it to the Chromecast.

**Comment by vajonam** [comment]
`It shouldn't matter whether you use an IP or a server name in the proxy configuration as Airsonic essentially uses the hostname you typed into the browser. That same hostname is used for casting as it is assumed that same hostname is valid from the Chromecasts perspective.`

I dont think that is the case. because when I proxy using IP address, the URLs that get generated and sent to the chromecast look like this.

http://192.168.100.2:4040/ss/ext/stream?player=1&id=1607&jwt=eyJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL3NzL2V4dC9zdHJlYW0_cGxheWVyPTEmaWQ9MTYwNyIsImV4cCI6MTUwNjk1Mzc5OX0.ebY7IuqqpDV9E7BpYKnbsZXmz5hIlYPccz9IBjVWmSQ

So I think the its based on the request hitting Jetty server rather than what you type into the browser.

**Comment by vajonam** [comment]
Setting this borke the webplayer, but casting worked.. some cross site scripting stuff am sure.. anyway I think you're right about the browserURL and HTML5 client app also having something to do with it..
