### ISSUE TITLE
HTML player not playing

### ISSUE THREAD

**Issue by adamdmoss** [airsonic/airsonic#577]
On both Firefox 55.0.2 and Chrome 61.0.3163.79 the player embedded in the airsonic web interface doesn't play anything.

In both browsers when I try to play a file I'll get the pop-up notification from the browser that the track has started, but the timer on the player does not increase and the player does not start playing the song.

Web client is on Linux/x64.  Audio on the client machine is otherwise fine in these browsers in YouTube etc.

(The airsonic 'Settings'->'Players' page calls the web player an 'integrated Flash player' but on my client the interface doesn't appear to be using Flash.  Don't know if that's related.)

**Comment by adamdmoss** [comment]
I'm at f5454bb0fd9a288774220b3d16b38075730cf5e8

**Comment by adamdmoss** [comment]
n.b. I've tried playing mp3, m4a and flac files.  I have checked my transcoding settings - seem okay.

airsonic.log doesn't have any errors I think, if I'm looking at the right thing:
```
2017-09-15 19:33:50.145  INFO --- o.a.p.c.StreamController                 : Got HTTP range: 0-
2017-09-15 19:33:50.147  INFO --- o.a.p.io.PlayQueueInputStream            : admin listening to "foo.m4a"
2017-09-15 19:33:51.748  INFO --- o.a.p.c.StreamController                 : Got HTTP range: 0-
2017-09-15 19:33:51.749  INFO --- o.a.p.io.PlayQueueInputStream            : admin listening to "bar.m4a"

```

**Comment by adamdmoss** [comment]
Hmm, surely it's a transcoder problem.  Am investigating.

**Comment by jooola** [comment]
> (The airsonic 'Settings'->'Players' page calls the web player an 'integrated Flash player' but on my client the interface doesn't appear to be using Flash. Don't know if that's related.)

Some texts and translations are really obsolete !

**Comment by Lightsockie** [comment]
Sure you have flash installed? Cuz it's pretty damn deprecated (finally). Also, have you seen #380 ?

**Comment by jooola** [comment]
Is airsonic behind a proxy ?
cc @adamdmoss @TangoSierraAlfaVI

**Comment by paul-mesnilgrente** [comment]
I have the same problem and I am under apache2 proxy, if I use the directly the URL with the port it works well. I don't know how to fix it though.

**Comment by jooola** [comment]
@paul-mesnilgrente Could you tell me if the stream gets blocked ? ( is the stream over http ? ( not https ?))
Use your browser console to test that

**Comment by paul-mesnilgrente** [comment]
The stream is over https. How do I do to test it in the browser console? As I said, it works now with the line in the virtualhost. Nothing special printed in the browser console. Only the usual `getPreventDefault() is deprecated` and `https://airsonic.example.com/airsonic/stream?player=1&id=5787` when I play a music...

**Comment by mcepl** [comment]
Exactly, the same, with Airsonic on http://192.168.0.5:8080/airsonic/ … meaning absolutly no proxying, no caching, nothing. Firefox looks like this and absolutely nothing happens after that (time counter doesn't move, no sound). And I don't see any Errors anywhere in the console.
![screenshot from 2018-02-12 18-09-17](https://user-images.githubusercontent.com/198999/36109486-dd46a6a8-101f-11e8-9c12-2311c7f8fcd6.png)

**Comment by adamdmoss** [comment]
> Is airsonic behind a proxy ?
> cc @adamdmoss @TangoSierraAlfaVI

Sorry for the late reply - yes mine is behind a reverse proxy.

**Comment by adamdmoss** [comment]
FYI adding the headers as mentioned in https://github.com/airsonic/airsonic/issues/577#issuecomment-359200843 solves the problem!

Oddly, Chrome doesn't need this, Firefox does. :shrug:
