### ISSUE TITLE
Support Request: Disable Now playing or hide from certain users.

### ISSUE THREAD

**Issue by HaoZeke** [airsonic/airsonic#579]
Hi.

Any chance there's an easy way to disable the now-playing sidebar which shows up on the right?
For a variety of reasons my users would be better off not knowing who else is using the service...

Could it be an admin only option maybe?

Details: I'm running the dockerized version with persistent data volumes.

**Comment by muff1nman** [comment]
There are two settings for this that can be set on a user by user basis: "Show what others are playing" and "Let others see what I am playing". So the capability is there, but there is no global option to prevent users from using a particular setting.

**Comment by itsthejb** [comment]
@muff1nman Great! I'd been looking for this to maximise screen space. Thanks!
