### ISSUE TITLE
Shoutcast radio urls are not playing

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#582]
Hi

AIrsonic does not seem to be abel to play Shoutcast urls when added as radio. 

The url for a playlist is like this

http://yp.shoutcast.com/sbin/tunein-station.pls?id=312852

This url is no problem in apps like Vlc or Clementine but Airsonic or its clients is not playing it. In this case I use Dsub to play my Airsonic radios.

I am using Airsonic v10.0.1 on  Java: 1.8.0_73, OS: Linux Debian, Apache Tomcat/8.0.14 (Debian) 

thanks

**Comment by jolny** [comment]
Does the URL inside the pls work?
http://radio6o8.com:8000

**Comment by gerroon** [comment]
@jolny 

Please bear in mind that the web ui cant play radios as far as I can tell. All my Airsonic radio usage goes through Dsub on Android, which I should have mentioned in the original post.

The url you provided plays fine in Dsub on Android. The shoutcast urls do not play in Dsub.
