### ISSUE TITLE
Can Airsonic be X-framed?

### ISSUE THREAD

**Issue by seanvree** [airsonic/airsonic#583]
OS:  Windows 10E x64 1703
Webserver: IIS 10
AirSonic: 10.0.1-RELEASE – August 23, 2017

Hey man! Thanks for this project! Awesome!

I posted an "issue of on Reddit" because I'm not sure if this is just my rig, or what, but I didn't get a response.  

https://www.reddit.com/r/airsonic/comments/72jurv/can_airsonic_be_xframed/

**ISSUE**:

Airsonic itself works great. However, I'm trying to get AirSonic to work with /r/organizr. When I launch airsonic from within Organizr (which uses my airsonic rev proxy link), I can get to the main airsonic landing page no problem (Left Image), but then as soon as I click on any links within airsonic, it will launch a new browser window to the airsonic rev proxy direct link (Right image).

I'm using Organizr with a bunch of other apps like Sonarr, Radarr, and PLEX, all configured for reverse proxy to my webserver, but this is the only app that I've seen do this.

I know this is a x-frame issue, but I can't figure it out.

I was running SubSonic, and it did it as well.

Any tips?

Screenshot:

![airsonic](https://user-images.githubusercontent.com/8906637/31077566-d6da0a1c-a733-11e7-8e96-c3bac5524f9e.png)

**Comment by lbesnard** [comment]
same for me using Organizr. would be a great feature

**Comment by seanvree** [comment]
Any update to this?! Would love to get this resolved!

**Comment by jooola** [comment]
Seems like the current structure of the UI cannot properly be x-framed (using frames it self)
Also since we are working on a new UI I don't think we are going to try to fix this by refactoring the current UI.

**Comment by jaylex32** [comment]
> Seems like the current structure of the UI cannot properly be x-framed (using frames it self)
> Also since we are working on a new UI I don't think we are going to try to fix this by refactoring the current UI.

hows that new ui going now that is been a year after your last comment? thanks in advance

**Comment by antipiot** [comment]
Would appreciate this aswell :-)
