### ISSUE TITLE
FR: Discogs.com

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#586]
Hi

It would be great if discogs.com is also offered as a context provider.

thanks

**Comment by biconou** [comment]
@gerroon  Any detailed user story suggestion for that ?

**Comment by gerroon** [comment]
Well why not? Maybe for things like when Last fm is not providing enough info these otheer services maybe can fill the necessary information. 

Also Discogs has sale stuff maybe available cassettes, lps etc can be listed too , just saying.

**Comment by jvoisin** [comment]
To implement this, one would have to add a few lines to [this file]( https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/webapp/WEB-INF/jsp/albumMain.jsp ).
