### ISSUE TITLE
org.airsonic.player.dao.UserDao: Unknown role: '12'

### ISSUE THREAD

**Issue by hohokus** [airsonic/airsonic#593]
low priority.  no obvious breakage or loss of functionality.

on centos7, migrated from subsonic 6.1.1 to airsonic 10.0.0.1 standalone.  followed migration steps from https://airsonic.github.io/docs/migrate/.  everything has migrated properly and appears to work normally.

warnings show up in the log on song change & log out, possibly on other actions:
2017-10-07 12:55:11.617  WARN --- org.airsonic.player.dao.UserDao          : Unknown role: '12'

doesn't appear to break anything, just logs the warnings.  i would guess caused by the migration process.

**Comment by jooola** [comment]
I guess this will need some DB manipulation.

**Comment by jooola** [comment]
To elaborate what I meant ( Maybe need confirmation from @muff1nman ) : 
Subsonic 6.1 ships a new roles, which is stored in the DB.
Airsonic has been forked from subsonic 5.3, so it doesn't include this new role.

So you need to delete this new role.
Don't really how to achieve this ...

At your own risk : 
*let's bet on the airsonic.script file : 
shutdown airsonic
remove the Role 12 lines in the airsonic.script file
and you may get a rid of those warnings.*

**Comment by hohokus** [comment]
that worked perfectly, thanks.

shutdown airsonic, backed up 'db' folder, commented out 'INSERT INTO ROLE' line and "INSERT INTO USER_ROLE" lines for value 12, restarted airsonic.

no errors, no warnings, everything works normally.

thanks!

**Comment by jooola** [comment]
@hohokus Great to hear closing this !
