### ISSUE TITLE
[FR] Get localized artist info

### ISSUE THREAD

**Issue by sprnza** [airsonic/airsonic#610]
Hi there!
Thanks for the amazing project!
I've got an idea I'd like to share with you. It would be amazing to have artist info loaded in the same language with one configured for airsonic UI. Currently for all languages we get this info [Metallica](https://www.last.fm/music/Metallica) but there is a [Russian](https://www.last.fm/ru/music/Metallica) or [Italian](https://www.last.fm/ru/music/Metallica) versions.

**Comment by sprnza** [comment]
Seems like it's [already implemented](https://github.com/airsonic/airsonic/blob/6fc6d9035166efcdbcedb8b94ba61f221d48b57d/airsonic-main/src/main/java/org/airsonic/player/service/LastFmService.java#L236), but it doesn't work for some reason.

**Comment by dorel14** [comment]
Hello
I think it's the same as this one 
Last Fm informations #226

**Comment by sprnza** [comment]
But it still doesn't work for some reason.
