### ISSUE TITLE
Issue related to this Last Fm informations #226

### ISSUE THREAD

**Issue by dorel14** [airsonic/airsonic#613]
## Problem description
I've setted up my Default language in French in General parameters  and set up Defaul in personnal setiing , then french translations of artist informatiosn doesn't work 
To make it work I had to set up French in boths parameters

### Steps to reproduce
1. Start New 10.1
2. Set up your Defautlt Language in Generel parameters and let default in personnal parameter
3. Go to an artist page => informations are in english
4. change your personnal parameters => informations are in your language

## System information

 * **Airsonic version**: 10.1.0
 * **Operating system**: Linux Raspbian   
 * **Proxy server**: Nginx
 * **Client**: Chrome

**Comment by jooola** [comment]
This already has been reported and we need to implement a new last.fm service since we are still using a deprecated one !
