### ISSUE TITLE
DLNA Recent Albums is just listing albums 

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#617]
Hi

When I browse recent albums in Bubleupnp app, all it does is to list albums line in the albums folder (unlike how recent albums work in the web ui).

Please list the recent albums same as it does in the web ui, and please serve the listing as newest album to oldest (when browsed in an app).

thanks

**Comment by gerroon** [comment]
line  = like

**Comment by jooola** [comment]
(( @muff1nman quick question : is this backend or frontend related ? should the API serve mixed albums or has the frontend to do this ? (Trying to see if this have to be done on New UI or not)

**Comment by gerroon** [comment]
Ideally what we see in the "home page" or the landing page of Airsonic should be served to Dlna control points as well.

**Comment by gerroon** [comment]
Regarding this issue, Recent albums listing and the regular album listing is the same.

**Comment by akpdw** [comment]
Hey!  Somebody else is using DLNA!  :)

I swear this worked when I first wrote it.  I thought at first that it had stopped working for me because I'd rebuilt my database and reimported everything, but I've added new albums since then and those didn't show up as recent either.

I'll fix it as soon as I have some time. Assuming nobody gets to it before I do.

(I think DLNA search is also broken, but that can be another issue.)

**Comment by gerroon** [comment]
@akpdw

Thanks for considering a fix. That would be great. Like I mentioned in anotert bug, it would be nice if Airsonic DLNA serves the main page in the web ui  as is. So the DLNA implementation does not feel much different than the API that is shown in Dsub or other native clients.

**Comment by gerroon** [comment]
I also highyly recommend BubbleUpnp Server inconjunction with AIrsonic server, along with the BubbleUpnp app on android. That way the server discovery is almost instant and the airsonic dlna servercan be accessed from outside of the local network. So it is almost like Dsub but over Dlna, assuming that all the missing features are implemented in the DLNA side.

**Comment by muff1nman** [comment]
Closed in #647
