### ISSUE TITLE
DLNA Upnp Random tracks does not work

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#619]
Hi
I have random tracks in Bubbleupnp when browsing Airsonic. However it does not seem to be doing anything. I put a number in there but the listing comes out empty.

thanks

**Comment by jooola** [comment]
Could you please not post duplicate issue, I see this is related to #618 so closing it.
Tell me otherwise

**Comment by gerroon** [comment]
This is not the same issue. I am talking about the Upnp player grabbing random tracks from the renderer

**Comment by gerroon** [comment]
This is not the same issue. I am talking about the Upnp player grabbing random tracks from the renderer

**Comment by jooola** [comment]
Either the features is not available either it is not working but can't be both ?
You are talking about UPNP or DLNA ?

**Comment by gerroon** [comment]
The random album was a feature request. This issue is either a feature request or a bug I cant know that because I do not know if it is implemented or not.

I am talking about conneccting my client to Airsonic DLNA and not being able to create a random playlist whics is provided as a feature in BubbleUpnp app. I can do this exact same thing with other Dlna servers.

**Comment by gerroon** [comment]
Why are you closing issues shitbutt bot?
