### ISSUE TITLE
Playlists not alphabetized correctly

### ISSUE THREAD

**Issue by flvinny521** [airsonic/airsonic#620]
## Problem description

I have imported many playlists to airsonic. Some of them are named with "proper" capitalization, but some names are lowercase. The lowercase titles are displayed below the capitalized titles, when I believe the capitalization should not affect alphabetization order. DSub displays the playlists with proper sorting.

### Steps to reproduce

1. Import or name a playlist "Z"
2. Import or name a playlist "a"
3. View the playlists in the left margin of the web UI: "Z" will appear above "a"

## System information

 * **Airsonic version**: *10.1.0-RELEASE – November 4, 2017*
 * **Operating system**: *OpenMediaVault 3.0.90 in Docker*
 * **Client**: *Chrome Version 63.0.3239.30 (Official Build) beta (64-bit), DSub*

**Comment by Lightsockie** [comment]
This is working as intended. An 'a' and an 'A' are not the same character. You can change how your stuff is organized somewhere in your settings panel (at least for Artists, not 100% if it translates to playlists too)
