### ISSUE TITLE
Null pointer exception at userChart.view - sun.awt.FontConfiguration.getVersion

### ISSUE THREAD

**Issue by VinArt** [airsonic/airsonic#627]
[stacktrace.txt](https://github.com/airsonic/airsonic/files/1464236/stacktrace.txt)
## Problem description

The problem is that airsonic does not display anything in Total/Streamed/Uploaded/Downloaded when clicking at Status menu. This happens with docker image.

### Steps to reproduce

1. Install airsonic via docker image
2. Upload some music
3. Select Status menu entry

## System information

 * **Airsonic version**: 10.1.0-RELEASE – November 4, 2017
 * **Operating system**: jetty/9.4.7.v20170914, java 1.8.0_131, Linux (90.8 MB / 223.0 MB) Fedora 26
 * **Proxy server**: Nginx 1.12.1-1.fc26
 * **Client**: Chrome 61

## Additional notes

I believe it is related to this https://github.com/appropriate/docker-jetty/issues/15 because of the stacktrace.

From browser:
status.view:136 GET userChart.view?type=total 500 (Server Error)
status.view:125 GET statusChart.view?type=stream&index=0 500 (Server Error)
status.view:144 GET userChart.view?type=download 500 (Server Error)
status.view:145 GET userChart.view?type=upload 500 (Server Error)
status.view:137 GET userChart.view?type=stream 500 (Server Error)

**Comment by jooola** [comment]
@muff1nman Do we take care of the docker problems ? Who is the maintainer ?

**Comment by jooola** [comment]
I don't understand, jetty should only be used for development purpose no ?

**Comment by VinArt** [comment]
@jooola I don't know. Jetty is fine in normal usage as embedded container, I think the issue is in how docker container is built, maybe I got the wrong address and should contact docker people...

**Comment by Tapchicoma** [comment]
This is the link to base docker image issue (Alpine JRE8):
https://github.com/docker-library/openjdk/issues/73

**Comment by Tapchicoma** [comment]
Seems we need to add installing `fontconfig` and `ttf-dejavu` packages in [Dockerfile](install/docker/Dockerfile)
