### ISSUE TITLE
Overnight scanning hangs

### ISSUE THREAD

**Issue by KingDuckZ** [airsonic/airsonic#634]
Overnight music scanning doesn't work anymore. When I check in the morning, the website says: "Scanning files: 386" and it stays like that. It all worked until 3 days ago, then this problem started happening after I renamed and moved some music files around in my collection.
In this state I'm unable to access the settings page, so I can't run a manual scan either. Yesterday, after restarting the daemon several times, after a few hours the settings page was suddenly accessible again. I was then able to clean the db and run a manual scan, which worked just fine. This morning the problem happened again, but I did nothing to my music collection compared to yesterday.

### Steps to reproduce

I don't know why the problem presented itself, so I'm unable to give any other details than those I already stated above.

## System information

 * **Airsonic version**: 10.1.0
 * **Operating system**: ArchLinux on Odroid-C2
 * **Proxy server**: both through nginx https and direct http connection to airsonic
 * **Client**: Firefox 57 on Gentoo

**Comment by jooola** [comment]
I guess no logs ?
I think the settings page disappearing bug already have a ticket here might be related...
