### ISSUE TITLE
Default charset select. (No way for display cp1252 encoded tags)

### ISSUE THREAD

**Issue by kvaps** [airsonic/airsonic#637]
## Problem description

Many Cyrillic tracks have IDv3 tags encoded with cp1252 charset, but airsonic try to read it as cp1251
There is no way for chandge this behavor to display it right, as a result: the half of my collection are displayed like `Òàíöïîë "Óëåòàé` or `Êîãî çà ñìåðòüþ ïîñûëàòü 17`

### Steps to reproduce

Try  to add any track into collection with cyrillic IDv3 tags.
Tags should be encoded in `windows-1252`, not `utf-8`

## System information

 * **Airsonic version**: 10.1.0-RELEASE – November 4, 2017
 * **Operating system**: [Docker image](https://hub.docker.com/r/binhex/arch-airsonic/)
 * **Proxy server**: Nginx
 * **Client**: Any

**Comment by jooola** [comment]
> Tags should be encoded in windows-1252, not utf-8
First of all, we are not planning to introduce any windows encoding system in this FOSS project.

I suggest you convert your tags to the universal encoding utf8.

I guess you have access to a shell ?
First install eyeD3 : 
```sh
sudo apt install eyed3
```
Then try this little script : 
( Run it at the root of your music library )
```sh
###UPGRADE TO ID3V2.4 AND ENCODE IN UTF8
find -type f -name "*.flac" -execdir eyeD3 --encoding utf8 --to-v2.4 {} \;
find -type f -name "*.mp3" -execdir eyeD3 --encoding utf8 --to-v2.4 {} \;
find -type f -name "*.ogg" -execdir eyeD3 --encoding utf8 --to-v2.4 {} \;
```

I you need some more help ask, or come to the IRC/Matrix community channels

**Comment by jooola** [comment]
If you get everything working please close the issue

**Comment by kvaps** [comment]
Hi @jooola, thanks it help, your solution is working nice. 
But I still thinking that option for select default charset is really needed.

Yes, I can use eyeD3 for decode charsets any time. But sometimes some audiofiles can be downloaded via torrent and there is need some posibility for share them without changes.

It should be simple way for implement this option.
Sorry I'm not good at java, but I think that you just need to pass charset parameter into function for parsing IDv3 tags.
