### ISSUE TITLE
Library Not Updating After Scan

### ISSUE THREAD

**Issue by jeffgt14** [airsonic/airsonic#650]
## Problem description

The scan function seems to be broken for me. When I add a new album or remove an album, Airsonic doesn’t seem to pick up the changes. Same thing happens if I change a folder name of an album already in the database.

### Steps to reproduce

 * **1. Add album to directory
 * **2. Hit "Scan media folders now"
 * **3. Look for Recently Added media

## System information

 * **Airsonic version: 10.1.0-RELEASE – November 4, 2017
 * **Operating system: Ubuntu 16.04
 * **Client: Apache Tomcat/8.0.32

## Additional notes

There is no issue on permissions and the only way to correct it is the Remove Media Folder/Scan/Clean Database/Add Media Folder/Rescan method. I don’t have to do anything else with the files other than clean up the database with the above method so I don’t see how it could be a permissions issue.

Generally my folder structure is /Music/Artist/Album/Tracks. I do have all my music on 3 Drives that are being managed with MergerFS to show up in /mnt/storage/Music so I’m not sure if somehow that is causing issues with Airsonic.

**Comment by jooola** [comment]
Could upgrade to 10.1.1 and test again ?

**Comment by jeffgt14** [comment]
I have upgraded and it’s doing the same however it’s not consistent. I added 3 albums 2 nights ago to my Music folder. All have the same permissions and only 2 show up.

**Comment by muff1nman** [comment]
Do your logs have anything interesting to report? Can you see if they are showing up in the database at all?

**Comment by jeffgt14** [comment]
Here's a section from my log when I added the files and scanned
[https://pastebin.com/gk4bR53s](url)

**Comment by vanyasem** [comment]
Nothing interesting in logs, running 10.1.1 on Arch Linux and can confirm that

**Comment by Meiden-fc** [comment]
Same problem here. Using latest airsonic standalone version on Ubuntu server 16.04.

**Comment by Meiden-fc** [comment]
Indeed, if I modify the files or the folders of an existing artist, that artist is showed as empty after doing a scan and a db clean-up.

**Comment by jeffgt14** [comment]
I’ve been experimenting with this some more for a while. It looks like as long as I never click “Scan Media Folders Now” and just let it scan once a day at it’s normal time then everything works. The moment I click that button then no scan seems to ever work until I completely clear out the database again.

**Comment by Meiden-fc** [comment]
How do you completely clear out the db?

**Comment by jooola** [comment]
To purge the airsonic DB, simply stop airsonic, backup the `airsonic_home` folder and wipe the content in it. and restart airsonic.
But you will loose all your configuration.

You might want to inspect the `airsonic_home/db/airsonic.script` file to simply delete all the media files entries using a powerful editor (doing a `:10000dd` in vim goes pretty fast).

So here are the steps: 
- Shutdown airsonic
- Delete the `airsonic_home/thumbs` folder
- Delete the `airsonic_home/lastfmcache` folder

Then in the `airsonic_home/db/airsonic.script` file : 
- Keep the ~ 300 first lines
- Users definition starts around line (~300)
```
[...]
INSERT INTO "USER" VALUES('admin','enc:encodedpassword',4706276728,0,0,FALSE,NULL)                                                                                                                  
[...]
```
- Users roles are right after (~320)
```
[...]
INSERT INTO USER_ROLE VALUES('admin',1)
[...]
```
- Then Music folders settings (~380)
```
[...]
INSERT INTO MUSIC_FOLDER VALUES(0,'/mnt/audio/','Audio Jo',TRUE,'2018-02-05 21:19:20.897000000')
[...]
```
- Music players
```
[...]
INSERT INTO PLAYER VALUES(1,NULL,'Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0','admin','88.181.92.92',TRUE,'2018-02-27 17:54:15.735000000','MEDIUM','OFF',TRUE,FALSE,FALSE,'WEB',NULL,TRUE,NULL)
[...]
```
- Users settings
```
[...]
INSERT INTO USER_SETTINGS VALUES('admin','en',NULL,TRUE,FALSE,35,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,35,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,'admin','enc:encoded','OFF',TRUE,0,FALSE,TRUE,FALSE,'NONE',NULL,'2018-02-27 17:51:01.277000000',TRUE,TRUE,TRUE,FALSE,'random',TRUE,TRUE,60,TRUE,40)
[...]
```
- Transcoding settings
```
[...]
INSERT INTO TRANSCODING VALUES(0,'wav > mp3','wav','mp3','ffmpeg -i %s -v 0 -f wav -','lame -b %b --tt %t --ta %a --tl %l -S --resample 44.1 - -',NULL,TRUE,TRUE)
[...]
```
- Avatar binaries and infos
```
[...]
INSERT INTO SYSTEM_AVATAR VALUES(0,'Formal','2018-02-05 21:11:30.323000000','img/png',48,48,'89504e470d0a1a0a0000000d494844520000003000000 [cuted ]
[...]
```
- Again some transcoding settings
```
[...]
INSERT INTO TRANSCODING2 VALUES(0,'mp3 audio','ogg oga aac m4a flac wav wma aif aiff ape mpc shn','mp3','ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -',NULL,NULL,TRUE)
[...]
```
- And finally the Media files. (You can wipe everything from here till the end of the file)
```
[...]
INSERT INTO MEDIA_FILE VALUES(0,'/mnt/audio/audiojeun','/mnt/audio/audiojeun','DIRECTORY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,'/mnt/audio',0,NULL,NULL,'2018-02-05 20:52:54.000000000','2018-02-05 20:52:54.000000000','2018-03-09 03:00:00.000000000','2018-02-05 20:52:54.000000000',TRUE,4)
[...]
```
And finally restart airsonic.

**Don't forget to make some backups before**

**Comment by jeffgt14** [comment]
Remove Media Folder/Scan/Clean Database/Add Media Folder/Rescan

You can just uncheck Enable to remove the media folder and check Enable again to add media folder back.

**Comment by 4oo4** [comment]
I'm getting this too, since I switched from the embedded DB to MySQL yesterday (I don't recall it happening before that). Does this happen with more than just the embedded DB? I'm getting this when I scan both through the API and doing the Scan Now from the GUI.

**Comment by jeffgt14** [comment]
I think you can close this for my purposes. I believe the issue stemmed from from how it scans through different MergerFS drives. I added the "func.getattr=newest" flac to my MergerFS mount and I think it fixed the issues. Would also explain why the issue appeared intermittently.

**Comment by breakall** [comment]
Just wanted to leave a comment that "touch ./*" in my folders then re-scan solved this problem for me.
