### ISSUE TITLE
upload doesn't refresh library

### ISSUE THREAD

**Issue by anarcat** [airsonic/airsonic#651]
## Problem description

When I upload an album through the Airsonic interface, it doesn't show up in the "recently added" section. I need to rescan the library for the thing to show up.

### Steps to reproduce

1. Upload an .zip album in `+ More` "Upload file"
2. Go to the `Home` "tab"
3. Click on the `recently added` "sub-tab"

## System information

 * **Airsonic version**: 10.1.0-RELEASE – November 4, 2017
 * **Operating system**: Linux Debian stretch, within a Docker container built with this [Dockerfile](https://github.com/anarcat/subsonic-docker-image/blob/airsonic/Dockerfile)
 * **Proxy server**: Apache
 * **Client**: Firefox 57

## Additional notes

I wonder if it could be because it's a .zip file?

**Comment by pshpsh** [comment]
I have this problem too with zip archive. Manual rescan works.
nginx as proxy server, electron app as client

**Comment by jooola** [comment]
Could you try with version 10.1.1 ?

**Comment by pshpsh** [comment]
For me it fixed in 10.1.1, but need more reviews.

**Comment by anarcat** [comment]
LGTM, fixed, awesome, yay, thanks :)
