### ISSUE TITLE
No reading/display of embedded lyrics

### ISSUE THREAD

**Issue by enaloha** [airsonic/airsonic#653]
## Problem description

All of my songs have embedded lyrics, but they are not displayed in Airsonic

### Steps to reproduce

1. Find songs in Airsonic that don't show lyrics
2. Add and embed lyrics to those songs e.g. in iTunes
3. Witness that they still won't show up in Airsonic

## System information

 * Airsonic version: 10.0.1
 * Operating system: QNAP as QPKG (see https://forum.qnap.com/viewtopic.php?f=320&t=137665&sid=e3725af6314d6d37bcdaa4de4efc21f4)
 * Proxy server: None
 * Client: Chrome

**Comment by erenfro** [comment]
This would be cool indeed. If I could do Java I'd help, but Java's one language I don't do.
