### ISSUE TITLE
Missing Content-Type when fetching fullsize cover art

### ISSUE THREAD

**Issue by wakeldakel** [airsonic/airsonic#658]
## Problem description

When a thumbnail cover art is fetched through the REST API, Airsonic will add the header `Content-Type: image/jpeg`. However, when cover art is fetched in full resolution, this header is missing. This causes some clients to not display cover art because the request might not be an image at all.

### Steps to reproduce

`/rest/getCoverArt.view?someparameters&size=100` will send the header `Content-Type: image/jpeg`,
`/rest/getCoverArt.view?someparameters` won't.

## System information

 * **Airsonic version**: 10.1.1
 * **Operating system**: Ubuntu 14.04.5
 * **Proxy server**: Apache

## Additional notes

I created a small hotfix for Apache:
```
SetEnvIf Request_URI "/rest/getCoverArt.view.*" SIGN
Header always add "Content-Type" "image/jpeg" env=SIGN
```
When those lines are added to Airsonic's vhost in Apache, it will always add that missing header.

**Comment by muff1nman** [comment]
Interesting - I'm trying to reproduce this but am not able to with a random one of my cover arts. What is the type of file for the cover art that is not working? Is it all of your cover arts?

**Comment by wakeldakel** [comment]
Thanks for your answer! :)
Yes, it isn't working on any file. My Library is mainly imported from iTunes, so a lot of m4a files, but also mp3's. When I add the header manually everything works fine, so the actual cover art data is sent correctly.

**Comment by muff1nman** [comment]
Is your cover art embedded in your files or separate? If it is separate what is the type of cover art file? Is it a jpg?

**Comment by wakeldakel** [comment]
All covers are embedded.
If it helps I can give you access to my Airsonic server.

**Comment by muff1nman** [comment]
Would you be able to send me one of the mp3 files which has a non working cover art? My email should be on my github profile.

**Comment by muff1nman** [comment]
thx got it. will try to reproduce with that file

**Comment by MichaelBechHansen** [comment]
I can confirm that fullsize cover art is sent back to client apps without Content-Type HTTP header.

in play:Sub (iOS client), I have implemented image download to validate the Content-type as "Image/*", and fullsize images are therefore rejected when no Content-type header is presented.
I have a temporary workaround ignoring the Content-type, and just trying to decode an image from the data sent... that works, but it would be much better to get a proper Content-type from the server.

**Comment by muff1nman** [comment]
Cool I think I got it reprod:
```
> GET /airsonic/coverArt.view?id=14516 HTTP/1.1
> Accept-Encoding: deflate, gzip
> Host: home.andrewdemaria.com
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Referer: https://muff1nmanshost/airsonic/main.view?id=14516
> Cookie: XXXX
> Connection: keep-alive
> 
< HTTP/1.1 200 
< Server: nginx
< Date: Wed, 20 Dec 2017 23:40:53 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: max-age=36000
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: SAMEORIGIN
```

**Comment by muff1nman** [comment]
Actually now this is sending `Content-Type: audio/mpeg` lol.

**Comment by muff1nman** [comment]
Think I have this fixed now, can one of you build from b0aff38cafd030ea97ae9bdcb65f0626db66944d and verify?

**Comment by wakeldakel** [comment]
Yes, I can confirm it works perfectly now. Thanks for the great work!

**Comment by MichaelBechHansen** [comment]
This seems to be an issue again...
I just tested with version "10.1.2-RELEASE – July 28, 2018", and the Content-Type Http-header is missing from the response headers when requesting a fullsize cover, but is present when specifying the "size=" parameter.
