### ISSUE TITLE
Now playing shows generic_gwt_principle

### ISSUE THREAD

**Issue by Tapchicoma** [airsonic/airsonic#663]
## Problem description

Right block in *Now playing* shows **GENERIC_GWT_PRINCIPLE**.

### Steps to reproduce

Seems this happens when Airsonic site is opened for a long time (more then 2 hours?)

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017
 * **Operating system**: official docker image
 * **Proxy server**: nginx-1.12.1
 * **Client**: Google Chrome 63.0.3239.108, (64 bit)

## Additional notes

Related log:
```
2017-12-25 15:50:26.470 INFO --- o.a.p.io.PlayQueueInputStream : GERNIC_JWT_PRINICPLE listening to "Rhythm of Life/01 Ignition.mp3"
--
```
![screenshot_20171225_165942](https://user-images.githubusercontent.com/1595262/34341288-01beda5c-e995-11e7-9883-1f79ae2a3347.png)

**Comment by muff1nman** [comment]
This is the username that is displayed for any anonymous access. (i.e. casting, share links, etc). Perhaps it would be sufficient to change the username to something without a typo (should be `GENERIC_JWT_PRINCIPLE`) or to Anonymous (localized accordingly)?

**Comment by Tapchicoma** [comment]
Always display `Anonymous` makes no sense, then better to remove it.

IMHO, good solution will be to display actual username.

**Comment by jooola** [comment]
>  displayed for any anonymous access. (i.e. casting, share links, etc). 

I don't think this is about registered users

**Comment by muff1nman** [comment]
@jooola is right - its anonymous access so there is no registered user associated. So in my mind the two options are:

1. Display `Anonymous` or something similar
2. Filter any current playing information from unregistered players.
