### ISSUE TITLE
Funny characters?

### ISSUE THREAD

**Issue by ytlevine** [airsonic/airsonic#665]
Just set up Airsonic, and noticing that a bunch of the Airsonic dropdowns have funny characters in them, mainly within dropdowns, like:
More actionsâ¦
Selected songsâ¦

Any way to fix that?

## System information

Version | 10.1.1-RELEASE – December 16, 2017
Server | Apache Tomcat/8.5.23, java 1.8.0_151, Linux (268.4 MB / 520.5 MB)

Running on Debian 8 (should be updated with all the latest updates installed) as a service.

No proxy server (yet).

Using the latest stable release of Chrome to access.

**Comment by jooola** [comment]
This has been fixed few commits ahead 10.1.1 release. they are meant to be ellipsis.

See a93a18a055aa90d5439ce87aa8f1bce12fdc7d84

Simply [build from the master](https://airsonic.github.io/docs/install/source/) branch and deploy the new war.

**Comment by ytlevine** [comment]
Thanks, didn't see that commit...

Guess I'll either wait for the next release or build from the master and update the war I'm running.

**Comment by ytlevine** [comment]
Just compiled from source and it seems to be fixed, thanks a lot!

**Comment by pimzand** [comment]
I found the badly UTF8 encoded ellipsis to still be there in ResourceBundle.properties,
and there is no ResourceBundle_en.properties which the commit is referring to.
Just switching to Dutch (like I'm supposed to) is the easiest way to fix it for me.

**Comment by pimzand** [comment]
@jooola thanks for helping a noob. I'm fine now.
