### ISSUE TITLE
Podcast Location

### ISSUE THREAD

**Issue by mccorkled** [airsonic/airsonic#666]
I just got this setup and I cannot find any documentation...

I don't have the podcast location mapped yet and I didn't mount one but I added 2 podcast RSS feeds. It shows that it downloaded them and I am unsure if they were just downloaded to the browser cache or if they are downloading within the container somewhere. I am new to Dockers.

The Podcasts show mapped to /airsonic/podcasts but as I said, I didn't set that up. Where did these Podcasts get download to and is there a way to listen to each one without downloading them?

Also, do Playlists have to go into a root folder, or can I map them to /music?

Thanks

**Comment by heyarne** [comment]
I'm not quite sure I understand your questions. I'll try to answer them as far as I understand you:

My podcasts are set up to be saved to `/sharedfolders/Downloads/Podcast`. The folder looks like this:

```
$ ls -l /sharedfolders/Downloads/Podcast/
total 40
drwxrwsr-x+ 2 airsonic airsonic 4096 Dec 22 08:34 Alternativlos
drwxrwsr-x+ 2 airsonic airsonic 4096 Dec 24 23:40 Ear Hustle
drwxrwsr-x+ 2 airsonic airsonic 4096 Nov 22 21:55 Love + Radio
drwxrwsr-x+ 2 airsonic airsonic 4096 Dec 30 08:41 Radiolab
drwxrwsr-x+ 2 airsonic airsonic 4096 Dec 22 08:35 SozioPod
```

There's a folder for every feed I subscribed to. Did you check the contents of `/airsonic/podcasts`? My guess is that by "you didn't set them up" you mean you didn't map the volume inside the docker container to something on your drive. You could still copy the folder as described [here](https://stackoverflow.com/questions/22049212/copying-files-from-docker-container-to-host), but that is a one-time action and you would have to do that everytime you try to access your podcasts from outside the docker container.

There's (to my knowledge) no way to listen to the podcasts without downloading them first in airsonic.  I don't understand your question about playlists. Playlists only exist in the airsonic database, they are nothing physically present on your hard drive (except for the tracks they contain).

**Comment by mccorkled** [comment]
I was only basing my setup off of this...
https://hub.docker.com/r/airsonic/airsonic/

    -v `pwd`/music:/airsonic/music:z \
    -v `pwd`/podcasts:/airsonic/podcasts:z \
    -v `pwd`/playlists:/airsonic/playlists:z \

From what I understand, this means I need a Music, Podcast, and Playlist folder. I looked in /config and it's empty. I mapped /music and my music came up after changing the directory within Airsonic from airsonic/music to /music. I am just unsure if I should make a folder called "Podcasts" and map it, or if they should go to my music folder or what. 

Thanks for the help. I'm super new to Linux and Docker but slowly getting the hang of it.

**Comment by jooola** [comment]
Podcasts have a dedicated folder, which is `/var/music/Podcasts` by default (so it is included inside the default music folder ).

Of course this location can be changed in the podcasts settings within airsonic.

Now comes the dockers mapping ( I don't know how docker works ), you can change the settings in airsonic to point a Podcast folder within the music folder ( you already mapped ) or add the mapping between your host podcast folder and the docker one.

And don't forget to set the right permissions.

I think I completed the answer of @heyarne which was pretty much complete !

If everything is fine, please close this ticket.

**Comment by mccorkled** [comment]
I set the podcast folder to /Music/_Podcasts but after it is downloaded it is not showing in there.

**Comment by heyarne** [comment]
It should be showing in your docker container at that location. You can verify this by executing:
```
docker exec -it $NAME_OF_YOUR_CONTAINER ls /music/_Podcasts
```

This executes `ls /music/_Podcasts` in the docker container. If you're unsure what the name of your container is, you can find it out using `docker ps` when the container is started. Can you play the downloaded episode in the web ui?

**Comment by mccorkled** [comment]
I don't know much about SSHing into my NAS but it has a nice GUI and I can navigate to the folder which is empty. The episode is playing fine within Airsonic's UI.

**Comment by heyarne** [comment]
Most probably your folder mapping is not correctly set up. You can either copy all your data out of the docker container to your *real* folders (the ones not inside docker; you can use `docker cp` for that), or you start over from scratch (which might be easier for you since you seem not to be familiar with the command line).

**Comment by mccorkled** [comment]
Well I have setup several containers successfully. Within Docker I mapped /Music and that folder is working within Airsonic. Then for the podcasts I set /Music/_Podcasts for the podcast setting within Airsonic since music was already mapped it should be able to read the folders within the /Music directory.

**Comment by heyarne** [comment]
I see. You're right, sounds like it should be working.
Could go to "Podcasts", select any Podcast, check any episode you didn't download so far, scroll down and click "Download Selected" then click on "About" and copy the log?

**Comment by mccorkled** [comment]
https://pastebin.com/i1wpJK5K

**Comment by jooola** [comment]
Could you try to map a second folder dedicated to pod-casts and not within the music folder ?
