### ISSUE TITLE
FR: Use the embedded covers in the songs for missing albums art.

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#667]
Hi

It looks like Airsonic only looks for things like cover.jpg etc for covers for albums. This is a bit of hinderance if one is missing those images in the folder. One has to sit down and download cover images one by one or try to extract from mp3 files if they have any. This is ok for couple albums but it is alot of work when one has hundreds of albums that needs rewiring like that.

I propose that Airsonic looks for the first audio file that has embedded cover if the album folder is missing cover/artwork images. 

thanks

**Comment by enaloha** [comment]
I don't think your assumption is correct. I have tons of albums in folders with no separate folder.jpg. The songs all have the album cover embedded and they show up fine in airsonic. So it seems to me that airsonic is already doing what you are requesting. There is an occasional problem with a few albums that don't show the proper cover art even though the art is embedded. I fix that by copying the embedded cover and repasting it (re-embedding).

**Comment by gerroon** [comment]
@enaloha thanks for reporting on this. I will investigate the issue further then.

**Comment by gerroon** [comment]
Do you have cover.jpg or cover.png?

**Comment by enaloha** [comment]
no separate image file at all. All my covers are stored inside the song file’s metadata.

**Comment by gerroon** [comment]
Ok that is interesting than. I will look into it. Let me see what is going.

**Comment by enaloha** [comment]
I have quite a few custom covers that I made myself. I can see them fine in my library. So yeah, I’m positive airsonic can retrieve covers from metadata.

**Comment by retro-78** [comment]
Hi

I can confirm too...

I use the meta data of each song to store the cover of the album and the cover appears on airsonic UI.

Don't forget to close the issue if it is solved =).

**Comment by Lightsockie** [comment]
Have the same problem as OP. A while back went through and manually dropped some cover.jpgs everywhere. Best example I could find of it not working is my misc folder of songs with different and/or no album arts embedded into each separate song. Maybe its from the folder not agreeing? Or it only choosing the "first" song of the dir? (Which for the "first" song is none)

**Comment by gerroon** [comment]
So it works for two people and it does not work for another two people. Lets see what the devs thing.

**Comment by enaloha** [comment]
No, that's not how this works. There are various scenarios and you will have to adapt to them or ask the devs to add the feature. Covers for a specific album will show up fine if any of the following conditions are met:

1. All songs have embedded covers
2. The first file has a embedded cover
3. The folder contains a cover.jpg

If the first song has no embedded cover (even if all others do) the album will not show a cover. My suggestion to you is to either embed a cover in all files (I would say this is the best solution), or just the first song, or add a cover.jpg to those albums that don't have metadata covers.

**Comment by adamhsparks** [comment]
I can confirm this behaviour. 

I have all of my files with covers embedded in the tags via Picard or Beets. Airsonic will show this in lists. However, if a "cover.jpg" is not present in the folder, there is nothing displayed in the main panel.

See examples:

![img_3130](https://user-images.githubusercontent.com/3195906/35192484-333d2ec6-fedf-11e7-9354-de4449b16f82.jpg)

> Artist view with all albums showing cover art.

![img_3131](https://user-images.githubusercontent.com/3195906/35192485-336a9ff0-fedf-11e7-8315-9212ed7cce87.jpg)

> Album with cover art embedded, no "cover.jpg" file in dir. This is the second album shown in the list above with the pinkish NPR cover.

![img_3132](https://user-images.githubusercontent.com/3195906/35192486-3395e73c-fedf-11e7-89f8-88c92d505a92.jpg)

> Album with cover art embedded and "cover.jpg" file in dir.

**Comment by adamhsparks** [comment]
I just realised I'm looking at Play:sub, not airsonic. Will recheck web interface when I'm able to. Perhaps this is the actual issue? Clients, not airsonic?

**Comment by adamhsparks** [comment]
I mistakenly thought that this was happening for me as well. Perhaps the OP is using a client that exhibits this behaviour? I know that the one I'm using on iOS does this. It does not display cover art for embedded tags, but for "cover.jpg". However, when browsing airsonic directly in a web browser, it behaves as expected.

**Comment by jooola** [comment]
So @enaloha is right. I tested a bit and everything leads to his answer.

Airsonic will try to get album cover in : 

1. cover.jpg
2. first song embed cover (ordered by song title alphabetically) (this assumes every song in the folder (album) has the same cover.

I think the problem is not the covers, but your library structure.
I you want to have a specific or a dummy cover for various artists folder just add a cover.jpg.

Please close this if my answer suits you.

**Comment by gerroon** [comment]
@joola 

#2 does not work for me. For test, I made only one song in a folder (7th song) has embed cover out of 11. So 10 songs do not have any cover and only one song has cover. All have the same artist album etc and are in the same folder.

The album does not show any cover at all.  

If you read my original entry you see what I was askingis that AIrsonic parses all songs until it finds a cover in a given folder(album). If there are no covers in any of the songs in the folder, it moves on.

**Comment by jooola** [comment]
> #2 does not work for me. For test, I made only one song in a folder (7th song) has embed cover out of 11. So 10 songs do not have any cover and only one song has cover. All have the same artist album etc and are in the same folder.
The album does not show any cover at all.

Is the song with embed cover the first song in a title alphabetically order ?

Ok, so yeah I get the idea, but we might need to consider few points : 
- various artists/albums folders with various covers (compilation)
- scanning time or time to load covers

And what is your use-case since it looks pretty special ?

Either you have a proper album with a unique cover art, either its a compilation with various covers and in this case I would not display any cover.

**Comment by gerroon** [comment]
Like I said, it is the 7th song (the track numbers is at the beginning of the file names) for testing purpose.

The idea of first song in the folder needs to have a cover embedded is a bit flawed in my opinion. Not all albums will have such neatly assigned stuff, especially various artists albumwhere the alphabetical order might not represent the first song of the album etc.

Anyway, my point is that Airsonic should exhaust searching in that album folder until it finds a song with an album cover, if it cant find anything in the first file, or in any file or a cover image it should move to scanning as usual.

My use case is that half of my library is not neatly organized and I have thousands of songs that are not neatly organized.

**Comment by jooola** [comment]
> Like I said, it is the 7th song (the track numbers is at the beginning of the file names) for testing purpose.

Ah sorry I really mean the title from the audio tags, not the file name.

> Anyway, my point is that Airsonic should exhaust searching in that album folder until it finds a song with an album cover, if it cant find anything in the first file, or in any file or a cover image it should move to scanning as usual.

Ok this will be taken in consideration but I'm not the backend dev so I will not fix it.
It needs to be discussed.

> My use case is that half of my library is not neatly organized and I have thousands of songs that are not neatly organized.

Generally you can't expect something to match each use cases since everyone here has a different way of sorting his library, when also including not organized libraries. So I don't know what those changes involves.

**Comment by gerroon** [comment]
Mine is just an FR as the title says. It is up to the devs to consider it. I am not here to demand anything, I understand that this issue is a bit stick and hard to handle all cases.

**Comment by SteveDinn** [comment]
I've just installed AirSonic as part of my preparation to leave Google Play Music, and while the music playing part is working great (obviously the main thing), this issue hit me hard. Probably a full third of my albums do not have artwork, but they all have it embedded in the tags.

**Comment by signedout** [comment]
> I've just installed AirSonic as part of my preparation to leave Google Play Music, and while the music playing part is working great (obviously the main thing), this issue hit me hard. Probably a full third of my albums do not have artwork, but they all have it embedded in the tags.

I'm in this very same scenario. My library structure is Artist/Album/files, and in many cases there's no cover.jpg but all files have embedded album art, and it's not showing.
