### ISSUE TITLE
Dlna is not serving thumbnails of the latest albums

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#668]
Hi

I am using Airsonic v10.1.1 on Debian X64  Tomcat. I can get the listing of the latest albums in BubbleUpnp app but the albums all are missign covers. On the other hand browsing the recent in Dsub or in the web app has no such issue. So this seems to be a limited case with Dlna.

thanks

**Comment by jooola** [comment]
Might be duplicate, I'll dig in the old tickets...
