### ISSUE TITLE
Removing Welcome Info

### ISSUE THREAD

**Issue by mccorkled** [airsonic/airsonic#679]
I have looked in the settings and cannot seem to find a way to remove this information and have albums or podcasts display instead. 
![1](https://user-images.githubusercontent.com/13697804/35164698-7b211846-fd19-11e7-86a0-5f1ec1182875.png)

Also, do you know why the frame is not properly fitting all of the information?
![1](https://user-images.githubusercontent.com/13697804/35164674-57a70862-fd19-11e7-8d6c-5809eb956b12.png)

Thanks :)

**Comment by jooola** [comment]
Here in Settings > General you should find something like this:
![image](https://user-images.githubusercontent.com/19195485/35183602-40550b0c-fde9-11e7-8027-84d3ef00830a.png)

You simply need to disable the "Show Getting started on startup" option.

About the frame size, I guess you have a small screen, and frame here have some kind of fixed min-width.
