### ISSUE TITLE
java.sql.SQLException: Integrity constraint violation - no parent UR_R_FK table: ROLE in statement...

### ISSUE THREAD

**Issue by sprnza** [airsonic/airsonic#687]
I get an error trying to play music. [Log](http://paste.speran.info/?07fa89a8ed2bb852#tplnrpyMo1lj8izCrQqo9b75xgJwzZQdrntvlCSadMo=)
It fails at the web interface only. I do able to play music using an android app.
New users are able to play music perfectly fine.
```
Version	10.1.1-RELEASE – December 16, 2017
Server	Apache Tomcat/8.5.23, java 1.8.0_144, Linux (309.7 MB / 613.5 MB)
```

**Comment by sprnza** [comment]
Seems like I screwed my database. Is there a way to reset it?

**Comment by sprnza** [comment]
So it was a problem with a folder without permissions configured for podcasts AND "User allowed to administrate podcasts" enabled. I've disabled "User allowed to administrate podcasts" and now I'm able to play music. But I can't get Podcasts working. I've set another folder for podcasts which a user running airsonic is able to write to but I still can't enable "User allowed to administrate podcasts" back to manage my podcasts.

**Comment by sprnza** [comment]
How to remove podcasts from the database directly?

**Comment by jooola** [comment]
Try to edit the users role (permissions) within the airsonic.script file , this might fix your problem, still I don't understand much the logs you provided, but as you mentioned it, looks like your DB is corrupted.

Did you tried to start with a fresh DB ?

**Comment by sprnza** [comment]
Nope, I haven't tried to start with a fress DB. The only thing is seems broken is "User allowed to administrate podcasts" tick. As I click it and try to Save I get this error:
```
PreparedStatementCallback; SQL [insert into user_role (username, role_id) values(?, ?)]; Integrity constraint violation - no parent UR_R_FK table: ROLE in statement [insert into user_role (username, role_id) values(?, ?)]; nested exception is java.sql.SQLException: Integrity constraint violation - no parent UR_R_FK table: ROLE in statement [insert into user_role (username, role_id) values(?, ?)]
```
Username and role_id are question marks. What role_id is the one I need? 11?

**Comment by jooola** [comment]
So any changes since our small discuss on IRC ?

**Comment by sprnza** [comment]
Hi @jooola ! Have you got any ideas regarding this? I miss podcasts.

**Comment by jooola** [comment]
I'm not really the guy that can help you on this matter but lets try anyway : 

If you could find a way to reproduce this it would be a good step forward.

From what I understand in : 
```
PreparedStatementCallback; SQL [insert into user_role (username, role_id) values(?, ?)]; Integrity constraint violation - no parent UR_R_FK table: ROLE in statement [insert into user_role (username, role_id) values(?, ?)]; nested exception is java.sql.SQLException: Integrity constraint violation - no parent UR_R_FK table: ROLE in statement [insert into user_role (username, role_id) values(?, ?)]
```
Either it tries to insert wrong values or it has a missing parent key (foreignkey ?).
I don't think it comes from the code, but more from a corrupted DB. (I might be completely wrong)

Somewhere in the db/airsonic.script you should see : 
![image](https://user-images.githubusercontent.com/19195485/36340761-792da096-13e3-11e8-8829-02e71cfa1d21.png)

If you have a missing ROLE this could be a problem.
Did you tried to restart with a fresh DB ? Moving entire airsonic_home and recreating it empty  (default would be /var/airsonic => /var/airsonic_bak and recreat /var/airsonic ).

Did your DB upgrade to subsonic 6.x.x someday ? If yes you might have some old irrelevant lines in the DB ( Maybe not, muff1nman added some DB changes so I don't know if he wiped the eventual migration changes ( I think subsonic 6 shipped a new role number 12)).

One of the solution would be to restart from scratch and only import what's matters to you ( users/ users settings / playlists / rated songs). But if you think you have too much important data in the old DB maybe we should try to fix it and not restart from scratch.

**Comment by sprnza** [comment]
I did have the "podcast" ROLE missing. I've never been using anything except airsonic. I think it got broken on the latest update because I never haven't been changing anything in airsonic's guts.
