### ISSUE TITLE
Album Art

### ISSUE THREAD

**Issue by mccorkled** [airsonic/airsonic#688]
Is there a way to force album art downloading?

**Comment by jooola** [comment]
Could you explain a bit more your question ?
Which album art?  From where ?
With what ?

**Comment by mccorkled** [comment]
All album art, I don't know where from, or how. That's what I want to know haha. When my album get added to AirSonic, there are a lot missing album art.

**Comment by jooola** [comment]
Could you please read #667.
If you didn't understand something just ask !

**Comment by jooola** [comment]
Could you please read #667.
If you didn't understand something just ask !

**Comment by jooola** [comment]
Could you please read #667.
If you didn't understand something just ask !

**Comment by enaloha** [comment]
If you have songs that are missing album art, you can handle that with a tagger such as kid3: https://sourceforge.net/projects/kid3/

**Comment by mccorkled** [comment]
I do not see a way to use metadata in #667.

Thanks.

**Comment by enaloha** [comment]
Airsonic will use most of the metadata embedded in your audio files, including album covers (unfortunately that is not true for lyrics just yet). If your song has a metadata-embedded cover, airsonic will display that cover. If your song has the wrong album art or does not contain album art, airsonic allows you to change it. It will search for covers at last.fm and add the cover to the cover. You can also enter a URL for any image file you would like to add to the song if you don't like the covers found at last.fm.

**Comment by mccorkled** [comment]
Does it automatically search Last.fm and embed them? I have no covers for a ton of my collection.

**Comment by enaloha** [comment]
Are you actually using the web client of airsonic? If so, you will see that under each cover image, there is an option to change the cover image. Just click it and see for yourself. So airsonic is not an automatic batch tagger. However, I already pointed you to one such tagger in a post above. There many more solutions for taggong and downloading covers depending on the platform you use.

**Comment by mccorkled** [comment]
I am using the web client. I don't want to have to run an entirely separate program just for grabbing album art. That seems very counter intuitive.

**Comment by jooola** [comment]
@mccorkled We will not implement a complete tagging engine within airsonic.
First this is lot of work, and a lot of external tools already do it really well.
If someone opens a PR with such a functionality it will probably be merged, but again, someone needs to do it !
