### ISSUE TITLE
Add Mpd support

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#689]
Hi

It would be nice if we have one more mode called MpdPlay along with jukebox mode. Basicaly Airsonic will pass the play list to a predefined Mpd server transparently hence the control of the playlist will be done by Mpd clients. 

Ampache has this feature and it is called localplay and it expands the usage cases.

What is nice is that Mpd has various output modes like http streaming, or pipe output etc this way Airsonic users can enjoy their collection in various extra ways if they also run Mpd alongside.

thanks

**Comment by gerroon** [comment]
Yeah Airsonic team should just give up on Jukebox mode

**Comment by gerroon** [comment]
f@k you @stale boy

**Comment by jvoisin** [comment]
Well, actually, nobody volunteered to implement this for 1.5 years, so I think that we can close it.
If anyone wants to work on it, feel free to to re-open the issue.
