### ISSUE TITLE
error: initscript does not exist: /etc/init.d/airsonic

### ISSUE THREAD

**Issue by z-vap** [airsonic/airsonic#695]
## Problem description

I was still working through getting this to work, and I noticed that when I attempted to generate the autostart, it threw an error stating **error: initscript does not exist: /etc/init.d/airsonic**.  I noticed in _contrib_ that there was some systemd environment/service files which helped me greatly, but I don't know the first thing about writing my own startup script.   

### Steps to reproduce

$ sudo update-rc.d airsonic defaults
update-rc.d: error: initscript does not exist: /etc/init.d/airsonic

## System information

 * **Airsonic version**: *10.1.1-RELEASE*
 * **Operating system**: *OpenmediaVault 3.0.97 (Erasmas) / Debian GNU/Linux 8.10 (jessie)*
 * **Client**: *Windows 10 / Chrome 64.0.3282*

**Comment by jooola** [comment]
First thing we don't provide any init.d scripts. PLease us the systemd service.

If your are you trying create it I suggest your to use the old subsonic starting script [here](https://github.com/airsonic/subsonic-svn/tree/upstream/subsonic-installer-debian/src/etc) or below : 
```sh
#! /bin/sh
### BEGIN INIT INFO
# Provides:          subsonic
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Subsonic daemon
# Description:       Starts the Subsonic daemon. Subsonic is a web-based
#                    music streamer, jukebox and Podcast receiver.
#                    See http://subsonic.org for more details.
### END INIT INFO

# Author: Sindre Mehus <sindre@activeobjects.no>

# To change the startup parameters of Subsonic, modify the service
# configuration file /etc/default/subsonic rather than this file.
[ -r /etc/default/subsonic ] && . /etc/default/subsonic

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Subsonic Daemon"
NAME=subsonic
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/$NAME
DAEMON_ARGS="--pidfile=$PIDFILE $SUBSONIC_ARGS"
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Run as root if SUBSONIC_USER is not set.
[ "$SUBSONIC_USER" = "" ] && SUBSONIC_USER=root

# Make sure Subsonic is started with system locale
if [ -r /etc/default/locale ]; then
    . /etc/default/locale 
    export LANG
fi

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started

    if [ -e $PIDFILE ]
    then
	ps -p $(cat $PIDFILE) > /dev/null
	[ "$?" = 0 ] && return 1
    fi

    touch $PIDFILE
    chown $SUBSONIC_USER $PIDFILE
    [ -e /var/subsonic ] && chown -R $SUBSONIC_USER /var/subsonic
    [ -e /tmp/subsonic ] && chown -R $SUBSONIC_USER /tmp/subsonic

    start-stop-daemon --start -c $SUBSONIC_USER --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS || return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2

	# Many daemons don't delete their pidfiles when they exit.
        rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
```

You will need to teak this one a bit since many option has been deprecated and some where added.

So you can rework it, and we will be pleased to have your final work so we could add it to our contrib forlder.

If you have any question regarding this script just let me know !

**Comment by z-vap** [comment]
Thanks it does seem to start using systemd.   Initially my system became un-responsive and I thought it was due to the airsonic.service, because it threw this error `[/etc/systemd/system/airsonic.service:4] Unknown lvalue 'AssertPathExists' in section 'Unit'` but the service still does start.   It seems well formed in the file, so I don't know why it is throwing that message.     Thanks for following up.

**Comment by z-vap** [comment]
Oh I am so sorry.  Yes you can close.   Why the AssertPathExists shows up I have no clue but it is not hindering airsonic in any way.  No issues here

**Comment by jooola** [comment]
The error your are getting comes from the [service file at the 4 line.](https://github.com/airsonic/airsonic/blob/master/contrib/airsonic.service#L4)
Is ask itself if the /var/airsonic dir exists.
So if you changed the default airsonic.home path this might be a reason why the warning show up.
Remove it or change it following your configuration.
