### ISSUE TITLE
Import new weblate translations

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#701]
Some time ago I managed to setup a translation service using Weblate.
Sadly we didn't find a way to check the formatting of all those files, mainly to avoid breakage.
Also the Weblate service allowed anyone to push translation into airsonic.

So we dropped Weblate and moved to Transifex.
Still some work has been made by some contributors and they may want to merge those changes into airsonic.

Here is a backup zip with all the translated files in different language : 
[i18n.zip](https://github.com/airsonic/airsonic/files/1764354/i18n.zip)

**Comment by comradekingu** [comment]
@jooola If you read the (updated) Terms of service on Transifex I imagine you will change your mind.

**Comment by jooola** [comment]
@comradekingu Which part of the terms ? (Would you mind linking me the part that you want me to read ?)

**Comment by jooola** [comment]
@comradekingu I will open a new issue regarding this change, I might have made a mistake when going to transifex,  I agree.

**Comment by comradekingu** [comment]
@jooola Transifex now doesn't allow any venue of commercialization for libre software projects, also nobody under the age of 18 is allowed to contribute, etc.

There is also extensive spying, the codebase is closed, the functionality is awful, communication is broken, fixing anything is 5 times as much work, etc. It is near impossible to fix error across languages on Transifex, on Weblate it is easy. Others are, for every reason I can imagine, doing the exact opposite, moving from Transifex to Weblate.

The Airsonic stringbase still had errors in it from Subsonic last time I checked and did anything about it. I imagine it went back to going stale on Transifex. I would argue being able to edit strings directly is way better, all-though it can be changed.

What was the issue with formatting?

**Comment by jooola** [comment]
@comradekingu The issue was when mixing some utf-8 encoding and Java Latin.
You already posted an issue regarding something similar some time ago:
https://github.com/airsonic/airsonic/issues/645

Will take some time to address this issue.
