### ISSUE TITLE
Web interface and API don't show songs, but do list a > 0 count of artists, albums and songs

### ISSUE THREAD

**Issue by muggenhor** [airsonic/airsonic#707]
## Problem description

Even though airsonic reports having found media none of it get displayed in the web interface or via the API (tried with Clementine).

From the logs:
```
2018-03-03 03:00:23.177  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 6293 entries.                                                                               
```

When looking more closely however, it does display statistics for the amount of available songs:
```
284 artists
793 albums
5,693 songs
84.14 GB
434 hours
```

Furthermore, when I use a DLNA capable client ([VLC for Android](https://play.google.com/store/apps/details?id=org.videolan.vlc)) it _does_ see the songs though. So somewhere from the media library to the web and API frontends the data gets lost.

## System information

 * **Airsonic version**: 10.1.1 (standalone, started through systemd)
 * **Operating system**: Debian 9.3 armhf inside an LXC container on an OpenWRT host
 * **Proxy server**: None
 * **Client**: Firefox 58, Clementine 1.3.1 and [VLC for Android](https://play.google.com/store/apps/details?id=org.videolan.vlc)

**Comment by jooola** [comment]
Might be duplicate of #681 # 706

**Comment by muggenhor** [comment]
I'm not sure about #706, as it seems to focus exclusively on the API which I use (Clementine) but don't program against.

Most of the symptoms match up with #681 though (just missing the DLNA bit, which I just added as a comment).

So this is indeed a duplicate.
