### ISSUE TITLE
jquery getPreventDefault() is deprecated warnings

### ISSUE THREAD

**Issue by eharris** [airsonic/airsonic#708]
## Problem description

When using Firefox developer tools, I'm getting warnings from jquery-1.7.1.min.js:3:6598 of:
```
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
```

## System information

 * **Airsonic version**: 10.1.1-RELEASE
 * **Operating system**: Debian 9, Tomcat 8.5.14, java 1.8.0_151
 * **Proxy server**: None
 * **Client**: Firefox 52.6.0 (64-bit)

**Comment by jooola** [comment]
Yes also noted this, still this is only a warning. No problem comes with it (yet).
