### ISSUE TITLE
Now playing sidebar doesn't show configured Player name

### ISSUE THREAD

**Issue by eharris** [airsonic/airsonic#710]
## Problem description

Now Playing sidebar does not display the configured Player name for the players being used.  It seems to always display either the logged in username (if using the web player) or some other identity string from the player itself (if using an external player).

## System information

 * **Airsonic version**: 10.1.1-RELEASE
 * **Operating system**: Debian 9, Tomcat 8.5.14, java 1.8.0_151
 * **Proxy server**: None
 * **Client**: Firefox 52.6.0 (64-bit)

**Comment by eharris** [comment]
Update: After restarting the airsonic server, now I am seeing the Player name as a suffix on the username in the form "user@playername".  I have only tested with the web player so far though.

So I guess this may be a problem with the server not picking up changes made in the Player config page until the server is restarted?

**Comment by jooola** [comment]
Do you have any way to reproduce this ?

**Comment by eharris** [comment]
I'm still trying to find a good way to reproduce this.
