### ISSUE TITLE
"Help" page still refers to  Sindre Mehus (sindre@activeobjects.no)

### ISSUE THREAD

**Issue by kiv57** [airsonic/airsonic#713]
I guess this doesn't need to fill the full template :

-> WebUI -> Help -> "About Airsonic" -> Cell "Contact".

Thanks for the hard work!

**Comment by jooola** [comment]
Using which language ?
Could you do the change ? on [Transifex](https://www.transifex.com/airsonic/airsonic/dashboard/)

**Comment by kiv57** [comment]
French

I'll have a look on Transifex, thanks.

**Comment by kiv57** [comment]
Solved : I joined the translation team for French, changed the corresponding string and translated some additional strings on the way ;)
