### ISSUE TITLE
Song with accented character ommitted from track listing

### ISSUE THREAD

**Issue by jessebl** [airsonic/airsonic#716]
## Problem description

In what I'm assuming is a problem in dealing with non-ASCII characters (although that's not my diagnosis to make), the Flaming Lips song "Pompeii am Götterdämmerung" does not appear properly in the webUI. It is absent from the track listing of its album, and appears below it with the accented characters replaced by question boxes.![](https://i.imgur.com/dYYeKCQ.png)

I wonder how/if this connects to #646.

### Steps to reproduce

1. Have a song in your library with an accented character
2. Navigate to the song's album in webUI
3. See the song with special characters appear below/outside of track listing

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017
 * **Operating system**: CentOS Linux release 7.4.1708 (Core)
 * **Proxy server**: nginx/1.10.3 (Ubuntu)
 * **Client**: Firefox 58.0.2

**Comment by jooola** [comment]
Could you please post the song somewhere I can get it ?

**Comment by jessebl** [comment]
From your perspective, what's the best way for me to do that, considering that I don't own the copyright?

This is the song:
title: Pompeii am Götterdämmerung
album: At War with the Mystics
artist: The Flaming Lips

**Comment by enaloha** [comment]
I think this could be related to #646, which I reported previously.

**Comment by jooola** [comment]
@jessebl Would you mind trying to re encode a copy of your file and check if it works with it ?
Use the instructions I gave in this issue : https://github.com/airsonic/airsonic/issues/637

**Comment by zrav** [comment]
I'm experiencing a variation of this issue: I can add the songs with accented characters to the play queue, but playback isn't possible, the player just stays at 0:00. When I rename the track, the issue goes away.
An example of an offending filename substring is "Antonín Dvořák".

**Comment by jessebl** [comment]
@jooola the track's tags are already encoded in utf8; `eyeD3` reports "Nothing to do."

@zrav in trying to replicate what you found, the song I mentioned in this issue will not even add to the queue.

**Comment by jooola** [comment]
@jessebl Could you join the community channel so I can get a copy of you file ? mention me @jooola to ring me please.

**Comment by jessebl** [comment]
Posted.

**Comment by sundararajanmohan** [comment]
I had same issue running on Raspberry Pi3. I overcame it by installing several "locale", namely FR, IT and CN. Ran a media scan again after a reboot and the files were picked up as proper tracks for streaming.

**Comment by varac** [comment]
I solved this by exporting `LANG` env variable to contain `en_US.UTF-8`, i.e. by adding `export LANG=en_US.UTF-8` to `/var/lib/tomcat8/bin/setenv.sh`

see http://fehlis.blogspot.com/2010/12/subsonic-on-linux-fix-issue-with.html or https://github.com/Mach5/supersonic/issues/68
