### ISSUE TITLE
Corrupt zip files

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#72]
<a href="https://github.com/davidkeefe24"><img src="https://avatars3.githubusercontent.com/u/6304202?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [davidkeefe24](https://github.com/davidkeefe24)**
_Friday May 13, 2016 at 11:46 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/72_

----

When using the "Download all" link you get a corrupt zip file. Selecting all files and using the dropdown option to download works fine though.

**Comment by go2tom42** [comment]
Still present in v10.1.2

**Comment by Benz0X** [comment]
This should close issue #72 and issue #678
