### ISSUE TITLE
api enhancements

### ISSUE THREAD

**Issue by phirestalker** [airsonic/airsonic#721]
I was wondering if the project would ever consider offering added API functionality on top of subsonic? If not, is there a way to submit code for subsonic? Is it on Github as well?

I am asking because I would like to be able to queue songs for each named player separately in airsonic and control currently streaming playlists for dumb devices like google home.

I figured I would ask before I started reading through the code and writing something up.

**Comment by Tapchicoma** [comment]
Related to #474

**Comment by jooola** [comment]
I suggest you browse the repository and you will find many tickets concerning the new API.
=> #474 #553 #522 #519 

Also you could join us on the community channels if you want to discuss more about this.
Ask muff1nman or jooola
