### ISSUE TITLE
Music suddenly missing - Folder/album is lost when its tags are changed

### ISSUE THREAD

**Issue by thrdroom** [airsonic/airsonic#722]
## Problem description

Some Tracks get suddenly and randomly marked as "Missing" (see screenshot) in my imported playlists. This happens to tracks without any clear reason. It does not seems to be related to filenaming/pathnaming or filepermissions, as sometimes only single tracks from the same folder/album seems to be affected.
If i search for this tracks via hand in airsonic, or visit the album page i can play them fine, but in the playlists they get marked as missing.
Thats a major problem cause these tracks wont get played in the playlist nor get synced with any client (e.g. Dsub Android).

![screenshot](https://user-images.githubusercontent.com/5912061/37656819-68509a3e-2c49-11e8-9e57-2da69c7e48cc.png)

### Steps to reproduce

1. Install airsonic
2. Point airsonic to itunes musicfolder
3. Scan media folders
4. Add folder for playlists
5. Point airsonics "Import playlists from" to this folder
6. Export playlists from itunes
7. Scan media folders (Playlists get automatically imported)
8. Change songs(tags,albumart) and/or playlists in itunes, add new songs to playlists/library in itunes
9. Export playlists from itunes to playlistfolder
10. Scan media folders (Playlists get automatically imported)
11. Some tracks should be affected now (i have around 15k songs so you maybe need enough to trigger this bug)

*I am not sure if Step 8 is really necessary or not.

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017
 * **Operating system**: macOS High Sierra 10.13.2
 * **Client**: Chromium, Firefox ESR, Dsub Android

## Additional notes
All this posts here are directly related to my described problem:
[http://forum.subsonic.org/forum/viewtopic.php?f=2&t=12272](http://forum.subsonic.org/forum/viewtopic.php?f=2&t=12272)
[http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17641](http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17641)
[http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17592](http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17592)

Libresonic had the exact same problem which they fixed in the recent version 6.1.3. As i dont have access to their codebase i cant directly reference the commit that fixed the problem.

In this post [http://forum.subsonic.org/forum/viewtopic.php?f=2&t=12272&p=67972&hilit=unraid#p74912](http://forum.subsonic.org/forum/viewtopic.php?f=2&t=12272&p=67972&hilit=unraid#p74912) a workaround for this bug is described as it seems to be related with the "last-modified"-timestamp of the files and the folder. This workaround is not accetable as it involves touching the media-sourcefiles which timestamps should stay unaltered as long as not intended to change files or folders.

This thread [http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17641](http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17641) is diretly related to the problem described in my bugreport here.

As adviced in this post [http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17592](http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17592) i tried this query in the <UrlOfSubsonic>/db.view without any success.

`UPDATE MEDIA_FILE
SET children_last_updated = '1970-01-01 01:00:00.0'
WHERE TYPE IN ( 'ALBUM', 'DIRECTORY')`

If you need further informations from me please let me know.

I hope that we can quickly get a fix for this bug and new binary releases asap, as it seems critical to me!
ANY HOTFIXES ARE APPRECIATED.

**Comment by MitchMcHenry1** [comment]
I know this was closed from inactivity, but I just experienced the same issue.  Exact same scenario, but I use MusicBee rather than iTunes.  Used the same config for years with Madsonic and switched to Airsonic a year or so ago and have never had a problem.  Suddenly, one of the playlists now shows many missing files, but all are actually there and play fine from the album view.  So it's definitely a legit bug and should be reopened.

**Comment by eidolonify** [comment]
I've been having this issue as well. Rather than mucking around with timestamps, my workaround has been to set scan media folders to "Never." I have to manually scan the folders if I add or remove music (and then re-import my playlists), but it's not like I'm adding new music everyday and my playlists were breaking every time the automatic scan happened.
