### ISSUE TITLE
Huge traceback in the logs from normal Connection reset by peer IO exception

### ISSUE THREAD

**Issue by eharris** [airsonic/airsonic#724]
## Problem description

Whenever a connection is broken by a client (which is pretty common), a huge traceback of about 300 lines and 40k bytes is generated in the logs, but is largely useless.

The log message block starts with:
```
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer
```

It seems like it would be worth suppressing the huge traceback for such a common and expected condition.  It makes the logs huge for no useful reason and makes it harder to see and debug other real issues.

### Steps to reproduce

Stream a file from a client and skip to the next track before all the data from the last one has transferred, or from a client where you can otherwise force a premature close of the connection.

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017
 * **Operating system**: Debian stretch, Apache Tomcat/8.5.14 (Debian), java 1.8.0_162, Linux
 * **Proxy server**: None
 * **Client**: Any

**Comment by jooola** [comment]
I think this issue is a duplicate

**Comment by eharris** [comment]
I don't see another open issue regarding this, @jooola can you please link to the original this is a duplicate of?

**Comment by jooola** [comment]
Ok so it is duplicate but I closed most of these issues... Sorry for this.

See #562 #555 and maybe related to #548

**Comment by jooola** [comment]
A quick fix has been merged so closing this. #727
