### ISSUE TITLE
access is denied when trying to view folder

### ISSUE THREAD

**Issue by illumilore** [airsonic/airsonic#730]
After adding a music folder and scanning it, trying to click on it gives access is denied error, even though the file and all the parent folders belong to the exact same user that is running and they all have the read permission for that user.

## System information

 * **Airsonic version**: 10.1.1
 * **Operating system**: ubuntu 17.10
 * **Proxy server**: None
 * **Client**: *firefox

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by jooola** [comment]
Could you give us some logs, some informations about your files, a screen shot, or something.
