### ISSUE TITLE
Can't find last.fm artist for some artists only

### ISSUE THREAD

**Issue by lbesnard** [airsonic/airsonic#736]
## Problem description
I have noticed that some artists name don't get always found via the last.fm api. A little annoying as I really enjoy create radios via airsonic.

I haven't really managed to find the "pattern" for which this doesn't work. Probably related to special characters, and dots ? My collection is pretty clean, and was organised via beet.

Here are a list of artist names I have tested :

-M- <- works
Beatles, The <- works

Notorious B.I.G., The <- doesn't work
Nazgûl, The <- doesn't work
Rodrigo Y Gabriela & C.U.B.A_ <- doesn't work

## System information

 * **Airsonic version**: latest
 * **Operating system**: linux debian
 * **Client**: android dsub, or via firefox

**Comment by di-dc** [comment]
I think some of it is just around how last.fm spells/formats the artist name. At least for "Notorious B.I.G., The", it looks like last.fm expects it in the form "The Notorious B.I.G."

Just for reference, you can sign up for a last.fm API key for testing here: https://www.last.fm/api/account/create
Then you can make test calls to last.fm to check artist names:
http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=The%20Notorious%20B.I.G.&api_key=API_KEY_GOES_HERE

I haven't looked to see exactly how Airsonic formats the call to last.fm, but one option might be to include "autocorrect=1" in the call. For the Biggie example then, the following call succeeds:
http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Notorious%20B.I.G.,%20The&autocorrect=1&api_key=API_KEY_GOES_HERE

I don't know what other impacts this might have, though.

More info: https://www.last.fm/api/show/artist.getInfo

**Comment by di-dc** [comment]
As a related point, in a quick review it looks like maybe Airsonic is using a deprecated call to last.fm, and should (at some point) be updated to use their newer API:
https://www.last.fm/api/submissions

(Though I found some comments online implying the old API will not be discontinued, so this probably isn't very urgent.)
