### ISSUE TITLE
[How-to] save generated cover art to the media folder

### ISSUE THREAD

**Issue by a7medo778** [airsonic/airsonic#737]
hi guys
as the title says, is there a way to save the generated thumbs (that get generated when a file/artist doesnt have any) to the media folder or preferably just write it down to the media id3 ?

**Comment by jooola** [comment]
Airsonic doesn't provide such a feature. I guess you want to save the artist cover ? The cover is fetched from last.fm. You should find some scripts that download these covers for you.
