### ISSUE TITLE
Unable to install Airsonic WAR version on Ubuntu server 18.04 

### ISSUE THREAD

**Issue by hcombee** [airsonic/airsonic#742]
## Problem description

By default Ubuntu 18.04 comes with open-jdk-11 and Tomcat 8.5.30 and starting Airsonic throws this error:

´´´2018-05-11 07:41:27.760  WARN --- ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [applicationContext-sonos.xml]; nested exception is org.springframework.beans.FatalBeanException: Invalid NamespaceHandler class [org.apache.cxf.jaxws.spring.NamespaceHandler] for namespace [http://cxf.apache.org/jaxws]: problem with handler class file or dependent class; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
2018-05-11 07:41:27.768 ERROR --- o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception´´´

The installation docs tell me to install open-jdk-8, however Tomcat 8.5.30 seems to be compiled with Java 9 and will not run with open-jdk-8. When trying to connect to Tomcat it will give this message

´´´SEVERE [http-nio-8080-exec-1] org.apache.coyote.AbstractProtocol$ConnectionHandler.process Error reading request, ignored
     java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;´´´ 

### Steps to reproduce

Just install Tomcat8 and open-jdk-8 and tell Tomcat to use this version.
When you try to connect to http://x.x.x.x:8080, Tomcat will crash with the described message.

## System information

Ubuntu Server 18.04
Tomcat 8.5.30
Open-jdk-8
Airsonic 10.1.1 WAR

**Comment by muff1nman** [comment]
https://www.reddit.com/r/airsonic/comments/8hs95a/ubuntu_upgrade_broke_it/dym7f5c

**Comment by hcombee** [comment]
Thx for your help, but I seem to have found a workaround in the utility muffin research kitchen ;-).
By adding the module to the /etc/default/tomcat8 I was able to at least install airsonic.

JAVA_OPTS="-Djava.awt.headless=true -XX:+UseConcMarkSweepGC --add-modules=java.se.ee"
