### ISSUE TITLE
copy database from Corrupt OS?

### ISSUE THREAD

**Issue by threeeye** [airsonic/airsonic#744]
I have Airsonic installed on Ubuntu server (RPi),
The OS got Corrupted, is there a way to save the database?

**Comment by 4oo4** [comment]
You would want to look in `/var/airsonic/db` and see what you can salvage from there. I'm guessing you're using the embedded db instead of MySQL/PostgreSQL?

**Comment by threeeye** [comment]
Yes, I'm using the embedded db
In /db I have  :airsonic.lck, airsonic.log and airsonic.properties (in the new installation)

I just copy the files in /db and it will work?

**Comment by jooola** [comment]
Backup the entire /var/airsonic folder and should be good

`airsonic.script` is the script that is loaded each time you start airsonic.

**Comment by threeeye** [comment]
Thanks
I'll try it and report back...

**Comment by threeeye** [comment]
After copying the files I changed owner, group and permissions to airsonc:airsonic 777
It works !
Thanks
