### ISSUE TITLE
LDAPS and StartTLS problem

### ISSUE THREAD

**Issue by pacija** [airsonic/airsonic#746]
## Problem description

LDAP authentication does not seem to work with LDAPS ot StartTLS openldap server, when AES encryption is globally required for connection (ssf=128).

### Steps to reproduce

Setting LdapUrl to start with ldaps:

LdapUrl=ldaps://ldap.example.org:636/ou=people,ou=users,dc=example,dc=org

... throws the following error:

org.springframework.security.authentication.InternalAuthenticationServiceException: simple bind failed: ldap.example.org:636; nested exception is javax.naming.CommunicationException: simple bind failed: ldap.example.org:636 [Root exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

Setting LdapUrl to start with ldap:

LdapUrl=ldap://ldap.example.org:389/ou=people,ou=users,dc=example,dc=org

... throws different error:

org.springframework.security.authentication.InternalAuthenticationServiceException: [LDAP: error code 13 - confidentiality required]; nested exception is javax.naming.AuthenticationNotSupportedException: [LDAP: error code 13 - confidentiality required]

## System information

 * **Airsonic version**: *10.1.1-RELEASE*
 * **Operating system**: *11.1-RELEASE-p10*
 * **Proxy server**: *apache24-2.4.33_1*
 * **Client**: *Firefox 59*

## Additional notes

Perhaps this is not airsonic's issue but Tomcat's. I'm quite new to all this, any advice is welcome.

**Comment by muff1nman** [comment]
Can you try adding the SSL certificate for your ldap server to your JVM keystore where airsonic is running?

**Comment by pacija** [comment]
@muff1nman I managed to import my certificate to newly-created keystore (I would rather not touch default cacerts), but I need a little help where to specify it in Tomcat or airsonic.

Thank you in advance.

**Comment by pacija** [comment]
Better not to put another problem into mix - I backed up default cacerts and imported there.

After tomcat restart, ldap:// (StartTLS) gives the same error.

After another tomcat restart, ldaps:// seems to work (I can successfully log in). However, I get the following warning in airsonic.log:

```
2018-05-23 16:00:38.884  WARN --- o.a.p.service.SettingsService            : Failed to decode LDAP manager password.

org.apache.commons.codec.DecoderException: Illegal hexadecimal character V at index 0
```
I can send full trace if needed.

**Comment by pacija** [comment]
I see what is causing above warning, I've edited `airsonic.properties` directly with clear-text ldap password. It works but throws an error. After I edited password through web interface i see it hashed, and the warning disappeared.

So I have achieved secure ldap by means of ldaps. Any chance to support StarsTLS as well somewhere down the road?

**Comment by muff1nman** [comment]
Great to hear ldaps is working. Can you open a new issue with regards to StartTLS?

**Comment by pacija** [comment]
@muff1nman I won't clutter Airsonic's issues with StartTLS now, as I have working secure LDAP solution, and I think if devs have some time for Airsonic it can be better spent (kough kough get rid of flash in public player kough kough) :smile:

Closing

**Comment by dolphyvn** [comment]
@pacija : I'm having the same issue and would be great if you can share how did you solve this?

**Comment by echoxxzz** [comment]
> @pacija : I'm having the same issue and would be great if you can share how did you solve this?

In my case I'm using a Freebsd Samba Domain Controller as my LDAP backend and I'm running Airsonic on a FreeBSD 13 server so some of my file paths may differ for Linux/Windows but the steps are essential the same.

1. Copy the Samba DC ca.pem file from /var/db/samba4/private/tls folder to my Airsonic server. If you're using a Windows Domain Contoller you can export the CA cert using the Certificate Management Tool (lots of online tutorials how to-do this).
2. Import the ca.pem file into the cacerts trust store using the keytools utility on the Airsonic server:

        keytool -importcert -keystore $JAVA_HOME/lib/security/cacerts -file ca.pem

  Again if your using Windows these path may differ so you may have to search for the cacerts file. 

3. When prompted enter the default password "changeit" (unless you've already changed the default password) and make sure you answer "yes" to trust the cert.

4. Make sure Airsonic is using ldaps:\\ and port 636 for the LDAP URL and click off to auto add LDAP users then restart Airsonic and it should work.
