### ISSUE TITLE
Any user can change Transcoding settings

### ISSUE THREAD

**Issue by RIPASSAS** [airsonic/airsonic#749]
## Problem description

When logged in as an non-administrative account, using the page url "/transcodingSettings.view?", I am able to add, delete and tinker with other options on that page

### Steps to reproduce

1. Create a non-administrative account
2. Login with that account
3. Go to "http://localhost:8080/transcodingSettings.view?"

## System information

 * **Airsonic version**: 10.2.0-SNAPSHOT – May 31, 2018
 * **Operating system**: Ubuntu
 * **Proxy server**: None
 * **Client**: Chromium

## Additional notes

This was happening in a forked version, but the fork is recent so the main release should be affected as well

**Comment by muff1nman** [comment]
Thanks for bringing this to light.
