### ISSUE TITLE
Java Jukebox doesn't playback some flac files

### ISSUE THREAD

**Issue by glencoe** [airsonic/airsonic#751]
## Problem description
There are some flac files that are not played
by the new java jukebox. I got the questionable files
from bandcamp.

The progress bar starts it's animation. The animation
then runs for about 10 seconds without any sound playing.
After that the player jumps to the next playable file.

The log file does neither show an error message nor
the respective 
`starting jukebox for "<Album Name>/<filename>"`
message.

### Steps to reproduce
Might be hard to reproduce. The problem only occurs with
some albums i got as flac from bandcamp. Every file of
the respective albums is affected. E.g.:
https://bigthief.bandcamp.com/album/masterpiece
https://kinggizzard.bandcamp.com/album/flying-microtonal-banana

## System information

 * **Airsonic version**: 10.1.1-RELEASE
 * **Operating system**: archlinux 64bit, java 1.8.0_172
 * **Proxy server**:  None
 * **Client**: firefox 60.0.1

**Comment by biconou** [comment]
@glencoe 
I want to fix that issue. 
I would need one copy of your flac files that does not work.
Can you send it to me via a kind of drop box ? 

Or attach it to a comment in the issue.
