### ISSUE TITLE
[Build error]  Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate

### ISSUE THREAD

**Issue by Adnn** [airsonic/airsonic#760]
## Problem description

I am trying to build airsonic from source, following the procedure at:
https://airsonic.github.io/docs/install/source/

### Steps to reproduce

I start from a fresh ubuntu/xenial64 VM (on Vagrant).
I installed Maven and OpenJDK-9.

> Apache Maven 3.3.9

> openjdk version "9-internal"
> OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
> OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**EDIT**: The issue is the same if I use the system provided OpenJDK-8

I set my JAVA_HOME as follows
`export JAVA_HOME=/usr/lib/jvm/java-1.9.0-openjdk-amd64`

Then, I simply follow build procedure:

```
git clone https://github.com/airsonic/airsonic.git
cd airsonic
git checkout v10.1.1
mvn clean package
```

Which fails with

> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] Airsonic ........................................... SUCCESS [  0.340 s]
> [INFO] Subsonic REST API .................................. FAILURE [  0.193 s]
> [INFO] Sonos API .......................................... SKIPPED
> [INFO] Airsonic Main ...................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 26.231 s
> [INFO] Finished at: 2018-06-23T10:48:05+00:00
> [INFO] Final Memory: 18M/45M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate (default) on project subsonic-rest-api: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: An API incompatibility was encountered while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate: java.lang.IllegalAccessError: superclass access check failed: class org.jvnet.jaxb2.maven2.resolver.tools.MavenCatalogResolver (in unnamed module @0x28237492) cannot access class com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver (in module java.xml) because module java.xml does not export com.sun.org.apache.xml.internal.resolver.tools to unnamed module @0x28237492
> [ERROR] -----------------------------------------------------
> [ERROR] realm =    plugin>org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1
> [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
> [ERROR] urls[0] = file:/home/vagrant/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb2-plugin/0.13.1/maven-jaxb2-plugin-0.13.1.jar
> [ERROR] urls[1] = file:/home/vagrant/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb2-plugin-core/0.13.1/maven-jaxb2-plugin-core-0.13.1.jar
> [ERROR] urls[2] = file:/home/vagrant/.m2/repository/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
> [ERROR] urls[3] = file:/home/vagrant/.m2/repository/com/sun/org/apache/xml/internal/resolver/20050927/resolver-20050927.jar
> [ERROR] urls[4] = file:/home/vagrant/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
> [ERROR] urls[5] = file:/home/vagrant/.m2/repository/junit/junit/4.8.1/junit-4.8.1.jar
> [ERROR] urls[6] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
> [ERROR] urls[7] = file:/home/vagrant/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb22-plugin/0.13.1/maven-jaxb22-plugin-0.13.1.jar
> [ERROR] urls[8] = file:/home/vagrant/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar
> [ERROR] urls[9] = file:/home/vagrant/.m2/repository/org/glassfish/jaxb/jaxb-xjc/2.2.11/jaxb-xjc-2.2.11.jar
> [ERROR] urls[10] = file:/home/vagrant/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.4/maven-plugin-annotations-3.4.jar
> [ERROR] Number of foreign imports: 1
> [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by muff1nman** [comment]
Java 9 is not currently supported/tested.

**Comment by Adnn** [comment]
Hi @muff1nman, thank you for taking the time to review this issue,

The build procedure was also tested with Java 8 (OpenJDK-8, coming with Ubuntu 16.04), and the problem is also showing up.

**Comment by muff1nman** [comment]
@Adnn Java 8 works fine (see build bot). Closing as dup of #611
