### ISSUE TITLE
DLNA doesn't work from Docker container

### ISSUE THREAD

**Issue by Shurov** [airsonic/airsonic#761]
## Problem description

I'm running Airsonic from within Docker container. I still would like to use its DLNA server in my LAN. However, since (as far as I understand) the DLNA port is random on startup, I cannot expose it out from container.

### Steps to reproduce

1. Install Airsonic docker container
2. Activate DLNA service
3. Cannot find it within the same network

## System information

 * **Airsonic version**: Latest
 * **Operating system**: Debian 9 (Stretch), OMV 4

**Comment by jpsutton** [comment]
This isn't an airsonic bug but a consequence of the networking mode you've chosen for your container.  As I see it, this could be overcome by using either of the following options:

- by using the "-P" flag to "docker run" which would expose all listening ports from the container
- by setting up your container to use the macvlan network driver and then connecting it to a physical interface on your system.  This option allows you to assign a unique IP address to the docker container itself, without the need for the host to NAT individual ports.  One limitation you'll want to be aware of with macvlan is that containers setup this way are unable to communicate directly with the host via the network if they share the same physical interface.

**Comment by muff1nman** [comment]
Not a bug - the option I would go is to share a bridge with the host network.
