### ISSUE TITLE
LDAP Login allows unauthenticated access

### ISSUE THREAD

**Issue by turbomettwurst** [airsonic/airsonic#764]
## Problem description

*When fetching Useraccounts from LDAP a user can login using only the username, the password field is not required

### Steps to reproduce

1. Enable LDAP Login in airsonic.properties (i am using mail as a unique identifier)
2. Login using a Useraccount than can be found in LDAP and has proper privileges (e.g. group membership) without entering a password.
3. Listen to Music (or anything else)

## System information

 * **Airsonic version**: *10.1.1-RELEASE – December 16, 2017*
 * **Operating system**: *official docker image*
 * **Proxy server**: *Traefik* 
 * **Client**: *Firefox and Chromium  (pretty sure it doesn't matter ;-) )*

**Comment by muff1nman** [comment]
Thanks for the notice, however in the future please inform the developers in private about serious security issues before making a public github issue.

**Comment by turbomettwurst** [comment]
will do, thx for the quick fix :-)
