### ISSUE TITLE
DLNA server is visible but no songs are playable

### ISSUE THREAD

**Issue by glennguy** [airsonic/airsonic#768]
## Problem description
I can't get any sort of playback unsing DLNA. Can browse the files/songs no problem though. 

### Steps to reproduce
Install Airsonic (in docker container/synology)
Enable DLNA, set http address to http://192.168.1.4/airsonic (synology/docker host IP)
Browse DLNA in Windows (or other device) and try to play a file

## System information

 * **Airsonic version**: 10.1.1-RELEASE

 * **Operating system**: Synology Diskstation DSM 6.1.5. Docker using latest release of linuxserver.io airsonic container.
 * **Proxy server**:  None
 * **Client**: Windows 10/Firefox 62

## Additional notes
* **this is my docker run command:
```
sudo docker run \
  --network host \
  -v /volume3/docker/configs/airsonic:/config \
  -v /volume1/music:/music2 \
  linuxserver/airsonic
```

log did not say anything when attempting to access songs

I've read issue #761, however I can find the server across my network so I think this is not a duplicate issue.

**Comment by RuralHunter** [comment]
I have a similar problem and created #857 since this one is closed.
