### ISSUE TITLE
db/airsonic.data is very large

### ISSUE THREAD

**Issue by protist** [airsonic/airsonic#778]
## Problem description

I'm running out of room on my `/` partition, and traced high disc usage to `/var/airsonic/db/airsonic.data`, which is 4.9 G. Is that normal? I'm wondering why this file is so large.

### Steps to reproduce

1. Use Airsonic
2. Check disc usage

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017 (I haven't bothered upgrading to the latest version because I don't use LDAP.
 * **Operating system**: Linux, Raspbian (Debian)
 * **Proxy server**: None
 * **Client**: N/A.

## Additional notes

I have 11,119 music files in my library.

**Comment by fxthomas** [comment]
I've been seeing this for a while, and this even happened with Subsonic. The embedded HSQLDB database rarely cleans up after itself (equivalent to doing a `VACUUM` under Postgres) and gets fragmented over time.

I generally run this manually once in a while (download the HSQLDB 1.8.1 JAR from [here](https://sourceforge.net/projects/hsqldb/files/hsqldb/hsqldb_1_8_1/), and make backups before!):

    # Stop Airsonic
    systemctl stop airsonic.service

    # Cleanup DB
    sudo -uairsonic java -jar /usr/share/java/hsqldb-1.8.1.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/lib/airsonic/db/airsonic,user=sa,password='

    # Restart Airsonic
    systemctl start airsonic.service

It should be pretty easy to make Airsonic do this automatically, but I have never taken the time to do it.

**Comment by protist** [comment]
Thanks for the quick response. I'm using Debian and Tomcat, so I did a few things differently. I installed the latest version of HSQLDB instead, from the Debian repos. I also stopped Tomcat instead, and ran the java command as the user that owned the db file (`tomcat8`).
```
$ sudo apt-get install hsqldb-utils
$ sudo /etc/init.d/tomcat8 stop
$ sudo -u tomcat8 java -jar /usr/share/java/hsqldb-2.3.4.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/lib/airsonic/db/airsonic,user=sa,password='
Exception in thread "main" java.lang.IllegalArgumentException: invalid argrument --sql try:  java... org.hsqldb.util.DatabaseManagerSwing --help
	at org.hsqldb.util.DatabaseManagerSwing.main(Unknown Source)
```
I'm not sure what the error means. I tried several different things, but I'm not familiar enough with java to know how to fix it. Any advice would be appreciated! Thank you again.

**Comment by muff1nman** [comment]
> download the HSQLDB 1.8.1 JAR
not listening to directions, eh? This is actually pretty critical as hsqldb 2.x may make your database unusable by our 1.8.x client and is basically an entirely different database implementation.

**Comment by protist** [comment]
> not listening to directions, eh?

Guilty as charged. However, this was primarily because I had to modify the instructions anyway. As I stated in my previous reply, none of the three lines of code were appropriate for my install, so I was already forced to "not listen to directions".

Further (which I didn't mention previously), after downloading and extracting hsqldb, it was unclear what `/usr/share/java/hsqldb-2.3.4.jar` referred to above. There is a `*.jar` file at `/path/to/download/hsqldb/lib/hsqldb.jar`, but this didn't work (`Error: Unable to access jarfile /home/pi/hsqldb/hsqldb/lib/hsqldb.jar`, despite the path being correct).

hsqldb does bundle instructions on building itself, but it includes installing Ant… and then the question is which version to install? So… it seemed easier to install from my distro's repos, which would also prevent `make install` scattering files through my file system. But obviously I made a poor decision.

Would you have any tips on how to install `hsqldb-2.3.4.jar` easily? Cheers.

**Comment by muff1nman** [comment]
No need to install, you can run it from the same directory you downloaded it to, but you need to remove what you downloaded before and make sure to get a 1.8 version. The sourceforge download is a bit confusing, don't click for latest. Click down below where it mentions 1.8

**Comment by protist** [comment]
Thanks for the reply. Ah whoops, I quoted the wrong version number in my previous reply. I think I already tried what was suggested, but I just realised that `java -jar` didn't like the absolute path for some reason. Anyway, I tried again, but I'm getting a different error. I'll list all relevant commands, to be explicit.
```
$ rm -rf *
$ wget https://sourceforge.net/projects/hsqldb/files/hsqldb/hsqldb_1_8_1/hsqldb_1_8_1_3.zip/download
$ unzip download
$ sudo -u tomcat8 java -jar hsqldb/lib/hsqldb.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/lib/airsonic/db/airsonic,user=sa,password='
Error: Could not find or load main class org.hsqldb.util.SqlTool
```

**Comment by muff1nman** [comment]
Hm, well I know for sure this method should work and is a bit better because you use the exact version airsonic is using:

```
$ cp airsonic.war /tmp/
$ cd /tmp/
$ mkdir airsonic
$ cd airsonic
$ jar -xvf /tmp/airsonic.war 
$ cd WEB-INF/lib
$ java -jar hsqldb-1.8.0.7.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/home/andrew/.cache/airsonic/db/airsonic,user=sa'
```
```

**Comment by protist** [comment]
Thanks again @muff1nman. I again modified the command slightly, changing the username and database path, but I'm getting a different error now.
```
$ sudo -u tomcat8 java -jar hsqldb-1.8.0.7.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/lib/airsonic/db/airsonic,user=sa,password='
Var settings not of format NAME=var[,...]
```

**Comment by fxthomas** [comment]
This is suite strange. I've been using this for a long time without any
issues, although I remember having fiddled a lot with HSQLDB's
documentation at first.

Two things come to mind:
* You're not using exactly the same version as me (even though that's the
one used by Airsonic). Can you try with 1.8.1?
* Can you try using password="" at the end of the string?

Otherwise maybe db.view will be easier to work with (go to http://<Airsonic
URL>/db.view as an administrator user).

**Comment by fxthomas** [comment]
The JAR file you're executing had 1.8.0 in it though, right?

Have you checked that /var/lib/airsonic is the correct path for your
Airsonic installation? I used mine in the example, but yours may be
different (the path after inlineRc should point to the db/airsonic file in
your installation).

**Comment by protist** [comment]
>Have you checked that /var/lib/airsonic is the correct path for your Airsonic installation?

Arrgghhh… sorry for all the confusion. I started this thread with the correct path, but at some point I inserted the `lib/`. FWIW the final command that worked was the following:

```
sudo -u tomcat8 java -jar hsqldb-1.8.0.7.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/airsonic/db/airsonic,user=sa'
```

The command took 48:27 to run, and what a rollercoaster it was! The file started at 5.0G, it went down to 494M, then gradually rose again to 5.0G before rapidly plummeting to 8.0M right at the end! That's a crazy difference though, ~600-fold. Also, when I booted my system, it previously took tens of minutes before it was useable, due to high disk IO. Now tomcat/airsonic is working smoothly, and it's almost instantly useable after tomcat starts.

Thank you for all the help. I really appreciate it, as does my new smoothly-running system! It's definitely something that I'll do regularly now, but would be neat if airsonic could schedule this task by itself. Thanks again.

**Comment by fxthomas** [comment]
Yeah, that's one of the pain point of using HSQLDB instead of a real database. Mine was 3GB back when I was forced to look up the `CHECKPOINT DEFRAG` trick...

Regular uses of Airsonic won't increase disk usage a lot, but scanning media will rewrite the database from scratch, that apparently is never cleaned.

There's an option in HSQLDB 2.x (see [here](http://hsqldb.org/doc/guide/dbproperties-chapt.html#N15F9A)) where you can setup automatic defrags and checkpoints, but I was never able to enable it properly on our version, and gave up because of lack of time.

**Comment by protist** [comment]
> scanning media will rewrite the database from scratch

Ah okay, I see. I have Airsonic set to scan nightly, so that must be what it is.

> There's an option in HSQLDB 2.x

Is it possible to just trigger an external clean as per this thread, after the scan (or scheduled)?

**Comment by fxthomas** [comment]
> Is it possible to just trigger an external clean as per this thread, after the scan (or scheduled)?

For now I would just use a crontab or systemd timer to stop Airsonic, defrag, then restart it, right after the scheduled time for media scans.

If people want to dive into the code:

* One easy option is to issue `CHECKPOINT DEFRAG` after a scan. This won't fix the underlying issue (meaning, with scans disabled and given enough changes you'll end up in the same state), but this will fix it in 95% of cases.
* Fixing the underlying cause will require being able to change HSQLDB settings to automatically clean up the database. I'm still not sure if this is possible on the version we're using (1.8), but this is the ideal solution.

**Comment by protist** [comment]
Hi, I just thought I'd give a bit of an update, before I set up the cronjob. After 14 days, with daily scans, the database increased from 8.0M to 103M. What's odd is that after another one day, it went up to 256M. I didn't track it further, but I wonder if there's a geometric component to the increase?

Also, I'd previously been having several performance issues, which now seem fixed.

* After initially migrating from Libresonic to Airsonic, tomcat had been crashing regularly. I had to set up a daily job to restart it every morning. Since cleaning the database, this has no longer been a problem.
* Tomcat previously used ~284M of RAM (30% of my Raspberry Pi). It now uses 197M, a reduction of 30% the previous amount. (Although this could plausibly be related to something else updating.)

**Comment by protist** [comment]
One other quick question. As mentioned above, I'm always prompted to give the password. In the basic command:
```
$ sudo -u tomcat8 java -jar /path/to/hsqldb-1.8.0.7.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/airsonic/db/airsonic,user=sa'
sa's password:
```

If I add `password=`, I get an error. i.e.
```
$ sudo -u tomcat8 java -jar /path/to/hsqldb-1.8.0.7.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/airsonic/db/airsonic,user=sa,password='
Var settings not of format NAME=var[,...]
```

If I try password=""`, I still get the prompt. i.e. if I try the following:
```
$ sudo -u tomcat8 java -jar /path/to/hsqldb-1.8.0.7.jar --sql 'CHECKPOINT DEFRAG;' --inlineRc 'url=jdbc:hsqldb:file:/var/airsonic/db/airsonic,user=sa,password=""'
sa's password:
```

If I'm running a cron job, I'd obvious not want it to be interactive. Would you know of the proper syntax to run this command without interaction? Thanks again.

**Comment by fxthomas** [comment]
Hi!

So, answering in order:

* I also experienced regular crashes when my database crossed 1 or 2 GB,
but I was using Libresonic back then. I'm glad I'm not the only one!
* I did not track memory usage that closely, so I don't really know about a
decrease.
* I spent a lot of time trying to find the correct connexion line last
time... I suppose it changed between releases? That sucks quite a bit. If
you do find the correct incantation, please share it here!
