### ISSUE TITLE
HTML Player misidentifies media files after upgrade to 10.1.2

### ISSUE THREAD

**Issue by mcepl** [airsonic/airsonic#779]
## Problem description

When I have upgraded standalone Airsonic to 10.1.2 (from 10.1.1; running on CentOS 7 with OpenJDK Java 1.8.0_181 from RH packages), suddenly web player started to misbehave.

When the queue is empty and nothing happens, it looks correctly:

![snimek z 2018-08-10 09-09-03](https://user-images.githubusercontent.com/198999/43943805-201c13ca-9c7d-11e8-8903-7b2f3ec1d817.png)

Web player displays correctly, and seems to be ready to play. When I selected a song to be played, however, even after waiting, no sound is played and only URL is shown over the player

![snimek z 2018-08-10 09-11-56](https://user-images.githubusercontent.com/198999/43943897-79ed0d00-9c7d-11e8-8856-01913fb3d0c4.png)

Console displays
```
Nelze přehrát média. Chybí dekodéry pro požadované formáty: video/mp4 playQueue.view
```
(in Czech it means "Media cannot be played. Missing decoders for the required formats: video/mp4 playQueue.view", which doesn't make sense ... the song is (according to ffplay)
```
Stream #0:0: Audio: mp3, 48000 Hz, stereo, s16p, 183 kb/s
    Metadata:
      encoder         : LAME3.100
```
The URL is ``http://192.168.0.5:8080/airsonic/stream?player=2&id=154`` (my AirSonic runs on ``http://192.168.0.5:8080/airsonic/`` obviously). When I click large blank area opens over the bottom part of the screen and music starts playing.

![snimek z 2018-08-10 09-14-02](https://user-images.githubusercontent.com/198999/43943996-c1ce4aee-9c7d-11e8-912c-36bbd146d44c.png)

It completely covers any controllers of the player, so the player is basically unmanageable.

## System information

 * **Airsonic version**:  10.1.2-RELEASE – 28 July 2018
 * **Operating system**: CentOS Linux release 7.5.1804 (Core)
 * **Proxy server**:  None
 * **Client**: Firefox 61.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0) running on openSUSE Tumbleweed (MozillaFirefox-61.0.1-1.1.x86_64)

**Comment by jooola** [comment]
I don't think this has something to do with the upgrade from 10.1.1 to 10.1.2. This version bump was only a security fix for ldap.

**Comment by mcepl** [comment]
Yeah, it was some kind of fluke.
