### ISSUE TITLE
Save/Remember/Bookmark Track/Podcast/Audiobook position

### ISSUE THREAD

**Issue by senguendk** [airsonic/airsonic#786]
## Feature request

It would be great if it were possible to bookmark (maybe even automatically) the current position of a track/podcast/audiobook that is playing. I am aware that some clients - such as DSub - can do this; however, it would be great if the webinterface would also support this kind of functionality.

**Comment by MidnightSnowleopard** [comment]
Agreed, would very much appreciate this functionality even in a very basic form
