### ISSUE TITLE
Can't access settings tab through reverse proxy

### ISSUE THREAD

**Issue by kauron** [airsonic/airsonic#789]
## Problem description

Can't access settings tab through reverse proxy. When clicked, the button does nothing, and no event is logged in the About tab. When control clicking or opening in a new tab, the tab opens without the rest of the surrounding interface. This does not happen when accessing the web interface from `localhost:8080`.

### Steps to reproduce

1. Install Airsonic and nginx
2. Configure nginx reverse proxy according to [this guide][2].
3. Start the `nginx` and `airsonic` services
4. Login to the web interface through the proxy (through https)
5. Click the settings button/tab: the interface doesn't change.

## System information

 * **Airsonic version**: 10.1.2-RELEASE – July 28, 2018 (installed from [AUR][1])
 * **Operating system**: Arch Linux
 * **Proxy server**: nginx 1.14.0
 * **Client**: chromium 68.0.3440.106, firefox 61.0.2

## Additional information

nginx configuration:

```
server {
      listen 443 ssl;
      server_name <domain>;

      error_log  /var/log/nginx/transfer-error.log warn;
      access_log  /var/log/nginx/transfer-access.log;

      ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem; # managed by Certbot
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

      # enable session resumption to improve https performance
      # http://vincent.bernat.im/en/blog/2011-ssl-session-reuse-rfc5077.html
      ssl_session_cache shared:SSL:50m;

      # Airsonic reverse proxy
      location /airsonic {
          proxy_set_header X-Real-IP         $remote_addr;
          proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Host  $http_host;
          proxy_set_header Host              $http_host;
          proxy_max_temp_file_size           0;
          proxy_pass                         http://127.0.0.1:8080;
          proxy_redirect                     https:// https://;
      }

      location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /var/lib/letsencrypt/;
        default_type "text/plain";
        try_files $uri =404;
      }
}

```
[1]: https://aur.archlinux.org/packages/airsonic/
[2]: https://airsonic.github.io/docs/proxy/nginx/

**Comment by jooola** [comment]
Use your browser console to get more details of this bug.

**Comment by Yetangitu** [comment]
Check whether your browser warns about blocking insecure scripts:

![image](https://user-images.githubusercontent.com/2754838/44628086-dc5b4880-a939-11e8-9513-2d0c7caa7917.png)

Enabling these 'insecure' (as in loaded through a http://... url) scripts makes the thing work again. The root cause of this problem seems to be some part of Airsonic using absolute URL's to refer to parts of the UI. Airsonic itself probably connects to the revese proxy through http (i.e. 'insecure') whereas the proxy only offers encrypted access to the world. Loading unencrypted content within an encrypted site is 'insecure' and as such blocked by default.

Here's one of the culprits, fresh from the inspector:

![image](https://user-images.githubusercontent.com/2754838/44628195-92736200-a93b-11e8-9c21-ba777cd7abe7.png)

For now I'd say just enable those 'insecure' scripts. The solution is found somewhere in the myriad of code which is Airsonic and all its dependencies. While solving this problem may I suggest also adding an option to block all third-party content? An observant reader will have noticed the uBlock shield in vthe first image showing it blocked 9 resources from loading. This is because I don't see why Google needs to get a hit when I play a song. I can live without reCaptcha (which I guess is what Google is used for) so I'd like to have the option of keeping everything in-house. If I find some time I'll have a look at these problems one of these days. Don't hold your breath though, time is a finite and stressed resource.

**Comment by kauron** [comment]
It was exactly that. Thank you. I was concerned that the setting editing (password changing and so on) was being sent over http and not https when enabling the unsafe sources.

When loading the other tabs, the request was done over https, but the first request to load the settings tab was done over http (`http://<domain>/airsonic/musicFolderSettings`), then redirected to https and all other elements are loaded through https.

![Console log](https://user-images.githubusercontent.com/9221197/44628390-13802880-a93f-11e8-888a-31545fa4197d.png)

![Network request header](https://user-images.githubusercontent.com/9221197/44628404-72de3880-a93f-11e8-8a4f-3b7a11b84410.png)

**Comment by Yetangitu** [comment]
Here's a real solution to this problem: set `server.use-forward-headers=true` by adding `-Dserver.use-forward-headers=true` to the startup script or the _systemd_ unit file. This makes _Tomcat_ use the data found in `X-Forwarded-Proto` and `X-Forwarded-For` (which you already added to the _nginx_ site configuration). This way all content is served using _https_ and the 'insecure location' problem does not occur.

When using a startup script (e.g. when using _sysvinit_ the following works (showing only the relevant part):

```
exec ${JAVA} -Xmx${AIRSONIC_MAX_MEMORY}m \
  -Dserver.address=${AIRSONIC_HOST} \
  -Dserver.contextPath=${AIRSONIC_CONTEXT_PATH} \
  -Dserver.port=${AIRSONIC_PORT} \
  -Dserver.use-forward-headers=true \
  -Dairsonic.port=${AIRSONIC_PORT} \
  -Dairsonic.home=${AIRSONIC_HOME} \
  -Dairsonic.defaultMusicFolder=${AIRSONIC_DEFAULT_MUSIC_FOLDER} \
  -Dairsonic.defaultPodcastFolder=${AIRSONIC_DEFAULT_PODCAST_FOLDER} \
  -Dairsonic.defaultPlaylistFolder=${AIRSONIC_DEFAULT_PLAYLIST_FOLDER} \
  -Djava.awt.headless=true \
  -jar airsonic.war
```

When using a systemd unit file use somthing like this:

```
[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/srv/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/srv/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx200m"
Environment="AIRSONIC_HOME=/srv/airsonic"
Environment="HOST=127.0.0.1"
Environment="PORT=8080"
Environment="CONTEXT_PATH=/"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/default/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.context-path=${CONTEXT_PATH} \
          -Dserver.address=${HOST} \
          -Dserver.port=${PORT} \
          -Dserver.use-forward-headers=true \
          -Djava.awt.headless=true \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=airsonic
Group=airsonic

[Install]
WantedBy=multi-user.target
```

For more info on this subject see the Spring Boot documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-use-tomcat-behind-a-proxy-server

**Comment by ABotelho23** [comment]
How would someone do this using the Docker image and have it be a persistent change that also survives updating the image?

**Comment by Yetangitu** [comment]
I don't use the Docker image so I can not give a definite statement on the subject. What I do know is that updating docker images is a known problem:

https://github.com/moby/moby/issues/3285

The suggested `docker update` command does not seem to support changing the environment or the startup command. You can view the container configuration parameters using `docker inspect <container_id>`, look for `Env' and `Cmd`.

**Comment by Yetangitu** [comment]
An alternative approach would be to inject startup parameters to the container. As to whether that is possible with this image I do not know.

**Comment by kauron** [comment]
You can pass Java options when creating the container with `docker run` with the env variable `JAVA_OPTS`, as described in the [airsonic docs](https://airsonic.github.io/docs/install/docker/#advanced-configuration).

**Comment by ABotelho23** [comment]
In case curious, this is what I ended up using for my Docker run command

`sudo docker run --user=1004:1001 --name=airsonic -v /home/airsonic/data:/airsonic/data -v /home/airsonic/music/link:/airsonic/music -v /home/airsonic/playlists:/airsonic/playlists -v /home/airsonic/podcasts:/airsonic/podcasts -e JAVA_OPTS="-Xmx200m -Dairsonic.home=/airsonic/data -Dserver.context-path=${CONTEXT_PATH} -Dserver.use=ProxyPreserveHost -Dserver.use-forward-headers=true -Djava.awt.headless=true -jar ${JAVA_JAR} $JAVA_ARGS" -p 4040:4040 -d airsonic/airsonic`

Obviously things like --user and the -v volumes will be different, but the `-e JAVA_OPTS="-Xmx200m -Dairsonic.home=/airsonic/data -Dserver.context-path=${CONTEXT_PATH} -Dserver.use=ProxyPreserveHost -Dserver.use-forward-headers=true -Djava.awt.headless=true -jar ${JAVA_JAR} $JAVA_ARGS" -p 4040:4040 -d airsonic/airsonic` is the important part.

and I just had to add `proxy_set_header X-Forwarded-Proto $scheme;` to the subdomain's config file for NGINX

**Comment by andyforceno** [comment]
The suggestion to add "java -Dserver.use-forward-headers=true" doesn't work for me. I'm running Airsonic behind an nginx reverse proxy. My browser (Firefox) is also not warning me about blocking mixed or insecure content. No errors in the console. It seems fairly random, once a month or so the settings button disappears, and at some point it comes back.
