### ISSUE TITLE
intermittent web player scrobbles flood last.fm

### ISSUE THREAD

**Issue by fejjj** [airsonic/airsonic#791]
## Problem description

using the web player my lastfm gets flooded with scrobbles sometimes. 

## System information

 * **Airsonic version**: 10.1.2-RELEASE – July 28, 2018
 * **Operating system**: ubuntu-mate 18.04
 * **Proxy server**: nginx/1.14.0
 * **Client**: google chrome (windows 7)
## Additional notes

![image](https://user-images.githubusercontent.com/39070602/44832918-fc1c9600-abf1-11e8-913a-0f88b4c2d06f.png)

**Comment by fejjj** [comment]
i was also having trouble with the web player queue getting stopped after 1-2 tracks, which seemed related.  the problem seems to have stopped when i disabled transcoding of flacs.

**Comment by heyarne** [comment]
The scrobbling issue is a known one. The cause of it is described [here](https://github.com/airsonic/airsonic/issues/776).

**Comment by muff1nman** [comment]
Marking as duplicate.
