### ISSUE TITLE
Subsonic API broken in 10.2.0-SNAPSHOT compiled 8/29/2018

### ISSUE THREAD

**Issue by surfrock66** [airsonic/airsonic#793]
## Problem description

Airsonic works perfectly in the web browser, but apps using the API (DSub in my case) are not able to load the library.  In the app, testing the connection to the server reports as ok, but the contents of the library remain unavailable.

### Steps to reproduce

1. Compile airsonic from source
2. Confirm library is intact by browsing the web interface
3. Connect to the server from DSub; in the "server" setup click the "Test connection" and see "Connection is ok" message
4.  Attempt to browse the library or playlists; have the app time out with the message "A network error occurred"

## System information

 * **Airsonic version**: 10.2.0-SNAPSHOT – August 29, 2018; Apache Tomcat/8.5.27, java 1.8.0_181, Linux 
 * **Operating system**: Ubuntu Server 18.04.1
 * **Proxy server**: None
 * **Client**: Chrome on Debian Buster, also DSub 5.4.2 on LineageOS 15.1 on Nexus6P

**Comment by biconou** [comment]
@surfrock66 

Could you post a copy of your server log file ?

**Comment by surfrock66** [comment]
To be honest I rebuild from source weekly and it's working now, I forgot I submitted this bug.  It's been working for about 3 weeks.
