### ISSUE TITLE
Update album dates after updating song date tags

### ISSUE THREAD

**Issue by holocronweaver** [airsonic/airsonic#797]
## Problem description

After updating the date id3 tags on a bunch of song files, I started a media scan in Airsonic. After the scan concluded I noted the corresponding album dates in Airsonic were not updated.

### Steps to reproduce

* Add album to Airsonic.
* Update id3 `date` tags on all tracks in album.
* Perform a media scan and database cleanup in Airsonic.
* Note that the album in Airsonic still has the old date.

## System information

 * **Airsonic version**: 10.1.2-RELEASE – July 28, 2018
 * **Operating system**: Ubuntu 16.04
 * **Proxy server**: None
 * **Client**: Firefox 61.0.1

**Comment by holocronweaver** [comment]
Still an issue, not sure what 'stale' indicates.

**Comment by avlouis** [comment]
I have seen this issue on my personal server.  However, when trying to replicate on a test server, I cannot replicate the behavior.  Album years get updated correctly.  I am going to keep working on replicating the issue in a test environment.  My initial examination of the code (long-time user, looking to become a contributor) leads me to believe that existing files may not update on a re-scan because the MediaFileService pulls the file's info from memory cache or the database, resorting to filesystem access only when the memory cache and database lookups fail.

**Comment by holocronweaver** [comment]
Would be nice if there was a way to rescan the library to force an update, and avoid using any kind of cache as aviouis mentioned.

**Comment by eharris** [comment]
When you updated the tags on the files, did you also update the modification timestamp of the file? Some tools give you the option to preserve the original mtime of the file.  The mtime changing is how Airsonic detects if a file needs to be rescanned.

**Comment by holocronweaver** [comment]
I have confirmed that Quod Libet is updating the file modification timestamp to the current time, but Airsonic is not updating its database even after a cleanup + scan. For example, I changed all the dates in an album from 2004 to 1977 (the original release date rather than the re-release date), but Airsonic still reports the 2004 date.

**Comment by eharris** [comment]
I think that the directory tree containing the changed files also has to have it's timestamp updated, which normally occurs on most filesystems.

There is also a workaround that has been included from #607 (also related to #359), although it would be nice if that was exposed in a more user-friendly manner.

**Comment by holocronweaver** [comment]
I normally use **Quod Libet / Ex Falso** to modify tags, and apparently they update file modification but not directory modification times. I tried using **EasyTAG** instead and the directory modification times changed as expected.

I will try out the `IgnoreFileTimestamps` property in the `lilbresonic.properties` file as mentioned in #607.

Many thanks!

**Comment by tesshucom** [comment]
Looks like it's resolved in #607. Close this.
If you encounter any related issues, please report a new one.
