### ISSUE TITLE
user settings not saved

### ISSUE THREAD

**Issue by lbesnard** [airsonic/airsonic#799]
## Problem description
as admin user, everytime I try to add
"User is allowed to change personal settings and password" to a new user and click save, the option is actually not being saved 90% of the time. And if it does, it will disappear eventually.

### Steps to reproduce
1. connect as admin
2. select an existing user in settings
3. tick "User is allowed to change personal settings and password", or and any other boxes
4. load user information again. Settings lost.

## System information
airsonic 10.1.1
Linux debian

**Comment by eharris** [comment]
Your list of reproduction steps results in as-expected behavior.  You must click the "Save" button in order for any changes to be saved.

As this is reported against a pretty old version and has had no updates, closing.
