### ISSUE TITLE
WebPlayer audio glitches and hangs

### ISSUE THREAD

**Issue by zrav** [airsonic/airsonic#806]
## Problem description

https://www.reddit.com/r/airsonic/comments/9ivb9h/glitches_in_music_playback/ 

I and others are experiencing frequent audio glitches during playback using the Airsonic web player. The glitches are short, and sound like a corrupt mp3 frame. They appear randomly, playing the same part of the track again does not trigger the glitch again. The original files on disk are perfectly fine.

Additionally, playback often hangs at the end of the track. The song already finished, but the player shows 1-2 seconds missing and hangs. Looking at "top" on the server shows that during the hang ffmpeg is transcoding the file again and again.

From my outside perspective this looks like a time sync / file duration problem.

The problem appeared roughly half a year ago, possibly with an Airsonic version upgrade.

### Steps to reproduce

Setup Airsonic, feed it with files and play back with transcoding. Listen to it for 15 minutes.
\* Additional yet unknown steps/conditions might be necessary to trigger the problem.

## System information

 * **Airsonic version**: 10.1.2
 * **Operating system**: Ubuntu 18.04 in LXD container on Ubuntu 18.04 host.
 * **Proxy server**: none
 * **Client**: WebPlayer using current FireFox and Chrome

**Comment by stanelie** [comment]
I am experiencing the same audio glitches/skipping artifacts while streaming perfectly fine audio files over the web player. Interestingly, if I rewind a bit and go over the same part of a song, I hear the same glitch.

I do not experience this issue with Libresonic, using the same source audio files from the same folder on the same server.

**Comment by FoxBob79** [comment]
Same problem here! Playing flac files over the web-player is impossible. Music stops after ~90 sec...

**Comment by Yetangitu** [comment]
https://github.com/airsonic/airsonic/issues/685

**Comment by yannickbarbeaux** [comment]
Same problem for me with Airsonic 10.6.2, frequent glitches with mp3 or flac.If I rewind a bit and go over the same part of a song, I also hear the same glitch at the same timing. Of course, I have verified the files and they play flawlessly in VLC.
They playback also sometimes stops, at the end of a song or sometimes in the middle. I cannot resume playing, must skip the song.
