### ISSUE TITLE
Status icon for Users

### ISSUE THREAD

**Issue by YondaimeCB** [airsonic/airsonic#817]
Hi,

Is there a way to remove the "Status" icon for all users except for the Admin?

Thanks!

**Comment by muff1nman** [comment]
Can you expand on what icon you are referring to?

**Comment by eharris** [comment]
This looks like it has been abandoned, so can this be closed?  Can always reopen later if more information is provided.

**Comment by YondaimeCB** [comment]
Hi Evan,

Sorry for the late response, yes all good, happy with airsonic ☺

Thank you!

Regards,
Carlos
