### ISSUE TITLE
Can't recover password due to deprecated reCaptcha V1

### ISSUE THREAD

**Issue by btuso** [airsonic/airsonic#818]
## Problem description

*The recover password page uses deprecated reCaptcha V1, which makes recovering your password impossible.*

<img width="553" alt="recaptchav1" src="https://user-images.githubusercontent.com/1541954/47585308-46d93680-d933-11e8-8270-a73220d4033f.png">

### Steps to reproduce

1. *Connect to an Airsonic instance*
2. *Press the "Forgot your password" link*

## System information

 * **Airsonic version**: *10.1.2-RELEASE*
 * **Operating system**: *Linux, Debian*
 * **Proxy server**: Nginx
 * **Client**: *Airsonic Web via Chrome 69*

**Comment by jooola** [comment]
Wait for next release or build from master:
https://github.com/airsonic/airsonic/pull/774
