### ISSUE TITLE
Downsample on mobile connection

### ISSUE THREAD

**Issue by h3man1** [airsonic/airsonic#831]
## Problem description

I use airsonic on my server and dsub as my Android client. Both are up to date.

What I would like to achieve is to direct play my music if I'm connected to WiFi and to downsample my music to 320kbps mp3 if I'm on a mobile network.

How to do this?

In dsub I can set up a maximum Bitrate for WiFi and mobile but these settings have no effect on airsonic. No matter what I set it to it will always direct play.

In airsonic I can only set per client limits not per connection obviously. But even if I do that only mp3 files get downsampled and flac files get direct played. I have to set up the flac transcoder to transcode to mp3 320. But this transcodes every flac streamed to my Android and is actually not what I would like.

Any ideas if what I want is actually possible?

## System information

 * **Airsonic version**: *10.1.2*
 * **Operating system**: *Debian 9*
 * **Client**: *DSub*

**Comment by muff1nman** [comment]
Have you asked the dsub folks (@daneren2005)?

**Comment by gerroon** [comment]
Downsampling in Dsub works for me, I just set them in Dsub and it just works. Maybe a an Android version issue?
