### ISSUE TITLE
Long website loading after server restart

### ISSUE THREAD

**Issue by bigfoot50** [airsonic/airsonic#835]
Hi, 
I installed airsonic standalone WAR on an Linux CentOS7 virtual machine with a apache proxy on the same machine.
After each server reboot it take so long, that the apache proxy send a time out and high CPU peak, when I want to login. With the Port in the address it takes also long, but no server time out.
After that procedure I can login normal with the Proxy (without the port in the address).

The server restart is most 2h again before I want to login first time after restart, so all Services should be run.

After login all side and menu loadings also slow with a high CPU utilization at that time.

How can I speed up all?

**Comment by tmowbray** [comment]
Having same issue on Ubuntu 18.04...

**Comment by bigfoot50** [comment]
After change to oracle Java now it´s a bit faster, but high CPU usage for each click still there.
