### ISSUE TITLE
Unable to login with Chrome browser

### ISSUE THREAD

**Issue by kk7ds** [airsonic/airsonic#836]
## Problem description

I am unable to log into airsonic 10.1.2-RELEASE using Chrome 70.0.3538.102. Using the docker image as a way to replicate (it happens with the bare war download as well), I hit the login page, try admin/admin and immediately get redirected to a 403 page that says:

```
Status | 403
-- | --
Error | Forbidden
Message | Could not verify the provided CSRF token because your session was not found.
Path | /login
Time | Thu Nov 29 15:30:07 GMT 2018
Exception |  
Java version | Oracle Corporation 1.8.0_171
Operating system | Linux 4.4.0-70-generic
Server | Apache Tomcat/8.5.23
Memory | Used 108 of 237 MB
```
On a hint from a redditor, I tried whatever Safari browser was on my system and it works fine. He said Firefox works for him, but Chrome does not.

### Steps to reproduce

1. docker run -p 4040:4040 -d airsonic/airsonic
2. Chrome to http://host:4040
3. Login as admin/admin

## System information

 * **Airsonic version**: 10.1.2-RELEASE
 * **Operating system**: MacOS Sierra
 * **Proxy server**: None
 * **Client**: Chrome 70.0.3538.102

**Comment by jooola** [comment]
@kk7ds I think I alreay faced this issue, try to enable cookies, this should fix your problem.
You can add an exception for airsonic.

**Comment by kk7ds** [comment]
I don't have cookies disabled, and indeed have a bunch of cookies set for the host/url that I'm accessing airsonic from.

**Comment by muff1nman** [comment]
Running with 70.0.3538.67 works fine against the master branch. Can you try ensuring that you don't have something cached by dong a hard refresh in chrome (control - shift - r).

**Comment by kk7ds** [comment]
Yep, Ctrl-Shift refresh was the first thing I tried since it mentioned a problem with the session. I also tried private browsing to rule out any other cookies I might have for the host. Note that this was the absolute first interaction I had with airsonic on this machine or any, so it's not like I had previously logged in, gotten a stale session cookie and then later had trouble logging back in again. This was step 2 after "start airsonic" in my attempt to see if airsonic is what I'm looking for.

Anyway, after poking around via Safari I'm not really pursuing it anymore. I filed this to try to be a good citizen and capture the error before I moved on, especially since the other reditor mentioned the same experience and all the other browsers I tried worked fine.

Feel free to close if you think it's just something fluke-esque on our installs somehow.

**Comment by jvoisin** [comment]
I sometimes can reproduce this on my instance. Refreshing the page and logging in again fixes it, but it's still annoying.

**Comment by jvoisin** [comment]
This is a duplicated of #1047.
