### ISSUE TITLE
Airsonic in Tomcat behind Nginx Reverse Proxy via HTTPS

### ISSUE THREAD

**Issue by jangrewe** [airsonic/airsonic#838]
## Problem description

This is not really a "problem", but rahter me sharing how i got Airsonic to work in Tomcat behind Nginx without having to fiddle with the `context-path`. This is on Debian 9 (stretch) with the nginx-extras package, which includes all the modules i needed for this.

### Steps to reproduce

Configure Nginx like you usually would and then use this as the base location:
```
location / {
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  https;
    proxy_set_header X-Forwarded-Host   $http_host;
    proxy_set_header Host               $http_host;
    proxy_max_temp_file_size            0;
    proxy_pass                          http://127.0.0.1:8080/airsonic/;
    proxy_redirect                      http://$host/airsonic https://$host;
    proxy_cookie_path                   /airsonic /;
    rewrite                             ^/airsonic(.*)$ $1 last;
    subs_filter_types                   text/html;
    subs_filter                         '/airsonic' '';
}
```

For me this takes care of rewriting all the forms, cookie paths, etc. YMMV.

**Comment by muff1nman** [comment]
Thanks for the note. Feel free to send a PR to the docs (https://github.com/airsonic/documentation).
