### ISSUE TITLE
LDAP URL and whitespace / special characters

### ISSUE THREAD

**Issue by NeXsGen** [airsonic/airsonic#840]
## Problem description

Having users in a OU that contains a space causes an exception in the springer security ldap module. According to rfcs, spaces can be escaped with %20 in a LDAP url, but upon trying an ldap query the module still fails. 
Example: ldap://ad.domain.com:389/OU=Test OU,DC=ad,DC=domain,DC=com

### Steps to reproduce
Create an OU containing a space, add a test user, adjust ldap url to point to newly created ou, restart airsonic, attempt to authenticate, check log and watch spring security go down in a blaze of glory.

 * **Airsonic version**: 10.1.2-RELEASE – July 28, 2018
 * **Operating system**: CentOS 7
Note: the filter works fine with groups containing spaces.

**Comment by muff1nman** [comment]
This might be a good candidate to raise with the upstream spring security folks (unless we're configuring it wrong).
