### ISSUE TITLE
Surefile test fails since commit "archetype code for rest api integration tests"

### ISSUE THREAD

**Issue by EvilDragon** [airsonic/airsonic#842]
## Problem description

I am having issues to compile Airsonic since commit 6b4874f33ce92e14f102b6bf216ca5ea207fe780.
The previous PR still works fine.

The failure is the following:

`Results :

Failed tests: 
  AirsonicRestApiJukeboxIntTest>AbstractAirsonicRestApiJukeboxIntTest.jukeboxStartActionTest:202->AbstractAirsonicRestApiJukeboxIntTest.lambda$playListItem1isCorrect$2:168 JSON path "$.subsonic-response.jukeboxPlaylist.entry[0].title" expected:<01 - Gaspard de la Nuit - i. Ondine> but was:<02 - Gaspard de la Nuit - ii. Le Gibet>
  AirsonicRestApiJukeboxLegacyIntTest.jukeboxStartActionTest:49->AbstractAirsonicRestApiJukeboxIntTest.jukeboxStartActionTest:202->AbstractAirsonicRestApiJukeboxIntTest.lambda$playListItem1isCorrect$2:168 JSON path "$.subsonic-response.jukeboxPlaylist.entry[0].title" expected:<01 - Gaspard de la Nuit - i. Ondine> but was:<02 - Gaspard de la Nuit - ii. Le Gibet>

Tests run: 99, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Airsonic 10.2.0-SNAPSHOT:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [  1.388 s]
[INFO] Subsonic REST API .................................. SUCCESS [  8.326 s]
[INFO] Sonos API .......................................... SUCCESS [  8.807 s]
[INFO] Airsonic Main ...................................... FAILURE [07:27 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:47 min
[INFO] Finished at: 2018-12-06T21:12:09+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project airsonic-main: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/airsonic/airsonic/airsonic-main/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :airsonic-main
`
Let me know if you need the full log.

I'm following the official guide to build it from source and tried it on two different PCs (both running ArchLinux, maybe that's the issue).

openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b26)
OpenJDK 64-Bit Server VM (build 25.192-b26, mixed mode)

As far as I understand, that commit added tests - and the playlist test fails because it receives the wrong title...?
I've never had any playlist issues on Airsonic installations, so maybe it's just the test that's having issues on my system?

**Comment by muff1nman** [comment]
I believe this is resolved in #844
