### ISSUE TITLE
/etc/sysconfig/airsonic not obeyed

### ISSUE THREAD

**Issue by stanelie** [airsonic/airsonic#848]
Hi.

I was trying to have Airsonic running at the root of my webserver. I read that you need to rename the airsonic.war package to ROOT.war to achieve this. I then tried to adjust /etc/sysconfig/airsonic to match the new file name as per the documentation (last line of https://airsonic.github.io/docs/install/war-standalone/#systemd). It didn't work, it looks like the /etc/sysconfig/airsonic file is completely ignored, or I don't know how to reload the service so that it takes it into account.

I was able to fix my issue by modifying /etc/systemd/system/airsonic.service to match what I wanted.

Maybe the docs should be corrected?

**Comment by jooola** [comment]
You are mixing 2 different documentation, the one for Tomcat and the one for standalone.
What needs to be changed is the context-path option for the standalone installation.
Renaming the war file to ROOT is only for tomcat installations.

**Comment by stanelie** [comment]
Hum...
When running the standalone version, the console output mentions tomcat 8.5 somewhere in there, so, I assumed the standalone version was a repackaged Tomcat.

**Comment by jooola** [comment]
Yes, it is using tomcat-embed, but the configuration of this one isn't the same as running the complete service.

**Comment by jooola** [comment]
I personally don't use the /etc/sysconfig/airsonic file, and configure everything within the service file.
It keeps things clean.

**Comment by stanelie** [comment]
Regardless, trying to follow the docs and modifying /etc/sysconfig/airsonic had no effects. Maybe I didn't have to rename the package to ROOT.war, but I definitely had to modify /etc/systemd/system/airsonic.service for things to work.

**Comment by jooola** [comment]
Could you please paste your configuration please ? OS, Versions,
configuration files ?

**Comment by stanelie** [comment]
I am using Ubuntu 16.04.5 LTS.

Here is my /etc/systemd/system/airsonic.service file :
```
[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/var/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/ROOT.war"
Environment="JAVA_OPTS=-Xmx700m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=8080"
Environment="CONTEXT_PATH="
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/sysconfig/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.context-path=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=airsonic
Group=airsonic

[Install]
WantedBy=multi-user.target
```
Do you need other infos?

**Comment by jooola** [comment]
You didn't see the note at the bottom of the page.

When your are using a Debian derived system such as Ubuntu, you need to store the `/etc/sysconfig/airsonic` file under `/etc/default/airsonic`.
![image](https://user-images.githubusercontent.com/19195485/49893017-ba36f900-fe4a-11e8-94c5-4491ad54c792.png)

**Comment by stanelie** [comment]
Yes I did.
For sake of clarity and to not confuse the issue, I didn't mention it in the first post, but I did put that file in /etc/default on my Debian based Ubuntu system. No effect.

**Comment by jooola** [comment]
Ok, though it was that... Did you reloaded the systemctl daemon ?
`sudo systemctl daemon-reload`

**Comment by jooola** [comment]
Let's not spam the github bug tracker, could you join one of the community channels on IRC or Matrix ?

**Comment by stanelie** [comment]
`sudo systemctl daemon-reload` had no effect

**Comment by jooola** [comment]
@stanelie Did you managed to fix this issue ?

**Comment by stanelie** [comment]
Kinda, as stated in the first post. But I went back to libresonic because of other issues I was having.

**Comment by jvoisin** [comment]
I didn't touch the `/etc/sysconfig/airsonic` file either: everything in the unit file does the job.
