### ISSUE TITLE
Feature request: support rfid scanner to select songs

### ISSUE THREAD

**Issue by tobiasnix** [airsonic/airsonic#851]
Would be nice to have support for rfid-scanner and ID management. If the box is in jukebox mode it would give easy access to the media collection eg for kids.

Functionality needed: 
* Scan a RFID card
* Assign / remove scanned ID to a song, playlist, video, ...
* Play a song, playlist, video, ... whatever was connected to that ID.

**Comment by heyarne** [comment]
You can probably hack this together using the REST api. The relevant parts can be read about [here](http://www.subsonic.org/pages/api.jsp#jukeboxControl).

**Comment by jooola** [comment]
What about QR codes linking to some resources ?

**Comment by heyarne** [comment]
> What about QR codes linking to some resources ?

Yes; this is why I suggested the REST api. Playing a song can basically be done by calling http://your-server/rest/stream?f=json&v=1.15.0&u=username&p=password&c=some-client-name. Other functionality could be implemented in a similar way.

**Comment by jvoisin** [comment]
I do agree with @heyarne (except for the part about sending passwords in cleartext in GET): QR codes and RFID stuff are a bit out of scope for the core of a media-streamer. This is exactly why there is an API, to allow people to plug crazy things to it.

**Comment by heyarne** [comment]
> except for the part about sending passwords in cleartext in GET
Don't get me wrong: I don't think that's a good idea, but unfortunately that's the current status of the REST API. You can see #69 for more info.

**Comment by jvoisin** [comment]
Ouch :/

**Comment by jvoisin** [comment]
I don't think that it's worth keeping this issue open, since odds are that nobody will implement this.
Feel free to prove me wrong, I'll be happy to review your pull-request.
