### ISSUE TITLE
Remove UI dependency to externally hosted static assets

### ISSUE THREAD

**Issue by zrav** [airsonic/airsonic#853]
## Problem description

Currently Airsonics web-UI makes use of Google hosted font files. This causes problems in offline / airgapped networks.

### Steps to reproduce

Disconnect network from internet, access and use the Airsonic web-UI. Notice long delays, as the browser waits for the asset requests to time out.

## System information

 * **Airsonic version**: v10.1.2

## Additional notes

There's no reason these files couldn't be provided by Airsonic itself.

**Comment by jooola** [comment]
Haha, this one has a big history ^^.

Duplicate of #174 #399

**Comment by jooola** [comment]
Could be cherry picked from https://github.com/Libresonic/libresonic/pull/173
