### ISSUE TITLE
Feature request: shuffle filter exclusions

### ISSUE THREAD

**Issue by sean-v8** [airsonic/airsonic#854]
Current stock subsonic user here, considering making the jump if some help can be provided on a rather niche issue... have made some other minor personal modifications to the subsonic source but I'm not very versed in java web frameworks, been having trouble figuring out where to start with this one..

I have a decently big collection (~80,000 songs), largely comprised of live concert recordings (~80%), which makes the main shuffle feature pretty much useless as the function tends to pull only from these folders (seems to be significantly moreso than the statistically-expected ~80% of the time)

I could:
- split my collection, but my folder is auto-sorted into a single folder as I add things to an iTunes library before they become accessible through subsonic, would like to keep that functionality (I know, I know, "just stop using iTunes" but versions up to 10.7 are perfect for quickly navigating and jamming along to my live collections, have tried many others and nothing comes close, subsonic included... for listening purposes I stick to subsonic)
- shuffle only by genres that don't tend to have these live shows, but sometimes it's cool to mix things up

So, I noticed the work on #134 which seems to add ways to filter a shuffle by various fields, I guess what I'd be asking for is an extra "exclusions" option, ideally allowing multiple regex matches to check against various fields... in my case it would be something like:

- all albums that begin with yyyy-mm-dd
- the "Radio" and "Podcast" genres

I guess one other solution for my problem could be to enhance the "Media Folder" setup to allow for subdirectory exclusions, idk if that would be a more straightforward/useful route..

I realize this is a weird request that would probably only help crazy live-show-addicted hippies like myself, but hopefully there's enough utility in this idea for others for it to gain some traction..

**Comment by muff1nman** [comment]
There is a global excludes - but that prevents airsonic from even picking up the songs at all. Regardless, I've marked this as an enhancement request - most likely satisfied by adding smart playlists as mentioned in the other issue.

**Comment by eharris** [comment]
Somewhat related to #718?
