### ISSUE TITLE
External (Postgresql) database much slower than hsql

### ISSUE THREAD

**Issue by Yetangitu** [airsonic/airsonic#860]
I've been running Airsonic with an external (_Postgresql_) database for about a year now. For developing CUE support (https://github.com/airsonic/airsonic/pull/856) I added a testing instance using the 'legacy' (hsql) database and pointed it at the same library of about 200.000 tracks. This made clear just how big the performance discrepancy between the two is. That _hsql_ would be faster was to be expected given that it is mostly in-memory but I do wonder whether there is something else in play: running a full scan over the entire library takes about 50 minutes when using _hsql_ versus  ~5 hours when using _Postgresql_. In both cases the database is kept on the same SSD and runs on the same server as Airsonic runs on. That server is nothing special, a rather memory-starved (2GB) Intel SS4200 with a dual-core Pentium E2220. I did some experiments with:

- different jdbc drivers; pgjdbc-ng (http://impossibl.github.io/pgjdbc-ng/) ended up being twice as slow as the default driver
- connecting through unix sockets (using https://github.com/fiken/junixsocket - no noticeable performance difference)
- connecting through localhost instead of the public address (as expected this made no difference)

While scanning using _hsql_ the java process sits at ~60% with peaks up to ~170% (dual-core) when committing the database log (it does this several times during a scan), process size goes up to ~700MB (I got GC/heap errors before, had to raise the maximum heap size from 200MB to 600MB (as said this is a memory-starved server).  When using _Postgresql_ java hovers around 15% and postgres around 9%, java process size lies around 500MB and the system has plenty of idle time. Average disk IO lies at 100KB/s for the postgres wal writer process (which writes the journal) with occasional peaks around 1MB for postgres writer. All this is clearly within system capacity and the slowdown does not seem to be caused by IO or CPU starvation. Something is slowing the combination Airsonic/Postgresql down but I have not tracked down the culprit yet.

**Comment by RuralHunter** [comment]
maybe you can check what sql is running in pg when the scan is in progress.

**Comment by Yetangitu** [comment]
I did, it runs a relatively normal amount of SELECT-this-and-that code before changing (first deleting, then re-adding) a row. The _hsql_ version connected ~2.1 million times to the database for a library with ~200.000 items, on _Postgresql_ it seems to generate about 6 SELECT/INSERT/UPDATE statements and 2 COMMITs per album item, nothing excessive.

**Comment by RuralHunter** [comment]
"connected ~2.1 million times to the database", why does it need to connect so many times? If this is the case, I think that's why it is so slow on pg.

**Comment by Yetangitu** [comment]
While connection pooling might make a small difference I don't think that is where the time goes. I'm more tempted to suspect the number of transactions (~400/s) to be the culprit here and will experiment a bit with disabling transactions. While this would not be suitable for production it could help find the culprit.

**Comment by Yetangitu** [comment]
BTW, the answer to the reason for all those connection attempts is that Airsonic uses org.springframework.jdbc.datasource.DriverManagerDataSource to manage connections. The documentation for this piece of code explicitly states the following:

> NOTE: This class is not an actual connection pool; it does not actually pool Connections. It just serves as simple replacement for a full-blown connection pool, implementing the same standard interface, but creating new Connections on every call.
> 
> ...
> If you need a "real" connection pool outside of a Java EE container, consider Apache Commons DBCP or C3P0. Commons DBCP's BasicDataSource and C3P0's ComboPooledDataSource are full connection pool beans, supporting the same basic properties as this class plus specific settings (such as minimal/maximal pool size etc).

It might be worth looking into replacing o.s.j.d.DriverManagerDataSource with one of the above to see whether that leads to better performance when using an external database.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/DriverManagerDataSource.html

**Comment by Yetangitu** [comment]
OK, solved the problem, it now runs faster with _Postgresql_ than it does with _hsql_, it now does a full scan over a library of 200.000 tracks in about 15 minutes. The solution lies in using connection pooling, the fix is simple (use _org.apache.commons.dbcp2.BasicDataSource instead of _org.springframework.jdbc.datasource.DriverManagerDataSource_ and add the dependency to `airsonic-main/pom.xml`as in the following PR: https://github.com/airsonic/airsonic/pull/864

**Comment by RuralHunter** [comment]
Great!
