### ISSUE TITLE
Problem while trying to scan folder

### ISSUE THREAD

**Issue by dorel14** [airsonic/airsonic#870]
## Problem description

*When clicking on scan media folder now , nothong is done and i have this message 
2019-01-25 18:03:28.981  WARN --- o.airsonic.player.util.FileUtil          : Failed to list children for /var/music

### Steps to reproduce

*Install new airsonic with tomcat 8 on debian + mysql db , try to scan your music folder

## System information

 * **Airsonic version**: * 10.1.2-RELEASE – 28 juillet 2018
 * **Operating system**: * Apache Tomcat/8.0.14 (Debian), java 1.8.0_171, Linux (278,8 MB / 350,1 MB)
  * **Proxy server**: Nginx  1.6.2
 * **Client**: * Chrome
  ## Additional notes

**Comment by jooola** [comment]
@dorel14 Did you fixed your problem ?
