### ISSUE TITLE
Support startScan Rest API

### ISSUE THREAD

**Issue by SenorSmartyPants** [airsonic/airsonic#875]
## Problem description

Add startScan Rest API. This will support media managers notifying Airsonic to scan for newly added content.

## System information
Added to Subsonic API version 1.15 
getScanStatus was added in that same revision

**Comment by SenorSmartyPants** [comment]
Hmm, This seems to be implemented already. 

My setup was not starting scans when requested. I'll do some more testing.

**Comment by muff1nman** [comment]
Yep we should be mostly 1.15 compatible.
