### ISSUE TITLE
stream through .pls or .m3u over the internet

### ISSUE THREAD

**Issue by aristosv** [airsonic/airsonic#877]
This is not a bug, I just want to ask a simple question, but I didn't find any forums or any other way to discuss/ask questions for airsonic. Please let me know if there is and I'll ask there.

For the past week I've been installing and evaluating streaming servers and now I'm doing this with airsonic. The features I'm looking for are simple. A library of mp3 files will exist locally on the server, and I will create playlists from those mp3 files. My question is: can I create a streaming link (.pls or .m3u or any other) that I can share with multiple streaming clients over the internet?

I have raspberry pi's in retail shops playing music (currently located on their sd cards) and I want them to stream the music from airsonic.

Is this possible?

edit: I have actually been through the documentation but I didn't find anything related, and there is no "Features" list on the airsonic website.

Thanks

**Comment by danbo** [comment]
This seems outside of the scope of the project.

I think you want https://github.com/AzuraCast/AzuraCast

**Comment by aristosv** [comment]
thank you
