### ISSUE TITLE
No "Save" button in"Advanced" Parameters. Impossible to save SMTP server definition + Updated file for French translation

### ISSUE THREAD

**Issue by darkTux31** [airsonic/airsonic#885]
Issue with Advanced Configuration. See below

**Comment by darkTux31** [comment]
Hi folks!
[stacktrace.txt](https://github.com/airsonic/airsonic/files/2873148/stacktrace.txt)

When I go to the Advanced section in Parmaters, I enter my SMTP server, my credentials but there is no "Save" button to apply my changes. 
I run the webapp in Tomcat 9 on my Raspberry Pi 2.
Another strange thing: when I cliek on "Advanced" in the Parameters section, I get the stacktrace you can find in attachment.
Thank you for the great job done on airsonic!

**Comment by darkTux31** [comment]
In addition, here is my contribution to french translation in the webapp. Many characters were missing in the transcoding.
[ResourceBundle_fr.properties.TXT](https://github.com/airsonic/airsonic/files/2873212/ResourceBundle_fr.properties.TXT)

**Comment by darkTux31** [comment]
This issue occurs when I have "French" as selected language in Airsonic. When I set to "English" the issue does not occur.

**Comment by darkTux31** [comment]
I have reviewed all entries in ResourceBundle_fr.properties. Now, "Adanvanced" admin page runs OK. Here is the file, it may be useful for french users. Just rename the file as "ResourceBundle_fr.properties" and put it in WEB-INF/classes/org/airsonic/player/i18n. It can be bundled in the war file, I let you push this file in the next airsonic war release.

[ResourceBundle_fr.properties.NEW.txt](https://github.com/airsonic/airsonic/files/2877739/ResourceBundle_fr.properties.NEW.txt)

**Comment by muff1nman** [comment]
@jooola would you be able to take a look at this?

**Comment by jooola** [comment]
Yup, sure.

**Comment by dreamsness** [comment]
Hello,
Thanks @darkTux31 for the help
I want to add something
In the line 427 in your file , one balise isn't close : 
`<li> Possibilit\u00E9 d'envoyer la sortie \u00E0 stdout.**</li>**`
