### ISSUE TITLE
Recommended way to upgrade Airsonic (Tomcat WAR version)?

### ISSUE THREAD

**Issue by protist** [airsonic/airsonic#886]
## Problem description

What is the recommended way to upgrade the Tomcat WAR version of Airsonic, while keeping all data intact?

Should we follow the normal [installation instructions](https://airsonic.github.io/docs/install/war-tomcat/)? Or should we only replace `/var/lib/tomcat8/webapps/airsonic.war`, leaving `/var/lib/tomcat8/webapps/airsonic/` and `/var/lib/tomcat8/work/*` intact? What are files in these two directories for anyway?

### Steps to reproduce

1. Attempt to upgrade

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017
 * **Operating system**: Linux, Raspbian (Debian)
 * **Proxy server**: None
 * **Client**: N/A.

**Comment by nate2014jatc** [comment]
just replacing the war file leads to many errors and an unusable server on my end.

**Comment by xerg0n** [comment]
This was asked before on reddit, [here](https://www.reddit.com/r/airsonic/comments/as6crr/airsonic_1021_released/) and [here](https://www.reddit.com/r/airsonic/comments/9bz837/procedure_for_updating/). Basically its:
* shutdown tomcat
* replace war and delete the airsonic folder under webapps
* start tomcat

Worked without any problem for me.

**Comment by protist** [comment]
> This was asked before on reddit

Thanks. I had actually found both threads, but there were conflicting responses, and the devs hadn't replied in either thread. I wanted an official response from the devs, and preferably in the manual too.

FWIW your instructions are yet another permutation! Some have said remove `/var/lib/tomcat8/webapps/airsonic/` and `/var/lib/tomcat8/work/*`, some have said leave them, but you are the first to say only remove the former!

**Comment by xerg0n** [comment]
Hey, 
I am not the dev, but double checked what I did last time I updated to be sure.
 I have the war deployed to root and did:
```
service tomcat8 stop
cd /usr/local/apache-tomcat-8.0/webapps
rm ROOT.war
rm -R ROOT
wget https://github.com/airsonic/airsonic/releases/download/v10.2.1/airsonic.war
mv airsonic.war ROOT.war
chown www ROOT.war
service tomcat8 start
```

I did not do any backups, so in case you are worried about this replace the rm with mv to a different name. 

I overlooked the part about the work folder, but looking at [this](https://github.com/Esri/geoportal-server/wiki/Clear-the-Tomcat-Work-Folder) it seems like its a good idea to remove the work folder to clear the cache. This basically makes my response equal to the reddit one

**Comment by protist** [comment]
This issue was closed, but I was still waiting for an official response.

**Comment by jvoisin** [comment]
I [added some lines to the documentation]( https://github.com/airsonic/documentation/commit/9227adf691603538f2cf59fdec6e8c13ed06eeba ).

It'll show up as soon as the documentation's website is rebuilt.

**Comment by protist** [comment]
Thank you. A few of the paths are inconsistent with [this file](https://airsonic.github.io/docs/install/war-tomcat/), but overall it worked fine for me.
