### ISSUE TITLE
Wider previous and next buttons

### ISSUE THREAD

**Issue by topas-rec** [airsonic/airsonic#890]
## Problem description

Navigation with the mouse to click the previous and the next button (next song, previous song) is not easy enough in my eyes. I can hit the play button easier, because it is wider.

I recommend to make the buttons a bit wider (not higher - that might increase the whole playing bars height)

On a Full HD widescreen display my playing bar is only filled with button half. So _on my screen_ there is enough space for wider next and previous buttons.

### Steps to reproduce

Click previous and next buttons on a Full HD display.

## System information

 * **Airsonic version**: 10.2.1
 * **Operating system**: Linux Mint 18.3
 * **Proxy server**: none
 * **Client**: Firefox

## Additional notes

Docker image 10.2.1

**Comment by jaylex32** [comment]
this is something that im guessing will come with the new ui but who knows when that is coming. hopefully soon, I vote also for wider buttons.

**Comment by heyarne** [comment]
@jaylex32 Feel free to test https://heyarne.github.io/airsonic-ui.

**Comment by jaylex32** [comment]
> @jaylex32 Feel free to test https://heyarne.github.io/airsonic-ui and leave feedback. It's far from feature complete but quite usable.

I have try this in the past  but it doesn't work and I try today again and still doesn't work.

**Comment by heyarne** [comment]
> > @jaylex32 Feel free to test https://heyarne.github.io/airsonic-ui and leave feedback. It's far from feature complete but quite usable.
> 
> I have try this in the past but it doesn't work and I try today again and still doesn't work.

If you need help you can find me in the matrix chat or write me on reddit, I don't want to hijack the conversation here.

**Comment by jvoisin** [comment]
This is done in #977

**Comment by topas-rec** [comment]
Thanks!

**Comment by eharris** [comment]
This was fixed with #977 (as noted above, but apparently this didn't get closed yet).
