### ISSUE TITLE
Message | Could not verify the provided CSRF token because your session was not found.

### ISSUE THREAD

**Issue by ackstorm23** [airsonic/airsonic#893]
## Problem description

Fresh install of airsonic via docker does not allow admin login

### Steps to reproduce

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

1.  Create docker instance
```
docker create \
  --name=airsonic \
  -p 4444:4040 \
  --restart unless-stopped \
  linuxserver/airsonic

```

2. Try to login
3. Receive the following error:

```
Status | 403
-- | --
Error | Forbidden
Message | Could not verify the provided CSRF token because your session was not found.
Path | /login
Time | Tue Feb 26 11:15:59 CST 2019
Exception |  
Java version | Oracle Corporation 1.8.0_191
Operating system | Linux 4.9.75-rancher
Server | Apache Tomcat/8.5.35
Memory | Used 343 of 723 MB
```

## System information

Airsonic Version: Latest via Docker
OS:  RancherOS docker image (  linuxserver/airsonic)
Proxy Server: none
Client:   Firefox Browser
Cookies:  Fully Enabled

## Additional notes

Cookies are enabled. Nothing is blocking them.

**Comment by ackstorm23** [comment]
I originally had 'third party cookies' blocked in firefox.  I turned this off and refreshed the airsonic login page.  After trying to login again with no cookie blocking at all, it still results in the same error.

**Comment by ackstorm23** [comment]
Works fine in Microsoft EDGE, seems to be specific to firefox.

**Comment by ackstorm23** [comment]
Digging through my cookies manually, I don't see any airsonic cookies being created. 

Content blocking under options is "STANARD: Only blocks known trackers in Private Windows."

I've even added an exception for the site's URL under Manage Permissions, and it still has this problem.

Hard refresh has not fixed it either.

**Comment by jooola** [comment]
Did you tried the airsonic/airsonic docker image ? We don't have anything to do with the linuxserver/airsonic image.

**Comment by jooola** [comment]
I just tested the linuxserver image and it is working fine on my side (using firefox). Did you tried purging your cookies for this address ?

**Comment by ackstorm23** [comment]
I cleared all cookies for that IP and loaded a new tab and logged in - same error. 

That IP is being used for other docker instances a well and I had to re-login to all of those, so I know that clearing the cookies worked for everything else.  

It just didn't affect airsonic.  :/

**Comment by muff1nman** [comment]
linuxserver/airsonic image is not supported.
