### ISSUE TITLE
DNLA can not be used

### ISSUE THREAD

**Issue by tesshucom** [airsonic/airsonic#975]
## Problem description

DNLA can be started without error.
However, the client can not search.

### Steps to reproduce

Check "Enable DLNA server" in DLNA / UPnP
and specify and save a valid "LAN Server address".
(Normal DLNA / UPnP startup operation)

## System information

Checked with common android apps.
xperia video & tomcat standalone at Windows10

0d78c30 last safety point
143a220 Many library updates at the same time. DWR Failure point.
8a1f36c DWR fix point
f04ec61 current

Problems occur in all revisions after 143a220.
DNLA starts without error but can not search from the client.

## Additional notes

cling-core has been updated in 143a220.

cling-core 2.0.1 -> 2.1.2
cling-support 2.0.1 -> 2.1.2
seamless-util 1.1.0 -> 1.1.2

Downgrading these did not improve the situation.
___

In addition to the above, the situation improved when the class dependency was corrected.
> org.airsonic.player.service.upnp.ApacheUpnpServiceConfiguration
> (Revert to the previous state)

I'm sorry.
It seems best to do better with Configuration, but I'm not familiar with DLNA / UPnP.

**Comment by muff1nman** [comment]
Thanks for the PR - should be fixed now.
